IF NOT EXISTS ( SELECT 1 FROM SYS.TABLES A INNER JOIN SYS.COLUMNS B ON A.object_id = B.object_id WHERE A.name ='LOJA_VENDA' AND B.name ='ID_TIPO_MODALIDADE')
	BEGIN
		EXEC('ALTER TABle loja_venda add ID_TIPO_MODALIDADE SMALLINT 		 
			  ALTER TABle loja_venda add ID_TIPO_ORIGEM SMALLINT 
		')
	END
