IF NOT EXISTS ( SELECT 1 FROM SYS.TABLES A INNER JOIN SYS.COLUMNS B ON A.OBJECT_ID = B.OBJECT_ID WHERE A.NAME ='LOJA_PEDIDO_ENTREGA_LISTA' AND B.NAME = 'FRETE')
	BEGIN
		EXEC('ALTER TABLE LOJA_PEDIDO_ENTREGA_LISTA ADD FRETE NUMERIC(14,2)')
     END
IF NOT EXISTS ( SELECT 1 FROM SYS.TABLES A INNER JOIN SYS.COLUMNS B ON A.OBJECT_ID = B.OBJECT_ID WHERE A.NAME ='LOJA_PEDIDO_ENTREGA_LISTA' AND B.NAME = 'VALOR_TOTAL')
	BEGIN
		EXEC('ALTER TABLE LOJA_PEDIDO_ENTREGA_LISTA ADD VALOR_TOTAL  NUMERIC(14,2)')
     END