IF NOT EXISTS( SELECT 1 FROM SYS.OBJECTS WHERE NAME ='HR_XFK14686_LOJA_VENDA' )
 BEGIN
  EXEC('ALTER TABLE [dbo].[LOJA_VENDA]  WITH CHECK ADD  CONSTRAINT [HR_XFK14686_LOJA_VENDA] FOREIGN KEY([ID_TIPO_ORIGEM])
REFERENCES [dbo].[HR_VENDA_TIPO_ORIGEM] ([ID_TIPO_ORIGEM])')
END

