IF NOT EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE NAME ='W_HR_LOJA_MOTIVOS_TROCAS' )
 BEGIN 
	EXEC('
		CREATE VIEW [dbo].[W_HR_LOJA_MOTIVOS_TROCAS]
	AS
	 SELECT
	   LTRIM(RTRIM(MOTIVO_TROCA)) AS MOTIVO_TROCA
	  ,LTRIM(RTRIM(DESC_MOTIVO)) AS DESC_MOTIVO
	 FROM
	  HR_LOJA_MOTIVOS_TROCAS
	')
 END

