UPDATE CADASTRO_CLI_FOR SET  EMAIL ='NFECIAHERINGXML@HERING.COM.BR'
WHERE NOME_CLIFOR ='CIA HERING'

UPDATE CADASTRO_CLI_FOR SET EMAIL ='NFECIAHERINGXML@HERING.COM.BR'
WHERE NOME_CLIFOR ='FÁBRICA ANÁPOLIS'

UPDATE CADASTRO_CLI_FOR SET EMAIL_NFE ='NFECIAHERINGXML@HERING.COM.BR'
WHERE NOME_CLIFOR ='CIA HERING'

UPDATE CADASTRO_CLI_FOR SET EMAIL_NFE ='NFECIAHERINGXML@HERING.COM.BR'
WHERE NOME_CLIFOR ='FÁBRICA ANÁPOLIS'
