IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'OMS_CHANGE_TRACKING'
                      AND COLUMN_NAME = 'ID_FULFILLMENT')
  ALTER TABLE [dbo].[OMS_CHANGE_TRACKING]
    ADD ID_FULFILLMENT VARCHAR(5)
    
