IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[HR_NFE_REFERENCIA]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[HR_NFE_REFERENCIA](
	[CODIGO_FILIAL] [varchar](6) NOT NULL,
	[FILIAL] [varchar](25) NOT NULL,
	[NF_NUMERO] [varchar](9) NOT NULL,
	[SERIE_NF] [varchar](6) NOT NULL,
	[CHAVE_NFE] [varchar](44) NOT NULL,
	[PRODUTO] [varchar](10) NOT NULL,
	[COR_PRODUTO] [varchar](10) NOT NULL,
	[TAMANHO] [int] NOT NULL,
	[CODIGO_BARRA] [varchar](13) NULL,
	[QTDE] [int] NULL,
	[PRECO] [numeric](13, 2) NULL,
	[FORNECEDOR] [varchar](25) NULL,
	[ARQUIVO] [varchar](50) NOT NULL,
	[EMISSAO] [datetime] NULL,
	[ICMS] [numeric](13, 2) NULL,
	[GRADE] [varchar](6) NULL,
	[IPI] [numeric](13, 2) NULL,
	[ICMST] [numeric](13, 2) NULL,
	[ROMANEIO_SAIDA] [varchar](15) NULL,
	[SOBRA_GERADA] [int] NULL,
 CONSTRAINT [PK_HR_NFE_REFERENCIA] PRIMARY KEY CLUSTERED 
(
	[CODIGO_FILIAL] ASC,
	[FILIAL] ASC,
	[NF_NUMERO] ASC,
	[SERIE_NF] ASC,
	[CHAVE_NFE] ASC,
	[PRODUTO] ASC,
	[COR_PRODUTO] ASC,
	[TAMANHO] ASC,
	[ARQUIVO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
