IF NOT EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[W_HR_DEVOLUCAO_SUGESTAO]'))
EXEC dbo.sp_executesql @statement = N'CREATE VIEW [dbo].[W_HR_DEVOLUCAO_SUGESTAO]  
AS  
SELECT  ARQUIVO,NF_NUMERO,SERIE_NF,PRODUTO,COR_PRODUTO,CODIGO_BARRA,SUM(QTDE) AS QTDE  
FROM(  
SELECT ARQUIVO,NF_NUMERO,SERIE_NF,PRODUTO,COR_PRODUTO,CODIGO_BARRA,SUM(QTDE) AS QTDE  FROM DBO.HR_NFE_REFERENCIA A  
GROUP BY ARQUIVO,NF_NUMERO,SERIE_NF,PRODUTO,COR_PRODUTO,CODIGO_BARRA  
UNION ALL  
SELECT ARQUIVO,NF_NUMERO,SERIE_NF,PRODUTO,COR_PRODUTO,CODIGO_BARRA,-SUM(QTDE) FROM HR_DEVOLUCAO_SUGESTAO  
GROUP BY ARQUIVO,NF_NUMERO,SERIE_NF,PRODUTO,COR_PRODUTO,CODIGO_BARRA ) AS GERAL   
GROUP BY ARQUIVO,NF_NUMERO,SERIE_NF,PRODUTO,COR_PRODUTO,CODIGO_BARRA' 
