CREATE FUNCTION DBO.FC_CODIFICAPROMO
(@CODIGO_FILIAL VARCHAR(6)      
,@sequencia numeric(10)    
)      
RETURNS VARCHAR(12)      
	WITH ENCRYPTION 
AS    
BEGIN      
      
DECLARE @SEQUENCIA_CARACTER_FILIAL VARCHAR(100) SET @SEQUENCIA_CARACTER_FILIAL = 'N365ZPFEYCIQK9MDWG48T7UABS2L1VJHXR' -- NAO TEM O E O "Ó" PARA NAO CONFUNDIR NA IMPRESSAO      
DECLARE @SEQUENCIA_CARACTER_1 VARCHAR(100) SET @SEQUENCIA_CARACTER_1 = 'QDWG48T7UABS2L1VN365ZPFEYCIJHXRK9M' -- NAO TEM O E O "Ó" PARA NAO CONFUNDIR NA IMPRESSAO      
DECLARE @SEQUENCIA_CARACTER_2 VARCHAR(100) SET @SEQUENCIA_CARACTER_2 = 'TDWG4857EN36UABS2PFJHXZQVIRK9YCL1M' -- NAO TEM O E O "Ó" PARA NAO CONFUNDIR NA IMPRESSAO      
DECLARE @SEQUENCIA_CARACTER_3 VARCHAR(100) SET @SEQUENCIA_CARACTER_3 = 'QD8T7UA2LBS1VN365HXRKZPFEWG49MYCIJ' -- NAO TEM O E O "Ó" PARA NAO CONFUNDIR NA IMPRESSAO      
DECLARE @SEQUENCIA_CARACTER_4 VARCHAR(100) SET @SEQUENCIA_CARACTER_4 = '2L1VN48T7365ZPFEYCIJHXRK9MQDWGUABS' -- NAO TEM O E O "Ó" PARA NAO CONFUNDIR NA IMPRESSAO      
DECLARE @SEQUENCIA_CARACTER_5 VARCHAR(100) SET @SEQUENCIA_CARACTER_5 = 'WG487QDUABSR2LCIJHXTK9M1VN365ZPFEY' -- NAO TEM O E O "Ó" PARA NAO CONFUNDIR NA IMPRESSAO      
DECLARE @SEQUENCIA_CARACTER_6 VARCHAR(100) SET @SEQUENCIA_CARACTER_6 = 'JHXRK9MFEYBS2L1VNQDWG48T7UACI365ZP' -- NAO TEM O E O "Ó" PARA NAO CONFUNDIR NA IMPRESSAO      
DECLARE @SEQUENCIA_CARACTER_7 VARCHAR(100) SET @SEQUENCIA_CARACTER_7 = '4865ZPFEYCIJHXT7WGMUABS2L1VNRK9QD3' -- NAO TEM O E O "Ó" PARA NAO CONFUNDIR NA IMPRESSAO      
DECLARE @SEQUENCIA_CARACTER_8 VARCHAR(100) SET @SEQUENCIA_CARACTER_8 = '5ZPIJHXRK9MQDWGFEYC648T7UA1VN3BS2L' -- NAO TEM O E O "Ó" PARA NAO CONFUNDIR NA IMPRESSAO      
  
declare @sequenciaAumentada numeric(14)    
set @sequenciaAumentada = @sequencia * 10000     
     
DECLARE @CODIGO_TICKET_HERING VARCHAR(14)      
SET @CODIGO_TICKET_HERING = ''      
  
      
-- FILIAL 4 DIGITOS     
if isnumeric(@CODIGO_FILIAL) = 0 -- se houver algum dia, codigo da filial com letras    
begin    
 SET @CODIGO_TICKET_HERING = @CODIGO_TICKET_HERING + RIGHT(REPLICATE('0',4)+RTRIM(LTRIM(@CODIGO_FILIAL)),4)      
end    
else    
begin    
 declare @codigoFilialAumentada numeric(10)    
 set @codigoFilialAumentada = convert(numeric(4),@CODIGO_FILIAL)*100    
 -- 4      
 SELECT @CODIGO_TICKET_HERING = @CODIGO_TICKET_HERING + SUBSTRING(@SEQUENCIA_CARACTER_FILIAL,(1+(@codigoFilialAumentada/34/34/34) % (34)),1)      
 -- 1      
 SELECT @CODIGO_TICKET_HERING = @CODIGO_TICKET_HERING + SUBSTRING(@SEQUENCIA_CARACTER_FILIAL,(1+(@codigoFilialAumentada) % (34)),1)      
 -- 3      
 SELECT @CODIGO_TICKET_HERING = @CODIGO_TICKET_HERING + SUBSTRING(@SEQUENCIA_CARACTER_FILIAL,(1+(@codigoFilialAumentada/34/34) % (34)),1)      
 -- 2      
 SELECT @CODIGO_TICKET_HERING = @CODIGO_TICKET_HERING + SUBSTRING(@SEQUENCIA_CARACTER_FILIAL,(1+(@codigoFilialAumentada/34) % (34)),1)      
end    
    
    
-- 3      
SELECT @CODIGO_TICKET_HERING = @CODIGO_TICKET_HERING + SUBSTRING(@SEQUENCIA_CARACTER_1,(1+(@sequenciaAumentada/34/34) % (34)),1)      
-- 5    
SELECT @CODIGO_TICKET_HERING = @CODIGO_TICKET_HERING + SUBSTRING(@SEQUENCIA_CARACTER_2,(1+(@sequenciaAumentada/34/34/34/34) % (34)),1)      
-- 6    
SELECT @CODIGO_TICKET_HERING = @CODIGO_TICKET_HERING + SUBSTRING(@SEQUENCIA_CARACTER_3,(1+(@sequenciaAumentada/34/34/34/34/34) % (34)),1)      
-- 4      
SELECT @CODIGO_TICKET_HERING = @CODIGO_TICKET_HERING + SUBSTRING(@SEQUENCIA_CARACTER_4,(1+(@sequenciaAumentada/34/34/34) % (34)),1)      
-- 1      
SELECT @CODIGO_TICKET_HERING = @CODIGO_TICKET_HERING + SUBSTRING(@SEQUENCIA_CARACTER_5,(1+(@sequenciaAumentada) % (34)),1)      
-- 8    
SELECT @CODIGO_TICKET_HERING = @CODIGO_TICKET_HERING + SUBSTRING(@SEQUENCIA_CARACTER_6,(1+(@sequenciaAumentada/34/34/34/34/34/34/34) % (34)),1)      
-- 7    
SELECT @CODIGO_TICKET_HERING = @CODIGO_TICKET_HERING + SUBSTRING(@SEQUENCIA_CARACTER_7,(1+(@sequenciaAumentada/34/34/34/34/34/34) % (34)),1)      
-- 2      
SELECT @CODIGO_TICKET_HERING = @CODIGO_TICKET_HERING + SUBSTRING(@SEQUENCIA_CARACTER_8,(1+(@sequenciaAumentada/34) % (34)),1)      
  
if CONVERT(VARCHAR(10), GETDATE(), 112) != @sequencia
begin
	set  @CODIGO_TICKET_HERING = 'o00000000' 
end 
 
RETURN @CODIGO_TICKET_HERING      
      
END 