IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[HR_CLIENTES_DEPENDENTES]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[HR_CLIENTES_DEPENDENTES](
	[CODIGO_CLIENTE] [varchar](14) NOT NULL,
	[ID_DEPENDENTE] [int] NOT NULL,
	[NOME] [varchar](60) NOT NULL,
	[DATA_NASCIMENTO] [datetime] NULL,
	[SEXO] [varchar](1) NULL,
	[INTERESSE] [varchar](80) NULL,
	[INATIVO]  BIT NULL,
	[DATA_CADASTRO] [datetime] NULL,
	[DATA_PARA_TRANSFERENCIA] [datetime] NULL,
 CONSTRAINT [PK_HR_CLIENTES_DEPENDENTES] PRIMARY KEY CLUSTERED 
(
	[CODIGO_CLIENTE] ASC,
	[ID_DEPENDENTE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END