 

IF NOT EXISTS ( SELECT 1 FROM SYS.tables WHERE name = 'HR_VENDA_PROMOCAO')
BEGIN
	CREATE TABLE [dbo].[HR_VENDA_PROMOCAO](
		[CODIGO_FILIAL] [char](6) NOT NULL,
		[TICKET] [char](8) NOT NULL,
		[DATA_VENDA] [datetime] NOT NULL,
		[ID_PROMOCAO] [int] NOT NULL,
		[DATA_PARA_TRANSFERENCIA] [datetime] NOT NULL,
		[CODIGO_VOUCHER] [varchar](20) NULL,
		[VALOR_DESCONTO] [numeric](9, 2) NULL,
	 CONSTRAINT [XPK[HR_VENDA_PROMOCAO] PRIMARY KEY CLUSTERED 
	(
		[CODIGO_FILIAL] ASC,
		[TICKET] ASC,
		[DATA_VENDA] ASC,
		[ID_PROMOCAO] ASC
	)
	) ON [PRIMARY]
END