IF NOT EXISTS (SELECT 1 FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.object_id = B.object_id WHERE A.NAME = 'HR_VENDA_PROMOCAO' AND B.NAME = 'ID_TIPO_PROMOCAO')
BEGIN 
	EXEC ('ALTER TABLE HR_VENDA_PROMOCAO ADD ID_TIPO_PROMOCAO INT')
END
