IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='LOJA_MOTIVOS_CANCELAMENTOS' AND COLUMN_NAME='INATIVO')
ALTER TABLE LOJA_MOTIVOS_CANCELAMENTOS ADD INATIVO BIT

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='LOJA_MOTIVOS_CANCELAMENTOS' AND COLUMN_NAME='CANCELA_OMNI')
ALTER TABLE LOJA_MOTIVOS_CANCELAMENTOS ADD CANCELA_OMNI BIT