IF  NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[LOJA_NOTA_FISCAL]') AND name = N'IDX_HR_LOJA_NOTA_FISCAL_DATA_HORA_EMISSAO')
BEGIN 
	CREATE NONCLUSTERED INDEX [IDX_HR_LOJA_NOTA_FISCAL_DATA_HORA_EMISSAO] ON [dbo].[LOJA_NOTA_FISCAL] 
	(
		[DATA_HORA_EMISSAO] ASC
	)
	INCLUDE ( [CODIGO_FILIAL],
	[NF_NUMERO],
	[SERIE_NF],
	[NATUREZA_OPERACAO_CODIGO],
	[EMISSAO],
	[DATA_SAIDA],
	[QTDE_TOTAL],
	[VALOR_TOTAL],
	[NOTA_IMPRESSA],
	[DATA_CANCELAMENTO],
	[TIPO_ORIGEM],
	[CHAVE_NFE],
	[PROTOCOLO_AUTORIZACAO_NFE],
	[DATA_AUTORIZACAO_NFE],
	[STATUS_NFE],
	[LOG_STATUS_NFE],
	[TIPO_EMISSAO_NFE],
	[PROTOCOLO_CANCELAMENTO_NFE],
	[JUSTIFICATIVA_CONTINGENCIA],
	[DATA_CONTINGENCIA]
	)
END