IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[TRIU_ETL_HR_SAP_LOJA_NOTA]'))
EXEC('
CREATE TRIGGER [dbo].[TRIU_ETL_HR_SAP_LOJA_NOTA]
ON HR_SAP_LOJA_NOTA
FOR INSERT,UPDATE 
NOT FOR REPLICATION 
AS
BEGIN

  IF EXISTS(SELECT TOP 1 1 FROM Inserted INNER JOIN LJ_LX_ETL_TIPO ON LJ_LX_ETL_TIPO.DESC_ETL_TIPO = ''HR_SAP_LOJA_NOTA'' WHERE LJ_LX_ETL_TIPO.INATIVO = 0 AND LJ_LX_ETL_TIPO.ORIGEM = 1 )
  BEGIN
	INSERT INTO LJ_ETL_REPOSITORIO (TABELA, FILTRO, ID_ETL_TIPO, INDICA_EXCLUSAO)
	SELECT DISTINCT ''HR_SAP_LOJA_NOTA'', ''CHAVE_ORIGEM=''+CONVERT(VARCHAR(40),Inserted.CHAVE_ORIGEM) + ''|Varchar'', LJ_LX_ETL_TIPO.Id_Etl_Tipo, 0 
	FROM Inserted 
	  INNER JOIN LJ_LX_ETL_TIPO ON LJ_LX_ETL_TIPO.DESC_ETL_TIPO = ''HR_SAP_LOJA_NOTA''
	WHERE LJ_LX_ETL_TIPO.INATIVO = 0 AND LJ_LX_ETL_TIPO.ORIGEM = 1 and inserted.STATUS in (''1'', ''4'', ''9'') and Inserted.HR_ENVIA_RETAIL=1
  END
END')