IF (SELECT Column_Default FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HR_SAP_LOJA_NOTA' AND COLUMN_NAME = 'RETORNOU_LOJA') IS NULL
BEGIN 
ALTER TABLE HR_SAP_LOJA_NOTA ADD  DEFAULT 0 FOR RETORNOU_LOJA
END