IF NOT EXISTS(SELECT 1 FROM SYS.objects WHERE NAME = 'HR_SAP_LOJA_NOTA_LOG') 
BEGIN
EXEC ('CREATE TABLE [dbo].[HR_SAP_LOJA_NOTA_LOG](
	[ID] [numeric](14, 0) IDENTITY(1,1) NOT NULL,
	[CODIGO_LINX] [varchar](20) NULL,
	[CHAVE_ORIGEM] [varchar](40) NULL,
	[STATUS] [tinyint] NOT NULL,
	[DATA_LOG] [datetime] NULL,
	[MENSAGEM] [varchar](max) NULL,
	[NF_NUMERO] [varchar](15) NULL,
	[SERIE_NF] [varchar](6) NULL,
	[EMISSAO_NF] [datetime] NULL,
	[SOLICITA_CANCELAMENTO] [bit] NULL,
	[INCONSISTENCIA] [bit] NULL,
	[MENSAGEM_INCONSISTENCIA] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

ALTER TABLE [dbo].[HR_SAP_LOJA_NOTA_LOG] ADD  DEFAULT (getdate()) FOR [DATA_LOG]')
END