
IF NOT EXISTS(SELECT 1 FROM PARAMETROS WHERE PARAMETRO = 'HR_ATUALIZADOR_URL') 		
BEGIN
INSERT INTO PARAMETROS(PARAMETRO,DESC_PARAMETRO,VALOR_ATUAL,TIPO_DADO,
			GLOBAL,ESCOPO,POR_USUARIO_OK,PERMITE_POR_EMPRESA,
			ENVIA_PARA_LOJA,PERMITE_POR_LOJA,PERMITE_POR_TERMINAL,
			PERMITE_ALTERAR_NA_LOJA,PERMITE_ALTERAR_NO_TERMINAL,
			ENVIA_PARA_REPRESENTANTE,PERMITE_POR_REPRESENTANTE,
			PERMITE_ALTERAR_NO_REPRESENTANTE,PENULT_ATUALIZACAO,
			ULT_ATUALIZACAO,DATA_PARA_TRANSFERENCIA)
VALUES('HR_ATUALIZADOR_URL','URL DO ATUALIZADOR AUTOMATICO DA HERING','SEVERALGUMTIPO','C',
  	   0,0,0,0,1,1,0,0,0,0,0,0,GETDATE(),GETDATE(),GETDATE())
END  	   


IF NOT EXISTS(SELECT 1 FROM PARAMETROS WHERE PARAMETRO = 'HR_ATUALIZA_AUTOMATICO') 		
BEGIN
INSERT INTO PARAMETROS(PARAMETRO,DESC_PARAMETRO,VALOR_ATUAL,TIPO_DADO,
			GLOBAL,ESCOPO,POR_USUARIO_OK,PERMITE_POR_EMPRESA,
			ENVIA_PARA_LOJA,PERMITE_POR_LOJA,PERMITE_POR_TERMINAL,
			PERMITE_ALTERAR_NA_LOJA,PERMITE_ALTERAR_NO_TERMINAL,
			ENVIA_PARA_REPRESENTANTE,PERMITE_POR_REPRESENTANTE,
			PERMITE_ALTERAR_NO_REPRESENTANTE,PENULT_ATUALIZACAO,
			ULT_ATUALIZACAO,DATA_PARA_TRANSFERENCIA)
VALUES('HR_ATUALIZA_AUTOMATICO','INDICA USO DO ATUALIZADOR AUTOMATICO DA HERING','.F.','L',
  	   0,0,0,0,1,1,0,0,0,0,0,0,GETDATE(),GETDATE(),GETDATE())
END  	  



IF NOT EXISTS(SELECT 1 FROM PARAMETROS WHERE PARAMETRO = 'HR_ATUALIZADOR_FORCA')        
BEGIN
INSERT INTO PARAMETROS(PARAMETRO,DESC_PARAMETRO,VALOR_ATUAL,TIPO_DADO,
                  GLOBAL,ESCOPO,POR_USUARIO_OK,PERMITE_POR_EMPRESA,
                  ENVIA_PARA_LOJA,PERMITE_POR_LOJA,PERMITE_POR_TERMINAL,
                  PERMITE_ALTERAR_NA_LOJA,PERMITE_ALTERAR_NO_TERMINAL,
                  ENVIA_PARA_REPRESENTANTE,PERMITE_POR_REPRESENTANTE,
                  PERMITE_ALTERAR_NO_REPRESENTANTE,PENULT_ATUALIZACAO,
                  ULT_ATUALIZACAO,DATA_PARA_TRANSFERENCIA)
VALUES('HR_ATUALIZADOR_FORCA','FORMA PARA O ATUALIZADOR AUTOMATICO DA HERING','.F.','L',
         0,0,0,0,1,1,0,0,0,0,0,0,GETDATE(),GETDATE(),GETDATE())
END     


IF NOT EXISTS(SELECT 1 FROM PARAMETROS WHERE PARAMETRO = 'HR_ATUALIZADOR_HOST') 		
BEGIN
INSERT INTO PARAMETROS(PARAMETRO,DESC_PARAMETRO,VALOR_ATUAL,TIPO_DADO,
			GLOBAL,ESCOPO,POR_USUARIO_OK,PERMITE_POR_EMPRESA,
			ENVIA_PARA_LOJA,PERMITE_POR_LOJA,PERMITE_POR_TERMINAL,
			PERMITE_ALTERAR_NA_LOJA,PERMITE_ALTERAR_NO_TERMINAL,
			ENVIA_PARA_REPRESENTANTE,PERMITE_POR_REPRESENTANTE,
			PERMITE_ALTERAR_NO_REPRESENTANTE,PENULT_ATUALIZACAO,
			ULT_ATUALIZACAO,DATA_PARA_TRANSFERENCIA)
VALUES('HR_ATUALIZADOR_HOST','Ftp do atualizador','ftp286.linxsaas.com.br','C',
  	   0,0,0,0,1,1,0,0,0,0,0,0,GETDATE(),GETDATE(),GETDATE())
END  	   


IF NOT EXISTS(SELECT 1 FROM PARAMETROS WHERE PARAMETRO = 'HR_ATUALIZADOR_USER') 		
BEGIN
INSERT INTO PARAMETROS(PARAMETRO,DESC_PARAMETRO,VALOR_ATUAL,TIPO_DADO,
			GLOBAL,ESCOPO,POR_USUARIO_OK,PERMITE_POR_EMPRESA,
			ENVIA_PARA_LOJA,PERMITE_POR_LOJA,PERMITE_POR_TERMINAL,
			PERMITE_ALTERAR_NA_LOJA,PERMITE_ALTERAR_NO_TERMINAL,
			ENVIA_PARA_REPRESENTANTE,PERMITE_POR_REPRESENTANTE,
			PERMITE_ALTERAR_NO_REPRESENTANTE,PENULT_ATUALIZACAO,
			ULT_ATUALIZACAO,DATA_PARA_TRANSFERENCIA)
VALUES('HR_ATUALIZADOR_USER','user Ftp do atualizador','286.ftp','C',
  	   0,0,0,0,1,1,0,0,0,0,0,0,GETDATE(),GETDATE(),GETDATE())
END  	   



IF NOT EXISTS(SELECT 1 FROM PARAMETROS WHERE PARAMETRO = 'HR_ATUALIZADOR_PASSWORD') 		
BEGIN
INSERT INTO PARAMETROS(PARAMETRO,DESC_PARAMETRO,VALOR_ATUAL,TIPO_DADO,
			GLOBAL,ESCOPO,POR_USUARIO_OK,PERMITE_POR_EMPRESA,
			ENVIA_PARA_LOJA,PERMITE_POR_LOJA,PERMITE_POR_TERMINAL,
			PERMITE_ALTERAR_NA_LOJA,PERMITE_ALTERAR_NO_TERMINAL,
			ENVIA_PARA_REPRESENTANTE,PERMITE_POR_REPRESENTANTE,
			PERMITE_ALTERAR_NO_REPRESENTANTE,PENULT_ATUALIZACAO,
			ULT_ATUALIZACAO,DATA_PARA_TRANSFERENCIA)
VALUES('HR_ATUALIZADOR_PASSWORD','user Ftp do atualizador','J3ouG5tsaN*emT#','C',
  	   0,0,0,0,1,1,0,0,0,0,0,0,GETDATE(),GETDATE(),GETDATE())
END  	   




IF NOT EXISTS(SELECT 1 FROM PARAMETROS_LOJA WHERE PARAMETRO = 'HR_ATUALIZA_AUTOMATICO') 		
BEGIN 
	INSERT INTO PARAMETROS_LOJA(PARAMETRO,CODIGO_FILIAL,VALOR_ATUAL,PERMITE_ALTERAR_NA_LOJA,DATA_PARA_TRANSFERENCIA) 
	SELECT TOP 1 'HR_ATUALIZA_AUTOMATICO',
				 ?main.p_codigo_filial ,
				 '.T.',
				 '0',
				 GETDATE()
END

IF NOT EXISTS(SELECT 1 FROM PARAMETROS_LOJA WHERE PARAMETRO = 'HR_ATUALIZADOR_FORCA') 		
BEGIN 
	INSERT INTO PARAMETROS_LOJA(PARAMETRO,CODIGO_FILIAL,VALOR_ATUAL,PERMITE_ALTERAR_NA_LOJA,DATA_PARA_TRANSFERENCIA) 
	SELECT TOP 1 'HR_ATUALIZADOR_FORCA',
				 ?main.p_codigo_filial ,
				 '.T.',
				 '0',
				 GETDATE()
END


IF NOT EXISTS(SELECT 1 FROM PARAMETROS_LOJA WHERE PARAMETRO = 'HR_ATUALIZADOR_URL') 		
BEGIN 
	insert into parametros_Loja(PARAMETRO,CODIGO_FILIAL,VALOR_ATUAL,PERMITE_ALTERAR_NA_LOJA,DATA_PARA_TRANSFERENCIA) 
	SELECT TOP 1  'HR_ATUALIZADOR_URL',
 				  ?main.p_codigo_filial ,
				  'http://atualizaversao.ciahering.com.br:8091/dotUpdateService.asmx',
				  '0',
				  GETDATE() 
END