/* Parte 1 - Implantacao Motor */

-- Criar tabelas 
IF NOT EXISTS ( SELECT 1 FROM SYS.objects WHERE objects.name  = 'HR_PROMOCAO')
 BEGIN
	 EXEC('CREATE TABLE HR_PROMOCAO (
				ID_PROMOCAO	INT NOT NULL,
				DESCRICAO VARCHAR(MAX) NOT NULL,
				REGRA VARCHAR(MAX) NOT NULL,
				CODIGO VARCHAR(MAX) NULL,
				DATA_ATUALIZACAO DATETIME NULL,
				ID_TIPO_PROMOCAO INT,
				INATIVO BIT NOT NULL,
				CLIENTE_IDENTIFICADO BIT NULL,
				EXCLUSIVA BIT NULL,
				UNICA BIT NULL,
				TIPO_VAREJO VARCHAR(MAX) NULL,
				DESCONTO_TIPO_VAREJO NUMERIC(10,2) NULL,
				FRETE_GRATIS BIT,
				ID_VOUCHER VARCHAR(20)
			  CONSTRAINT [PK_HR_LOJA_PROMOCAO] PRIMARY KEY( ID_PROMOCAO ASC )
		)')
 END

 
IF NOT EXISTS(
SELECT 1 FROM SYS.tables A
INNER JOIN SYS.COLUMNS B
ON A.object_id = B.object_id
WHERE A.name ='HR_PROMOCAO' and B.name ='FRETE_GRATIS')
BEGIN
EXEC(' ALTER TABLE HR_PROMOCAO ADD FRETE_GRATIS BIT ')
end

IF NOT EXISTS(
SELECT 1 FROM SYS.tables A
INNER JOIN SYS.COLUMNS B
ON A.object_id = B.object_id
WHERE A.name ='HR_PROMOCAO' and B.name ='ID_VOUCHER')
BEGIN
EXEC(' ALTER TABLE HR_PROMOCAO ADD id_voucher varchar(20) ')
END

 IF NOT EXISTS ( SELECT 1 FROM SYS.objects WHERE objects.name = 'HR_PROMOCAO_LOJAS')
 BEGIN
	EXEC('CREATE TABLE HR_PROMOCAO_LOJAS(
				ID_PROMOCAO	INT,
				CODIGO_FILIAL VARCHAR(6),
				DATA_INICIO	DATETIME,
				DATA_FIM DATETIME
			 CONSTRAINT [PK_HR_PROMOCAO_LOJAS] PRIMARY KEY(ID_PROMOCAO ASC, CODIGO_FILIAL ASC)
		)')

	EXEC('ALTER TABLE HR_PROMOCAO_LOJAS ADD CONSTRAINT [FK_HR_PROMOCAO_LOJAS__HR_PROMOCAO] FOREIGN KEY (ID_PROMOCAO) REFERENCES HR_PROMOCAO(ID_PROMOCAO)')
 END

 
 IF NOT EXISTS ( SELECT 1 FROM SYS.objects WHERE objects.name = 'HR_PROMOCAO_PRODUTOS')
 BEGIN
	 EXEC('CREATE TABLE DBO.[HR_PROMOCAO_PRODUTOS](
				ID_PROMOCAO	INT,
				SEQUENCIA INT,
				PRODUTO	CHAR(12),
				COR_PRODUTO	CHAR(10),
			 CONSTRAINT [PK_HR_PROMOCAO_PRODUTOS] PRIMARY KEY(
				ID_PROMOCAO ASC,
				SEQUENCIA ASC,
				PRODUTO ASC,
				COR_PRODUTO ASC
			)
		)')

	EXEC('ALTER TABLE HR_PROMOCAO_PRODUTOS ADD CONSTRAINT [FK_HR_PROMOCAO_PRODUTOS__HR_PROMOCAO] FOREIGN KEY (ID_PROMOCAO) REFERENCES HR_PROMOCAO(ID_PROMOCAO)')
END


IF NOT EXISTS ( SELECT 1 FROM SYS.objects WHERE objects.name = 'HR_PROMOCAO_SCRIPT')
BEGIN	 
	EXEC('CREATE TABLE HR_PROMOCAO_SCRIPT(
				ID_SCRIPT INT NOT NULL,
				ID_TIPO_PROMOCAO INT NULL,
				DESCRICAO VARCHAR(50) NOT NULL,
				SCRIPT VARCHAR(MAX) NOT NULL,
				ORDEM INT NULL,
			CONSTRAINT [PK_HR_PROMOCAO_SCRIPT] PRIMARY KEY (ID_SCRIPT)
		)')
END

IF EXISTS ( SELECT 1 FROM SYS.OBJECTS WHERE OBJECTS.NAME = 'HR_PROMOCAO_CLIENTE')
BEGIN
	EXEC ('DROP TABLE HR_PROMOCAO_CLIENTE')	 
END
IF NOT EXISTS ( SELECT 1 FROM SYS.OBJECTS WHERE OBJECTS.NAME = 'HR_PROMOCAO_CLIENTE')
BEGIN
	EXEC('CREATE TABLE HR_PROMOCAO_CLIENTE (
			ID_PROMOCAO INT NOT NULL,
			CPF_CLIENTE VARCHAR(20) NOT NULL,
			DATA_HORA DATETIME NOT NULL,
			TIPO CHAR(1) NOT NULL,
		  CONSTRAINT PK_HR_PROMOCAO_CLIENTE PRIMARY KEY (ID_PROMOCAO ASC, CPF_CLIENTE ASC, TIPO ASC)
		 )')
END


IF NOT EXISTS ( SELECT 1 FROM SYS.objects WHERE objects.name = 'HR_PROMOCAO_FORMA_ENTREGA')
BEGIN	
	EXEC('CREATE TABLE [dbo].HR_PROMOCAO_FORMA_ENTREGA (
		[ID_PROMOCAO] [int] NOT NULL,
		[FORMA_ENTREGA] [varchar](50) NOT NULL,
		[DATA_HORA] [datetime] NOT NULL,
	PRIMARY KEY CLUSTERED 
	(
		[ID_PROMOCAO] ASC,
		[FORMA_ENTREGA] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]	')

	EXEC('ALTER TABLE [dbo].HR_PROMOCAO_FORMA_ENTREGA ADD CONSTRAINT [DF_HR_PROMOCAO_FORMA_ENTREGA__DATA_HORA]  DEFAULT (getdate()) FOR [DATA_HORA]')
	
END


IF NOT EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'W_HR_VENDA_TROCA_PRODUTO')
BEGIN
  EXEC ('CREATE VIEW [dbo].[W_HR_VENDA_TROCA_PRODUTO] AS      
	SELECT LVP.CODIGO_FILIAL, LVP.TICKET, LVP.DATA_VENDA, LVP.PRODUTO, LVP.COR_PRODUTO, LVP.QTDE, LVP.PRECO_LIQUIDO, LPV.PEDIDO  
	FROM dbo.LOJA_VENDA_PRODUTO  (NOLOCK) LVP  
	LEFT JOIN LOJA_PEDIDO_VENDA (NOLOCK) LPV ON LVP.CODIGO_FILIAL =LPV.CODIGO_FILIAL AND LVP.TICKET =LPV.TICKET AND LVP.DATA_VENDA = LPV.DATA_VENDA  AND LVP.ITEM =LPV.ITEM_VENDA   
 UNION ALL     
	SELECT LVT.CODIGO_FILIAL, LVT.TICKET, LVT.DATA_VENDA, LVT.PRODUTO, LVT.COR_PRODUTO, (LVT.QTDE * -1) AS QTDE, LVT.PRECO_LIQUIDO  , CONVERT(INT,NULL) AS PEDIDO    
	FROM dbo.LOJA_VENDA_TROCA (NOLOCK) LVT  
 UNION ALL  
	SELECT LP.CODIGO_FILIAL_ORIGEM AS CODIGO_FILIAL,CONVERT(VARCHAR(8),LPV.TICKET) AS TICKET, CONVERT(DATE,LP.DATA) AS DATA_VENDA, LPP.PRODUTO,  LPP.COR_PRODUTO, LPP.QTDE, LPP.PRECO_LIQUIDO, LP.PEDIDO  
	FROM LOJA_PEDIDO (NOLOCK) LP     
	 INNER JOIN LOJA_PEDIDO_PRODUTO (NOLOCK) LPP ON LP.CODIGO_FILIAL_ORIGEM =LPP.CODIGO_FILIAL_ORIGEM AND  LP.PEDIDO =LPP.PEDIDO AND LP.CANCELADO =0 AND LPP.CANCELADO =0		
	 LEFT JOIN LOJA_PEDIDO_VENDA (NOLOCK) LPV  ON LP.CODIGO_FILIAL_ORIGEM = LPV.CODIGO_FILIAL_ORIGEM  AND LP.PEDIDO = LPV.PEDIDO  AND LPP.ITEM = LPV.ITEM     
	WHERE (LPV.TICKET IS NULL or LPP.INDICA_ENTREGA_FUTURA =1)')
 
END
ELSE
BEGIN
  EXEC ('ALTER VIEW [dbo].[W_HR_VENDA_TROCA_PRODUTO] AS      
	SELECT LVP.CODIGO_FILIAL, LVP.TICKET, LVP.DATA_VENDA, LVP.PRODUTO, LVP.COR_PRODUTO, LVP.QTDE, LVP.PRECO_LIQUIDO, LPV.PEDIDO  
	FROM dbo.LOJA_VENDA_PRODUTO  (NOLOCK) LVP  
	LEFT JOIN LOJA_PEDIDO_VENDA (NOLOCK) LPV ON LVP.CODIGO_FILIAL =LPV.CODIGO_FILIAL AND LVP.TICKET =LPV.TICKET AND LVP.DATA_VENDA = LPV.DATA_VENDA  AND LVP.ITEM =LPV.ITEM_VENDA   
 UNION ALL     
	SELECT LVT.CODIGO_FILIAL, LVT.TICKET, LVT.DATA_VENDA, LVT.PRODUTO, LVT.COR_PRODUTO, (LVT.QTDE * -1) AS QTDE, LVT.PRECO_LIQUIDO  , CONVERT(INT,NULL) AS PEDIDO    
	FROM dbo.LOJA_VENDA_TROCA (NOLOCK) LVT  
 UNION ALL  
	SELECT LP.CODIGO_FILIAL_ORIGEM AS CODIGO_FILIAL,CONVERT(VARCHAR(8),LPV.TICKET) AS TICKET, CONVERT(DATE,LP.DATA) AS DATA_VENDA, LPP.PRODUTO,  LPP.COR_PRODUTO, LPP.QTDE, LPP.PRECO_LIQUIDO, LP.PEDIDO  
	FROM LOJA_PEDIDO (NOLOCK) LP     
	 INNER JOIN LOJA_PEDIDO_PRODUTO (NOLOCK) LPP ON LP.CODIGO_FILIAL_ORIGEM =LPP.CODIGO_FILIAL_ORIGEM AND  LP.PEDIDO =LPP.PEDIDO AND LP.CANCELADO =0 AND LPP.CANCELADO =0		
	 LEFT JOIN LOJA_PEDIDO_VENDA (NOLOCK) LPV  ON LP.CODIGO_FILIAL_ORIGEM = LPV.CODIGO_FILIAL_ORIGEM  AND LP.PEDIDO = LPV.PEDIDO  AND LPP.ITEM = LPV.ITEM     
	WHERE (LPV.TICKET IS NULL or LPP.INDICA_ENTREGA_FUTURA =1)')
 
END

IF NOT EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'W_HR_TIPO_VAREJO')
 BEGIN
   EXEC ('CREATE VIEW [dbo].[W_HR_TIPO_VAREJO] AS SELECT RTRIM(LTRIM(TIPO_VAREJO)) TIPO_VAREJO FROM CLIENTE_VAR_TIPOS (NOLOCK)')
 END
ELSE
 BEGIN
   EXEC ('ALTER VIEW [dbo].[W_HR_TIPO_VAREJO] AS SELECT RTRIM(LTRIM(TIPO_VAREJO)) TIPO_VAREJO FROM CLIENTE_VAR_TIPOS (NOLOCK)')
 END

IF NOT EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'W_HR_PROMOCAO')
 BEGIN
   EXEC ('CREATE VIEW [dbo].[W_HR_PROMOCAO] AS SELECT ID_PROMOCAO, DESCRICAO, REGRA, CODIGO, DATA_ATUALIZACAO, ID_TIPO_PROMOCAO, INATIVO, EXCLUSIVA, UNICA, CLIENTE_IDENTIFICADO, TIPO_VAREJO, DESCONTO_TIPO_VAREJO, 0 AS FRETE_GRATIS, ID_VOUCHER, 0 AS UTILIZA_FORMA_PAGAMENTO FROM HR_PROMOCAO (NOLOCK)')
 END
ELSE
 BEGIN
   EXEC ('ALTER VIEW [dbo].[W_HR_PROMOCAO] AS SELECT ID_PROMOCAO, DESCRICAO, REGRA, CODIGO, DATA_ATUALIZACAO, ID_TIPO_PROMOCAO, INATIVO, EXCLUSIVA, UNICA, CLIENTE_IDENTIFICADO, TIPO_VAREJO, DESCONTO_TIPO_VAREJO, 0 AS FRETE_GRATIS, ID_VOUCHER, 0 AS UTILIZA_FORMA_PAGAMENTO FROM HR_PROMOCAO (NOLOCK)')
 END

IF NOT EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'W_HR_PROMOCAO_PRODUTOS')
 BEGIN
   EXEC ('CREATE VIEW [dbo].[W_HR_PROMOCAO_PRODUTOS] AS SELECT ID_PROMOCAO, SEQUENCIA, PRODUTO, COR_PRODUTO FROM dbo.HR_PROMOCAO_PRODUTOS (NOLOCK) WHERE DATA_HORA_INATIVACAO IS NULL')
 END
ELSE
 BEGIN
   EXEC ('ALTER VIEW [dbo].[W_HR_PROMOCAO_PRODUTOS] AS SELECT ID_PROMOCAO, SEQUENCIA, PRODUTO, COR_PRODUTO FROM dbo.HR_PROMOCAO_PRODUTOS (NOLOCK) WHERE DATA_HORA_INATIVACAO IS NULL')
 END

IF NOT EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'W_HR_PROMOCAO_LOJAS')
 BEGIN
   EXEC ('CREATE VIEW [dbo].[W_HR_PROMOCAO_LOJAS] AS SELECT ID_PROMOCAO, CODIGO_FILIAL, DATA_INICIO, DATA_FIM  FROM dbo.HR_PROMOCAO_LOJAS (NOLOCK)')
 END
ELSE
 BEGIN
   EXEC ('ALTER VIEW [dbo].[W_HR_PROMOCAO_LOJAS] AS SELECT ID_PROMOCAO, CODIGO_FILIAL, DATA_INICIO, DATA_FIM  FROM dbo.HR_PROMOCAO_LOJAS (NOLOCK)')
 END

IF NOT EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'W_HR_PROMOCAO_CLIENTE')
 BEGIN
   EXEC ('CREATE VIEW [dbo].[W_HR_PROMOCAO_CLIENTE] AS SELECT ID_PROMOCAO, CPF_CLIENTE, DATA_HORA, TIPO FROM dbo.HR_PROMOCAO_CLIENTE (NOLOCK)')
 END
ELSE
 BEGIN
   EXEC ('ALTER VIEW [dbo].[W_HR_PROMOCAO_CLIENTE] AS SELECT ID_PROMOCAO, CPF_CLIENTE, DATA_HORA, TIPO FROM dbo.HR_PROMOCAO_CLIENTE (NOLOCK)')
 END

IF NOT EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'W_HR_CLIENTES')
 BEGIN
   EXEC ('CREATE VIEW [dbo].[W_HR_CLIENTES] AS SELECT CODIGO_CLIENTE, PF_PJ ,RG_IE, CPF_CGC, TIPO_VAREJO, CLIENTE_VAREJO, CIDADE, UF, CEP, ANIVERSARIO, SEXO, CADASTRAMENTO, 
   	   EMAIL, DATA_PARA_TRANSFERENCIA, ESTADO_CIVIL, PAIS, INATIVO_PARA_CRM, DATA_CRM, DDD_CELULAR, CELULAR, DDD, TELEFONE, SEM_CREDITO FROM dbo.CLIENTES_VAREJO (NOLOCK)')
 END
ELSE
 BEGIN
   EXEC ('ALTER VIEW [dbo].[W_HR_CLIENTES] AS SELECT CODIGO_CLIENTE, PF_PJ ,RG_IE, CPF_CGC, TIPO_VAREJO, CLIENTE_VAREJO, CIDADE, UF, CEP, ANIVERSARIO, SEXO, CADASTRAMENTO, 
   	   EMAIL, DATA_PARA_TRANSFERENCIA, ESTADO_CIVIL, PAIS, INATIVO_PARA_CRM, DATA_CRM, DDD_CELULAR, CELULAR, DDD, TELEFONE, SEM_CREDITO FROM dbo.CLIENTES_VAREJO (NOLOCK)')
 END

 IF NOT EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'W_HR_PROMOCAO_FORMA_ENTREGA')
 BEGIN
   EXEC ('CREATE VIEW W_HR_PROMOCAO_FORMA_ENTREGA AS SELECT T1.ID_PROMOCAO, T1.FORMA_ENTREGA, T1.DATA_HORA FROM HR_PROMOCAO_FORMA_ENTREGA T1')
 END
ELSE
 BEGIN
    EXEC ('ALTER VIEW W_HR_PROMOCAO_FORMA_ENTREGA AS SELECT T1.ID_PROMOCAO, T1.FORMA_ENTREGA, T1.DATA_HORA FROM HR_PROMOCAO_FORMA_ENTREGA T1')
 END
 
 IF NOT EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'W_HR_LOJA_PROMOCAO_LOJAS')
  BEGIN
	EXEC('CREATE VIEW dbo.W_HR_LOJA_PROMOCAO_LOJAS  
		AS  
			SELECT A.ID_PROMOCAO,CONVERT(VARCHAR(253),B.DESCRICAO) AS DESC_PROMOCAO, A.CODIGO_FILIAL, A.DATA_INICIO AS INICIO, A.DATA_FIM AS FIM,
			 REGRA AS DETALHE_PROMOCAO
			FROM HR_PROMOCAO_LOJAS A  
			  INNER JOIN HR_PROMOCAO B ON A.ID_PROMOCAO = B.ID_PROMOCAO  
			WHERE INATIVO = 0')
  END
ELSE
  BEGIN
	EXEC('ALTER VIEW dbo.W_HR_LOJA_PROMOCAO_LOJAS  
		AS  
			SELECT A.ID_PROMOCAO,CONVERT(VARCHAR(253),B.DESCRICAO) AS DESC_PROMOCAO, A.CODIGO_FILIAL, A.DATA_INICIO AS INICIO, A.DATA_FIM AS FIM,
			 REGRA AS DETALHE_PROMOCAO
			FROM HR_PROMOCAO_LOJAS A  
			  INNER JOIN HR_PROMOCAO B ON A.ID_PROMOCAO = B.ID_PROMOCAO  
			WHERE INATIVO = 0')
  END


IF NOT EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'W_HR_VENDA_TROCA_PRODUTO')
 BEGIN
  EXEC ('CREATE VIEW [dbo].[W_HR_VENDA_TROCA_PRODUTO]
AS
SELECT
  LVP.CODIGO_FILIAL,
  LVP.TICKET,
  LVP.DATA_VENDA,
  LVP.PRODUTO,
  LVP.COR_PRODUTO,
  LVP.QTDE,
  LVP.PRECO_LIQUIDO,
  LVP.PRECO_LIQUIDO AS PRECO_BRUTO,
  LPV.PEDIDO,
  LV.CODIGO_CLIENTE
FROM dbo.LOJA_VENDA_PRODUTO(NOLOCK) LVP
INNER JOIN LOJA_VENDA(NOLOCK) LV
  ON LV.CODIGO_FILIAL = LVP.CODIGO_FILIAL
  AND LV.DATA_VENDA = LVP.DATA_VENDA
  AND LV.TICKET = LVP.TICKET
LEFT JOIN LOJA_PEDIDO_VENDA(NOLOCK) LPV
  ON LVP.CODIGO_FILIAL = LPV.CODIGO_FILIAL
  AND LVP.TICKET = LPV.TICKET
  AND LVP.DATA_VENDA = LPV.DATA_VENDA
  AND LVP.ITEM = LPV.ITEM_VENDA
UNION ALL
SELECT
  LVT.CODIGO_FILIAL,
  LVT.TICKET,
  LVT.DATA_VENDA,
  LVT.PRODUTO,
  LVT.COR_PRODUTO,
  (LVT.QTDE * -1) AS QTDE,
  LVT.PRECO_LIQUIDO,
  LVT.PRECO_LIQUIDO AS PRECO_BRUTO,
  CONVERT(int, NULL) AS PEDIDO,
  LV.CODIGO_CLIENTE
FROM dbo.LOJA_VENDA_TROCA(NOLOCK) LVT
INNER JOIN LOJA_VENDA(NOLOCK) LV
  ON LV.CODIGO_FILIAL = LVT.CODIGO_FILIAL
  AND LV.DATA_VENDA = LVT.DATA_VENDA
  AND LV.TICKET = LVT.TICKET
UNION ALL
SELECT
  LP.CODIGO_FILIAL_ORIGEM AS CODIGO_FILIAL,
  CONVERT(varchar(8), LPV.TICKET) AS TICKET,
  CONVERT(date, LP.DATA) AS DATA_VENDA,
  LPP.PRODUTO,
  LPP.COR_PRODUTO,
  LPP.QTDE,
  LPP.PRECO_LIQUIDO,
  LPP.PRECO_LIQUIDO AS PRECO_BRUTO,
  LP.PEDIDO,
  LP.CODIGO_CLIENTE
FROM LOJA_PEDIDO(NOLOCK) LP
INNER JOIN LOJA_PEDIDO_PRODUTO(NOLOCK) LPP
  ON LP.CODIGO_FILIAL_ORIGEM = LPP.CODIGO_FILIAL_ORIGEM
  AND LP.PEDIDO = LPP.PEDIDO
  AND LP.CANCELADO = 0
  AND LPP.CANCELADO = 0
LEFT JOIN LOJA_PEDIDO_VENDA(NOLOCK) LPV
  ON LP.CODIGO_FILIAL_ORIGEM = LPV.CODIGO_FILIAL_ORIGEM
  AND LP.PEDIDO = LPV.PEDIDO
  AND LPP.ITEM = LPV.ITEM
WHERE (LPV.TICKET IS NULL
OR LPP.INDICA_ENTREGA_FUTURA = 1)')
 END
ELSE
 BEGIN
  EXEC ('ALTER VIEW [dbo].[W_HR_VENDA_TROCA_PRODUTO]
AS
SELECT
  LVP.CODIGO_FILIAL,
  LVP.TICKET,
  LVP.DATA_VENDA,
  LVP.PRODUTO,
  LVP.COR_PRODUTO,
  LVP.QTDE,
  LVP.PRECO_LIQUIDO,
  LVP.PRECO_LIQUIDO AS PRECO_BRUTO,
  LPV.PEDIDO,
  LV.CODIGO_CLIENTE
FROM dbo.LOJA_VENDA_PRODUTO(NOLOCK) LVP
INNER JOIN LOJA_VENDA(NOLOCK) LV
  ON LV.CODIGO_FILIAL = LVP.CODIGO_FILIAL
  AND LV.DATA_VENDA = LVP.DATA_VENDA
  AND LV.TICKET = LVP.TICKET
LEFT JOIN LOJA_PEDIDO_VENDA(NOLOCK) LPV
  ON LVP.CODIGO_FILIAL = LPV.CODIGO_FILIAL
  AND LVP.TICKET = LPV.TICKET
  AND LVP.DATA_VENDA = LPV.DATA_VENDA
  AND LVP.ITEM = LPV.ITEM_VENDA
UNION ALL
SELECT
  LVT.CODIGO_FILIAL,
  LVT.TICKET,
  LVT.DATA_VENDA,
  LVT.PRODUTO,
  LVT.COR_PRODUTO,
  (LVT.QTDE * -1) AS QTDE,
  LVT.PRECO_LIQUIDO,
  LVT.PRECO_LIQUIDO AS PRECO_BRUTO,
  CONVERT(int, NULL) AS PEDIDO,
  LV.CODIGO_CLIENTE
FROM dbo.LOJA_VENDA_TROCA(NOLOCK) LVT
INNER JOIN LOJA_VENDA(NOLOCK) LV
  ON LV.CODIGO_FILIAL = LVT.CODIGO_FILIAL
  AND LV.DATA_VENDA = LVT.DATA_VENDA
  AND LV.TICKET = LVT.TICKET
UNION ALL
SELECT
  LP.CODIGO_FILIAL_ORIGEM AS CODIGO_FILIAL,
  CONVERT(varchar(8), LPV.TICKET) AS TICKET,
  CONVERT(date, LP.DATA) AS DATA_VENDA,
  LPP.PRODUTO,
  LPP.COR_PRODUTO,
  LPP.QTDE,
  LPP.PRECO_LIQUIDO,
  LPP.PRECO_LIQUIDO AS PRECO_BRUTO,
  LP.PEDIDO,
  LP.CODIGO_CLIENTE
FROM LOJA_PEDIDO(NOLOCK) LP
INNER JOIN LOJA_PEDIDO_PRODUTO(NOLOCK) LPP
  ON LP.CODIGO_FILIAL_ORIGEM = LPP.CODIGO_FILIAL_ORIGEM
  AND LP.PEDIDO = LPP.PEDIDO
  AND LP.CANCELADO = 0
  AND LPP.CANCELADO = 0
LEFT JOIN LOJA_PEDIDO_VENDA(NOLOCK) LPV
  ON LP.CODIGO_FILIAL_ORIGEM = LPV.CODIGO_FILIAL_ORIGEM
  AND LP.PEDIDO = LPV.PEDIDO
  AND LPP.ITEM = LPV.ITEM
WHERE (LPV.TICKET IS NULL
OR LPP.INDICA_ENTREGA_FUTURA = 1)')
 END


 -- Criar Campos novos 

IF NOT EXISTS (SELECT 1 FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID('LOJA_PEDIDO_PRODUTO') AND NAME = 'HR_PRECO_PERSONALIZACAO')
	EXEC('ALTER TABLE LOJA_PEDIDO_PRODUTO ADD HR_PRECO_PERSONALIZACAO NUMERIC(14,2) NULL')
IF NOT EXISTS (SELECT 1 FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID('HR_PROMOCAO') AND NAME = 'CLIENTE_IDENTIFICADO')
	EXEC('ALTER TABLE HR_PROMOCAO ADD CLIENTE_IDENTIFICADO BIT NULL')
IF NOT EXISTS (SELECT 1 FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID('HR_PROMOCAO') AND NAME = 'EXCLUSIVA')
	EXEC('ALTER TABLE HR_PROMOCAO ADD EXCLUSIVA BIT NULL')
IF NOT EXISTS (SELECT 1 FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID('HR_PROMOCAO') AND NAME = 'UNICA')
	EXEC('ALTER TABLE HR_PROMOCAO ADD UNICA BIT NULL')
IF NOT EXISTS (SELECT 1 FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID('HR_PROMOCAO') AND NAME = 'TIPO_VAREJO')
	EXEC('ALTER TABLE HR_PROMOCAO ADD TIPO_VAREJO VARCHAR(MAX) NULL')
IF NOT EXISTS (SELECT 1 FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID('HR_PROMOCAO') AND NAME = 'DESCONTO_TIPO_VAREJO')
	EXEC('ALTER TABLE HR_PROMOCAO ADD DESCONTO_TIPO_VAREJO NUMERIC(10,2) NULL')


 IF NOT EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'FN_SPLITSTRING')
 BEGIN
 EXEC('CREATE FUNCTION DBO.FN_SPLITSTRING ( @STRINGTOSPLIT VARCHAR(MAX), @SEPARATOR VARCHAR(20) )
RETURNS @RETURNLIST TABLE ([NAME] [NVARCHAR] (500))
AS
BEGIN

 DECLARE @NAME NVARCHAR(255)
 DECLARE @POS INT

 WHILE CHARINDEX(@SEPARATOR, @STRINGTOSPLIT) > 0
 BEGIN
  SELECT @POS  = CHARINDEX(@SEPARATOR, @STRINGTOSPLIT)  
  SELECT @NAME = SUBSTRING(@STRINGTOSPLIT, 1, @POS-1)

  INSERT INTO @RETURNLIST 
  SELECT @NAME

  SELECT @STRINGTOSPLIT = SUBSTRING(@STRINGTOSPLIT, @POS+1, LEN(@STRINGTOSPLIT)-@POS)
 END

 INSERT INTO @RETURNLIST
 SELECT @STRINGTOSPLIT

 RETURN
END')
 END

 IF NOT EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'SP_HR_PROMOCAO')
 BEGIN
	exec('	CREATE PROCEDURE DBO.SP_HR_PROMOCAO (@CODIGO_FILIAL CHAR(6), @TICKET VARCHAR(8) = NULL, @DATA_VENDA DATETIME, @PEDIDO INT = NULL, @CPF_CLIENTE VARCHAR(20) = NULL, @FORMA_ENTREGA VARCHAR(50) = '''') 
	AS 
	BEGIN
		DECLARE @TBL_LST TABLE (    ID_LISTA int,    QTD_GATILHO int  )  DECLARE @TBL_LISTA TABLE (    ID_LISTA int,    QTD_GATILHO int,    PRODUTO char(12),    COR_PRODUTO char(10)  )  DECLARE @TBL_FINAL TABLE (    ID_PROMOCAO int,    DATA_INICIO datetime,    DATA_FIM datetime,    MESG varchar(max),    DESCONTOPROM numeric(14, 2),    TIPO int,    GERA_TICKET bit,    QUANTIDADE_VOUCHER int,    VALIDADE_VOUCHER datetime,    TIPO_VOUCHER int /*3= VALOR / 4= PORCENTAGEM*/,    VALOR_VOUCHER numeric(14, 2),    TEXTO_CAMPANHA varchar(max),    CODIGO_VOUCHER varchar(20),    TIPO_GATILHO_RESGATE int,    VALOR_GATILHO_RESGATE numeric(18, 2),    BRINDE bit default 0,    FRETE_GRATIS bit default 0,    FRETE_GRATIS_EXTRA bit default 0  );  DECLARE @TBL_LOOP TABLE (    CODIGO_FILIAL char(6),    TICKET char(8),    DATA_VENDA datetime,    PRODUTO char(12),    COR_PRODUTO char(10),    QTDE numeric(14, 2),    PRECO_LIQUIDO numeric(14, 2),    PRECO_BRUTO numeric(14, 2),    UTILIZADO bit,    LINHA int  );  DECLARE @TBL_VENDA TABLE (    CODIGO_FILIAL char(6),    TICKET char(8),    DATA_VENDA datetime,    PRODUTO char(12),    COR_PRODUTO char(10),    QTDE numeric(14, 2),    PRECO_LIQUIDO numeric(14, 2),    PRECO_BRUTO numeric(14, 2),    UTILIZADO bit,    LINHA int  );  DECLARE @TBL_VENDA_FIM TABLE (    CODIGO_FILIAL char(6),    TICKET char(8),    DATA_VENDA datetime,    PRODUTO char(12),    COR_PRODUTO char(10),    QTDE numeric(14, 2),    PRECO_LIQUIDO numeric(14, 2),    PRECO_BRUTO numeric(14, 2)  );  DECLARE @TBL_PROVISORIA TABLE (    LINHA int,    CODIGO_FILIAL char(6),    TICKET char(8),    DATA_VENDA datetime,    PRODUTO char(12),    COR_PRODUTO char(10),    QTDE numeric(14, 2),    PRECO_LIQUIDO numeric(14, 2),    PRECO_BRUTO numeric(14, 2),    UTILIZADO bit  );  DECLARE @TBL_PROVISORIA_LOOK TABLE (    LINHA int,    CODIGO_FILIAL char(6),    TICKET char(8),    DATA_VENDA datetime,    PRODUTO char(12),    COR_PRODUTO char(10),    QTDE numeric(14, 2),    PRECO_LIQUIDO numeric(14, 2),    PRECO_BRUTO numeric(14, 2)  );  DECLARE @TBL_GATILHO_LOOK TABLE (    ID_SEQUENCIAL int,    ID_LISTA int,    QTD_GATILHO int,    QTDE numeric(12, 2)  )  DECLARE @TBL_FORMAS_ENTREGA TABLE (   FORMA_ENTREGA VARCHAR(50)  )  DECLARE @IND_MULTIPLO int,          @TOTAL_MULTIPLO int,          @VALOR_MULTIPLO numeric(18, 2),          @TOTAL_MULTIPLO_TROCA int,          @DESCONTO numeric(18, 2),          @QTDE int,          @TOP int,          @QTD_GATILHO numeric(12, 2),          @VLR_PRODUTO_PROMO numeric(12, 2),          @IND_GATILHO int,          @TEM_GATILHO_LOOK bit,          @ID_PROMO_EXTRA int = 0,          @CPF varchar(20) = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(@CPF_CLIENTE, ''.'', ''''), ''/'', ''''), ''\'', ''''), ''-'', ''''), '' '', ''''),          @CLIENTE_IDENTIFICADO bit = 0,          @EXCLUSIVA bit = 0,          @UNICA bit = 0,          @TIPO_VAREJO_VALIDO bit = 0  DECLARE @TIPO_VAREJO varchar(25) = (SELECT TOP 1    TIPO_VAREJO  FROM W_HR_CLIENTES  WHERE CPF_CGC = @CPF  ORDER BY W_HR_CLIENTES.DATA_PARA_TRANSFERENCIA DESC)  DECLARE @DESCONTO_TIPO_VAREJO numeric(14, 2),          @ID_PROMO_TV int,          @DATA_INICIO_TV datetime,          @DATA_FIM_TV datetime,          @DESCRICAO_TV varchar(max),          @DESCONTO_TIPO_VAREJO_CHECK numeric(14, 2)  SELECT TOP 1    @DESCONTO_TIPO_VAREJO = T1.DESCONTO_TIPO_VAREJO / 100,    @ID_PROMO_TV = T1.ID_PROMOCAO,    @DATA_INICIO_TV = T2.DATA_INICIO,    @DATA_FIM_TV = T2.DATA_FIM,    @DESCRICAO_TV = T1.DESCRICAO  FROM W_HR_PROMOCAO T1  JOIN W_HR_PROMOCAO_LOJAS T2    ON T2.ID_PROMOCAO = T1.ID_PROMOCAO  WHERE T2.CODIGO_FILIAL = @CODIGO_FILIAL  AND @DATA_VENDA BETWEEN T2.DATA_INICIO AND T2.DATA_FIM  AND T1.ID_TIPO_PROMOCAO = 10  AND EXISTS (SELECT    NAME  FROM FN_SPLITSTRING(T1.TIPO_VAREJO, '','')  WHERE NAME = @TIPO_VAREJO)  ORDER BY DESCONTO_TIPO_VAREJO DESC  INSERT INTO @TBL_VENDA    SELECT      CODIGO_FILIAL,      ISNULL(TICKET, ''''),      DATA_VENDA,      W_HR_VENDA_TROCA_PRODUTO.PRODUTO,      COR_PRODUTO,      SUM(QTDE),      PRECO_LIQUIDO,      CASE        WHEN PRECO_BRUTO > PRECO_LIQUIDO THEN PRECO_BRUTO - (PRECO_BRUTO * ISNULL(@DESCONTO_TIPO_VAREJO, 0))        ELSE PRECO_LIQUIDO      END,      0,      0    FROM W_HR_VENDA_TROCA_PRODUTO    INNER JOIN PRODUTOS      ON W_HR_VENDA_TROCA_PRODUTO.PRODUTO = PRODUTOS.PRODUTO    WHERE CODIGO_FILIAL = @CODIGO_FILIAL    AND (TICKET = @TICKET    OR PEDIDO = @PEDIDO)    AND DATA_VENDA = @DATA_VENDA    AND QTDE != 0    AND PRODUTOS.UNIDADE != ''KG''    GROUP BY CODIGO_FILIAL,             TICKET,             DATA_VENDA,             W_HR_VENDA_TROCA_PRODUTO.PRODUTO,             COR_PRODUTO,             PRECO_LIQUIDO,             PRECO_BRUTO  IF ISNULL(@ID_PROMO_TV, 0) != 0  BEGIN    INSERT INTO @TBL_FINAL      SELECT        @ID_PROMO_TV,        @DATA_INICIO_TV,        @DATA_FIM_TV,        @DESCRICAO_TV,        0,        10 AS TIPO_PROMOCAO,        CONVERT(bit, 0) AS GERA_TICKET,        0 QUANTIDADE_VOUCHER,        NULL VALIDADE_VOUCHER,        NULL TIPO_VOUCHER,        NULL VALOR_VOUCHER,        NULL TEXTO_CAMPANHA,        NULL CODIGO_VOUCHER,        NULL TIPO_GATILHO_RESGATE,        NULL VALOR_GATILHO_RESGATE,     CONVERT(bit, 0) AS BRINDE,     CONVERT(BIT, 0) AS FRETE_GRATIS,     CONVERT(BIT, 0) AS FRETE_GRATIS_EXTRA  END  WHILE EXISTS (SELECT      *    FROM @TBL_VENDA    WHERE ABS(QTDE) > 1)  BEGIN    DELETE FROM @TBL_LOOP;    INSERT INTO @TBL_LOOP      SELECT TOP 1        *      FROM @TBL_VENDA      WHERE ABS(QTDE) > 1;    SET @QTDE = (SELECT      ABS(QTDE)    FROM @TBL_LOOP);    IF (@QTDE > 1)    BEGIN      INSERT INTO @TBL_VENDA        SELECT          CODIGO_FILIAL,          TICKET,          DATA_VENDA,          PRODUTO,          COR_PRODUTO,          CASE            WHEN QTDE < 0 THEN -1            ELSE 1          END,          PRECO_LIQUIDO,          PRECO_BRUTO,          0,          (SELECT            COUNT(*)          FROM @TBL_VENDA T2          WHERE T1.PRODUTO = T2.PRODUTO          AND T1.COR_PRODUTO = T2.COR_PRODUTO)        FROM @TBL_LOOP T1;      UPDATE T1      SET T1.QTDE =                   CASE                     WHEN T1.QTDE < 0 THEN T1.QTDE + 1                     ELSE T1.QTDE - 1                   END      FROM @TBL_VENDA AS T1      INNER JOIN @TBL_LOOP AS T2        ON T1.CODIGO_FILIAL = T2.CODIGO_FILIAL        AND T1.TICKET = T2.TICKET        AND T1.DATA_VENDA = T2.DATA_VENDA        AND T1.PRODUTO = T2.PRODUTO        AND T1.COR_PRODUTO = T2.COR_PRODUTO        AND T1.QTDE = T2.QTDE      SET @QTDE = @QTDE - 1;    END  END  UPDATE @TBL_VENDA  SET LINHA = LINHA + 1    /* QUILO START */  INSERT INTO @TBL_VENDA    SELECT      CODIGO_FILIAL,      TICKET,      DATA_VENDA,      W_HR_VENDA_TROCA_PRODUTO.PRODUTO,      COR_PRODUTO,      SUM(QTDE),      SUM(QTDE) * PRECO_LIQUIDO,      SUM(QTDE) * PRECO_LIQUIDO,      1,      1    FROM W_HR_VENDA_TROCA_PRODUTO    INNER JOIN PRODUTOS      ON W_HR_VENDA_TROCA_PRODUTO.PRODUTO = PRODUTOS.PRODUTO    WHERE CODIGO_FILIAL = @CODIGO_FILIAL    AND (TICKET = @TICKET    OR PEDIDO = @PEDIDO)    AND DATA_VENDA = @DATA_VENDA    AND QTDE != 0    AND PRODUTOS.UNIDADE = ''KG''    GROUP BY CODIGO_FILIAL,             TICKET,             DATA_VENDA,             W_HR_VENDA_TROCA_PRODUTO.PRODUTO,             COR_PRODUTO,             PRECO_LIQUIDO  /* QUILO END*/  UPDATE @TBL_VENDA  SET PRECO_LIQUIDO = (PRECO_LIQUIDO * -1)  WHERE QTDE = -1
		
		IF EXISTS (SELECT * FROM @TBL_VENDA T1 WHERE PRECO_LIQUIDO > PRECO_BRUTO AND UTILIZADO = 0)  BEGIN    UPDATE @TBL_FINAL SET DESCONTOPROM = DESCONTOPROM + (SELECT SUM(PRECO_LIQUIDO * QTDE) - SUM(PRECO_BRUTO * QTDE) FROM @TBL_VENDA T1 WHERE PRECO_LIQUIDO > PRECO_BRUTO AND UTILIZADO = 0)   WHERE ID_PROMOCAO = @ID_PROMO_TV  END    SELECT DISTINCT   ID_PROMOCAO     ,DATA_INICIO     ,DATA_FIM     ,MESG     ,DESCONTOPROM     ,TIPO     ,GERA_TICKET     ,QUANTIDADE_VOUCHER     ,VALIDADE_VOUCHER     ,TIPO_VOUCHER     ,VALOR_VOUCHER     ,TEXTO_CAMPANHA     ,CODIGO_VOUCHER     ,TIPO_GATILHO_RESGATE     ,VALOR_GATILHO_RESGATE     ,BRINDE  FROM @TBL_FINAL  WHERE (DESCONTOPROM > 0  OR GERA_TICKET = 1  OR BRINDE = 1)
	END
')
 END

 IF EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE OBJECTS.NAME = 'FC_CODIFICAVOUCHER')
BEGIN
	EXEC ('DROP FUNCTION FC_CODIFICAVOUCHER')	 
END
IF NOT EXISTS ( SELECT 1 FROM SYS.OBJECTS WHERE OBJECTS.NAME = 'FC_CODIFICAVOUCHER')
BEGIN
	EXEC('
	CREATE FUNCTION [dbo].[FC_CODIFICAVOUCHER] (@DATA DATETIME, @CODIGO_FILIAL VARCHAR(10), @TICKET VARCHAR(10), @ID_PROMOCAO INT)                  
 RETURNS VARCHAR (50)                  
AS                  
BEGIN                 

 DECLARE @LANCAMENTO_CAIXA VARCHAR (7)
 DECLARE @TERMINAL VARCHAR (3)

 SELECT @TERMINAL = TERMINAL, @LANCAMENTO_CAIXA = LANCAMENTO_CAIXA
 FROM LOJA_VENDA (NOLOCK) 
 WHERE TICKET = @TICKET AND CODIGO_FILIAL = @CODIGO_FILIAL AND DATA_VENDA = @DATA

 IF @LANCAMENTO_CAIXA IS NULL --Compatibilidade com a versão anterior quando era passado GETDATE ao invés de DATA_VENDA
	SELECT TOP 1 @LANCAMENTO_CAIXA = LANCAMENTO_CAIXA, @TERMINAL = TERMINAL 
	FROM LOJA_VENDA (NOLOCK) 
	WHERE TICKET = @TICKET AND CODIGO_FILIAL = @CODIGO_FILIAL
	ORDER BY DATA_VENDA DESC

 RETURN ''VC_BF_'' + 
 RIGHT(''000'' + RTRIM(@CODIGO_FILIAL), 4) + 
 @LANCAMENTO_CAIXA +
 RTRIM(@TERMINAL)
 
END')
END