IF NOT EXISTS(SELECT 1
          FROM   INFORMATION_SCHEMA.COLUMNS
          WHERE  TABLE_NAME = 'LOJA_MOTIVOS_DESCONTO'
                 AND COLUMN_NAME = 'HR_GERENTE')
BEGIN
  ALTER TABLE LOJA_MOTIVOS_DESCONTO
    ADD HR_GERENTE [BIT]
END 


Exec('UPDATE LOJA_MOTIVOS_DESCONTO SET HR_GERENTE =1 WHERE HR_GERENTE IS NULL')


IF NOT EXISTS(SELECT 1
          FROM   INFORMATION_SCHEMA.COLUMNS
          WHERE  TABLE_NAME = 'LOJA_MOTIVOS_DESCONTO'
                 AND COLUMN_NAME = 'INATIVO')
BEGIN
  ALTER TABLE LOJA_MOTIVOS_DESCONTO
    ADD INATIVO [BIT]
END 
