CREATE PROCEDURE [DBO].[SP_GETNEXTGRPR] (@STRFILIAL VARCHAR(25), @STRSERIENF CHAR(3), @BUPDATE BIT = 1 , @GERAR INT =0, @ID_PROMOCAO INT = NULL)
	WITH ENCRYPTION 
AS
BEGIN
	SET NOCOUNT ON
	
	DECLARE @BSEQUENCIALPORFILIAL BIT, @STRSEQUENCIAL VARCHAR(6), @CODIGFILIAL VARCHAR(6), @STRCODE VARCHAR(20)

	SELECT @BSEQUENCIALPORFILIAL = SEQUENCIAL_POR_FILIAL FROM SERIES_NF WHERE SERIE_NF = @STRSERIENF
	SELECT @CODIGFILIAL = COD_FILIAL FROM FILIAIS WHERE FILIAL  = @STRFILIAL
	
	IF @BSEQUENCIALPORFILIAL = 1 AND @GERAR=1
	BEGIN
		IF NOT EXISTS(SELECT 1 FROM FATURAMENTO_SEQUENCIAIS WHERE FILIAL = @STRFILIAL AND SERIE_NF = @STRSERIENF)
		BEGIN
			SELECT @STRSEQUENCIAL = '000001'
			IF @BUPDATE = 1
				INSERT INTO FATURAMENTO_SEQUENCIAIS (FILIAL, SERIE_NF, SEQUENCIAL) VALUES (@STRFILIAL, @STRSERIENF, @STRSEQUENCIAL)
		END
		ELSE
		BEGIN
			SELECT 
				@STRSEQUENCIAL = REPLACE(STR(ISNULL(CONVERT(INT, SEQUENCIAL), 0) + 1, 6), ' ', '0') 
			FROM 
				FATURAMENTO_SEQUENCIAIS (NOLOCK) 
			WHERE 
				FILIAL = @STRFILIAL AND SERIE_NF = @STRSERIENF

			WHILE EXISTS(SELECT 1 FROM LOJA_EVENTOS_LOG A INNER JOIN LOJAS_VAREJO B ON A.CODIGO_FILIAL = B.CODIGO_FILIAL WHERE B.FILIAL = @STRFILIAL and TIPO_EVENTO ='98' and A.HISTORICO = @STRSEQUENCIAL)
				SELECT @STRSEQUENCIAL = REPLACE(STR(CONVERT(INT, @STRSEQUENCIAL) + 1, 6), ' ', '0') 
			IF @BUPDATE	= 1
				UPDATE FATURAMENTO_SEQUENCIAIS SET SEQUENCIAL = @STRSEQUENCIAL WHERE FILIAL = @STRFILIAL AND SERIE_NF = @STRSERIENF
		END
		SELECT @STRSEQUENCIAL AS INTEIRA ,DBO.FC_CODIFICAPROMO(@CODIGFILIAL,@STRSEQUENCIAL) AS SEQUENCIAL
	END
		ELSE
		BEGIN
			SELECT @STRCODE=CODIGO fROM HR_LOJA_PROMOCAO_CUPOM_LOJA A
			WHERE CODIGO_FILIAL = @CODIGFILIAL
			AND A.DATA IS NULL
			
			UPDATE HR_LOJA_PROMOCAO_CUPOM_LOJA SET DATA = CONVERT(DATE,GETDATE()) WHERE CODIGO_FILIAL = @CODIGFILIAL AND CODIGO=@STRCODE 
			
			SELECT @STRCODE AS INTEIRA , @STRCODE AS SEQUENCIAL
		END
	SET NOCOUNT OFF
END