IF  EXISTS (SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[LOJA_SAIDAS_ORIGEM]') AND NAME = N'XPKLOJA_SAIDAS_ORIGEM')
BEGIN
ALTER TABLE [DBO].[LOJA_SAIDAS_ORIGEM] DROP CONSTRAINT [XPKLOJA_SAIDAS_ORIGEM]
END

IF  EXISTS (SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[LOJA_SAIDAS_ORIGEM]') )
BEGIN
ALTER TABLE LOJA_SAIDAS_ORIGEM ALTER COLUMN ROMANEIO_PRODUTO_ENTRADA CHAR(15) NOT NULL
END

IF NOT EXISTS (SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[LOJA_SAIDAS_ORIGEM]') AND NAME = N'XPKLOJA_SAIDAS_ORIGEM')
BEGIN
ALTER TABLE [DBO].[LOJA_SAIDAS_ORIGEM] ADD  CONSTRAINT [XPKLOJA_SAIDAS_ORIGEM] PRIMARY KEY CLUSTERED 
(
	[ROMANEIO_PRODUTO] ASC,
	[FILIAL] ASC,
	[PRODUTO] ASC,
	[COR_PRODUTO] ASC,
	[ROMANEIO_PRODUTO_ENTRADA] ASC,
	[FILIAL_ENTRADA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
END