
IF NOT EXISTS(SELECT 1 FROM PARAMETROS WHERE PARAMETRO = 'HR_TITULO_PROMO') 		
BEGIN
INSERT INTO PARAMETROS(PARAMETRO,DESC_PARAMETRO,VALOR_ATUAL,TIPO_DADO,
			GLOBAL,ESCOPO,POR_USUARIO_OK,PERMITE_POR_EMPRESA,
			ENVIA_PARA_LOJA,PERMITE_POR_LOJA,PERMITE_POR_TERMINAL,
			PERMITE_ALTERAR_NA_LOJA,PERMITE_ALTERAR_NO_TERMINAL,
			ENVIA_PARA_REPRESENTANTE,PERMITE_POR_REPRESENTANTE,
			PERMITE_ALTERAR_NO_REPRESENTANTE,PENULT_ATUALIZACAO,
			ULT_ATUALIZACAO,DATA_PARA_TRANSFERENCIA)
VALUES('HR_TITULO_PROMO','Titulo do Ticket de Promocao Hering','PROMOÇÃO 135 ANOS HERING','C',
  	   0,0,0,0,1,1,0,0,0,0,0,0,GETDATE(),GETDATE(),GETDATE())
END  	   

IF NOT EXISTS(SELECT 1 FROM PARAMETROS WHERE PARAMETRO = 'HR_MSG01_PROMO') 		
BEGIN
INSERT INTO PARAMETROS(PARAMETRO,DESC_PARAMETRO,VALOR_ATUAL,TIPO_DADO,
			GLOBAL,ESCOPO,POR_USUARIO_OK,PERMITE_POR_EMPRESA,
			ENVIA_PARA_LOJA,PERMITE_POR_LOJA,PERMITE_POR_TERMINAL,
			PERMITE_ALTERAR_NA_LOJA,PERMITE_ALTERAR_NO_TERMINAL,
			ENVIA_PARA_REPRESENTANTE,PERMITE_POR_REPRESENTANTE,
			PERMITE_ALTERAR_NO_REPRESENTANTE,PENULT_ATUALIZACAO,
			ULT_ATUALIZACAO,DATA_PARA_TRANSFERENCIA)
VALUES('HR_MSG01_PROMO','Mensagem linha 1 do ticket de promocao',' ','C',
  	   0,0,0,0,1,1,0,0,0,0,0,0,GETDATE(),GETDATE(),GETDATE())
END  	


IF NOT EXISTS(SELECT 1 FROM PARAMETROS WHERE PARAMETRO = 'HR_MSG02_PROMO') 		
BEGIN
INSERT INTO PARAMETROS(PARAMETRO,DESC_PARAMETRO,VALOR_ATUAL,TIPO_DADO,
			GLOBAL,ESCOPO,POR_USUARIO_OK,PERMITE_POR_EMPRESA,
			ENVIA_PARA_LOJA,PERMITE_POR_LOJA,PERMITE_POR_TERMINAL,
			PERMITE_ALTERAR_NA_LOJA,PERMITE_ALTERAR_NO_TERMINAL,
			ENVIA_PARA_REPRESENTANTE,PERMITE_POR_REPRESENTANTE,
			PERMITE_ALTERAR_NO_REPRESENTANTE,PENULT_ATUALIZACAO,
			ULT_ATUALIZACAO,DATA_PARA_TRANSFERENCIA)
VALUES('HR_MSG02_PROMO','Mensagem linha 2 do ticket de promocao codigo ',' ','C',
  	   0,0,0,0,1,1,0,0,0,0,0,0,GETDATE(),GETDATE(),GETDATE())
END  	


IF NOT EXISTS(SELECT 1 FROM PARAMETROS WHERE PARAMETRO = 'HR_MSG03_PROMO') 		
BEGIN
INSERT INTO PARAMETROS(PARAMETRO,DESC_PARAMETRO,VALOR_ATUAL,TIPO_DADO,
			GLOBAL,ESCOPO,POR_USUARIO_OK,PERMITE_POR_EMPRESA,
			ENVIA_PARA_LOJA,PERMITE_POR_LOJA,PERMITE_POR_TERMINAL,
			PERMITE_ALTERAR_NA_LOJA,PERMITE_ALTERAR_NO_TERMINAL,
			ENVIA_PARA_REPRESENTANTE,PERMITE_POR_REPRESENTANTE,
			PERMITE_ALTERAR_NO_REPRESENTANTE,PENULT_ATUALIZACAO,
			ULT_ATUALIZACAO,DATA_PARA_TRANSFERENCIA)
VALUES('HR_MSG03_PROMO','Mensagem linha 3 do ticket de promocao',' ','C',
  	   0,0,0,0,1,1,0,0,0,0,0,0,GETDATE(),GETDATE(),GETDATE())
END  	


IF NOT EXISTS(SELECT 1 FROM PARAMETROS WHERE PARAMETRO = 'HR_MSG04_PROMO') 		
BEGIN
INSERT INTO PARAMETROS(PARAMETRO,DESC_PARAMETRO,VALOR_ATUAL,TIPO_DADO,
			GLOBAL,ESCOPO,POR_USUARIO_OK,PERMITE_POR_EMPRESA,
			ENVIA_PARA_LOJA,PERMITE_POR_LOJA,PERMITE_POR_TERMINAL,
			PERMITE_ALTERAR_NA_LOJA,PERMITE_ALTERAR_NO_TERMINAL,
			ENVIA_PARA_REPRESENTANTE,PERMITE_POR_REPRESENTANTE,
			PERMITE_ALTERAR_NO_REPRESENTANTE,PENULT_ATUALIZACAO,
			ULT_ATUALIZACAO,DATA_PARA_TRANSFERENCIA)
VALUES('HR_MSG04_PROMO','Mensagem linha 4 do ticket de promocao',' ','C',
  	   0,0,0,0,1,1,0,0,0,0,0,0,GETDATE(),GETDATE(),GETDATE())
END  	


IF NOT EXISTS(SELECT 1 FROM PARAMETROS WHERE PARAMETRO = 'HR_MSG05_PROMO') 		
BEGIN
INSERT INTO PARAMETROS(PARAMETRO,DESC_PARAMETRO,VALOR_ATUAL,TIPO_DADO,
			GLOBAL,ESCOPO,POR_USUARIO_OK,PERMITE_POR_EMPRESA,
			ENVIA_PARA_LOJA,PERMITE_POR_LOJA,PERMITE_POR_TERMINAL,
			PERMITE_ALTERAR_NA_LOJA,PERMITE_ALTERAR_NO_TERMINAL,
			ENVIA_PARA_REPRESENTANTE,PERMITE_POR_REPRESENTANTE,
			PERMITE_ALTERAR_NO_REPRESENTANTE,PENULT_ATUALIZACAO,
			ULT_ATUALIZACAO,DATA_PARA_TRANSFERENCIA)
VALUES('HR_MSG05_PROMO','Mensagem linha 5 do ticket de promocao',' ','C',
  	   0,0,0,0,1,1,0,0,0,0,0,0,GETDATE(),GETDATE(),GETDATE())
END  	

IF NOT EXISTS(SELECT 1 FROM PARAMETROS WHERE PARAMETRO = 'HR_MSG06_PROMO') 		
BEGIN
INSERT INTO PARAMETROS(PARAMETRO,DESC_PARAMETRO,VALOR_ATUAL,TIPO_DADO,
			GLOBAL,ESCOPO,POR_USUARIO_OK,PERMITE_POR_EMPRESA,
			ENVIA_PARA_LOJA,PERMITE_POR_LOJA,PERMITE_POR_TERMINAL,
			PERMITE_ALTERAR_NA_LOJA,PERMITE_ALTERAR_NO_TERMINAL,
			ENVIA_PARA_REPRESENTANTE,PERMITE_POR_REPRESENTANTE,
			PERMITE_ALTERAR_NO_REPRESENTANTE,PENULT_ATUALIZACAO,
			ULT_ATUALIZACAO,DATA_PARA_TRANSFERENCIA)
VALUES('HR_MSG06_PROMO','Mensagem linha 6 do ticket de promocao',' ','C',
  	   0,0,0,0,1,1,0,0,0,0,0,0,GETDATE(),GETDATE(),GETDATE())
END  	


IF NOT EXISTS(SELECT 1 FROM PARAMETROS WHERE PARAMETRO = 'HR_MSG07_PROMO') 		
BEGIN
INSERT INTO PARAMETROS(PARAMETRO,DESC_PARAMETRO,VALOR_ATUAL,TIPO_DADO,
			GLOBAL,ESCOPO,POR_USUARIO_OK,PERMITE_POR_EMPRESA,
			ENVIA_PARA_LOJA,PERMITE_POR_LOJA,PERMITE_POR_TERMINAL,
			PERMITE_ALTERAR_NA_LOJA,PERMITE_ALTERAR_NO_TERMINAL,
			ENVIA_PARA_REPRESENTANTE,PERMITE_POR_REPRESENTANTE,
			PERMITE_ALTERAR_NO_REPRESENTANTE,PENULT_ATUALIZACAO,
			ULT_ATUALIZACAO,DATA_PARA_TRANSFERENCIA)
VALUES('HR_MSG07_PROMO','Mensagem linha 7 do ticket de promocao',' ','C',
  	   0,0,0,0,1,1,0,0,0,0,0,0,GETDATE(),GETDATE(),GETDATE())
END  	


IF NOT EXISTS(SELECT 1 FROM PARAMETROS WHERE PARAMETRO = 'HR_MSG08_PROMO') 		
BEGIN
INSERT INTO PARAMETROS(PARAMETRO,DESC_PARAMETRO,VALOR_ATUAL,TIPO_DADO,
			GLOBAL,ESCOPO,POR_USUARIO_OK,PERMITE_POR_EMPRESA,
			ENVIA_PARA_LOJA,PERMITE_POR_LOJA,PERMITE_POR_TERMINAL,
			PERMITE_ALTERAR_NA_LOJA,PERMITE_ALTERAR_NO_TERMINAL,
			ENVIA_PARA_REPRESENTANTE,PERMITE_POR_REPRESENTANTE,
			PERMITE_ALTERAR_NO_REPRESENTANTE,PENULT_ATUALIZACAO,
			ULT_ATUALIZACAO,DATA_PARA_TRANSFERENCIA)
VALUES('HR_MSG08_PROMO','Mensagem linha 8 do ticket de promocao',' ','C',
  	   0,0,0,0,1,1,0,0,0,0,0,0,GETDATE(),GETDATE(),GETDATE())
END  	


IF NOT EXISTS(SELECT 1 FROM PARAMETROS WHERE PARAMETRO = 'HR_MSG09_PROMO') 		
BEGIN
INSERT INTO PARAMETROS(PARAMETRO,DESC_PARAMETRO,VALOR_ATUAL,TIPO_DADO,
			GLOBAL,ESCOPO,POR_USUARIO_OK,PERMITE_POR_EMPRESA,
			ENVIA_PARA_LOJA,PERMITE_POR_LOJA,PERMITE_POR_TERMINAL,
			PERMITE_ALTERAR_NA_LOJA,PERMITE_ALTERAR_NO_TERMINAL,
			ENVIA_PARA_REPRESENTANTE,PERMITE_POR_REPRESENTANTE,
			PERMITE_ALTERAR_NO_REPRESENTANTE,PENULT_ATUALIZACAO,
			ULT_ATUALIZACAO,DATA_PARA_TRANSFERENCIA)
VALUES('HR_MSG09_PROMO','Mensagem linha 9 do ticket de promocao',' ','C',
  	   0,0,0,0,1,1,0,0,0,0,0,0,GETDATE(),GETDATE(),GETDATE())
END  


