IF NOT EXISTS(SELECT 1
          FROM   INFORMATION_SCHEMA.COLUMNS
          WHERE  TABLE_NAME = 'PRODUTO_CORES'
                 AND COLUMN_NAME = 'COTA_VENDA')
BEGIN
  ALTER TABLE PRODUTO_CORES    ADD COTA_VENDA VARCHAR(6)
END 
