IF NOT EXISTS ( SELECT 1 FROM SYS.COLUMNS WHERE NAME = 'NOME_ENTREGA' AND OBJECT_NAME(OBJECT_ID) = 'LOJA_PEDIDO')
BEGIN
	ALTER TABLE LOJA_PEDIDO ADD NOME_ENTREGA VARCHAR(255)
END 

IF NOT EXISTS ( SELECT 1 FROM SYS.COLUMNS WHERE NAME = 'MENSAGEM_CARTAO' AND OBJECT_NAME(OBJECT_ID) = 'LOJA_PEDIDO')
BEGIN
	ALTER TABLE LOJA_PEDIDO ADD MENSAGEM_CARTAO VARCHAR(255)
END 

IF NOT  EXISTS ( SELECT 1 FROM SYS.COLUMNS WHERE NAME = 'TRACKING' AND OBJECT_NAME(OBJECT_ID) = 'LOJA_PEDIDO')
BEGIN
	alter table LOJA_PEDIDO add TRACKING varchar(255)
END 

IF NOT EXISTS ( SELECT 1 FROM SYS.COLUMNS WHERE NAME = 'CODIGO_SITE' AND OBJECT_NAME(OBJECT_ID) = 'LOJA_PEDIDO')
BEGIN
	alter table LOJA_PEDIDO add CODIGO_SITE varchar(255)
END


IF NOT EXISTS ( SELECT 1 FROM SYS.COLUMNS WHERE NAME = 'FORMA_ENVIO' AND OBJECT_NAME(OBJECT_ID) = 'LOJA_PEDIDO')
BEGIN
	alter table LOJA_PEDIDO add FORMA_ENVIO varchar(255)
END 


IF NOT EXISTS ( SELECT 1 FROM SYS.COLUMNS WHERE NAME = 'B2C_LOJA' AND OBJECT_NAME(OBJECT_ID) = 'LOJA_PEDIDO')
BEGIN
	alter table LOJA_PEDIDO add B2C_LOJA bit
END 

IF NOT EXISTS ( SELECT 1 FROM SYS.COLUMNS WHERE NAME = 'MOTIVO_CANCELAMENTO' AND OBJECT_NAME(OBJECT_ID) = 'LOJA_PEDIDO')
BEGIN
	alter table LOJA_PEDIDO add MOTIVO_CANCELAMENTO int
END 

IF NOT EXISTS ( SELECT 1 FROM SYS.COLUMNS WHERE NAME = 'CONFERIDO' AND OBJECT_NAME(OBJECT_ID) = 'LOJA_PEDIDO')
BEGIN
	alter table LOJA_PEDIDO add CONFERIDO bit
END 


IF NOT EXISTS ( SELECT 1 FROM SYS.COLUMNS WHERE NAME = 'VOLUME' AND OBJECT_NAME(OBJECT_ID) = 'LOJA_PEDIDO')
BEGIN
	alter table LOJA_PEDIDO add VOLUME int
END 

IF NOT EXISTS ( SELECT 1 FROM SYS.COLUMNS WHERE NAME = 'PESO' AND OBJECT_NAME(OBJECT_ID) = 'LOJA_PEDIDO')
BEGIN
	alter table LOJA_PEDIDO add PESO numeric(7,3)
END


IF NOT EXISTS ( SELECT 1 FROM SYS.COLUMNS WHERE NAME = 'SEQUENCIA_VALE' AND OBJECT_NAME(OBJECT_ID) = 'LOJAS_VAREJO')
BEGIN
	ALTER TABLE LOJAS_VAREJO ADD SEQUENCIA_VALE varchar(255)
END

IF NOT EXISTS ( SELECT 1 FROM SYS.COLUMNS WHERE NAME = 'PERG_FUNCIONARIO' AND OBJECT_NAME(OBJECT_ID) = 'LOJAS_VAREJO')
BEGIN
	ALTER TABLE LOJAS_VAREJO ADD PERG_FUNCIONARIO INT
END 

IF NOT EXISTS ( SELECT 1 FROM SYS.COLUMNS WHERE NAME = 'B2C_CAMISA_NOME' AND OBJECT_NAME(OBJECT_ID) = 'LOJA_PEDIDO_PRODUTO')
BEGIN
	ALTER TABLE LOJA_PEDIDO_PRODUTO ADD B2C_CAMISA_NOME varchar (40)
END

IF NOT EXISTS ( SELECT 1 FROM SYS.COLUMNS WHERE NAME = 'B2C_CAMISA_NUMERO' AND OBJECT_NAME(OBJECT_ID) = 'LOJA_PEDIDO_PRODUTO')
BEGIN
	ALTER TABLE LOJA_PEDIDO_PRODUTO ADD B2C_CAMISA_NUMERO varchar(3)
END

IF NOT EXISTS ( SELECT 1 FROM SYS.COLUMNS WHERE NAME = 'B2C_NOME_PERSONALIZACAO' AND OBJECT_NAME(OBJECT_ID) = 'LOJA_PEDIDO_PRODUTO')
BEGIN
	ALTER TABLE LOJA_PEDIDO_PRODUTO ADD B2C_NOME_PERSONALIZACAO varchar (65)
END

IF NOT EXISTS ( SELECT 1 FROM SYS.COLUMNS WHERE NAME = 'B2C_NUMERO_PERSONALIZACAO' AND OBJECT_NAME(OBJECT_ID) = 'LOJA_PEDIDO_PRODUTO')
BEGIN
	ALTER TABLE LOJA_PEDIDO_PRODUTO ADD B2C_NUMERO_PERSONALIZACAO varchar(65)
END


IF NOT EXISTS ( SELECT 1 FROM SYS.COLUMNS WHERE NAME = 'QTDE_CONFERIDA' AND OBJECT_NAME(OBJECT_ID) = 'LOJA_PEDIDO_PRODUTO')
BEGIN
	ALTER TABLE LOJA_PEDIDO_PRODUTO ADD QTDE_CONFERIDA int
END

IF NOT EXISTS ( SELECT 1 FROM SYS.COLUMNS WHERE NAME = 'CONFERIDO' AND OBJECT_NAME(OBJECT_ID) = 'LOJA_PEDIDO_PRODUTO')
BEGIN
	ALTER TABLE LOJA_PEDIDO_PRODUTO ADD CONFERIDO bit 
END

IF NOT EXISTS ( SELECT 1 FROM SYS.COLUMNS WHERE NAME = 'TRACKING' AND OBJECT_NAME(OBJECT_ID) = 'LOJA_PEDIDO_PRODUTO')
BEGIN	
	ALTER TABLE LOJA_PEDIDO_PRODUTO ADD TRACKING varchar(15)
END

IF NOT EXISTS ( SELECT 1 FROM SYS.COLUMNS WHERE NAME = 'LARGURA' AND OBJECT_NAME(OBJECT_ID) = 'LOJA_PEDIDO_PRODUTO')
BEGIN	
	ALTER TABLE LOJA_PEDIDO_PRODUTO ADD LARGURA numeric(10,5)
END

IF NOT EXISTS ( SELECT 1 FROM SYS.COLUMNS WHERE NAME = 'COMPRIMENTO' AND OBJECT_NAME(OBJECT_ID) = 'LOJA_PEDIDO_PRODUTO')
BEGIN	
	ALTER TABLE LOJA_PEDIDO_PRODUTO ADD COMPRIMENTO numeric(14,2)
END

IF NOT  EXISTS ( SELECT 1 FROM SYS.COLUMNS WHERE NAME = 'ESPESSURA' AND OBJECT_NAME(OBJECT_ID) = 'LOJA_PEDIDO_PRODUTO')
BEGIN	
	ALTER TABLE LOJA_PEDIDO_PRODUTO ADD ESPESSURA numeric(14,2 )
END

IF NOT  EXISTS ( SELECT 1 FROM SYS.COLUMNS WHERE NAME = 'TERMINAL_VENDA_SUSPENSA' AND OBJECT_NAME(OBJECT_ID) = 'LOJA_VENDA')
BEGIN	
	alter table LOJA_VENDA add TERMINAL_VENDA_SUSPENSA char(3)
END

IF NOT  EXISTS ( SELECT 1 FROM SYS.COLUMNS WHERE NAME = 'ANM_CODIGO_DESC_VALE' AND OBJECT_NAME(OBJECT_ID) = 'LOJA_VENDA')
BEGIN	
	alter table LOJA_VENDA add ANM_CODIGO_DESC_VALE varchar(255)
END

IF NOT  EXISTS ( SELECT 1 FROM SYS.COLUMNS WHERE NAME = 'COD_PRODUTO_BARRA_LEITURA' AND OBJECT_NAME(OBJECT_ID) = 'LOJA_VENDA')
BEGIN	
	alter table LOJA_VENDA add COD_PRODUTO_BARRA_LEITURA int
END

IF NOT EXISTS(SELECT 1 FROM SYS.columns where name = 'DESCONTO_PGTO' AND OBJECT_NAME(columns.object_id) = 'LOJA_PEDIDO_PGTO')
BEGIN
	ALTER TABLE LOJA_PEDIDO_PGTO ADD DESCONTO_PGTO NUMERIC(14,2)
END

IF NOT EXISTS(SELECT 1 FROM SYS.columns where name = 'DESCONTO_PGTO' AND OBJECT_NAME(columns.object_id) = 'LOJA_PEDIDO')
BEGIN
	ALTER TABLE LOJA_PEDIDO ADD DESCONTO_PGTO NUMERIC(14,2)
END

 