IF NOT EXISTS(SELECT 1 FROM SYS.objects WHERE NAME = 'HR_CONTROLE_SAIDAS_ORIGEM') 
BEGIN
EXEC ('
CREATE TABLE [dbo].[HR_CONTROLE_SAIDAS_ORIGEM](
	[FILIAL_DESTINO] [varchar](25) NOT NULL,
	[FILIAL] [varchar](25) NOT NULL,
	[DATA_LIMITE] [datetime] NOT NULL,
	[ULT_ALTERACAO] [datetime] NULL,
 CONSTRAINT [PK_HR_CONTROLE_SAIDAS_ORIGEM] PRIMARY KEY CLUSTERED 
(
	[FILIAL_DESTINO] ASC,
	[FILIAL] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]')
END