if not exists (select 1 from sys.objects where name ='SP_HR_VINCULA_PROMOCAO_TICKET')
begin
exec
('CREATE PROCEDURE [dbo].[SP_HR_VINCULA_PROMOCAO_TICKET](@CODIGO_FILIAL CHAR(6), @DATA_VENDA DATETIME, @TICKET VARCHAR(8), @PEDIDO INT)
  AS
  BEGIN
  
  -- Daniel Martins 20200629 -  Adicionado campo frete_gratis na @TBL_FINAL
  
  
  DELETE FROM HR_VENDA_PROMOCAO 
    WHERE CODIGO_FILIAL = @CODIGO_FILIAL
  AND TICKET = @TICKET
  AND DATA_VENDA = @DATA_VENDA
  AND CODIGO_VOUCHER IS NULL


  DECLARE @CPF_CLIENTE VARCHAR(19)

  if @CPF_CLIENTE is null and @TICKET is not null
  select @CPF_CLIENTE = CLIENTES_VAREJO.CPF_CGC
  from loja_venda (nolock)
  inner join CLIENTES_VAREJO
  on LOJA_VENDA.CODIGO_CLIENTE = CLIENTES_VAREJO.CODIGO_CLIENTE
  where loja_venda.TICKET = @TICKET

    DECLARE @TBL_FINAL TABLE (
  ID_PROMOCAO INT
    ,DATA_INICIO DATETIME
    ,DATA_FIM DATETIME
    ,MESG VARCHAR(MAX)
    ,DESCONTOPROM NUMERIC(14,2)
    ,TIPO INT
    ,GERA_TICKET BIT
    ,QUANTIDADE_VOUCHER INT
    ,VALIDADE_VOUCHER DATETIME
    ,TIPO_VOUCHER INT /*3= VALOR / 4= PORCENTAGEM*/
    ,VALOR_VOUCHER NUMERIC(14, 2)
    ,TEXTO_CAMPANHA VARCHAR(MAX)
    ,CODIGO_VOUCHER VARCHAR(20)
    ,TIPO_GATILHO_RESGATE INT
    ,VALOR_GATILHO_RESGATE NUMERIC(18,2)
 , brinde BIT,
 frete_gratis bit
  )

   BEGIN TRY 
    INSERT INTO @TBL_FINAL (ID_PROMOCAO, DATA_INICIO, DATA_FIM, MESG, DESCONTOPROM, TIPO, GERA_TICKET, QUANTIDADE_VOUCHER, VALIDADE_VOUCHER, TIPO_VOUCHER, VALOR_VOUCHER, TEXTO_CAMPANHA, CODIGO_VOUCHER, TIPO_GATILHO_RESGATE, VALOR_GATILHO_RESGATE, brinde, frete_gratis)  
    EXEC SP_HR_PROMOCAO @CODIGO_FILIAL, @TICKET, @DATA_VENDA, @PEDIDO, @CPF_CLIENTE
   END TRY
   BEGIN CATCH
    INSERT INTO @TBL_FINAL (ID_PROMOCAO, DATA_INICIO, DATA_FIM, MESG, DESCONTOPROM, TIPO, GERA_TICKET, QUANTIDADE_VOUCHER)  
    EXEC SP_HR_PROMOCAO @CODIGO_FILIAL, @TICKET, @DATA_VENDA, @PEDIDO, @CPF_CLIENTE
   END CATCH

    INSERT INTO HR_VENDA_PROMOCAO(      
  CODIGO_FILIAL,
  TICKET,
  DATA_VENDA,
  ID_PROMOCAO,
  DATA_PARA_TRANSFERENCIA,
  CODIGO_VOUCHER,
  VALOR_DESCONTO
  )
    SELECT @CODIGO_FILIAL,
   @TICKET,
   @DATA_VENDA,
   ID_PROMOCAO,
   GETDATE(),
   NULL,
   DESCONTOPROM
    FROM @TBL_FINAL
  WHERE DATA_INICIO <= CONVERT(DATE,GETDATE())
  AND DATA_FIM >= CONVERT(DATE,GETDATE())
  AND DESCONTOPROM > 0 
  END')
  END