IF NOT EXISTS ( SELECT 1 FROM SYS.objects WHERE NAME = 'W_OMS_LOJA_VENDA')
BEGIN
EXEC('
CREATE VIEW [dbo].[W_OMS_LOJA_VENDA]
AS


SELECT 
CODIGO_FILIAL
,TICKET
,DATA_VENDA
,CODIGO_DESCONTO
,CODIGO_CLIENTE
,PERIODO
,DATA_DIGITACAO
,VENDEDOR
,OPERACAO_VENDA
,CODIGO_TAB_PRECO
,COMISSAO
,DESCONTO
,CONVERT(INT,QTDE_TOTAL) AS QTDE_TOTAL
,VALOR_TIKET
,VALOR_VENDA_BRUTA
,VALOR_TROCA
,CONVERT(INT,QTDE_TROCA_TOTAL) AS QTDE_TROCA_TOTAL
,TICKET_IMPRESSO
,TERMINAL
,GERENTE_LOJA
,GERENTE_PERIODO
,CODIGO_FILIAL_PGTO
,TERMINAL_PGTO
,LANCAMENTO_CAIXA
,VALOR_CANCELADO
,CONVERT(INT,TOTAL_QTDE_CANCELADA) AS TOTAL_QTDE_CANCELADA
,DATA_HORA_CANCELAMENTO
,PERIODO_FECHAMENTO
,VALOR_PAGO
,FATOR
,SUGESTAO_COD_FORMA_PGTO
,VALOR_IPI
,DATA_PARA_TRANSFERENCIA
,MOTIVO_CANCELAMENTO
,COD_FIDELIDADE_PROGRAMA
,QTDE_PONTOS_ACUMULADOS
,QTDE_PONTOS_RESGATADOS
,COD_FIDELIDADE_RESGATE
,CPF_CGC_ECF
,LX_HASH
,NSU_ACUMULO_FIDELIDADE
,NSU_RESGATE_FIDELIDADE
,HORA_ACUMULO_FIDELIDADE
,HORA_RESGATE_FIDELIDADE
,ID_ACAO_CAMPANHA
,VALOR_FRETE
,ID_MOTIVO_DEVOLUCAO
,TERMINAL_VENDA_SUSPENSA
,COD_PRODUTO_BARRA_LEITURA
,ANM_CODIGO_DESC_VALE
,LX_VENDA_ORIGEM
 FROM LOJA_VENDA')END