CREATE FUNCTION [dbo].[LX_LJ_CALCULA_DATA_VENCTO] (@TipoPGTO as char(02),  @OperVenda as char(03) )
RETURNS TABLE
AS
RETURN
(
	SELECT TOP 1 B.TIPO_PGTO, 
					case when B.TIPO_A_VISTA = 0 then
					( case when cast((A.DIAS_VENCIMENTO / 30 ) as int) = (A.DIAS_VENCIMENTO / 30 ) and isnull(A.DIAS_VENCIMENTO, 0) > 0
						   then ( case when c.VENC_RELATIVO IS NOT NULL
									   then DATEADD(MONTH, (A.DIAS_VENCIMENTO / 30 ), c.VENC_RELATIVO) +(A.DIAS_VENCIMENTO % 30 )
					   else DATEADD(MONTH, (A.DIAS_VENCIMENTO / 30 ), getdate()) + (A.DIAS_VENCIMENTO % 30 ) end )
			  else getdate() + A.DIAS_VENCIMENTO end )
	else getdate() end as DTVENCIMENTO
	FROM LOJA_FORMAS_PARCELAS A
	INNER JOIN TIPOS_PGTO B ON A.TIPO_PGTO = B.TIPO_PGTO 
	INNER JOIN LOJA_FORMAS_PGTO C ON A.COD_FORMA_PGTO = C.COD_FORMA_PGTO
	LEFT JOIN LOJA_OPERACOES_PGTOS D ON A.COD_FORMA_PGTO = D.COD_FORMA_PGTO
	WHERE D.OPERACAO_VENDA = @OperVenda and A.TIPO_PGTO = @TipoPGTO
	AND ISNULL(C.ATIVAR_EM, DATEADD(D, -1, getdate())) <= getdate()
	AND ISNULL(C.DESATIVAR_EM, DATEADD(D, 1, getdate())) >= getdate()
)