--DM 102727 - Wendel Crespigio #3# - Tratamento para melhoria de performance.
--DM 76917  - Wendel Crespigio #3# - Tratamento para melhoria de performance nike.
--DM 48244  - Wendel Crespigio #2# - Criação de indice na tabela PRODUTOS_BARRA
--DM 32806  - Wendell Crespigio Criação dos indices para melhoria de Performace.

IF NOT EXISTS (SELECT * FROM sysindexes WHERE name = 'XIE1LOJA_PEDIDO_VENDEDOR' AND id = object_id('LOJA_PEDIDO_VENDEDOR'))
BEGIN
	CREATE NONCLUSTERED INDEX [XIE1LOJA_PEDIDO_VENDEDOR]
	ON [dbo].[LOJA_PEDIDO_VENDEDOR] ([VENDEDOR],[DATA_PARA_TRANSFERENCIA])
END

IF NOT EXISTS (SELECT * FROM sysindexes WHERE name = 'XIE5LOJA_VENDA' AND id = object_id('LOJA_VENDA'))
BEGIN
	CREATE NONCLUSTERED INDEX [XIE5LOJA_VENDA]
	ON [dbo].[LOJA_VENDA] ([DATA_PARA_TRANSFERENCIA])
	INCLUDE ([CODIGO_CLIENTE])
END


IF NOT EXISTS (SELECT * FROM sysindexes WHERE name = 'XIE3LOJA_CAIXA_LANCAMENTOS' AND id = object_id('LOJA_CAIXA_LANCAMENTOS'))
BEGIN
	CREATE NONCLUSTERED INDEX [XIE3LOJA_CAIXA_LANCAMENTOS]
	ON [dbo].[LOJA_CAIXA_LANCAMENTOS] ([DATA_PARA_TRANSFERENCIA])
	INCLUDE ([CAIXA_VENDEDOR])
END


IF NOT EXISTS (SELECT * FROM sysindexes WHERE name = 'XIE5LOJA_VENDA_PGTO' AND id = object_id('LOJA_VENDA_PGTO'))
BEGIN
	CREATE NONCLUSTERED INDEX [XIE5LOJA_VENDA_PGTO]
	ON [dbo].[LOJA_VENDA_PGTO] ([DATA_PARA_TRANSFERENCIA])
	INCLUDE ([CAIXA_VENDEDOR])
END


IF NOT EXISTS (SELECT * FROM sysindexes WHERE name = 'XIE1LOJA_PEDIDO' AND id = object_id('LOJA_PEDIDO'))
BEGIN
	CREATE NONCLUSTERED INDEX [XIE1LOJA_PEDIDO]
	ON [dbo].[LOJA_PEDIDO] ([DATA_PARA_TRANSFERENCIA])
	INCLUDE ([CODIGO_CLIENTE])
END


IF NOT EXISTS (SELECT * FROM sysindexes WHERE name = 'XIE7LOJA_ENTRADAS_PRODUTO' AND id = object_id('LOJA_ENTRADAS_PRODUTO'))
BEGIN
	CREATE NONCLUSTERED INDEX XIE7LOJA_ENTRADAS_PRODUTO
	ON [dbo].[LOJA_ENTRADAS_PRODUTO] ([DATA_PARA_TRANSFERENCIA])
	INCLUDE ([FILIAL],[ROMANEIO_PRODUTO])
END


IF NOT EXISTS (SELECT * FROM sysindexes WHERE name = 'XIE1LOJA_RESERVA_PRODUTO' AND id = object_id('LOJA_RESERVA_PRODUTO'))
BEGIN
	CREATE NONCLUSTERED INDEX [XIE1LOJA_RESERVA_PRODUTO]
	ON [dbo].[LOJA_RESERVA_PRODUTO] ([DATA_PARA_TRANSFERENCIA])
	INCLUDE ([NUMERO_RESERVA],[FILIAL])
END


IF NOT EXISTS (SELECT * FROM sysindexes WHERE name = 'XIE1LOJA_RESERVA' AND id = object_id('LOJA_RESERVA'))
BEGIN
	CREATE NONCLUSTERED INDEX [XIE1LOJA_RESERVA]
	ON [dbo].[LOJA_RESERVA] ([DATA_PARA_TRANSFERENCIA])
	INCLUDE ([FILIAL],[NUMERO_RESERVA])
END



IF NOT EXISTS (SELECT * FROM sysindexes WHERE name = 'XIE1LOJA_RESERVA_PRODUTO' AND id = object_id('LOJA_RESERVA_PRODUTO'))
BEGIN
	CREATE NONCLUSTERED INDEX [XIE1LOJA_RESERVA_PRODUTO]
	ON [dbo].[LOJA_RESERVA_PRODUTO] ([DATA_PARA_TRANSFERENCIA])
	INCLUDE ([NUMERO_RESERVA],[FILIAL])
END


IF NOT EXISTS (SELECT * FROM sysindexes WHERE name = 'XIE1LOJA_RESERVA' AND id = object_id('LOJA_RESERVA'))
BEGIN
	CREATE NONCLUSTERED INDEX [[XIE1LOJA_RESERVA]
	ON [dbo].[LOJA_RESERVA] ([DATA_PARA_TRANSFERENCIA])
	INCLUDE ([FILIAL],[NUMERO_RESERVA])
END


IF NOT EXISTS (SELECT * FROM sysindexes WHERE name = 'XIE4LOJA_SAIDAS' AND id = object_id('LOJA_SAIDAS'))
BEGIN
	CREATE NONCLUSTERED INDEX XIE4LOJA_SAIDAS
	ON [dbo].[LOJA_SAIDAS] ([SAIDA_ENCERRADA],[DATA_PARA_TRANSFERENCIA])
	INCLUDE ([ROMANEIO_PRODUTO],[FILIAL])
END


IF NOT EXISTS (SELECT * FROM sysindexes WHERE name = 'XIE5LOJA_SAIDAS_PRODUTO' AND id = object_id('LOJA_SAIDAS_PRODUTO'))
BEGIN
	CREATE NONCLUSTERED INDEX XIE5LOJA_SAIDAS_PRODUTO
	ON [dbo].[LOJA_SAIDAS_PRODUTO] ([DATA_PARA_TRANSFERENCIA])
	INCLUDE ([ROMANEIO_PRODUTO],[FILIAL])
END


IF NOT EXISTS (SELECT * FROM sysindexes WHERE name = 'XIE7LOJA_VENDA_PRODUTO' AND id = object_id('LOJA_VENDA_PRODUTO'))
BEGIN
	CREATE NONCLUSTERED INDEX XIE7LOJA_VENDA_PRODUTO
	ON [dbo].[LOJA_VENDA_PRODUTO] ([DATA_PARA_TRANSFERENCIA])
	INCLUDE ([TICKET],[CODIGO_FILIAL],[DATA_VENDA])
END


IF NOT EXISTS (SELECT * FROM sysindexes WHERE name = 'XIE3LOJA_VENDA_PARCELAS' AND id = object_id('LOJA_VENDA_PARCELAS'))
BEGIN
	CREATE NONCLUSTERED INDEX XIE3LOJA_VENDA_PARCELAS
	ON [dbo].[LOJA_VENDA_PARCELAS] ([DATA_PARA_TRANSFERENCIA])
	INCLUDE ([TERMINAL],[LANCAMENTO_CAIXA],[CODIGO_FILIAL])
END


IF NOT EXISTS (SELECT * FROM sysindexes WHERE name = 'XIE4LOJA_VENDA_TROCA' AND id = object_id('LOJA_VENDA_TROCA'))
BEGIN
	CREATE NONCLUSTERED INDEX XIE4LOJA_VENDA_TROCA
	ON [dbo].[LOJA_VENDA_TROCA] ([DATA_PARA_TRANSFERENCIA])
	INCLUDE ([TICKET],[CODIGO_FILIAL],[DATA_VENDA])
END


IF NOT EXISTS (SELECT * FROM sysindexes WHERE name = 'XIE2LOJA_VENDA_VENDEDORES' AND id = object_id('LOJA_VENDA_VENDEDORES'))
BEGIN
	CREATE NONCLUSTERED INDEX XIE2LOJA_VENDA_VENDEDORES
	ON [dbo].[LOJA_VENDA_VENDEDORES] ([DATA_PARA_TRANSFERENCIA])
	INCLUDE ([CODIGO_FILIAL],[TICKET],[DATA_VENDA])
END


IF NOT EXISTS (SELECT * FROM sysindexes WHERE name = 'XIE2LOJA_VENDA_TROCA_ORIGEM' AND id = object_id('LOJA_VENDA_TROCA_ORIGEM'))
BEGIN
	CREATE NONCLUSTERED INDEX [XIE2LOJA_VENDA_TROCA_ORIGEM]
	ON [dbo].[LOJA_VENDA_TROCA_ORIGEM] ([DATA_PARA_TRANSFERENCIA])
	INCLUDE ([CODIGO_FILIAL],[TICKET],[DATA_VENDA])
END
 

IF NOT EXISTS (SELECT * FROM sysindexes WHERE name = 'XIE4LOJA_VENDA_PRODUTO' AND id = object_id('LOJA_VENDA_PRODUTO'))
BEGIN
	CREATE NONCLUSTERED INDEX [XIE4LOJA_VENDA_PRODUTO]
	ON [dbo].[LOJA_VENDA_PRODUTO] ([DATA_PARA_TRANSFERENCIA])
	INCLUDE ([TICKET],[CODIGO_FILIAL],[DATA_VENDA])
END



IF NOT EXISTS (SELECT * FROM sysindexes WHERE name = 'XIE5LOJA_VENDA' AND id = object_id('LOJA_VENDA'))
BEGIN
	CREATE NONCLUSTERED INDEX [XIE5LOJA_VENDA]
	ON [dbo].[LOJA_VENDA] ([DATA_PARA_TRANSFERENCIA])
	INCLUDE ([CODIGO_FILIAL_PGTO],[TERMINAL_PGTO],[LANCAMENTO_CAIXA])
END



IF NOT EXISTS (SELECT * FROM sysindexes WHERE name = 'XIE6LOJA_VENDA' AND id = object_id('LOJA_VENDA'))
BEGIN
	CREATE NONCLUSTERED INDEX [XIE6LOJA_VENDA]
	ON [dbo].[LOJA_VENDA] ([CODIGO_FILIAL],[TERMINAL_PGTO],[LANCAMENTO_CAIXA])
	INCLUDE ([TICKET],[DATA_VENDA])
END


IF NOT EXISTS (SELECT * FROM sysindexes WHERE name = 'XIE1LOJA_CF_SAT' AND id = object_id('LOJA_CF_SAT'))
BEGIN
	CREATE NONCLUSTERED INDEX [XIE1LOJA_CF_SAT]
	ON [dbo].[LOJA_CF_SAT] ([STATUS_CFE])
	INCLUDE ([ID_LOJA_CF_SAT],[CODIGO_FILIAL])
END

--#2# - Inicio
IF NOT EXISTS (SELECT * FROM sysindexes WHERE name = 'XIE2PRODUTOS_BARRA' AND id = object_id('PRODUTOS_BARRA'))
BEGIN
	CREATE NONCLUSTERED INDEX [XIE2PRODUTOS_BARRA] 
	ON [dbo].[PRODUTOS_BARRA]
	(
		[TIPO_COD_BAR] ASC,
		[INATIVO] ASC
	)
	INCLUDE ([CODIGO_BARRA],
		[PRODUTO],
		[COR_PRODUTO],
		[TAMANHO],
		[GRADE])
END

--#2# - Fim
--#3# inicio 
IF NOT EXISTS (SELECT * FROM sysindexes WHERE name = 'XIE5LOJA_VENDA_PARCELAS' AND id = object_id('LOJA_VENDA_PARCELAS'))
begin 
	CREATE NONCLUSTERED INDEX [XIE5LOJA_VENDA_PARCELAS] ON [dbo].[LOJA_VENDA_PARCELAS] (VALOR) INCLUDE (TERMINAL,LANCAMENTO_CAIXA,CODIGO_FILIAL)
END

IF NOT EXISTS (SELECT * FROM sysindexes WHERE name = 'XIE8LOJA_VENDA_PGTO' AND id = object_id('LOJA_VENDA_PGTO'))
BEGIN 
	CREATE NONCLUSTERED INDEX [XIE8LOJA_VENDA_PGTO] ON [dbo].[LOJA_VENDA_PGTO] ([CODIGO_FILIAL],[SERIE_NF_SAIDA],[NUMERO_FISCAL_VENDA])	INCLUDE ([TERMINAL],[LANCAMENTO_CAIXA])
end
--#3# Fim 


IF NOT EXISTS (SELECT * FROM sysindexes WHERE name = 'XIE1_DADOS_CADASTRO_XML_NFE' AND id = object_id('DADOS_CADASTRO_XML_NFE'))
begin 
	CREATE NONCLUSTERED INDEX [XIE1_DADOS_CADASTRO_XML_NFE]
	ON [dbo].[DADOS_CADASTRO_XML_NFE] ([NF_SAIDA],[FILIAL],[SERIE_NF])
end

IF NOT EXISTS (SELECT * FROM sysindexes WHERE name = 'XIE7_PRODUTOS' AND id = object_id('PRODUTOS'))
begin 
	CREATE NONCLUSTERED INDEX [XIE7_PRODUTOS]
	ON [dbo].[PRODUTOS] ([INATIVO])
	INCLUDE ([PRODUTO],[TIPO_PRODUTO],[GRUPO_PRODUTO],[SUBGRUPO_PRODUTO],[COLECAO],[GRADE],[DESC_PROD_NF],[LINHA],[GRIFFE],[FABRICANTE])
end