Create VIEW [dbo].[W_IMPRESSAO_CFE_ITENS]
AS 
-- DM		  - Diego Moreno	- #15# - (08/04/2019) - Medida emergêncial de melhoria de performance ao realizar vendas com SAT.
-- DM74192    - Wendel Crespigio - #14# - 11/05/2018 - Tratamento para chamada da function FX_GTIN_BARCODE_SEEK não passar '' branco e sim null  
-- DM35380	  - Diego Moreno   - #13# - 22/06/2017 - Melhoria de performance ao buscar código de barras.
-- TP10769689 - Gilvano.Santos - #12# - (18/11/2015) - Adequação NT 2015.003 - Inclusão do codigo CEST
-- TP10312275 - GILVANO.SANTOS - #11# - (06/11/2015) - Correção da Left Join referente ao id_imposto 7 (IMPORT)
-- Sem TP banco online - Gerson Prado - #10# - (21/09/2015) - Adequação na chamada do metodo FX_LOCALIZA_CODIGO_BARRA, incluir parametro para uso do banco online,
-- TP8633089 - GILVANO.SANTOS/ JOÃO.GONZALES - #9# (23/05/2015) - Adequação para sempre enviar a aliquota de icms SAT no campo ICMS_ALIQUOTA_SAt QUANDO OCORRER REDUÇÃO DA BASE DE CALCULO.
-- TP8633089 - WENDEL CRESPIGIO - #8# (23/05/2015) - TRATAMENTO PARA QUANDO NÃO FOR ENCONTRADO UNIDADE -SOLICITAÇÃO PARA ATENDER TESTES DO QA. 
-- TP8625029 - DIEGO MORENO #7#  - (23/05/2015) - CORREÇÃO PARA TRATAR OS CASOS ONDE HÁ SUBSTITUIÇÃO TRIBUTÁRIA 05. TRATAMENTO APENAS PARA PIS E COFINS.
-- TP8692563 - JOAO.GONZALES/THIAGO MARCON - #6# - (23/05/2015) - correção nos campos ENCARGO e DESCONTO_TOTAL_ITEM
-- TP8692512 - JOAO.GONZALES - #5# - (23/05/2015) - Adequação para sempre enviar a aliquota de icms SAT no campo ICMS_ALIQUOTA_SAT, o campo ICMS_ALIQUOTA não será utilizado para SAT. Regra implementada no Client do MID
-- TP8679695 - JOAO.GONZALES - #4# - (22/05/2015) - IMPLEMENTAÇÃO DO DESCONTO NO TOTAL DOS ITENS, PARA REMOVER O CALCULO DO COMPONENTE
-- TP8666922 - JOAO.GONZALES - #3# - (21/05/2015) - IMPLEMENTAÇÃO DA REDUÇÃO DA BASE DE CÁLCULO DO ICMS.
-- TP8591113 - DIEGO MORENO #2#  - (21/05/2015) - CORREÇÃO PARA TRATAMENTO DE DESCONTOS E ACRESIMOS NO ITEM.
-- TP5639147 - GILVANO SANTOS - #1# - (27/03/2015) - IMPLANTAÇÃO CF-E SAT
SELECT 
LOJA_CF_SAT.CF_NUMERO AS NF, 
LOJA_CF_SAT.SERIE_NF, 
LOJAS_VAREJO.FILIAL, 
CASE ISNULL(LOJA_CF_SAT_ITEM.ITEM_CFE, 0) WHEN 0 THEN LOJA_CF_SAT_ITEM.ITEM_IMPRESSAO ELSE LOJA_CF_SAT_ITEM.ITEM_CFE END AS ITEM_CFE, 
CAST(LOJA_CF_SAT_ITEM.ITEM_IMPRESSAO AS CHAR(4)) AS ITEM_IMPRESSAO,
[dbo].[FX_REPLACE_CARACTER_ESPECIAL_NFE](0,LOJA_CF_SAT_ITEM.DESCRICAO_ITEM) as DESCRICAO_ITEM, 
LOJA_CF_SAT_ITEM.QTDE_ITEM, 
LOJA_CF_SAT_ITEM.CODIGO_ITEM, 
CASE WHEN CST_ICMS.ID_EXCECAO_IMPOSTO IS NULL AND (ICMS.ID_IMPOSTO = 1 OR SIMPLES_F.ID_IMPOSTO = 44) THEN '00' ELSE CST_ICMS.TRIBUT_ICMS END AS TRIBUT_ICMS, 
LOJA_CF_SAT_ITEM.TRIBUT_ORIGEM, 
CASE WHEN ISNULL(LOJA_CF_SAT_ITEM.UNIDADE,'') = '' THEN 'PC' ELSE LOJA_CF_SAT_ITEM.UNIDADE END AS UNIDADE,  --#8#
LOJA_CF_SAT_ITEM.CLASSIF_FISCAL, 
LOJA_CF_SAT_ITEM.CODIGO_FISCAL_OPERACAO, 
LOJA_CF_SAT_ITEM.PRECO_UNITARIO, 
CASE WHEN LOJA_CF_SAT_ITEM.DESCONTO_ITEM < 0 THEN 0 ELSE LOJA_CF_SAT_ITEM.DESCONTO_ITEM END AS DESCONTO_ITEM,	--DESCONTO UNITARIO ITEM
LOJA_CF_SAT_ITEM.VALOR_ITEM, 
LOJA_CF_SAT_ITEM.INDICADOR_CFOP, 
LOJA_CF_SAT_ITEM.ID_EXCECAO_IMPOSTO, 

TRIBUT_ICMS.DESCRICAO AS TRIBUT_ICMS_DESCRICAO, 
TRIBUT_ORIGEM.DESCRICAO AS TRIBUT_ORIGEM_DESCRICAO,
CLASSIF_FISCAL.DESC_CLASSIFICACAO, 
CTB_LX_NATUREZAS_OPERACAO.DENOMINACAO AS CODIGO_FISCAL_OPERACAO_DENOMINACAO, 

REPLACE(LOJA_CF_SAT_ITEM.OBS_ITEM,CHAR(1),'') AS OBS_ITEM, 
CASE WHEN CST_IPI.ID_EXCECAO_IMPOSTO IS NULL AND IPI.ID_IMPOSTO = 2 THEN '50' ELSE (CASE WHEN IPI.ID_IMPOSTO IS NULL THEN NULL ELSE CST_IPI.SITUACAO_TRIBUTARIA END) END AS CST_IPI, 
CASE WHEN CST_PIS.ID_EXCECAO_IMPOSTO IS NULL AND PIS.ID_IMPOSTO = 5 THEN '01' ELSE (CASE WHEN PIS.ID_IMPOSTO IS NULL THEN NULL ELSE CST_PIS.SITUACAO_TRIBUTARIA END) END AS CST_PIS, 
CASE WHEN CST_COFINS.ID_EXCECAO_IMPOSTO IS NULL AND COFINS.ID_IMPOSTO = 6 THEN '01' ELSE (CASE WHEN COFINS.ID_IMPOSTO IS NULL THEN NULL ELSE CST_COFINS.SITUACAO_TRIBUTARIA END) END AS CST_COFINS, 
CST_ISS.SITUACAO_TRIBUTARIA as CST_ISS,  
CST_ISS.NUMERO_PROCESSO AS NUMERO_PROCESSO_ISS,
CST_ISS.INDICADOR_INCENTIVO AS INDICADOR_INCENTIVO_ISS,

CASE WHEN ISNULL(CST_ICMS.TRIBUT_ICMS,'00') = '51' THEN ICMS_BST_PREDBC.PORCENT_REDUCAO_DE_BASE ELSE ICMS_PREDBC.PORCENT_REDUCAO_DE_BASE END AS pREDBC,

ISNULL(ICMS.VALOR_IMPOSTO,0) AS ICMS,      
ISNULL(ICMS.TAXA_IMPOSTO, 0) AS ICMS_ALIQUOTA,     	
--#3# #5#
case when (
			case when (CASE WHEN ISNULL(CST_ICMS.TRIBUT_ICMS,'00') = '51' THEN ICMS_BST_PREDBC.PORCENT_REDUCAO_DE_BASE ELSE ICMS_PREDBC.PORCENT_REDUCAO_DE_BASE END) >.00 
				then CONVERT(NUMERIC(13,10), ISNULL(ICMS.TAXA_IMPOSTO, 0) * 
						(100 - ( CASE WHEN ISNULL(CST_ICMS.TRIBUT_ICMS,'00') = '51' THEN ICMS_BST_PREDBC.PORCENT_REDUCAO_DE_BASE ELSE ICMS_PREDBC.PORCENT_REDUCAO_DE_BASE END )) / 100 )
			else .00 end
			) = .00 
	 then  ISNULL(ICMS.TAXA_IMPOSTO, 0) 
	 else --#9#
		(	case when (CASE WHEN ISNULL(CST_ICMS.TRIBUT_ICMS,'00') = '51' THEN ICMS_BST_PREDBC.PORCENT_REDUCAO_DE_BASE ELSE ICMS_PREDBC.PORCENT_REDUCAO_DE_BASE END) >.00 
				then CONVERT(NUMERIC(13,10), ISNULL(ICMS.TAXA_IMPOSTO, 0) * 
						(100 - ( CASE WHEN ISNULL(CST_ICMS.TRIBUT_ICMS,'00') = '51' THEN ICMS_BST_PREDBC.PORCENT_REDUCAO_DE_BASE ELSE ICMS_PREDBC.PORCENT_REDUCAO_DE_BASE END )) / 100 )
			else .00 end ) --#9#
end AS ICMS_ALIQUOTA_SAT, --#3# #5#
ISNULL(ICMS.BASE_IMPOSTO, 0) AS ICMS_BASE,
ISNULL(IPI.VALOR_IMPOSTO, 0) AS IPI, 
ISNULL(IPI.TAXA_IMPOSTO, 0) AS IPI_ALIQUOTA, 
ISNULL(IPI.BASE_IMPOSTO, 0) AS IPI_BASE, 
ISNULL(IRRF.VALOR_IMPOSTO, 0) AS IRRF, 
ISNULL(IRRF.TAXA_IMPOSTO, 0) AS IRRF_ALIQUOTA, 
ISNULL(IRRF.BASE_IMPOSTO, 0) AS IRRF_BASE, 
ISNULL(INSS.VALOR_IMPOSTO, 0) AS INSS, 
ISNULL(INSS.TAXA_IMPOSTO, 0) AS INSS_ALIQUOTA, 
ISNULL(INSS.BASE_IMPOSTO, 0) AS INSS_BASE, 
ISNULL(PIS.VALOR_IMPOSTO, 0) AS PIS, 
--ISNULL(PIS.TAXA_IMPOSTO, 0) AS PIS_ALIQUOTA, 
CASE WHEN CST_PIS.SITUACAO_TRIBUTARIA IS NOT NULL AND CST_PIS.SITUACAO_TRIBUTARIA = '05' AND PIS.ID_IMPOSTO = 5 THEN CST_PIS.TAXA_IMPOSTO ELSE ISNULL(PIS.TAXA_IMPOSTO, 0) END AS PIS_ALIQUOTA, -- #7#
ISNULL(PIS.BASE_IMPOSTO, 0) AS PIS_BASE, 
ISNULL(COFINS.VALOR_IMPOSTO, 0) AS COFINS, 
--ISNULL(COFINS.TAXA_IMPOSTO, 0) AS COFINS_ALIQUOTA, 
CASE WHEN CST_COFINS.SITUACAO_TRIBUTARIA IS NOT NULL AND CST_COFINS.SITUACAO_TRIBUTARIA  = '05' AND COFINS.ID_IMPOSTO = 6 THEN CST_COFINS.TAXA_IMPOSTO ELSE ISNULL(COFINS.TAXA_IMPOSTO, 0) END AS COFINS_ALIQUOTA, -- #7#
ISNULL(COFINS.BASE_IMPOSTO, 0) AS COFINS_BASE, 
ISNULL(IMPORT.VALOR_IMPOSTO, 0) AS I_IMPORT, 
ISNULL(IMPORT.TAXA_IMPOSTO, 0) AS I_IMPORT_ALIQUOTA, 
ISNULL(IMPORT.BASE_IMPOSTO, 0) AS I_IMPORT_BASE, 
ISNULL(IVA.VALOR_IMPOSTO, 0) AS IVA, 
ISNULL(IVA.TAXA_IMPOSTO, 0) AS IVA_ALIQUOTA, 
ISNULL(IVA.BASE_IMPOSTO, 0) AS IVA_BASE, 
ISNULL(RECARGO.VALOR_IMPOSTO, 0) AS RECARGO, 
ISNULL(RECARGO.TAXA_IMPOSTO, 0) AS RECARGO_ALIQUOTA, 
ISNULL(RECARGO.BASE_IMPOSTO, 0) AS RECARGO_BASE, 
ISNULL(IRPF.VALOR_IMPOSTO, 0) AS IRPF, 
ISNULL(IRPF.TAXA_IMPOSTO, 0) AS IRPF_ALIQUOTA, 
ISNULL(IRPF.BASE_IMPOSTO, 0) AS IRPF_BASE, 
ISNULL(DICMS.VALOR_IMPOSTO, 0) AS DICMS, 
ISNULL(DICMS.TAXA_IMPOSTO, 0) AS DICMS_ALIQUOTA, 
ISNULL(DICMS.BASE_IMPOSTO, 0) AS DICMS_BASE, 
ISNULL(ICMS_ST.VALOR_IMPOSTO, 0) AS ICMS_ST, 
ISNULL(ICMS_ST.TAXA_IMPOSTO, 0) AS ICMS_ST_ALIQUOTA, 
ISNULL(ICMS_ST.BASE_IMPOSTO, 0) AS ICMS_ST_BASE, 
ISNULL(ICMS_STR.VALOR_IMPOSTO, 0) AS ICMS_STR, 
ISNULL(ICMS_STR.TAXA_IMPOSTO, 0) AS ICMS_STR_ALIQUOTA, 
ISNULL(ICMS_STR.BASE_IMPOSTO, 0) AS ICMS_STR_BASE, 
ISNULL(ISS.VALOR_IMPOSTO, 0) AS ISS, 
ISNULL(ISS.TAXA_IMPOSTO, 0) AS ISS_ALIQUOTA, 
ISNULL(ISS.BASE_IMPOSTO, 0) AS ISS_BASE, 
ISNULL(IVA_IC.VALOR_IMPOSTO, 0) AS IVA_IC, 
ISNULL(IVA_IC.TAXA_IMPOSTO, 0) AS IVA_IC_ALIQUOTA, 
ISNULL(IVA_IC.BASE_IMPOSTO, 0) AS IVA_IC_BASE, 
ISNULL(PC_CSL.VALOR_IMPOSTO, 0) AS PC_CSL, 
ISNULL(PC_CSL.TAXA_IMPOSTO, 0) AS PC_CSL_ALIQUOTA, 
ISNULL(PC_CSL.BASE_IMPOSTO, 0) AS PC_CSL_BASE, 
ISNULL(PIS_R.VALOR_IMPOSTO, 0) AS PIS_R, 
ISNULL(PIS_R.TAXA_IMPOSTO, 0) AS PIS_R_ALIQUOTA, 
ISNULL(PIS_R.BASE_IMPOSTO, 0) AS PIS_R_BASE, 
ISNULL(COFINS_R.VALOR_IMPOSTO, 0) AS COFINS_R, 
ISNULL(COFINS_R.TAXA_IMPOSTO, 0) AS COFINS_R_ALIQUOTA, 
ISNULL(COFINS_R.BASE_IMPOSTO, 0) AS COFINS_R_BASE, 
ISNULL(CSLL_R.VALOR_IMPOSTO, 0) AS CSLL_R, 
ISNULL(CSLL_R.TAXA_IMPOSTO, 0) AS CSLL_R_ALIQUOTA, 
ISNULL(CSLL_R.BASE_IMPOSTO, 0) AS CSLL_R_BASE, 
ISNULL(IRRF_R.VALOR_IMPOSTO, 0) AS IRRF_R, 
ISNULL(IRRF_R.TAXA_IMPOSTO, 0) AS IRRF_R_ALIQUOTA, 
ISNULL(IRRF_R.BASE_IMPOSTO, 0) AS IRRF_R_BASE, 
ISNULL(INSS_R.VALOR_IMPOSTO, 0) AS INSS_R, 
ISNULL(INSS_R.TAXA_IMPOSTO, 0) AS INSS_R_ALIQUOTA, 
ISNULL(INSS_R.BASE_IMPOSTO, 0) AS INSS_R_BASE, 
ISNULL(ISS_R.VALOR_IMPOSTO, 0) AS ISS_R, 
ISNULL(ISS_R.TAXA_IMPOSTO, 0) AS ISS_R_ALIQUOTA, 
ISNULL(ISS_R.BASE_IMPOSTO, 0) AS ISS_R_BASE, 
ISNULL(PIS_S.VALOR_IMPOSTO, 0) AS PIS_S, 
ISNULL(PIS_S.TAXA_IMPOSTO, 0) AS PIS_S_ALIQUOTA, 
ISNULL(PIS_S.BASE_IMPOSTO, 0) AS PIS_S_BASE, 
ISNULL(COFINS_S.VALOR_IMPOSTO, 0) AS COFINS_S, 
ISNULL(COFINS_S.TAXA_IMPOSTO, 0) AS COFINS_S_ALIQUOTA, 
ISNULL(COFINS_S.BASE_IMPOSTO, 0) AS COFINS_S_BASE, 
ISNULL(CSLL_S.VALOR_IMPOSTO, 0) AS CSLL_S, 
ISNULL(CSLL_S.TAXA_IMPOSTO, 0) AS CSLL_S_ALIQUOTA, 
ISNULL(CSLL_S.BASE_IMPOSTO, 0) AS CSLL_S_BASE, 
ISNULL(RTEIVA.VALOR_IMPOSTO, 0) AS RTEIVA, 
ISNULL(RTEIVA.TAXA_IMPOSTO, 0) AS RTEIVA_ALIQUOTA, 
ISNULL(RTEIVA.BASE_IMPOSTO, 0) AS RTEIVA_BASE, 
ISNULL(RTEIVA_R.VALOR_IMPOSTO, 0) AS RTEIVA_R, 
ISNULL(RTEIVA_R.TAXA_IMPOSTO, 0) AS RTEIVA_R_ALIQUOTA, 
ISNULL(RTEIVA_R.BASE_IMPOSTO, 0) AS RTEIVA_R_BASE, 
ISNULL(ICA.VALOR_IMPOSTO, 0) AS ICA, 
ISNULL(ICA.TAXA_IMPOSTO, 0) AS ICA_ALIQUOTA, 
ISNULL(ICA.BASE_IMPOSTO, 0) AS ICA_BASE, 
ISNULL(RTEICA.VALOR_IMPOSTO, 0) AS RTEICA, 
ISNULL(RTEICA.TAXA_IMPOSTO, 0) AS RTEICA_ALIQUOTA, 
ISNULL(RTEICA.BASE_IMPOSTO, 0) AS RTEICA_BASE, 
ISNULL(RTEFTE.VALOR_IMPOSTO, 0) AS RTEFTE, 
ISNULL(RTEFTE.TAXA_IMPOSTO, 0) AS RTEFTE_ALIQUOTA, 
ISNULL(RTEFTE.BASE_IMPOSTO, 0) AS RTEFTE_BASE, 
ISNULL(RTEFTE_R.VALOR_IMPOSTO, 0) AS RTEFTE_R, 
ISNULL(RTEFTE_R.TAXA_IMPOSTO, 0) AS RTEFTE_R_ALIQUOTA, 
ISNULL(RTEFTE_R.BASE_IMPOSTO, 0) AS RTEFTE_R_BASE, 

ISNULL(SIMPLES_F.VALOR_IMPOSTO, 0) AS SIMPLES_F,  ISNULL(SIMPLES_F.TAXA_IMPOSTO,	0) AS SIMPLES_F_ALIQUOTA,     	ISNULL(SIMPLES_F.BASE_IMPOSTO, 0) AS SIMPLES_F_BASE,
--#4#
((LOJA_CF_SAT_ITEM.VALOR_DESCONTOS + ISNULL(ICMS_ZF.VALOR_IMPOSTO,0) + ISNULL(PIS_ZF.VALOR_IMPOSTO,0) + ISNULL(COFINS_ZF.VALOR_IMPOSTO,0))+CASE WHEN LOJA_CF_SAT_ITEM.DESCONTO_ITEM < 0 THEN 0 ELSE ISNULL(LOJA_CF_SAT_ITEM.DESCONTO_ITEM * LOJA_CF_SAT_ITEM.QTDE_ITEM, 0) END) AS VALOR_DESCONTOS,	--VALOR DE DESCONTO RATEADO PROVENIENTE DA VENDA (não usado para SAT)
--#4#
CASE WHEN LOJA_CF_SAT_ITEM.DESCONTO_ITEM < 0 THEN 0 ELSE ISNULL(LOJA_CF_SAT_ITEM.DESCONTO_ITEM * LOJA_CF_SAT_ITEM.QTDE_ITEM, 0) END AS DESCONTO_TOTAL_ITEM,	--#6#TOTAL DE DESCONTO NO ITEM
--ISNULL(LOJA_CF_SAT_ITEM.PRECO_UNITARIO, 0) + CASE WHEN LOJA_CF_SAT_ITEM.DESCONTO_ITEM < 0 THEN 0 ELSE ISNULL(LOJA_CF_SAT_ITEM.DESCONTO_ITEM, 0) END AS VALOR_UNITARIO_BRUTO, 
ISNULL(LOJA_CF_SAT_ITEM.PRECO_UNITARIO, 0) + CASE WHEN LOJA_CF_SAT_ITEM.DESCONTO_ITEM < 0 THEN ISNULL(LOJA_CF_SAT_ITEM.DESCONTO_ITEM, 0) ELSE ISNULL(LOJA_CF_SAT_ITEM.DESCONTO_ITEM, 0) END AS VALOR_UNITARIO_BRUTO,  --#2#
--ISNULL(LOJA_CF_SAT_ITEM.VALOR_ITEM, 0) + CASE WHEN LOJA_CF_SAT_ITEM.DESCONTO_ITEM < 0 THEN 0 ELSE ISNULL(LOJA_CF_SAT_ITEM.DESCONTO_ITEM * LOJA_CF_SAT_ITEM.QTDE_ITEM, 0) END AS VALOR_ITEM_BRUTO,
ISNULL(LOJA_CF_SAT_ITEM.VALOR_ITEM, 0) + CASE 	WHEN LOJA_CF_SAT_ITEM.DESCONTO_ITEM < 0 THEN ISNULL(LOJA_CF_SAT_ITEM.DESCONTO_ITEM * LOJA_CF_SAT_ITEM.QTDE_ITEM, 0) ELSE ISNULL(LOJA_CF_SAT_ITEM.DESCONTO_ITEM * LOJA_CF_SAT_ITEM.QTDE_ITEM, 0) END AS VALOR_ITEM_BRUTO, --#2#

CASE WHEN DESCONTO_ITEM >=0 THEN 0 ELSE (DESCONTO_ITEM *-1) * QTDE_ITEM END ENCARGO, --#6#

CASE WHEN ISNULL(LOJA_CF_SAT_ITEM.OBS_ITEM,'') = '' THEN NULL ELSE REPLACE(LOJA_CF_SAT_ITEM.OBS_ITEM,CHAR(1),'') END AS INFORMACAO_ADICIONAL_PROD, -- #3#	

---ISNULL(CST_ICMS.CODIGO_ENQUADRAMENTO,999) AS CODIGO_ENQUADRAMENTO,  -- (2.0) IPI BEBIDAS
---CST_ICMS.CODIGO_CLASSE_TRIBUTACAO,									-- (2.0) IPI BEBIDAS	 

ISNULL(ICMS_SN.VALOR_IMPOSTO, 0) AS ICMS_SN,  ISNULL(ICMS_SN.TAXA_IMPOSTO,  0) AS ICMS_SN_ALIQUOTA,       ISNULL(ICMS_SN.BASE_IMPOSTO, 0) AS ICMS_SN_BASE,
ISNULL(PIS_SN.VALOR_IMPOSTO, 0) AS PIS_SN,  ISNULL(PIS_SN.TAXA_IMPOSTO,     0) AS PIS_SN_ALIQUOTA,        ISNULL(PIS_SN.BASE_IMPOSTO, 0) AS PIS_SN_BASE,
ISNULL(COFINS_SN.VALOR_IMPOSTO, 0) AS COFINS_SN,  ISNULL(COFINS_SN.TAXA_IMPOSTO,  0) AS COFINS_SN_ALIQUOTA,          ISNULL(COFINS_SN.BASE_IMPOSTO, 0) AS COFINS_SN_BASE,
ICMS_SN.ID_IMPOSTO AS  ID_IMPOSTO_ICMS_SN,
PIS_SN.ID_IMPOSTO AS  ID_IMPOSTO_PIS_SN,
COFINS_SN.ID_IMPOSTO AS  ID_IMPOSTO_COFINS_SN,

ISNULL(ICMS_BST.VALOR_IMPOSTO,0) AS ICMS_BST,      
ISNULL(ICMS_BST.TAXA_IMPOSTO, 0) AS ICMS_BST_ALIQUOTA,     	
ISNULL(ICMS_BST.BASE_IMPOSTO, 0) AS ICMS_BST_BASE,

--CASE WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('AGRUPAMENTO_NF', LOJAS_VAREJO.CODIGO_FILIAL), '0') <> '2' THEN '' 
--ELSE DBO.FX_LOCALIZA_CODIGO_BARRA(LOJA_CF_SAT_ITEM.CODIGO_ITEM, ISNULL(DBO.FX_PARAMETRO_LOJA('AGRUPAMENTO_NF', LOJAS_VAREJO.CODIGO_FILIAL), '0'),'') END EAN, 
CASE WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('AGRUPAMENTO_NF', LOJAS_VAREJO.CODIGO_FILIAL), '0') <> '2' THEN '' 
ELSE DBO.FX_GTIN_BARCODE_SEEK(LOJA_CF_SAT_ITEM.CODIGO_ITEM, ISNULL(DBO.FX_PARAMETRO_LOJA('AGRUPAMENTO_NF', LOJAS_VAREJO.CODIGO_FILIAL), '0'),null,null,null) END EAN, -- #13# #14#
--#10# DBO.FX_LOCALIZA_CODIGO_BARRA(LOJA_CF_SAT_ITEM.CODIGO_ITEM, ISNULL(DBO.FX_PARAMETRO_LOJA('AGRUPAMENTO_NF', LOJAS_VAREJO.CODIGO_FILIAL), '0')) END EAN, 

ISNULL(ICMS_ZF.VALOR_IMPOSTO,	  0) AS ICMS_ZF,	ISNULL(ICMS_ZF.TAXA_IMPOSTO,	0) AS ICMS_ZF_ALIQUOTA,		ISNULL(ICMS_ZF.BASE_IMPOSTO,	0) AS ICMS_ZF_BASE,
ISNULL(PIS_ZF.VALOR_IMPOSTO,      0) AS PIS_ZF,     ISNULL(PIS_ZF.TAXA_IMPOSTO,     0) AS PIS_ZF_ALIQUOTA,      ISNULL(PIS_ZF.BASE_IMPOSTO,     0) AS PIS_ZF_BASE,
ISNULL(COFINS_ZF.VALOR_IMPOSTO,   0) AS COFINS_ZF,  ISNULL(COFINS_ZF.TAXA_IMPOSTO,	0) AS COFINS_ZF_ALIQUOTA,   ISNULL(COFINS_ZF.BASE_IMPOSTO,  0) AS COFINS_ZF_BASE,
CST_ICMS_ZF.SITUACAO_TRIBUTARIA as ST_MOT_DESONERACAO,
ISNULL(LOJA_CF_SAT_ITEM.VALOR_APROX_IMPOSTOS,0) AS VALOR_IMPOSTO_ITEM,
CONVERT(CHAR(36),LOJA_CF_SAT_ITEM.CODIGO_FCI) AS CODIGO_FCI,  --LOJA_CF_SAT_ITEM.CODIGO_FCI
LOJA_CF_SAT.LANCAMENTO_CAIXA,
LOJA_CF_SAT.TERMINAL,
CONVERT(CHAR(38), LOJA_CF_SAT.GUID_VENDA_SAT) AS GUID_VENDA_SAT,
LOJA_CF_SAT.GUID_VENDA_SAT as GUID_VENDA, --#15#
LOJA_CF_SAT.ID_LOJA_CF_SAT, --#5#
TABELA_LX_CEST.CODIGO_CEST AS CODIGO_CEST--#12#
FROM 
      LOJA_CF_SAT_ITEM 
      INNER JOIN LOJA_CF_SAT ON LOJA_CF_SAT.CODIGO_FILIAL = LOJA_CF_SAT_ITEM.CODIGO_FILIAL AND LOJA_CF_SAT.ID_LOJA_CF_SAT = LOJA_CF_SAT_ITEM.ID_LOJA_CF_SAT   
	  INNER JOIN LOJAS_VAREJO ON LOJA_CF_SAT_ITEM.CODIGO_FILIAL = LOJAS_VAREJO.CODIGO_FILIAL 
      LEFT JOIN CLIENTES_VAREJO ON LOJA_CF_SAT.CODIGO_CLIENTE = CLIENTES_VAREJO.CODIGO_CLIENTE 
      LEFT JOIN TRIBUT_ORIGEM ON LOJA_CF_SAT_ITEM.TRIBUT_ORIGEM = TRIBUT_ORIGEM.TRIBUT_ORIGEM 
      LEFT JOIN TRIBUT_ICMS ON LOJA_CF_SAT_ITEM.TRIBUT_ICMS = TRIBUT_ICMS.TRIBUT_ICMS 
      LEFT JOIN CLASSIF_FISCAL ON LOJA_CF_SAT_ITEM.CLASSIF_FISCAL = CLASSIF_FISCAL.CLASSIF_FISCAL 
      LEFT JOIN CTB_LX_INDICADOR_CFOP ON LOJA_CF_SAT_ITEM.INDICADOR_CFOP = CTB_LX_INDICADOR_CFOP.INDICADOR_CFOP 
      LEFT JOIN CTB_LX_NATUREZAS_OPERACAO ON LOJA_CF_SAT_ITEM.CODIGO_FISCAL_OPERACAO = CTB_LX_NATUREZAS_OPERACAO.CODIGO_FISCAL_OPERACAO 

      LEFT JOIN LOJA_CF_SAT_IMPOSTO ICMS ON LOJA_CF_SAT_ITEM.ID_LOJA_CF_SAT = ICMS.ID_LOJA_CF_SAT
		AND LOJA_CF_SAT_ITEM.CODIGO_FILIAL = ICMS.CODIGO_FILIAL AND LOJA_CF_SAT_ITEM.ITEM_IMPRESSAO = ICMS.ITEM_IMPRESSAO 
		AND LOJA_CF_SAT_ITEM.SUB_ITEM_TAMANHO = ICMS.SUB_ITEM_TAMANHO AND ICMS.ID_IMPOSTO = 1

      LEFT JOIN LOJA_CF_SAT_IMPOSTO IPI ON LOJA_CF_SAT_ITEM.ID_LOJA_CF_SAT = IPI.ID_LOJA_CF_SAT
		AND LOJA_CF_SAT_ITEM.CODIGO_FILIAL = IPI.CODIGO_FILIAL AND LOJA_CF_SAT_ITEM.ITEM_IMPRESSAO = IPI.ITEM_IMPRESSAO 
		AND LOJA_CF_SAT_ITEM.SUB_ITEM_TAMANHO = IPI.SUB_ITEM_TAMANHO AND IPI.ID_IMPOSTO = 2

	  LEFT JOIN LOJA_CF_SAT_IMPOSTO IRRF ON LOJA_CF_SAT_ITEM.ID_LOJA_CF_SAT = IRRF.ID_LOJA_CF_SAT
		AND LOJA_CF_SAT_ITEM.CODIGO_FILIAL = IRRF.CODIGO_FILIAL AND LOJA_CF_SAT_ITEM.ITEM_IMPRESSAO = IRRF.ITEM_IMPRESSAO 
		AND LOJA_CF_SAT_ITEM.SUB_ITEM_TAMANHO = IRRF.SUB_ITEM_TAMANHO AND IRRF.ID_IMPOSTO = 3
      
	  LEFT JOIN LOJA_CF_SAT_IMPOSTO INSS ON LOJA_CF_SAT_ITEM.ID_LOJA_CF_SAT = INSS.ID_LOJA_CF_SAT
		AND LOJA_CF_SAT_ITEM.CODIGO_FILIAL = INSS.CODIGO_FILIAL AND LOJA_CF_SAT_ITEM.ITEM_IMPRESSAO = INSS.ITEM_IMPRESSAO 
		AND LOJA_CF_SAT_ITEM.SUB_ITEM_TAMANHO = INSS.SUB_ITEM_TAMANHO AND INSS.ID_IMPOSTO = 4

      LEFT JOIN LOJA_CF_SAT_IMPOSTO PIS ON LOJA_CF_SAT_ITEM.ID_LOJA_CF_SAT = PIS.ID_LOJA_CF_SAT
		AND LOJA_CF_SAT_ITEM.CODIGO_FILIAL = PIS.CODIGO_FILIAL AND LOJA_CF_SAT_ITEM.ITEM_IMPRESSAO = PIS.ITEM_IMPRESSAO 
		AND LOJA_CF_SAT_ITEM.SUB_ITEM_TAMANHO = PIS.SUB_ITEM_TAMANHO AND PIS.ID_IMPOSTO = 5

      LEFT JOIN LOJA_CF_SAT_IMPOSTO COFINS ON LOJA_CF_SAT_ITEM.ID_LOJA_CF_SAT = COFINS.ID_LOJA_CF_SAT
		AND LOJA_CF_SAT_ITEM.CODIGO_FILIAL = COFINS.CODIGO_FILIAL AND LOJA_CF_SAT_ITEM.ITEM_IMPRESSAO = COFINS.ITEM_IMPRESSAO 
		AND LOJA_CF_SAT_ITEM.SUB_ITEM_TAMANHO = COFINS.SUB_ITEM_TAMANHO AND COFINS.ID_IMPOSTO = 6

      LEFT JOIN LOJA_CF_SAT_IMPOSTO IMPORT ON LOJA_CF_SAT_ITEM.ID_LOJA_CF_SAT = IMPORT.ID_LOJA_CF_SAT --#7#
		AND LOJA_CF_SAT_ITEM.CODIGO_FILIAL = IMPORT.CODIGO_FILIAL AND LOJA_CF_SAT_ITEM.ITEM_IMPRESSAO = IMPORT.ITEM_IMPRESSAO 
		AND LOJA_CF_SAT_ITEM.SUB_ITEM_TAMANHO = IMPORT.SUB_ITEM_TAMANHO AND IMPORT.ID_IMPOSTO = 7

      LEFT JOIN LOJA_CF_SAT_IMPOSTO IVA ON LOJA_CF_SAT_ITEM.ID_LOJA_CF_SAT = IVA.ID_LOJA_CF_SAT
		AND LOJA_CF_SAT_ITEM.CODIGO_FILIAL = IVA.CODIGO_FILIAL AND LOJA_CF_SAT_ITEM.ITEM_IMPRESSAO = IVA.ITEM_IMPRESSAO 
		AND LOJA_CF_SAT_ITEM.SUB_ITEM_TAMANHO = IVA.SUB_ITEM_TAMANHO AND IVA.ID_IMPOSTO = 8

      LEFT JOIN LOJA_CF_SAT_IMPOSTO RECARGO ON LOJA_CF_SAT_ITEM.ID_LOJA_CF_SAT = RECARGO.ID_LOJA_CF_SAT
		AND LOJA_CF_SAT_ITEM.CODIGO_FILIAL = RECARGO.CODIGO_FILIAL AND LOJA_CF_SAT_ITEM.ITEM_IMPRESSAO = RECARGO.ITEM_IMPRESSAO 
		AND LOJA_CF_SAT_ITEM.SUB_ITEM_TAMANHO = RECARGO.SUB_ITEM_TAMANHO AND RECARGO.ID_IMPOSTO = 9

      LEFT JOIN LOJA_CF_SAT_IMPOSTO IRPF ON LOJA_CF_SAT_ITEM.ID_LOJA_CF_SAT = IRPF.ID_LOJA_CF_SAT
		AND LOJA_CF_SAT_ITEM.CODIGO_FILIAL = IRPF.CODIGO_FILIAL AND LOJA_CF_SAT_ITEM.ITEM_IMPRESSAO = IRPF.ITEM_IMPRESSAO 
		AND LOJA_CF_SAT_ITEM.SUB_ITEM_TAMANHO = IRPF.SUB_ITEM_TAMANHO AND IRPF.ID_IMPOSTO = 10
      
	  LEFT JOIN LOJA_CF_SAT_IMPOSTO DICMS ON LOJA_CF_SAT_ITEM.ID_LOJA_CF_SAT = DICMS.ID_LOJA_CF_SAT
		AND LOJA_CF_SAT_ITEM.CODIGO_FILIAL = DICMS.CODIGO_FILIAL AND LOJA_CF_SAT_ITEM.ITEM_IMPRESSAO = DICMS.ITEM_IMPRESSAO 
		AND LOJA_CF_SAT_ITEM.SUB_ITEM_TAMANHO = DICMS.SUB_ITEM_TAMANHO AND DICMS.ID_IMPOSTO = 11

      LEFT JOIN LOJA_CF_SAT_IMPOSTO ICMS_ST ON LOJA_CF_SAT_ITEM.ID_LOJA_CF_SAT = ICMS_ST.ID_LOJA_CF_SAT
		AND LOJA_CF_SAT_ITEM.CODIGO_FILIAL = ICMS_ST.CODIGO_FILIAL AND LOJA_CF_SAT_ITEM.ITEM_IMPRESSAO = ICMS_ST.ITEM_IMPRESSAO 
		AND LOJA_CF_SAT_ITEM.SUB_ITEM_TAMANHO = ICMS_ST.SUB_ITEM_TAMANHO AND ICMS_ST.ID_IMPOSTO = 12
      
	  LEFT JOIN LOJA_CF_SAT_IMPOSTO ICMS_STR ON LOJA_CF_SAT_ITEM.ID_LOJA_CF_SAT = ICMS_STR.ID_LOJA_CF_SAT
		AND LOJA_CF_SAT_ITEM.CODIGO_FILIAL = ICMS_STR.CODIGO_FILIAL AND LOJA_CF_SAT_ITEM.ITEM_IMPRESSAO = ICMS_STR.ITEM_IMPRESSAO 
		AND LOJA_CF_SAT_ITEM.SUB_ITEM_TAMANHO = ICMS_STR.SUB_ITEM_TAMANHO AND ICMS_STR.ID_IMPOSTO = 13
      
	  LEFT JOIN LOJA_CF_SAT_IMPOSTO ISS ON LOJA_CF_SAT_ITEM.ID_LOJA_CF_SAT = ISS.ID_LOJA_CF_SAT
		AND LOJA_CF_SAT_ITEM.CODIGO_FILIAL = ISS.CODIGO_FILIAL AND LOJA_CF_SAT_ITEM.ITEM_IMPRESSAO = ISS.ITEM_IMPRESSAO 
		AND LOJA_CF_SAT_ITEM.SUB_ITEM_TAMANHO = ISS.SUB_ITEM_TAMANHO AND ISS.ID_IMPOSTO = 14

      LEFT JOIN LOJA_CF_SAT_IMPOSTO IVA_IC ON LOJA_CF_SAT_ITEM.ID_LOJA_CF_SAT = IVA_IC.ID_LOJA_CF_SAT
		AND LOJA_CF_SAT_ITEM.CODIGO_FILIAL = IVA_IC.CODIGO_FILIAL AND LOJA_CF_SAT_ITEM.ITEM_IMPRESSAO = IVA_IC.ITEM_IMPRESSAO 
		AND LOJA_CF_SAT_ITEM.SUB_ITEM_TAMANHO = IVA_IC.SUB_ITEM_TAMANHO AND IVA_IC.ID_IMPOSTO = 15

      LEFT JOIN LOJA_CF_SAT_IMPOSTO PC_CSL ON LOJA_CF_SAT_ITEM.ID_LOJA_CF_SAT = PC_CSL.ID_LOJA_CF_SAT
		AND LOJA_CF_SAT_ITEM.CODIGO_FILIAL = PC_CSL.CODIGO_FILIAL and LOJA_CF_SAT_ITEM.ITEM_IMPRESSAO = PC_CSL.ITEM_IMPRESSAO 
		AND LOJA_CF_SAT_ITEM.SUB_ITEM_TAMANHO = PC_CSL.SUB_ITEM_TAMANHO AND PC_CSL.ID_IMPOSTO = 16

      LEFT JOIN LOJA_CF_SAT_IMPOSTO PIS_R ON LOJA_CF_SAT_ITEM.ID_LOJA_CF_SAT = PIS_R.ID_LOJA_CF_SAT
		AND LOJA_CF_SAT_ITEM.CODIGO_FILIAL = PIS_R.CODIGO_FILIAL AND LOJA_CF_SAT_ITEM.ITEM_IMPRESSAO = PIS_R.ITEM_IMPRESSAO 
		AND LOJA_CF_SAT_ITEM.SUB_ITEM_TAMANHO = PIS_R.SUB_ITEM_TAMANHO AND PIS_R.ID_IMPOSTO = 17

      LEFT JOIN LOJA_CF_SAT_IMPOSTO COFINS_R ON LOJA_CF_SAT_ITEM.ID_LOJA_CF_SAT = COFINS_R.ID_LOJA_CF_SAT
		AND LOJA_CF_SAT_ITEM.CODIGO_FILIAL = COFINS_R.CODIGO_FILIAL AND LOJA_CF_SAT_ITEM.ITEM_IMPRESSAO = COFINS_R.ITEM_IMPRESSAO 
		AND LOJA_CF_SAT_ITEM.SUB_ITEM_TAMANHO = COFINS_R.SUB_ITEM_TAMANHO AND COFINS_R.ID_IMPOSTO = 18

      LEFT JOIN LOJA_CF_SAT_IMPOSTO CSLL_R ON LOJA_CF_SAT_ITEM.ID_LOJA_CF_SAT = CSLL_R.ID_LOJA_CF_SAT
		AND LOJA_CF_SAT_ITEM.CODIGO_FILIAL = CSLL_R.CODIGO_FILIAL AND LOJA_CF_SAT_ITEM.ITEM_IMPRESSAO = CSLL_R.ITEM_IMPRESSAO 
		AND LOJA_CF_SAT_ITEM.SUB_ITEM_TAMANHO = CSLL_R.SUB_ITEM_TAMANHO AND CSLL_R.ID_IMPOSTO = 19

      LEFT JOIN LOJA_CF_SAT_IMPOSTO IRRF_R ON LOJA_CF_SAT_ITEM.ID_LOJA_CF_SAT = IRRF_R.ID_LOJA_CF_SAT
		AND LOJA_CF_SAT_ITEM.CODIGO_FILIAL = IRRF_R.CODIGO_FILIAL AND LOJA_CF_SAT_ITEM.ITEM_IMPRESSAO = IRRF_R.ITEM_IMPRESSAO 
		AND LOJA_CF_SAT_ITEM.SUB_ITEM_TAMANHO = IRRF_R.SUB_ITEM_TAMANHO AND IRRF_R.ID_IMPOSTO = 20

      LEFT JOIN LOJA_CF_SAT_IMPOSTO INSS_R ON LOJA_CF_SAT_ITEM.ID_LOJA_CF_SAT = INSS_R.ID_LOJA_CF_SAT
		AND LOJA_CF_SAT_ITEM.CODIGO_FILIAL = INSS_R.CODIGO_FILIAL AND LOJA_CF_SAT_ITEM.ITEM_IMPRESSAO = INSS_R.ITEM_IMPRESSAO 
		AND LOJA_CF_SAT_ITEM.SUB_ITEM_TAMANHO = INSS_R.SUB_ITEM_TAMANHO AND INSS_R.ID_IMPOSTO = 21

      LEFT JOIN LOJA_CF_SAT_IMPOSTO ISS_R ON LOJA_CF_SAT_ITEM.ID_LOJA_CF_SAT = ISS_R.ID_LOJA_CF_SAT
		AND LOJA_CF_SAT_ITEM.CODIGO_FILIAL = ISS_R.CODIGO_FILIAL AND LOJA_CF_SAT_ITEM.ITEM_IMPRESSAO = ISS_R.ITEM_IMPRESSAO 
		AND LOJA_CF_SAT_ITEM.SUB_ITEM_TAMANHO = ISS_R.SUB_ITEM_TAMANHO AND ISS_R.ID_IMPOSTO = 22 

      LEFT JOIN LOJA_CF_SAT_IMPOSTO PIS_S ON LOJA_CF_SAT_ITEM.ID_LOJA_CF_SAT = PIS_S.ID_LOJA_CF_SAT
		AND LOJA_CF_SAT_ITEM.CODIGO_FILIAL = PIS_S.CODIGO_FILIAL AND LOJA_CF_SAT_ITEM.ITEM_IMPRESSAO = PIS_S.ITEM_IMPRESSAO 
		AND LOJA_CF_SAT_ITEM.SUB_ITEM_TAMANHO = PIS_S.SUB_ITEM_TAMANHO AND PIS_S.ID_IMPOSTO = 23 

      LEFT JOIN LOJA_CF_SAT_IMPOSTO COFINS_S ON LOJA_CF_SAT_ITEM.ID_LOJA_CF_SAT = COFINS_S.ID_LOJA_CF_SAT
		AND LOJA_CF_SAT_ITEM.CODIGO_FILIAL = COFINS_S.CODIGO_FILIAL AND LOJA_CF_SAT_ITEM.ITEM_IMPRESSAO = COFINS_S.ITEM_IMPRESSAO 
		AND LOJA_CF_SAT_ITEM.SUB_ITEM_TAMANHO = COFINS_S.SUB_ITEM_TAMANHO AND COFINS_S.ID_IMPOSTO = 24
	   
      LEFT JOIN LOJA_CF_SAT_IMPOSTO CSLL_S ON LOJA_CF_SAT_ITEM.ID_LOJA_CF_SAT = CSLL_S.ID_LOJA_CF_SAT
		AND LOJA_CF_SAT_ITEM.CODIGO_FILIAL = CSLL_S.CODIGO_FILIAL AND LOJA_CF_SAT_ITEM.ITEM_IMPRESSAO = CSLL_S.ITEM_IMPRESSAO 
		AND LOJA_CF_SAT_ITEM.SUB_ITEM_TAMANHO = CSLL_S.SUB_ITEM_TAMANHO AND CSLL_S.ID_IMPOSTO = 25 

      LEFT JOIN LOJA_CF_SAT_IMPOSTO RTEIVA ON LOJA_CF_SAT_ITEM.ID_LOJA_CF_SAT = RTEIVA.ID_LOJA_CF_SAT
		AND LOJA_CF_SAT_ITEM.CODIGO_FILIAL = RTEIVA.CODIGO_FILIAL AND LOJA_CF_SAT_ITEM.ITEM_IMPRESSAO = RTEIVA.ITEM_IMPRESSAO 
		AND LOJA_CF_SAT_ITEM.SUB_ITEM_TAMANHO = RTEIVA.SUB_ITEM_TAMANHO AND RTEIVA.ID_IMPOSTO = 30 

      LEFT JOIN LOJA_CF_SAT_IMPOSTO RTEIVA_R ON LOJA_CF_SAT_ITEM.ID_LOJA_CF_SAT = RTEIVA_R.ID_LOJA_CF_SAT
		AND LOJA_CF_SAT_ITEM.CODIGO_FILIAL = RTEIVA_R.CODIGO_FILIAL AND LOJA_CF_SAT_ITEM.ITEM_IMPRESSAO = RTEIVA_R.ITEM_IMPRESSAO 
		AND LOJA_CF_SAT_ITEM.SUB_ITEM_TAMANHO = RTEIVA_R.SUB_ITEM_TAMANHO AND RTEIVA_R.ID_IMPOSTO = 31
	   
      LEFT JOIN LOJA_CF_SAT_IMPOSTO ICA ON LOJA_CF_SAT_ITEM.ID_LOJA_CF_SAT = ICA.ID_LOJA_CF_SAT
		AND LOJA_CF_SAT_ITEM.CODIGO_FILIAL = ICA.CODIGO_FILIAL AND LOJA_CF_SAT_ITEM.ITEM_IMPRESSAO = ICA.ITEM_IMPRESSAO 
		AND LOJA_CF_SAT_ITEM.SUB_ITEM_TAMANHO = ICA.SUB_ITEM_TAMANHO AND ICA.ID_IMPOSTO = 32 
      
	  LEFT JOIN LOJA_CF_SAT_IMPOSTO RTEICA ON LOJA_CF_SAT_ITEM.ID_LOJA_CF_SAT = RTEICA.ID_LOJA_CF_SAT
		AND LOJA_CF_SAT_ITEM.CODIGO_FILIAL = RTEICA.CODIGO_FILIAL AND LOJA_CF_SAT_ITEM.ITEM_IMPRESSAO = RTEICA.ITEM_IMPRESSAO 
		AND LOJA_CF_SAT_ITEM.SUB_ITEM_TAMANHO = RTEICA.SUB_ITEM_TAMANHO AND RTEICA.ID_IMPOSTO = 33 

      LEFT JOIN LOJA_CF_SAT_IMPOSTO RTEFTE ON LOJA_CF_SAT_ITEM.ID_LOJA_CF_SAT = RTEFTE.ID_LOJA_CF_SAT
		AND LOJA_CF_SAT_ITEM.CODIGO_FILIAL = RTEFTE.CODIGO_FILIAL AND LOJA_CF_SAT_ITEM.ITEM_IMPRESSAO = RTEFTE.ITEM_IMPRESSAO 
		AND LOJA_CF_SAT_ITEM.SUB_ITEM_TAMANHO = RTEFTE.SUB_ITEM_TAMANHO AND RTEFTE.ID_IMPOSTO = 34 
      	  
	  LEFT JOIN LOJA_CF_SAT_IMPOSTO RTEFTE_R ON LOJA_CF_SAT_ITEM.ID_LOJA_CF_SAT = RTEFTE_R.ID_LOJA_CF_SAT
		AND LOJA_CF_SAT_ITEM.CODIGO_FILIAL = RTEFTE_R.CODIGO_FILIAL AND LOJA_CF_SAT_ITEM.ITEM_IMPRESSAO = RTEFTE_R.ITEM_IMPRESSAO 
		AND LOJA_CF_SAT_ITEM.SUB_ITEM_TAMANHO = RTEFTE_R.SUB_ITEM_TAMANHO AND RTEFTE_R.ID_IMPOSTO = 35 

	  LEFT JOIN CTB_EXCECAO_IMPOSTO CST_ICMS (NOLOCK) ON CST_ICMS.ID_EXCECAO_IMPOSTO = LOJA_CF_SAT_ITEM.ID_EXCECAO_IMPOSTO 

      LEFT JOIN CTB_EXCECAO_IMPOSTO_ITEM CST_IPI ON CST_IPI.ID_EXCECAO_IMPOSTO = LOJA_CF_SAT_ITEM.ID_EXCECAO_IMPOSTO AND CST_IPI.ID_IMPOSTO = 2
      LEFT JOIN CTB_EXCECAO_IMPOSTO_ITEM CST_PIS ON CST_PIS.ID_EXCECAO_IMPOSTO = LOJA_CF_SAT_ITEM.ID_EXCECAO_IMPOSTO AND CST_PIS.ID_IMPOSTO = 5
      LEFT JOIN CTB_EXCECAO_IMPOSTO_ITEM CST_COFINS ON CST_COFINS.ID_EXCECAO_IMPOSTO = LOJA_CF_SAT_ITEM.ID_EXCECAO_IMPOSTO AND CST_COFINS.ID_IMPOSTO = 6
	  LEFT JOIN CTB_EXCECAO_IMPOSTO_ITEM CST_ISS (NOLOCK) ON CST_ISS.ID_EXCECAO_IMPOSTO = LOJA_CF_SAT_ITEM.ID_EXCECAO_IMPOSTO AND CST_ISS.ID_IMPOSTO IN (14,22)  

      LEFT JOIN CTB_EXCECAO_IMPOSTO_ITEM ICMS_ST_MVAST ON ICMS_ST_MVAST.ID_EXCECAO_IMPOSTO = LOJA_CF_SAT_ITEM.ID_EXCECAO_IMPOSTO 
	  AND (ICMS_ST_MVAST.ID_IMPOSTO = 12 OR ICMS_ST_MVAST.ID_IMPOSTO = 13)

      LEFT JOIN CTB_EXCECAO_IMPOSTO_ITEM ICMS_PREDBC ON ICMS_PREDBC.ID_EXCECAO_IMPOSTO = LOJA_CF_SAT_ITEM.ID_EXCECAO_IMPOSTO AND ICMS_PREDBC.ID_IMPOSTO = 1

      LEFT JOIN LOJA_CF_SAT_IMPOSTO ICMS_ZF (NOLOCK) ON LOJA_CF_SAT_ITEM.ID_LOJA_CF_SAT = ICMS_ZF.ID_LOJA_CF_SAT
		AND LOJA_CF_SAT_ITEM.CODIGO_FILIAL = ICMS_ZF.CODIGO_FILIAL AND LOJA_CF_SAT_ITEM.ITEM_IMPRESSAO = ICMS_ZF.ITEM_IMPRESSAO 
		AND LOJA_CF_SAT_ITEM.SUB_ITEM_TAMANHO = ICMS_ZF.SUB_ITEM_TAMANHO AND ICMS_ZF.ID_IMPOSTO = 36

      LEFT JOIN LOJA_CF_SAT_IMPOSTO PIS_ZF (NOLOCK) ON LOJA_CF_SAT_ITEM.ID_LOJA_CF_SAT = PIS_ZF.ID_LOJA_CF_SAT
		AND LOJA_CF_SAT_ITEM.CODIGO_FILIAL = PIS_ZF.CODIGO_FILIAL AND LOJA_CF_SAT_ITEM.ITEM_IMPRESSAO = PIS_ZF.ITEM_IMPRESSAO 
		AND LOJA_CF_SAT_ITEM.SUB_ITEM_TAMANHO = PIS_ZF.SUB_ITEM_TAMANHO AND PIS_ZF.ID_IMPOSTO = 37

      LEFT JOIN LOJA_CF_SAT_IMPOSTO COFINS_ZF (NOLOCK) ON LOJA_CF_SAT_ITEM.ID_LOJA_CF_SAT = COFINS_ZF.ID_LOJA_CF_SAT
		AND LOJA_CF_SAT_ITEM.CODIGO_FILIAL = COFINS_ZF.CODIGO_FILIAL AND LOJA_CF_SAT_ITEM.ITEM_IMPRESSAO = COFINS_ZF.ITEM_IMPRESSAO 
		AND LOJA_CF_SAT_ITEM.SUB_ITEM_TAMANHO = COFINS_ZF.SUB_ITEM_TAMANHO AND COFINS_ZF.ID_IMPOSTO = 38

	  LEFT JOIN LOJA_CF_SAT_IMPOSTO SIMPLES_F (NOLOCK) ON LOJA_CF_SAT_ITEM.ID_LOJA_CF_SAT = SIMPLES_F.ID_LOJA_CF_SAT
		AND LOJA_CF_SAT_ITEM.CODIGO_FILIAL = SIMPLES_F.CODIGO_FILIAL AND LOJA_CF_SAT_ITEM.ITEM_IMPRESSAO = SIMPLES_F.ITEM_IMPRESSAO 
		AND LOJA_CF_SAT_ITEM.SUB_ITEM_TAMANHO = SIMPLES_F.SUB_ITEM_TAMANHO AND SIMPLES_F.ID_IMPOSTO = 44 

	  LEFT JOIN LOJA_CF_SAT_IMPOSTO ICMS_SN (NOLOCK) ON LOJA_CF_SAT_ITEM.ID_LOJA_CF_SAT = ICMS_SN.ID_LOJA_CF_SAT
		AND LOJA_CF_SAT_ITEM.CODIGO_FILIAL = ICMS_SN.CODIGO_FILIAL AND LOJA_CF_SAT_ITEM.ITEM_IMPRESSAO = ICMS_SN.ITEM_IMPRESSAO 
		AND LOJA_CF_SAT_ITEM.SUB_ITEM_TAMANHO = ICMS_SN.SUB_ITEM_TAMANHO AND ICMS_SN.ID_IMPOSTO = 55

	  LEFT JOIN LOJA_CF_SAT_IMPOSTO PIS_SN (NOLOCK) ON LOJA_CF_SAT_ITEM.ID_LOJA_CF_SAT = PIS_SN.ID_LOJA_CF_SAT
		AND LOJA_CF_SAT_ITEM.CODIGO_FILIAL = PIS_SN.CODIGO_FILIAL AND LOJA_CF_SAT_ITEM.ITEM_IMPRESSAO = PIS_SN.ITEM_IMPRESSAO 
		AND LOJA_CF_SAT_ITEM.SUB_ITEM_TAMANHO = PIS_SN.SUB_ITEM_TAMANHO AND PIS_SN.ID_IMPOSTO = 56

	  LEFT JOIN LOJA_CF_SAT_IMPOSTO COFINS_SN (NOLOCK) ON LOJA_CF_SAT_ITEM.ID_LOJA_CF_SAT = COFINS_SN.ID_LOJA_CF_SAT
		AND LOJA_CF_SAT_ITEM.CODIGO_FILIAL = COFINS_SN.CODIGO_FILIAL AND LOJA_CF_SAT_ITEM.ITEM_IMPRESSAO = COFINS_SN.ITEM_IMPRESSAO 
		AND LOJA_CF_SAT_ITEM.SUB_ITEM_TAMANHO = COFINS_SN.SUB_ITEM_TAMANHO AND COFINS_SN.ID_IMPOSTO = 57

	  LEFT JOIN LOJA_CF_SAT_IMPOSTO ICMS_BST (NOLOCK) ON LOJA_CF_SAT_ITEM.ID_LOJA_CF_SAT = ICMS_BST.ID_LOJA_CF_SAT
		AND LOJA_CF_SAT_ITEM.CODIGO_FILIAL = ICMS_BST.CODIGO_FILIAL AND LOJA_CF_SAT_ITEM.ITEM_IMPRESSAO = ICMS_BST.ITEM_IMPRESSAO 
		AND LOJA_CF_SAT_ITEM.SUB_ITEM_TAMANHO = ICMS_BST.SUB_ITEM_TAMANHO AND ICMS_BST.ID_IMPOSTO = 51

      LEFT JOIN CTB_EXCECAO_IMPOSTO_ITEM ICMS_BST_PREDBC ON ICMS_BST_PREDBC.ID_EXCECAO_IMPOSTO = LOJA_CF_SAT_ITEM.ID_EXCECAO_IMPOSTO AND ICMS_BST_PREDBC.ID_IMPOSTO = 51	  

      LEFT JOIN CTB_EXCECAO_IMPOSTO_ITEM CST_ICMS_ZF (NOLOCK) ON CST_ICMS_ZF.ID_EXCECAO_IMPOSTO = LOJA_CF_SAT_ITEM.ID_EXCECAO_IMPOSTO AND CST_ICMS_ZF.ID_IMPOSTO = 36

	  LEFT JOIN CEST_NCM LISTA_CEST_NCM ON LOJA_CF_SAT_ITEM.ID_CEST_NCM = LISTA_CEST_NCM.ID --#12#
      
	  LEFT JOIN TABELA_LX_CEST ON LISTA_CEST_NCM.ID_CEST = TABELA_LX_CEST.ID --#12#

