-- POSSP-5157  - Gilvano Santos - (31/03/2021) - Nota Técnica 2020.006
IF NOT EXISTS( SELECT 1 FROM SYS.sysobjects WHERE NAME = 'LOJA_INTERMEDIADORES_TRANSACAO_FILIAL' )
BEGIN
	CREATE TABLE [dbo].[LOJA_INTERMEDIADORES_TRANSACAO_FILIAL](
				[ID_INTERMEDIADOR] [int] NOT NULL,
				[COD_FILIAL] [char](6) NOT NULL,
				[IDCADINTTRAN] [varchar](60) NOT NULL,
				[INATIVO] [bit] DEFAULT 0 NOT NULL,
				[CODIGO_FILIAL] [char](6) NOT NULL,
	CONSTRAINT [XPKLOJA_INTERMEDIADORES_TRANSACAO_FILIAL] PRIMARY KEY CLUSTERED 
    (
                [ID_INTERMEDIADOR] ASC, [COD_FILIAL] ASC, [IDCADINTTRAN] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
    CONSTRAINT [XAKLOJA_INTERMEDIADORES_TRANSACAO_FILIAL] UNIQUE NONCLUSTERED 
	(
			[IDCADINTTRAN] ASC,
			[COD_FILIAL] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
	CONSTRAINT [XFK10001_LOJA_INTERMEDIADORES_TRANSACAO_FILIAL] FOREIGN KEY
	(
		[ID_INTERMEDIADOR]
	)
	REFERENCES [dbo].[LOJA_INTERMEDIADORES_TRANSACAO] ([ID_INTERMEDIADOR]) ON DELETE CASCADE--,
	/*CONSTRAINT [XFK10002_LOJA_INTERMEDIADORES_TRANSACAO_FILIAL] FOREIGN KEY
	(
		[COD_FILIAL]
	)
    REFERENCES [dbo].[FILIAIS] ([COD_FILIAL])
	*/
	
	) ON [PRIMARY]
END