CREATE FUNCTION [dbo].[FX_VALIDATABELAIBPT] (@UF CHAR(2))

RETURNS TABLE
AS 
-- PRODSHOP-10020 - FERNANDO MARINHO - 31/12/2021 - #3# - AJUSTE NO FIM VIGENCIA 
-- DM36131   - WENDEL CRESPIGIO #2# - 29/06/2017 - Wendel Crespigio - Correção conforme verificação com Thiago Marcon passou a verificar o ncm do produto na validação
-- TP9148545 - JORGE.DAMASCO - #1# - (30/06/2015) - CRIAÇÃO DA FUNÇÃO PARA RETORNAR O INÍCIO/FIM VIGÊNCIA DA TABELA
--													IBPT, QUANTOS DIAS FALTAM PARA VENCER E SE EXISTE UMA PRÓXIMA
--													TABELA VALIDA. A FUNÇÃO FOI CRIADA PARA PODERMOS DAR UMA MELHOR
--													MANUTENÇÃO EM CASO DE ALGUMA MUDANÇA.
RETURN (

WITH CTETABELAIBPT AS 
			(
				SELECT	TOP 1 UF, INICIO_VIGENCIA, FIM_VIGENCIA, CHAVE, NCM_NBS
				FROM	DBO.TABELA_ALIQUOTA_IMPOSTO_ITEM AS VIGENTE
				WHERE	VIGENTE.UF = @UF
				AND		CONVERT(VARCHAR(20),Getdate(),112) BETWEEN VIGENTE.INICIO_VIGENCIA AND VIGENTE.FIM_VIGENCIA
				ORDER BY FIM_VIGENCIA DESC --#3#
			)
			SELECT	VIGENTE.INICIO_VIGENCIA,
					VIGENTE.FIM_VIGENCIA,
					DATEDIFF(DAY, CONVERT(VARCHAR(20),Getdate(),112), VIGENTE.FIM_VIGENCIA) DIASVALIDADETAB,
					CAST(CASE WHEN PROXIMA.CHAVE IS NULL THEN 0 ELSE 1 END AS BIT) TEMPROXTABELA
			FROM	CTETABELAIBPT AS VIGENTE
			OUTER APPLY (SELECT TOP 1 INICIO_VIGENCIA ,FIM_VIGENCIA,NCM_NBS,CHAVE 
							FROM DBO.TABELA_ALIQUOTA_IMPOSTO_ITEM AS PROXIMA
			                		Inner Join PRODUTOS P --#2#
							ON PROXIMA.NCM_NBS = LEFT(REPLACE(P.CLASSIF_FISCAL,'.',''),8)  
							WHERE VIGENTE.UF = PROXIMA.UF 
							AND PROXIMA.INICIO_VIGENCIA > VIGENTE.FIM_VIGENCIA) AS PROXIMA 
)
