CREATE FUNCTION [DBO].[FN_NOTAS_REFERENCIADAS_DEV]  (@NOTAFISCAL CHAR(15), @SERIENOTA CHAR(6), @CODIGO_FILIAL CHAR(6))
RETURNS @LOJA_VENDA_ORIGEM TABLE
(
	CHAVE_NFE				VARCHAR(44),
	CHAVEACESSO				varchar(44), 
	NF						CHAR(15),
	SERIE					CHAR(6),
	FILIAL					VARCHAR(25) ,              
	ORIGEM_ENTRADA_SAIDA	VARCHAR(1),
	NF_ORIGEM				CHAR(15),
	SERIE_NF_ORIGEM			CHAR(6),
	MODELO_FISCAL	        varchar(3),                    
	NUMERO_ECF				varchar(20),
	NUMERO_COO				VARCHAR(9)
)
AS 
-- DM 94785 - Wendel Crespigio - #2# - 20/09/2018 - Tratamento do venda finalizada = 1  
-- DM 77455	- Diego Moreno    -  #1# - 08/06/2018 - Criação da function para melhoria de performance.
BEGIN	
	DECLARE @CODIGO_FILIAL_FILTRO CHAR(6), @TICKET_FILTRO CHAR(8), @DATA_VENDA_FILTRO DATETIME, 
	@NUMERO_FISCAL_TROCA CHAR(15), @SERIE_NF_ENTRADA CHAR(6), @NUMERO_MODELO_FISCAL VARCHAR(2),
	@NUMERO_FISCAL_TROCA2 CHAR(15), @SERIE_NF_ENTRADA2 CHAR(6),@NUMERO_ECF VARCHAR(20), @NUMERO_COO VARCHAR(6),
	@TERMINAL CHAR(3), @LANCAMENTO_CAIXA CHAR(7), @DATA_VENDA_FILTRO2 DATETIME 
--**********************************************************************************************************************************************************************				
						SELECT	@CODIGO_FILIAL_FILTRO = c.CODIGO_FILIAL_ORIGEM, 
								@TICKET_FILTRO = c.TICKET_ORIGEM, 
								@DATA_VENDA_FILTRO = c.DATA_VENDA_ORIGEM,
								@NUMERO_FISCAL_TROCA = A.NUMERO_FISCAL_TROCA, 
								@SERIE_NF_ENTRADA = A.SERIE_NF_ENTRADA  ,
								@NUMERO_MODELO_FISCAL = '2D'
						FROM LOJA_VENDA_PGTO A
						INNER   JOIN LOJA_VENDA B ON A.CODIGO_FILIAL = B.CODIGO_FILIAL AND 
								A.TERMINAL = B.TERMINAL AND 
								A.LANCAMENTO_CAIXA = B.LANCAMENTO_CAIXA 
						INNER   JOIN LOJA_VENDA_TROCA_ORIGEM C ON C.CODIGO_FILIAL = B.CODIGO_FILIAL AND 
								C.DATA_VENDA = B.DATA_VENDA AND 
								C.TICKET = B.TICKET AND 
								C.TICKET_ORIGEM <> C.TICKET 
						WHERE	A.NUMERO_FISCAL_TROCA =  @NOTAFISCAL
						AND		A.SERIE_NF_ENTRADA = @SERIENOTA
						--and		A.VENDA_FINALIZADA = 1 --#2#
--**********************************************************************************************************************************************************************

			SELECT	@NUMERO_FISCAL_TROCA2 = A.NUMERO_FISCAL_TROCA,
					@SERIE_NF_ENTRADA2 = A.SERIE_NF_ENTRADA, 
					@NUMERO_ECF = ISNULL(A.ID_EQUIPAMENTO, 1), 
					@NUMERO_COO = NULL ,
					@LANCAMENTO_CAIXA = A.LANCAMENTO_CAIXA,
					@TERMINAL = A.TERMINAL,
					@TICKET_FILTRO = C.TICKET_ORIGEM,
					@DATA_VENDA_FILTRO2 = C.DATA_VENDA_ORIGEM 
			FROM	LOJA_VENDA_PGTO A (NOLOCK)
			INNER JOIN LOJA_VENDA B (NOLOCK) ON	 A.CODIGO_FILIAL = B.CODIGO_FILIAL
											 AND A.TERMINAL = B.TERMINAL
											 AND A.LANCAMENTO_CAIXA = B.LANCAMENTO_CAIXA
			INNER JOIN LOJA_VENDA_TROCA_ORIGEM C (NOLOCK) ON	C.CODIGO_FILIAL = B.CODIGO_FILIAL
														  AND	C.DATA_VENDA = B.DATA_VENDA
														  AND	C.TICKET = B.TICKET
														  AND	C.TICKET <> C.TICKET_ORIGEM
			
			where	A.NUMERO_FISCAL_TROCA = @NOTAFISCAL
			AND		A.SERIE_NF_ENTRADA =	@SERIENOTA
			--and A.VENDA_FINALIZADA = 1 --#2#
			
			

--**********************************************************************************************************************************************************************

INSERT INTO @LOJA_VENDA_ORIGEM(CHAVE_NFE,CHAVEACESSO,  FILIAL, SERIE, 
			NF, ORIGEM_ENTRADA_SAIDA,NF_ORIGEM, SERIE_NF_ORIGEM,MODELO_FISCAL, NUMERO_ECF, NUMERO_COO)		

SELECT	DISTINCT
		CHAVE_NFE = CASE WHEN ISNULL(I.CHAVE_NFE, NF_ORIGEM.CHAVE_NFE_ORIGEM) IS NULL THEN NULL ELSE ISNULL(I.CHAVE_NFE, NF_ORIGEM.CHAVE_NFE_ORIGEM)END,	--#2#  
		CHAVEACESSO = (SELECT	TOP 1	SUBSTRING(M.COD_MUNICIPIO_IBGE, 1, 2)
					   FROM LCF_LX_MUNICIPIO M (NOLOCK)
					   INNER JOIN LCF_LX_UF U (NOLOCK) ON U.ID_UF = M.ID_UF
					   WHERE U.UF = F.UF
					   AND	 M.DESC_MUNICIPIO = dbo.FX_REPLACE_CARACTER_ESPECIAL_NFE(DEFAULT, F.CIDADE)) + 
					   SUBSTRING(CONVERT(CHAR(10), I.EMISSAO, 112), 3, 4) + RTRIM(F.CGC_CPF) + 
					   (SELECT		RIGHT('0' + RTRIM(ES.NUMERO_MODELO_FISCAL), 2) + CASE WHEN SN.COD_SERIE_SINTEGRA IS NOT NULL 
					   THEN RIGHT('00' + RTRIM(CASE WHEN SN.COD_SERIE_SINTEGRA = 'U' OR SN.COD_SERIE_SINTEGRA = 'UN' 
					   THEN '0' ELSE SN.COD_SERIE_SINTEGRA END), 3)
																																																												 ELSE RIGHT('00' + RTRIM(CASE WHEN SN.SERIE_NF = 'U' OR SN.SERIE_NF = 'UN' THEN '0' ELSE SN.SERIE_NF END), 3)
																																																												 END
						FROM	SERIES_NF SN (NOLOCK)
						INNER JOIN CTB_ESPECIE_SERIE ES (NOLOCK) ON SN.ESPECIE_SERIE = ES.ESPECIE_SERIE
						WHERE SERIE_NF = I.SERIE_NF) + RIGHT('00000000' + RTRIM(A.NF_NUMERO), 9), ISNULL(CONVERT(VARCHAR(40), H.NOME_CLIFOR), G.CLIENTE_VAREJO) AS FILIAL, 
						A.SERIE_NF AS SERIE, A.NF_NUMERO AS NF, 'S' AS ORIGEM_ENTRADA_SAIDA, 
						NF_ORIGEM.NF_ORIGEM, NF_ORIGEM.SERIE_NF_ORIGEM, NF_ORIGEM.MODELO_FISCAL, NF_ORIGEM.NUMERO_ECF, NF_ORIGEM.NUMERO_COO
FROM	LOJA_NOTA_FISCAL_ITEM A (NOLOCK)
LEFT JOIN LOJA_NOTA_FISCAL B (NOLOCK) ON	B.NF_NUMERO = A.NF_NUMERO
									  AND	B.SERIE_NF = A.SERIE_NF
									  AND	B.CODIGO_FILIAL = A.CODIGO_FILIAL
LEFT JOIN LOJAS_VAREJO E (NOLOCK) ON E.CODIGO_FILIAL = A.CODIGO_FILIAL
LEFT JOIN CADASTRO_CLI_FOR F (NOLOCK) ON E.FILIAL = F.NOME_CLIFOR
LEFT JOIN CLIENTES_VAREJO G (NOLOCK) ON B.CODIGO_CLIENTE = G.CODIGO_CLIENTE
LEFT JOIN CADASTRO_CLI_FOR H (NOLOCK) ON B.COD_CLIFOR = H.COD_CLIFOR
INNER JOIN (

			SELECT 
			ISNULL(G.CODIGO_FILIAL, F.CODIGO_FILIAL) AS CODIGO_FILIAL,	 
					ISNULL(G.NF_NUMERO, F.NF_NUMERO) AS NF_ORIGEM,				
					ISNULL(G.SERIE_NF, F.SERIE_NF) AS SERIE_NF_ORIGEM,			
					ISNULL(G.CHAVE_NFE, F.CHAVE_NFE) AS CHAVE_NFE_ORIGEM,
					@NUMERO_FISCAL_TROCA AS NF_TROCA, @SERIE_NF_ENTRADA AS SERIE_NF_TROCA, 
					@NUMERO_MODELO_FISCAL AS MODELO_FISCAL, ISNULL(E.ID_EQUIPAMENTO, 1) AS NUMERO_ECF,  
					E.NUMERO_CUPOM_FISCAL AS NUMERO_COO
			from LOJA_VENDA D (NOLOCK)  

			INNER JOIN LOJA_VENDA_PGTO E (NOLOCK) ON	E.CODIGO_FILIAL = D.CODIGO_FILIAL
												  AND	E.TERMINAL = D.TERMINAL
												  AND	E.LANCAMENTO_CAIXA = D.LANCAMENTO_CAIXA
			INNER JOIN LOJA_NOTA_FISCAL F (NOLOCK) ON	F.CODIGO_FILIAL = E.CODIGO_FILIAL
												   AND	F.NF_NUMERO = E.NUMERO_FISCAL_VENDA
												   AND	F.SERIE_NF = E.SERIE_NF_SAIDA
												   AND	F.STATUS_NFE = '5'
			LEFT JOIN LOJA_NOTA_FISCAL G (NOLOCK) ON	G.CODIGO_FILIAL = E.CODIGO_FILIAL
												  AND	G.NF_NUMERO = E.NUMERO_FISCAL_VINCULADA
												  AND	G.SERIE_NF = E.SERIE_NF_VINCULADA
												  AND	G.STATUS_NFE = '5' --#3#  
			WHERE	D.CODIGO_FILIAL = @CODIGO_FILIAL_FILTRO
			AND		D.TICKET = @TICKET_FILTRO 
			AND		D.DATA_VENDA = @DATA_VENDA_FILTRO


			/*--INICIO #2#*/
			UNION ALL

			SELECT ISNULL(I.CODIGO_FILIAL, F.CODIGO_FILIAL) AS CODIGO_FILIAL,			 
					ISNULL(I.NF_NUMERO, CONVERT(CHAR(18), F.CF_NUMERO)) AS NF_ORIGEM,	 
					ISNULL(I.SERIE_NF, F.SERIE_NF) AS SERIE_NF_ORIGEM,					 
					ISNULL(I.CHAVE_NFE, F.CHAVE_CFE) AS CHAVE_NFE_ORIGEM,
			@NUMERO_FISCAL_TROCA2 AS NF_TROCA, 
			@SERIE_NF_ENTRADA2 AS SERIE_NF_TROCA, 
			H.NUMERO_MODELO_FISCAL AS MODELO_FISCAL, 
			@NUMERO_ECF AS NUMERO_ECF, 
			@NUMERO_COO AS NUMERO_COO
			FROM  LOJA_VENDA D (NOLOCK) 
			INNER JOIN 	LOJA_VENDA_PGTO E (NOLOCK)		
			ON  D.CODIGO_FILIAL = E.CODIGO_FILIAL
			AND D.LANCAMENTO_CAIXA = E.LANCAMENTO_CAIXA
			AND D.TERMINAL = E.TERMINAL
									 
			INNER JOIN LOJA_CF_SAT F (NOLOCK) ON	F.CODIGO_FILIAL = E.CODIGO_FILIAL
											  AND	F.GUID_VENDA_SAT = E.GUID_VENDA_SAT
											  AND	F.STATUS_CFE = '5'
											  AND	F.TERMINAL = E.TERMINAL
											  AND	F.LANCAMENTO_CAIXA = E.LANCAMENTO_CAIXA
			INNER JOIN SERIES_NF G (NOLOCK) ON F.SERIE_NF = G.SERIE_NF
			-- INICIO #3#   
			LEFT JOIN LOJA_NOTA_FISCAL I (NOLOCK) ON	I.CODIGO_FILIAL = E.CODIGO_FILIAL
												  AND	I.NF_NUMERO = E.NUMERO_FISCAL_VINCULADA
												  AND	I.SERIE_NF = E.SERIE_NF_VINCULADA
												  AND	I.STATUS_NFE = '5'
			LEFT JOIN SERIES_NF J (NOLOCK) ON I.SERIE_NF = J.SERIE_NF
			-- FIM #3#  
			INNER JOIN CTB_ESPECIE_SERIE H (NOLOCK) ON H.ESPECIE_SERIE = ISNULL(J.ESPECIE_SERIE, G.ESPECIE_SERIE) --#3#  
			where	E.CODIGO_FILIAL = @CODIGO_FILIAL
			AND		E.LANCAMENTO_CAIXA = @LANCAMENTO_CAIXA
			AND		E.TERMINAL = @TERMINAL
			AND		D.CODIGO_FILIAL = @CODIGO_FILIAL_FILTRO
			AND		D.TERMINAL = @TERMINAL
			AND		D.TICKET = @TICKET_FILTRO
			AND		D.DATA_VENDA = @DATA_VENDA_FILTRO2
			--and E.VENDA_FINALIZADA = 1 --#2#
	
/*--FIM #2#*/
) AS NF_ORIGEM ON	NF_ORIGEM.NF_TROCA = B.NF_NUMERO
			   AND	NF_ORIGEM.SERIE_NF_TROCA = B.SERIE_NF
LEFT JOIN LOJA_NOTA_FISCAL I (NOLOCK) ON	I.CODIGO_FILIAL = NF_ORIGEM.CODIGO_FILIAL
									  AND	I.NF_NUMERO = NF_ORIGEM.NF_ORIGEM
									  AND	I.SERIE_NF = NF_ORIGEM.SERIE_NF_ORIGEM --#2#  
LEFT JOIN LOJA_CF_SAT J (NOLOCK) ON	 J.CODIGO_FILIAL = NF_ORIGEM.CODIGO_FILIAL
								 AND CONVERT(CHAR(18), J.CF_NUMERO) = NF_ORIGEM.NF_ORIGEM
								 AND J.SERIE_NF = NF_ORIGEM.SERIE_NF_ORIGEM --#2#  
WHERE	A.NF_NUMERO = @NOTAFISCAL and 
		a.SERIE_NF = @SERIENOTA   AND		
		B.TIPO_ORIGEM IN (2, 8)   AND		
		B.RECEBIMENTO = 1
	RETURN 
END