IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'LOJA_VENDA_TROCA'
                      AND COLUMN_NAME = 'ORIGEM_OMS')
  ALTER TABLE [dbo].[LOJA_VENDA_TROCA]
    ADD ORIGEM_OMS BIT NULL 
