
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CONTROLE_SALDO_ST_UF]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[CONTROLE_SALDO_ST_UF](
	[ID] [int] NOT NULL,
	[UF] [char](2) NOT NULL,
	[FILIAL] [varchar](25) NOT NULL,
	[UTIL_SALDO_ST_MEDIA] [bit] NOT NULL,
	[DATA_PARA_TRANSFERENCIA] [datetime] NULL
 CONSTRAINT [XPKCONTROLE_SALDO_ST_UF] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__CONTROLE___UTIL___577AB2FD]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[CONTROLE_SALDO_ST_UF] ADD  CONSTRAINT [DF__CONTROLE___UTIL___577AB2FD]  DEFAULT ((0)) FOR [UTIL_SALDO_ST_MEDIA]
END


IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[XFK10001_CONTROLE_SALDO_ST_UF]') AND parent_object_id = OBJECT_ID(N'[dbo].[CONTROLE_SALDO_ST_UF]'))
ALTER TABLE [dbo].[CONTROLE_SALDO_ST_UF]  WITH NOCHECK ADD  CONSTRAINT [XFK10001_CONTROLE_SALDO_ST_UF] FOREIGN KEY([FILIAL])
REFERENCES [dbo].[FILIAIS] ([FILIAL])


IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[XFK10001_CONTROLE_SALDO_ST_UF]') AND parent_object_id = OBJECT_ID(N'[dbo].[CONTROLE_SALDO_ST_UF]'))
ALTER TABLE [dbo].[CONTROLE_SALDO_ST_UF] CHECK CONSTRAINT [XFK10001_CONTROLE_SALDO_ST_UF]


IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[XFK10002_CONTROLE_SALDO_ST_UF]') AND parent_object_id = OBJECT_ID(N'[dbo].[CONTROLE_SALDO_ST_UF]'))
ALTER TABLE [dbo].[CONTROLE_SALDO_ST_UF] CHECK CONSTRAINT [XFK10002_CONTROLE_SALDO_ST_UF]



