IF EXISTS (	SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LJ_CADASTRO_MAQUINA_POS' AND COLUMN_NAME = 'DATA_PARA_TRANSFERENCIA' )
BEGIN
	DECLARE @DEF1 AS VARCHAR(100)
		
	SELECT @DEF1 = ( SELECT B.NAME FROM SYS.TABLES A INNER JOIN SYS.DEFAULT_CONSTRAINTS B ON A.OBJECT_ID	= B.PARENT_OBJECT_ID INNER JOIN SYS.COLUMNS C ON A.OBJECT_ID = C.OBJECT_ID
						WHERE A.NAME = 'LJ_CADASTRO_MAQUINA_POS' AND C.NAME = 'DATA_PARA_TRANSFERENCIA' )

	IF LTRIM(RTRIM(@DEF1)) <> ''
	BEGIN
		EXEC('ALTER TABLE LJ_CADASTRO_MAQUINA_POS DROP CONSTRAINT ' + @DEF1)
	END

	EXECUTE SP_BINDEFAULT 'DATA_ATUAL', 'DBO.LJ_CADASTRO_MAQUINA_POS.DATA_PARA_TRANSFERENCIA';	
END


IF EXISTS (	SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_VENDA_DADOS_CARTAO' AND COLUMN_NAME = 'DATA_PARA_TRANSFERENCIA' )
BEGIN
	DECLARE @DEF2 AS VARCHAR(100)
		
	SELECT @DEF2 = ( SELECT B.NAME FROM	SYS.TABLES A INNER JOIN SYS.DEFAULT_CONSTRAINTS B ON A.OBJECT_ID = B.PARENT_OBJECT_ID INNER JOIN SYS.COLUMNS C ON A.OBJECT_ID = C.OBJECT_ID
						WHERE A.NAME = 'LOJA_VENDA_DADOS_CARTAO' AND C.NAME = 'DATA_PARA_TRANSFERENCIA' )

	IF LTRIM(RTRIM(@DEF2)) <> ''
	BEGIN
		EXEC('ALTER TABLE LOJA_VENDA_DADOS_CARTAO DROP CONSTRAINT ' + @DEF2)
	END

	EXECUTE SP_BINDEFAULT 'DATA_ATUAL', 'DBO.LOJA_VENDA_DADOS_CARTAO.DATA_PARA_TRANSFERENCIA';	
END