IF NOT EXISTS(SELECT TIPO_EVENTO FROM LOJA_LX_EVENTOS_TIPOS WHERE TIPO_EVENTO = '50')
	INSERT INTO LOJA_LX_EVENTOS_TIPOS (TIPO_EVENTO, DESCRICAO, MODULO_EVENTO)
	VALUES(50,'Iniciado atualização do saldo de estoque via ETL', 7)

IF NOT EXISTS(SELECT TIPO_EVENTO FROM LOJA_LX_EVENTOS_TIPOS WHERE TIPO_EVENTO = '51')
	INSERT INTO LOJA_LX_EVENTOS_TIPOS (TIPO_EVENTO, DESCRICAO, MODULO_EVENTO)
	VALUES(51,'Encerrado atualização do saldo de estoque via ETL', 7)