--18/01/2018 - Wendel Crespigio - Criação da view  W_PARAMETROS_MOBILE

CREATE VIEW W_PARAMETROS_MOBILE      
AS      
  SELECT      
   A.CODIGO_FILIAL,     
   A.TERMINAL,     
   LTRIM(RTRIM(B.PARAMETRO)) AS PARAMETRO,     
   LTRIM(RTRIM(B.DESC_PARAMETRO)) AS DESC_PARAMETRO,      
   VALOR_ATUAL = LTRIM(RTRIM(CASE WHEN ISNULL(D.VALOR_ATUAL, '') = ''       
     THEN (CASE WHEN ISNULL(C.VALOR_ATUAL, '') = ''       
     THEN (CASE WHEN ISNULL(B.VALOR_ATUAL, '') = '' THEN B.VALOR_DEFAULT ELSE B.VALOR_ATUAL END)       
     ELSE C.VALOR_ATUAL END)       
     ELSE D.VALOR_ATUAL END)) ,  
   VALOR_DEFAULT = LTRIM(RTRIM(CASE WHEN ISNULL(D.VALOR_ATUAL, '') = ''       
     THEN (CASE WHEN ISNULL(C.VALOR_ATUAL, '') = ''       
     THEN (CASE WHEN ISNULL(B.VALOR_ATUAL, '') = '' THEN B.VALOR_DEFAULT ELSE B.VALOR_ATUAL END)       
      ELSE C.VALOR_ATUAL END)       
     ELSE D.VALOR_ATUAL END))    
  FROM      
   LOJA_TERMINAIS A       
   INNER JOIN PARAMETROS B ON B.ENVIA_PARA_LOJA = 1       
   LEFT JOIN PARAMETROS_LOJA C ON A.CODIGO_FILIAL = C.CODIGO_FILIAL AND B.PARAMETRO = C.PARAMETRO      
   LEFT JOIN PARAMETROS_LOJA_TERMINAL D ON A.CODIGO_FILIAL = D.CODIGO_FILIAL AND A.TERMINAL = D.TERMINAL AND B.PARAMETRO = D.PARAMETRO