IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[LX_CONFIG_VERSAO_UF]') AND TYPE IN (N'U'))

BEGIN
CREATE TABLE [DBO].[LX_CONFIG_VERSAO_UF](
	[UF] [CHAR](2) NOT NULL,
	[VERSAO] [VARCHAR](10) NOT NULL,
	[SISTEMA] [VARCHAR](50) NOT NULL,
	[COD_CRED] [VARCHAR](25) NULL,
	[INATIVO] [BIT] NOT NULL DEFAULT 0,
	[DATA_PARA_TRANSFERENCIA] [DATETIME] NULL,
 CONSTRAINT [XPKLX_CONFIG_VERSAO_UF] PRIMARY KEY CLUSTERED 
(
	[VERSAO],[UF],[SISTEMA]  ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

END;
