IF NOT EXISTS (SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID('DBO.LOJA_VENDA_PGTO') AND NAME = 'XIE9LOJA_VENDA_PAGTO')
CREATE NONCLUSTERED INDEX [XIE9LOJA_VENDA_PAGTO]
ON [dbo].[LOJA_VENDA_PGTO] ([CODIGO_FILIAL],[TERMINAL],[NUMERO_CUPOM_FISCAL],[ID_EQUIPAMENTO])





