IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[CLIENTE_VAR_DOCUMENTO_TIPO]') AND TYPE IN (N'U'))
    CREATE TABLE [dbo].[CLIENTE_VAR_DOCUMENTO_TIPO](
	    [ID] INT NOT NULL,
	    [TIPO] VARCHAR(25) NOT NULL,
	    [INATIVO] [bit] NOT NULL,
	    [DATA_PARA_TRANSFERENCIA] [datetime] NULL,
     CONSTRAINT [XPKCLIENTE_VAR_DOCUMENTO_TIPO] PRIMARY KEY NONCLUSTERED 
    (
	    [ID] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
    ) ON [PRIMARY]
    

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[CLIENTES_VAREJO_DOCUMENTO]') AND TYPE IN (N'U'))
BEGIN
    CREATE TABLE dbo.CLIENTES_VAREJO_DOCUMENTO(
	    ID INT NOT NULL,
	    CODIGO_CLIENTE VARCHAR(14) NOT NULL,
	    CODIGO_FILIAL CHAR(6) NOT NULL,
	    LEGENDA VARCHAR(50) NULL,
	    RESPONSAVEL VARCHAR(25) NULL,
	    ID_DOC_TIPO INT NOT NULL,
	    PATH_ARQUIVO VARCHAR(250) NULL,
	    CONTEUDO TEXT NULL,
	    INATIVO BIT NOT NULL,
	    DATA_PARA_TRANSFERENCIA [datetime] NULL,
     CONSTRAINT [XPKCLIENTES_VAREJO_DOCUMENTO] PRIMARY KEY NONCLUSTERED 
    (
	    ID ASC,
	    CODIGO_CLIENTE asc,
	    CODIGO_FILIAL asc
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
    ) ON [PRIMARY]

     ALTER TABLE [dbo].CLIENTES_VAREJO_DOCUMENTO  WITH NOCHECK ADD  CONSTRAINT [XFK12789_CLIENTES_VAREJO_DOCUMENTO] FOREIGN KEY(ID_DOC_TIPO)
    REFERENCES [dbo].[CLIENTE_VAR_DOCUMENTO_TIPO] (ID)
    NOT FOR REPLICATION 
    
    ALTER TABLE [dbo].CLIENTES_VAREJO_DOCUMENTO CHECK CONSTRAINT [XFK12789_CLIENTES_VAREJO_DOCUMENTO]

END


