--BASE DE DADOS DE LOJA
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[LOJA_CAIXA_CONFERENCIA]') AND TYPE IN (N'U'))
	and NOT EXISTS (SELECT * FROM sys.key_constraints WHERE parent_object_id= OBJECT_ID(N'[DBO].[LOJA_CAIXA_CONFERENCIA]') AND TYPE = 'PK') AND NOT EXISTS (SELECT * FROM SYS.tables WHERE NAME='CM_ESTOQUE_PA' AND TYPE='U')
	BEGIN

		IF (SELECT count(*) FROM LOJA_CAIXA_CONFERENCIA) > 1
		BEGIN
			--EXCLUIR REGISTROS CASO EXISTA DUPLICIDADE ANTES DE CRIAR A PK
			select CODIGO_FILIAL, PERIODO_FECHAMENTO, TERMINAL, DATA_FECHAMENTO, COD_PGTO_ADM ,
			max(TIPO_PGTO) TIPO_PGTO,max(VALOR_FECHAMENTO) VALOR_FECHAMENTO,max(VALOR_CALCULADO) VALOR_CALCULADO,CASE WHEN (max(VALOR_CALCULADO) <> max(VALOR_fECHAMENTO)) THEN 1 ELSE 0 END AS DIVERGENCIA,
			MAX(DATA_PARA_TRANSFERENCIA) DATA_PARA_TRANSFERENCIA,MAX(CODIGO_ADMINISTRADORA) CODIGO_ADMINISTRADORA,MAX(GERENTE) GERENTE,max(VENDEDOR) VENDEDOR
			INTO #TEMP_LOJA_CAIXA_CONFERENCIA
			from loja_caixa_conferencia 
			GROUP BY CODIGO_FILIAL, PERIODO_FECHAMENTO, TERMINAL, DATA_FECHAMENTO, COD_PGTO_ADM ;

			DELETE FROM LOJA_CAIXA_CONFERENCIA;

			INSERT INTO LOJA_CAIXA_CONFERENCIA (CODIGO_FILIAL, PERIODO_FECHAMENTO, TERMINAL, DATA_FECHAMENTO, COD_PGTO_ADM, TIPO_PGTO,VALOR_FECHAMENTO,VALOR_CALCULADO,DIVERGENCIA,DATA_PARA_TRANSFERENCIA, CODIGO_ADMINISTRADORA,GERENTE,VENDEDOR )
			SELECT CODIGO_FILIAL, PERIODO_FECHAMENTO, TERMINAL, DATA_FECHAMENTO, COD_PGTO_ADM, TIPO_PGTO,VALOR_FECHAMENTO,VALOR_CALCULADO,DIVERGENCIA,DATA_PARA_TRANSFERENCIA, CODIGO_ADMINISTRADORA,GERENTE,VENDEDOR FROM #TEMP_LOJA_CAIXA_CONFERENCIA;

			DROP TABLE #TEMP_LOJA_CAIXA_CONFERENCIA;

		END


        ALTER TABLE [dbo].[LOJA_CAIXA_CONFERENCIA] ADD  CONSTRAINT XPK_LOJA_CAIXA_CONFERENCIA PRIMARY KEY CLUSTERED 
        (
	        [CODIGO_FILIAL] ASC,
	        [PERIODO_FECHAMENTO] ASC,
	        [TERMINAL] ASC,
	        [DATA_FECHAMENTO] ASC,
	        [COD_PGTO_ADM] ASC
        )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = ON, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
    END



--BASE DE DADOS DE LOJA
IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[LOJA_CAIXA_CONFERENCIA]') AND TYPE IN (N'U'))
	AND NOT EXISTS (SELECT * FROM SYS.tables WHERE NAME='CM_ESTOQUE_PA' AND TYPE='U')
BEGIN

	 CREATE TABLE [dbo].[LOJA_CAIXA_CONFERENCIA](
		       [CODIGO_FILIAL] [char](6) NOT NULL,
		       [TERMINAL] [char](3) NOT NULL,
		       [PERIODO_FECHAMENTO] [char](2) NOT NULL,
		       [TIPO_PGTO] [char](1) NOT NULL,
		       [DATA_FECHAMENTO] [smalldatetime] NOT NULL,
		       [COD_PGTO_ADM] [char](3) NOT NULL,
		       [VALOR_FECHAMENTO] [numeric](14, 2) NULL,
		       [VALOR_CALCULADO] [numeric](14, 2) NULL,
		       [DIVERGENCIA] [bit] NULL,
		       [DATA_PARA_TRANSFERENCIA] [smalldatetime] NULL,
		       [CODIGO_ADMINISTRADORA] [char](2) NULL,
		       [GERENTE] [char](4) NULL,
		       [VENDEDOR] [char](4) NULL,
	    CONSTRAINT [XPK_LOJA_CAIXA_CONFERENCIA] PRIMARY KEY CLUSTERED
	    (
		       [CODIGO_FILIAL] ASC,
		       [PERIODO_FECHAMENTO] ASC,
		       [TERMINAL] ASC,
		       [DATA_FECHAMENTO] ASC,
		       [COD_PGTO_ADM] ASC
	    )WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	    ) ON [PRIMARY]

 END