IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'LOJA_VENDA_TROCA_TICKET'
                      AND COLUMN_NAME = 'STATUS_TROCA')

  ALTER TABLE [dbo].[LOJA_VENDA_TROCA_TICKET]
    add STATUS_TROCA BIT NOT NULL default 0 