IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = 'USA_CFOP_5929_COMP_NFE')
	INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
	SELECT	'USA_CFOP_5929_COMP_NFE' AS PARAMETRO,
			getdate() PENULT_ATUALIZACAO,
			'AC;AL;AP;BA;DF;ES;GO;MS;MG;PA;PB;PR;PE;RS;SP;SE' AS VALOR_DEFAULT,
			getdate()  ULT_ATUALIZACAO,
			'AC;AL;AP;BA;DF;ES;GO;MS;MG;PA;PB;PR;PE;RS;SP;SE' AS VALOR_ATUAL,
			'Define os estados que permitem emitir uma NF-e utilizando o CFOP 5929 para referenciar uma NFC-e/SAT' AS DESC_PARAMETRO,
			'C' AS TIPO_DADO,
			'' AS RANGE_VALOR_ATUAL,
			0 AS GLOBAL, 
			'Os estados configurados permitem a emissão da nota utilizando o CFOP 5929' AS NOTA_PROGRAMADOR,
			0 AS ESCOPO,
			0 AS POR_USUARIO_OK,
			0 AS PERMITE_POR_EMPRESA,
			1 AS ENVIA_PARA_LOJA,
			1 AS PERMITE_POR_LOJA,
			0 AS PERMITE_POR_TERMINAL,
			0 AS PERMITE_ALTERAR_NA_LOJA,
			0 AS PERMITE_ALTERAR_NO_TERMINAL,
			0 AS ENVIA_PARA_REPRESENTANTE,
			0 AS PERMITE_POR_REPRESENTANTE,
			0 AS PERMITE_ALTERAR_NO_REPRESENTANTE

	

			


