IF EXISTS ( SELECT 1 FROM PARAMETROS WHERE PARAMETRO = 'DATA_INI_BLOCOX')
	BEGIN
		UPDATE PARAMETROS SET VALOR_ATUAL = '01/10/2020', ULT_ATUALIZACAO = '20201001', PERMITE_ALTERAR_NO_TERMINAL = 0, PERMITE_POR_TERMINAL = 0  
		WHERE PARAMETRO = 'DATA_INI_BLOCOX'
	END