CREATE FUNCTION lx_LimiteLinkPgtoParc (@LocalCodFilial varchar(06), @intPayments INTEGER)
RETURNS @PaymentsTable 
	TABLE ( PARCELA_MAXIMA int, PARCELA_2 numeric(14, 2) NULL, PARCELA_3 numeric(14, 2) NULL, PARCELA_4 numeric(14, 2) NULL, 
			PARCELA_5 numeric(14, 2) NULL, PARCELA_6 numeric(14, 2) NULL, PARCELA_7 numeric(14, 2) NULL, PARCELA_8 numeric(14, 2) NULL, 
		    PARCELA_9 numeric(14, 2) NULL, PARCELA_10 numeric(14, 2) NULL, PARCELA_11 numeric(14, 2) NULL, PARCELA_12 numeric(14, 2) NULL,
			PARCELA_13 numeric(14, 2) NULL, PARCELA_14 numeric(14, 2) NULL, PARCELA_15 numeric(14, 2) NULL ) 
AS
BEGIN

insert into @PaymentsTable ( PARCELA_MAXIMA, PARCELA_2, PARCELA_3, PARCELA_4, parcela_5, PARCELA_6, PARCELA_7, PARCELA_8, 
		PARCELA_9, PARCELA_10, PARCELA_11, PARCELA_12, PARCELA_13, PARCELA_14, PARCELA_15 )
select  distinct y.PARCELA_MAXIMA, 
		Case when y.PARCELA_MAXIMA >= 2 and y.PARCELA_2 = 0 then 0.01 else y.PARCELA_2 end, 
		Case when y.PARCELA_MAXIMA >= 3 and y.PARCELA_3 = 0 then 0.01 else y.PARCELA_3 end,
		Case when y.PARCELA_MAXIMA >= 4 and y.PARCELA_4 = 0 then 0.01 else y.PARCELA_4 end,
		Case when y.PARCELA_MAXIMA >= 5 and y.PARCELA_5 = 0 then 0.01 else y.PARCELA_5 end,
		Case when y.PARCELA_MAXIMA >= 6 and y.PARCELA_6 = 0 then 0.01 else y.PARCELA_6 end,
		Case when y.PARCELA_MAXIMA >= 7 and y.PARCELA_7 = 0 then 0.01 else y.PARCELA_7 end,
		Case when y.PARCELA_MAXIMA >= 8 and y.PARCELA_8 = 0 then 0.01 else y.PARCELA_8 end, 
		Case when y.PARCELA_MAXIMA >= 9 and y.PARCELA_9 = 0 then 0.01 else y.PARCELA_9 end, 
		Case when y.PARCELA_MAXIMA >= 10 and y.PARCELA_10 = 0 then 0.01 else y.PARCELA_10 end,
		Case when y.PARCELA_MAXIMA >= 11 and y.PARCELA_11 = 0 then 0.01 else y.PARCELA_11 end,
		Case when y.PARCELA_MAXIMA >= 12 and y.PARCELA_12 = 0 then 0.01 else y.PARCELA_12 end,
		Case when y.PARCELA_MAXIMA >= 13 and y.PARCELA_13 = 0 then 0.01 else y.PARCELA_13 end,
		Case when y.PARCELA_MAXIMA >= 14 and y.PARCELA_14 = 0 then 0.01 else y.PARCELA_14 end,
		Case when y.PARCELA_MAXIMA >= 15 and y.PARCELA_15 = 0 then 0.01 else y.PARCELA_15 end
 from (

		SELECT X.CODIGO_ADMINISTRADORA,
			CASE WHEN SUM(X.PARCELA_15) > 0 THEN 15
				 WHEN SUM(X.PARCELA_14) > 0 THEN 14
				 WHEN SUM(X.PARCELA_13) > 0 THEN 13
				 WHEN SUM(X.PARCELA_12) > 0 THEN 12
				 WHEN SUM(X.PARCELA_11) > 0 THEN 11
				 WHEN SUM(X.PARCELA_10) > 0 THEN 10
				 WHEN SUM(X.PARCELA_9) > 0 THEN 9
				 WHEN SUM(X.PARCELA_8) > 0 THEN 8
				 WHEN SUM(X.PARCELA_7) > 0 THEN 7
				 WHEN SUM(X.PARCELA_6) > 0 THEN 6
				 WHEN SUM(X.PARCELA_5) > 0 THEN 5
				 WHEN SUM(X.PARCELA_4) > 0 THEN 4
				 WHEN SUM(X.PARCELA_3) > 0 THEN 3
				 WHEN SUM(X.PARCELA_2) > 0 THEN 2
			ELSE 1 END PARCELA_MAXIMA, 
			SUM(X.PARCELA_2) AS PARCELA_2,
			SUM(X.PARCELA_3) AS PARCELA_3,
			SUM(X.PARCELA_4) AS PARCELA_4,
			SUM(X.PARCELA_5) AS PARCELA_5,
			SUM(X.PARCELA_6) AS PARCELA_6,
			SUM(X.PARCELA_7) AS PARCELA_7,
			SUM(X.PARCELA_8) AS PARCELA_8,
			SUM(X.PARCELA_9) AS PARCELA_9,
			SUM(X.PARCELA_10) AS PARCELA_10,
			SUM(X.PARCELA_11) AS PARCELA_11,
			SUM(X.PARCELA_12) AS PARCELA_12,
			SUM(X.PARCELA_13) AS PARCELA_13,
			SUM(X.PARCELA_14) AS PARCELA_14,
			SUM(X.PARCELA_15) AS PARCELA_15
	FROM (
	SELECT  A.CODIGO_ADMINISTRADORA,
			CASE WHEN a.MAXIMO_PARCELAS = 2 THEN MIN(A.VALOR_MINIMO) ELSE 0 END PARCELA_2,
			CASE WHEN a.MAXIMO_PARCELAS = 3 THEN MIN(A.VALOR_MINIMO) ELSE 0 END PARCELA_3, 
			CASE WHEN a.MAXIMO_PARCELAS = 4 THEN MIN(A.VALOR_MINIMO) ELSE 0 END PARCELA_4, 
			CASE WHEN a.MAXIMO_PARCELAS = 5 THEN MIN(A.VALOR_MINIMO) ELSE 0 END PARCELA_5,
			CASE WHEN a.MAXIMO_PARCELAS = 6 THEN MIN(A.VALOR_MINIMO) ELSE 0 END PARCELA_6,
			CASE WHEN a.MAXIMO_PARCELAS = 7 THEN MIN(A.VALOR_MINIMO) ELSE 0 END PARCELA_7,
			CASE WHEN a.MAXIMO_PARCELAS = 8 THEN MIN(A.VALOR_MINIMO) ELSE 0 END PARCELA_8, 
			CASE WHEN a.MAXIMO_PARCELAS = 9 THEN MIN(A.VALOR_MINIMO) ELSE 0 END PARCELA_9, 
			CASE WHEN a.MAXIMO_PARCELAS = 10 THEN MIN(A.VALOR_MINIMO) ELSE 0 END PARCELA_10,
			CASE WHEN a.MAXIMO_PARCELAS = 11 THEN MIN(A.VALOR_MINIMO) ELSE 0 END PARCELA_11,
			CASE WHEN a.MAXIMO_PARCELAS = 12 THEN MIN(A.VALOR_MINIMO) ELSE 0 END PARCELA_12,
			CASE WHEN a.MAXIMO_PARCELAS = 13 THEN MIN(A.VALOR_MINIMO) ELSE 0 END PARCELA_13,
			CASE WHEN a.MAXIMO_PARCELAS = 14 THEN MIN(A.VALOR_MINIMO) ELSE 0 END PARCELA_14,
			CASE WHEN a.MAXIMO_PARCELAS = 15 THEN MIN(A.VALOR_MINIMO) ELSE 0 END PARCELA_15
	FROM
			LJ_LIMITE_PARCELAMENTO A
			LEFT JOIN FILIAIS B ON A.COD_FILIAL = B.COD_FILIAL
			LEFT JOIN LOJAS_VAREJO e ON B.FILIAL = e.FILIAL
		WHERE
			A.COD_FILIAL = @LocalCodFilial
			AND A.TIPO_PGTO = 'A' 
			and a.MAXIMO_PARCELAS <= @intPayments
			and a.inativo = 0
		GROUP BY A.CODIGO_ADMINISTRADORA, A.MAXIMO_PARCELAS
	) AS X
	GROUP BY X.CODIGO_ADMINISTRADORA
) y order by y.PARCELA_MAXIMA asc

RETURN
end
