
IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'LOJA_PEDIDO_ENTREGA'
                      AND COLUMN_NAME = 'ID_PEDIDO_ORIGEM')
  ALTER TABLE [dbo].[LOJA_PEDIDO_ENTREGA]
    ADD ID_PEDIDO_ORIGEM VARCHAR(20) NULL 


IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'LOJA_PEDIDO_ENTREGA'
                      AND COLUMN_NAME = 'FRETE')
  ALTER TABLE [dbo].[LOJA_PEDIDO_ENTREGA]
    ADD FRETE NUMERIC(14,2) NULL 




IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'LOJA_VENDEDORES'
                      AND COLUMN_NAME = 'LOGIN_GUID')
  ALTER TABLE [dbo].[LOJA_VENDEDORES]
    ADD LOGIN_GUID VARCHAR(255) NULL 


IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'LOJA_PEDIDO_PGTO'
                      AND COLUMN_NAME = 'DESCONTO_PGTO')
  ALTER TABLE [dbo].[LOJA_PEDIDO_PGTO]
    ADD DESCONTO_PGTO NUMERIC(14,2) NULL


IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'LOJA_PEDIDO'
                      AND COLUMN_NAME = 'NSU_FIDELIDADE')
  ALTER TABLE [dbo].[LOJA_PEDIDO]
    ADD NSU_FIDELIDADE VARCHAR(15) NULL


IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'LOJA_PEDIDO_PRODUTO'
                      AND COLUMN_NAME = 'QTD_TICKET_PRESENTE')
  ALTER TABLE [dbo].[LOJA_PEDIDO_PRODUTO]
    ADD QTD_TICKET_PRESENTE INT 
 

 
IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'LOJA_PEDIDO_PRODUTO'
                      AND COLUMN_NAME = 'COMPROVANTE')
  ALTER TABLE [dbo].[LOJA_PEDIDO_PRODUTO]
    ADD COMPROVANTE VARCHAR(MAX) 
 


IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'LOJA_PEDIDO'
                      AND COLUMN_NAME = 'CHANNEL_ID')
  ALTER TABLE [dbo].[LOJA_PEDIDO] ADD CHANNEL_ID VARCHAR(100)
 


IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'LOJA_GIFT_TRANSACAO'
                      AND COLUMN_NAME = 'PEDIDO')
  ALTER TABLE [dbo].[LOJA_GIFT_TRANSACAO]
    ADD PEDIDO INT
 


IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'LOJA_PEDIDO'
                      AND COLUMN_NAME = 'DADOS_ADICIONAIS')
  ALTER TABLE [dbo].[LOJA_PEDIDO]
    ADD DADOS_ADICIONAIS  VARCHAR(1024)
 



IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'LOJA_PEDIDO_PGTO'
                      AND COLUMN_NAME = 'FINALIZACAO')
  ALTER TABLE [dbo].[LOJA_PEDIDO_PGTO]
    ADD FINALIZACAO  VARCHAR(20)
 


IF NOT EXISTS(SELECT TOP 1 1 FROM LOJA_MOTIVOS_CANCELAMENTOS WHERE MOTIVO_CANCELAMENTO = '999')
BEGIN	

	INSERT INTO LOJA_MOTIVOS_CANCELAMENTOS (MOTIVO_CANCELAMENTO, DESC_MOTIVO)
	VALUES (999, 'ERRO LINX MOBILE')

	PRINT 'Criado Motivo de cancelamento Automático Mobile'
END


IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'LOJA_PEDIDO'
                      AND COLUMN_NAME = 'INDICA_LINXPAY')

	ALTER TABLE LOJA_PEDIDO ADD INDICA_LINXPAY BIT NOT NULL DEFAULT 0 


IF NOT EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_PROCESSOS_SP' AND COLUMN_NAME = 'HOTFIX')
BEGIN
       ALTER TABLE LOJA_PROCESSOS_SP ADD HOTFIX TINYINT  NULL
       
END


IF EXISTS (SELECT TOP 1 1 FROM INFORMATION_SCHEMA.COLUMNS A WHERE TABLE_NAME = 'LOJA_PROCESSOS_SP' AND COLUMN_NAME = 'VERSAO')
BEGIN
	ALTER TABLE LOJA_PROCESSOS_SP ALTER COLUMN VERSAO SMALLINT 
END
