IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_VENDA_ENTREGA') BEGIN

	CREATE TABLE LOJA_VENDA_ENTREGA
	(
	   CODIGO_FILIAL		         CHAR(6)		NOT NULL,
	   TICKET                        CHAR(8)		NOT NULL,
	   DATA_VENDA					 DATETIME		NOT NULL,
	   TERMINAL						 CHAR(03)		NOT NULL,
	   DELIVERY_INDPRES				 INT			NOT NULL,
	   TRANSPORTADORA				 VARCHAR(25)	NOT NULL,
	   VALOR_FRETE					 NUMERIC(18,2)	NULL,
	   ITEM_ENDERECO			     CHAR(18)		NULL,
	   CONSTRAINT PK_LOJA_PEDIDO_DELIVERY PRIMARY KEY (CODIGO_FILIAL, TICKET, DATA_VENDA)
	)
END