
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LJ_LISTA_PRESENTE') BEGIN

CREATE TABLE LJ_LISTA_PRESENTE(
 		CODIGO_FILIAL char(6) NOT NULL, 
		TICKET char(9) NOT NULL, 
		DATA_VENDA datetime NOT NULL, 
		COD_LISTA int,
		COD_ORDER varchar(30),
		QTDE_ITENS int, 
		TOTAL_ITENS numeric(14,2),
		TOTAL_LISTA	numeric(14,2), 
		TOTAL_FRETE numeric(14,2), 
		DESCONTO numeric(14,2),
		ID_FRETE int,
		TRANSPORTADORA varchar(100),
		PRAZO_ENTREGA int,
		MENSAGEM varchar(500),
		EMAIL varchar(30),
		TELEFONE varchar(20),
		ORDER_ID varchar(50),
        ORDER_NUMBER varchar(50),
		DATA_PARA_TRANSFERENCIA datetime
	  CONSTRAINT [XPKLJ_LISTA_PRESENTE] PRIMARY KEY CLUSTERED 
(
	[CODIGO_FILIAL] ASC,
	[TICKET] ASC,
	[DATA_VENDA] ASC	
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] 
End


IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LJ_LISTA_PRESENTE' and COLUMN_NAME = 'DESCONTO')
begin
	alter table LJ_LISTA_PRESENTE add  DESCONTO numeric(14,2)
End