
IF NOT EXISTS 
(
   SELECT
      1 
   FROM
      INFORMATION_SCHEMA.COLUMNS 
   WHERE
      TABLE_NAME = 'LOJA_PEDIDO_PRODUTO' 
      AND COLUMN_NAME = 'TIPO_BONIFICACAO'
)
BEGIN
   ALTER TABLE [dbo].[LOJA_PEDIDO_PRODUTO] ADD TIPO_BONIFICACAO INT 
END