-- POSSP-5446 - Gilvano Santos - (14/05/2021) - CAPTURA DO VALOR DE ENTRADA DA TRANSFERENCIA/DEVOLUÇÃO
IF NOT EXISTS(SELECT PARAMETRO FROM PARAMETROS WHERE PARAMETRO = 'PRECO_ROMANEIO_ENTRADA')
BEGIN
	Insert into parametros (PARAMETRO,PENULT_ATUALIZACAO,VALOR_DEFAULT, ULT_ATUALIZACAO ,VALOR_ATUAL, DESC_PARAMETRO,  
	TIPO_DADO,RANGE_VALOR_ATUAL, GLOBAL,NOTA_PROGRAMADOR,ESCOPO,POR_USUARIO_OK,	PERMITE_POR_EMPRESA,ENVIA_PARA_LOJA, PERMITE_POR_LOJA,
	PERMITE_POR_TERMINAL,PERMITE_ALTERAR_NA_LOJA,PERMITE_ALTERAR_NO_TERMINAL,
	ENVIA_PARA_REPRESENTANTE,PERMITE_POR_REPRESENTANTE,PERMITE_ALTERAR_NO_REPRESENTANTE,DATA_PARA_TRANSFERENCIA) 
	values('PRECO_ROMANEIO_ENTRADA',GETDATE(),'.F.', GETDATE(),'.F.','Habilita captura do preço no romaneio de entrada',	
		'L','',0,'Este parametro permite capturar o preço no romaneio de entrada para saidas associadas ao documento fiscal emitido na entrada da mercadoria.',
		0,0,1,1,1,0,1,0	,0,0,0,GETDATE())
END