--PRODSHOP-6938 - Eder Silva - 23/06/2021 - Criação dos parâmetros do Reshop (Único)

IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = 'UNICOLOYALTY_HABILITA')
	INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
	SELECT	'UNICOLOYALTY_HABILITA' AS PARAMETRO, CAST(0 AS DATETIME) PENULT_ATUALIZACAO, '' AS VALOR_DEFAULT, GETDATE() AS ULT_ATUALIZACAO, 
			'.F.' AS VALOR_ATUAL, '' AS DESC_PARAMETRO, 'L' AS TIPO_DADO, '' AS RANGE_VALOR_ATUAL, 1 AS GLOBAL, '' AS NOTA_PROGRAMADOR,
			0 AS ESCOPO, 0 AS POR_USUARIO_OK, 0 AS PERMITE_POR_EMPRESA,	1 AS ENVIA_PARA_LOJA,	1 AS PERMITE_POR_LOJA,	1 AS PERMITE_POR_TERMINAL,
			1 AS PERMITE_ALTERAR_NA_LOJA, 1 AS PERMITE_ALTERAR_NO_TERMINAL,	0 AS ENVIA_PARA_REPRESENTANTE,	0 AS PERMITE_POR_REPRESENTANTE, 0 AS PERMITE_ALTERAR_NO_REPRESENTANTE

IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = 'UNICOLOYALTY_URL')
	INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
	SELECT	'UNICOLOYALTY_URL' AS PARAMETRO, CAST(0 AS DATETIME) PENULT_ATUALIZACAO, '' AS VALOR_DEFAULT, GETDATE() AS ULT_ATUALIZACAO, 
			'https://www.unicosistemas.com.br' AS VALOR_ATUAL, '' AS DESC_PARAMETRO, 'C' AS TIPO_DADO, '' AS RANGE_VALOR_ATUAL, 1 AS GLOBAL, '' AS NOTA_PROGRAMADOR,
			0 AS ESCOPO, 0 AS POR_USUARIO_OK, 0 AS PERMITE_POR_EMPRESA,	1 AS ENVIA_PARA_LOJA,	1 AS PERMITE_POR_LOJA,	1 AS PERMITE_POR_TERMINAL,
			1 AS PERMITE_ALTERAR_NA_LOJA, 1 AS PERMITE_ALTERAR_NO_TERMINAL,	0 AS ENVIA_PARA_REPRESENTANTE,	0 AS PERMITE_POR_REPRESENTANTE, 0 AS PERMITE_ALTERAR_NO_REPRESENTANTE

IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = 'UNICOLOYALTY_USERNAME')
	INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
	SELECT	'UNICOLOYALTY_USERNAME' AS PARAMETRO, CAST(0 AS DATETIME) PENULT_ATUALIZACAO, '' AS VALOR_DEFAULT, GETDATE() AS ULT_ATUALIZACAO, 
			'' AS VALOR_ATUAL, '' AS DESC_PARAMETRO, 'C' AS TIPO_DADO, '' AS RANGE_VALOR_ATUAL, 1 AS GLOBAL, '' AS NOTA_PROGRAMADOR,
			0 AS ESCOPO, 0 AS POR_USUARIO_OK, 0 AS PERMITE_POR_EMPRESA,	1 AS ENVIA_PARA_LOJA,	1 AS PERMITE_POR_LOJA,	1 AS PERMITE_POR_TERMINAL,
			1 AS PERMITE_ALTERAR_NA_LOJA, 1 AS PERMITE_ALTERAR_NO_TERMINAL,	0 AS ENVIA_PARA_REPRESENTANTE,	0 AS PERMITE_POR_REPRESENTANTE, 0 AS PERMITE_ALTERAR_NO_REPRESENTANTE

IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = 'UNICOLOYALTY_PASSWORD')
	INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
	SELECT	'UNICOLOYALTY_PASSWORD' AS PARAMETRO, CAST(0 AS DATETIME) PENULT_ATUALIZACAO, '' AS VALOR_DEFAULT, GETDATE() AS ULT_ATUALIZACAO, 
			'' AS VALOR_ATUAL, '' AS DESC_PARAMETRO, 'C' AS TIPO_DADO, '' AS RANGE_VALOR_ATUAL, 1 AS GLOBAL, '' AS NOTA_PROGRAMADOR,
			0 AS ESCOPO, 0 AS POR_USUARIO_OK, 0 AS PERMITE_POR_EMPRESA,	1 AS ENVIA_PARA_LOJA,	1 AS PERMITE_POR_LOJA,	1 AS PERMITE_POR_TERMINAL,
			1 AS PERMITE_ALTERAR_NA_LOJA, 1 AS PERMITE_ALTERAR_NO_TERMINAL,	0 AS ENVIA_PARA_REPRESENTANTE,	0 AS PERMITE_POR_REPRESENTANTE, 0 AS PERMITE_ALTERAR_NO_REPRESENTANTE

IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = 'UNICOLOYALTY_CAMPANHA')
	INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
	SELECT	'UNICOLOYALTY_CAMPANHA' AS PARAMETRO, CAST(0 AS DATETIME) PENULT_ATUALIZACAO, '' AS VALOR_DEFAULT, GETDATE() AS ULT_ATUALIZACAO, 
			'.F.' AS VALOR_ATUAL, '' AS DESC_PARAMETRO, 'L' AS TIPO_DADO, '' AS RANGE_VALOR_ATUAL, 1 AS GLOBAL, '' AS NOTA_PROGRAMADOR,
			0 AS ESCOPO, 0 AS POR_USUARIO_OK, 0 AS PERMITE_POR_EMPRESA,	1 AS ENVIA_PARA_LOJA,	1 AS PERMITE_POR_LOJA,	1 AS PERMITE_POR_TERMINAL,
			1 AS PERMITE_ALTERAR_NA_LOJA, 1 AS PERMITE_ALTERAR_NO_TERMINAL,	0 AS ENVIA_PARA_REPRESENTANTE,	0 AS PERMITE_POR_REPRESENTANTE, 0 AS PERMITE_ALTERAR_NO_REPRESENTANTE

IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = 'UNICOLOYALTY_PINPAD')
	INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
	SELECT	'UNICOLOYALTY_PINPAD' AS PARAMETRO, CAST(0 AS DATETIME) PENULT_ATUALIZACAO, '' AS VALOR_DEFAULT, GETDATE() AS ULT_ATUALIZACAO, 
			'.F.' AS VALOR_ATUAL, '' AS DESC_PARAMETRO, 'L' AS TIPO_DADO, '' AS RANGE_VALOR_ATUAL, 1 AS GLOBAL, '' AS NOTA_PROGRAMADOR,
			0 AS ESCOPO, 0 AS POR_USUARIO_OK, 0 AS PERMITE_POR_EMPRESA,	1 AS ENVIA_PARA_LOJA,	1 AS PERMITE_POR_LOJA,	1 AS PERMITE_POR_TERMINAL,
			1 AS PERMITE_ALTERAR_NA_LOJA, 1 AS PERMITE_ALTERAR_NO_TERMINAL,	0 AS ENVIA_PARA_REPRESENTANTE,	0 AS PERMITE_POR_REPRESENTANTE, 0 AS PERMITE_ALTERAR_NO_REPRESENTANTE

IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = 'UNICOLOYALTY_OPEXCLUIDA')
	INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
	SELECT	'UNICOLOYALTY_OPEXCLUIDA' AS PARAMETRO, CAST(0 AS DATETIME) PENULT_ATUALIZACAO, '' AS VALOR_DEFAULT, GETDATE() AS ULT_ATUALIZACAO, 
			'' AS VALOR_ATUAL, '' AS DESC_PARAMETRO, 'C' AS TIPO_DADO, '' AS RANGE_VALOR_ATUAL, 1 AS GLOBAL, '' AS NOTA_PROGRAMADOR,
			0 AS ESCOPO, 0 AS POR_USUARIO_OK, 0 AS PERMITE_POR_EMPRESA,	1 AS ENVIA_PARA_LOJA,	1 AS PERMITE_POR_LOJA,	1 AS PERMITE_POR_TERMINAL,
			1 AS PERMITE_ALTERAR_NA_LOJA, 1 AS PERMITE_ALTERAR_NO_TERMINAL,	0 AS ENVIA_PARA_REPRESENTANTE,	0 AS PERMITE_POR_REPRESENTANTE, 0 AS PERMITE_ALTERAR_NO_REPRESENTANTE

IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = 'UNICOLOYALTY_EXC_TROCA')
	INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
	SELECT	'UNICOLOYALTY_EXC_TROCA' AS PARAMETRO, CAST(0 AS DATETIME) PENULT_ATUALIZACAO, '' AS VALOR_DEFAULT, GETDATE() AS ULT_ATUALIZACAO, 
			'.F.' AS VALOR_ATUAL, '' AS DESC_PARAMETRO, 'L' AS TIPO_DADO, '' AS RANGE_VALOR_ATUAL, 1 AS GLOBAL, '' AS NOTA_PROGRAMADOR,
			0 AS ESCOPO, 0 AS POR_USUARIO_OK, 0 AS PERMITE_POR_EMPRESA,	1 AS ENVIA_PARA_LOJA,	1 AS PERMITE_POR_LOJA,	1 AS PERMITE_POR_TERMINAL,
			1 AS PERMITE_ALTERAR_NA_LOJA, 1 AS PERMITE_ALTERAR_NO_TERMINAL,	0 AS ENVIA_PARA_REPRESENTANTE,	0 AS PERMITE_POR_REPRESENTANTE, 0 AS PERMITE_ALTERAR_NO_REPRESENTANTE

IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = 'UNICO_SERVICO_PRESENTE')
	INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
	SELECT	'UNICO_SERVICO_PRESENTE' AS PARAMETRO, CAST(0 AS DATETIME) PENULT_ATUALIZACAO, '' AS VALOR_DEFAULT, GETDATE() AS ULT_ATUALIZACAO, 
			'.F.' AS VALOR_ATUAL, '' AS DESC_PARAMETRO, 'L' AS TIPO_DADO, '' AS RANGE_VALOR_ATUAL, 1 AS GLOBAL, '' AS NOTA_PROGRAMADOR,
			0 AS ESCOPO, 0 AS POR_USUARIO_OK, 0 AS PERMITE_POR_EMPRESA,	1 AS ENVIA_PARA_LOJA,	1 AS PERMITE_POR_LOJA,	1 AS PERMITE_POR_TERMINAL,
			1 AS PERMITE_ALTERAR_NA_LOJA, 1 AS PERMITE_ALTERAR_NO_TERMINAL,	0 AS ENVIA_PARA_REPRESENTANTE,	0 AS PERMITE_POR_REPRESENTANTE, 0 AS PERMITE_ALTERAR_NO_REPRESENTANTE

IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = 'UNICO_SERVICO_CONSERTO')
	INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
	SELECT	'UNICO_SERVICO_CONSERTO' AS PARAMETRO, CAST(0 AS DATETIME) PENULT_ATUALIZACAO, '' AS VALOR_DEFAULT, GETDATE() AS ULT_ATUALIZACAO, 
			'.F.' AS VALOR_ATUAL, '' AS DESC_PARAMETRO, 'L' AS TIPO_DADO, '' AS RANGE_VALOR_ATUAL, 1 AS GLOBAL, '' AS NOTA_PROGRAMADOR,
			0 AS ESCOPO, 0 AS POR_USUARIO_OK, 0 AS PERMITE_POR_EMPRESA,	1 AS ENVIA_PARA_LOJA,	1 AS PERMITE_POR_LOJA,	1 AS PERMITE_POR_TERMINAL,
			1 AS PERMITE_ALTERAR_NA_LOJA, 1 AS PERMITE_ALTERAR_NO_TERMINAL,	0 AS ENVIA_PARA_REPRESENTANTE,	0 AS PERMITE_POR_REPRESENTANTE, 0 AS PERMITE_ALTERAR_NO_REPRESENTANTE


IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = 'UNICO_RECARGA_CELULAR')
	INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
	SELECT	'UNICO_RECARGA_CELULAR' AS PARAMETRO, CAST(0 AS DATETIME) PENULT_ATUALIZACAO, '' AS VALOR_DEFAULT, GETDATE() AS ULT_ATUALIZACAO, 
			'.F.' AS VALOR_ATUAL, '' AS DESC_PARAMETRO, 'L' AS TIPO_DADO, '' AS RANGE_VALOR_ATUAL, 1 AS GLOBAL, '' AS NOTA_PROGRAMADOR,
			0 AS ESCOPO, 0 AS POR_USUARIO_OK, 0 AS PERMITE_POR_EMPRESA,	1 AS ENVIA_PARA_LOJA,	1 AS PERMITE_POR_LOJA,	1 AS PERMITE_POR_TERMINAL,
			1 AS PERMITE_ALTERAR_NA_LOJA, 1 AS PERMITE_ALTERAR_NO_TERMINAL,	0 AS ENVIA_PARA_REPRESENTANTE,	0 AS PERMITE_POR_REPRESENTANTE, 0 AS PERMITE_ALTERAR_NO_REPRESENTANTE

IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = 'UNICO_VITRINE')
	INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
	SELECT	'UNICO_VITRINE' AS PARAMETRO, CAST(0 AS DATETIME) PENULT_ATUALIZACAO, '' AS VALOR_DEFAULT, GETDATE() AS ULT_ATUALIZACAO, 
			'.F.' AS VALOR_ATUAL, '' AS DESC_PARAMETRO, 'L' AS TIPO_DADO, '' AS RANGE_VALOR_ATUAL, 1 AS GLOBAL, '' AS NOTA_PROGRAMADOR,
			0 AS ESCOPO, 0 AS POR_USUARIO_OK, 0 AS PERMITE_POR_EMPRESA,	1 AS ENVIA_PARA_LOJA,	1 AS PERMITE_POR_LOJA,	1 AS PERMITE_POR_TERMINAL,
			1 AS PERMITE_ALTERAR_NA_LOJA, 1 AS PERMITE_ALTERAR_NO_TERMINAL,	0 AS ENVIA_PARA_REPRESENTANTE,	0 AS PERMITE_POR_REPRESENTANTE, 0 AS PERMITE_ALTERAR_NO_REPRESENTANTE

IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = 'UNICO_VCMAIS')
	INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
	SELECT	'UNICO_VCMAIS' AS PARAMETRO, CAST(0 AS DATETIME) PENULT_ATUALIZACAO, '' AS VALOR_DEFAULT, GETDATE() AS ULT_ATUALIZACAO, 
			'.F.' AS VALOR_ATUAL, '' AS DESC_PARAMETRO, 'L' AS TIPO_DADO, '' AS RANGE_VALOR_ATUAL, 1 AS GLOBAL, '' AS NOTA_PROGRAMADOR,
			0 AS ESCOPO, 0 AS POR_USUARIO_OK, 0 AS PERMITE_POR_EMPRESA,	1 AS ENVIA_PARA_LOJA,	1 AS PERMITE_POR_LOJA,	1 AS PERMITE_POR_TERMINAL,
			1 AS PERMITE_ALTERAR_NA_LOJA, 1 AS PERMITE_ALTERAR_NO_TERMINAL,	0 AS ENVIA_PARA_REPRESENTANTE,	0 AS PERMITE_POR_REPRESENTANTE, 0 AS PERMITE_ALTERAR_NO_REPRESENTANTE

IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = 'UNICO_VOUCHER_TROCA')
	INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
	SELECT	'UNICO_VOUCHER_TROCA' AS PARAMETRO, CAST(0 AS DATETIME) PENULT_ATUALIZACAO, '' AS VALOR_DEFAULT, GETDATE() AS ULT_ATUALIZACAO, 
			'.F.' AS VALOR_ATUAL, '' AS DESC_PARAMETRO, 'L' AS TIPO_DADO, '' AS RANGE_VALOR_ATUAL, 1 AS GLOBAL, '' AS NOTA_PROGRAMADOR,
			0 AS ESCOPO, 0 AS POR_USUARIO_OK, 0 AS PERMITE_POR_EMPRESA,	1 AS ENVIA_PARA_LOJA,	1 AS PERMITE_POR_LOJA,	1 AS PERMITE_POR_TERMINAL,
			1 AS PERMITE_ALTERAR_NA_LOJA, 1 AS PERMITE_ALTERAR_NO_TERMINAL,	0 AS ENVIA_PARA_REPRESENTANTE,	0 AS PERMITE_POR_REPRESENTANTE, 0 AS PERMITE_ALTERAR_NO_REPRESENTANTE

IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = 'UNICO_OMNI_LOJAS')
	INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
	SELECT	'UNICO_OMNI_LOJAS' AS PARAMETRO, CAST(0 AS DATETIME) PENULT_ATUALIZACAO, '' AS VALOR_DEFAULT, GETDATE() AS ULT_ATUALIZACAO, 
			'.F.' AS VALOR_ATUAL, '' AS DESC_PARAMETRO, 'L' AS TIPO_DADO, '' AS RANGE_VALOR_ATUAL, 1 AS GLOBAL, '' AS NOTA_PROGRAMADOR,
			0 AS ESCOPO, 0 AS POR_USUARIO_OK, 0 AS PERMITE_POR_EMPRESA,	1 AS ENVIA_PARA_LOJA,	1 AS PERMITE_POR_LOJA,	1 AS PERMITE_POR_TERMINAL,
			1 AS PERMITE_ALTERAR_NA_LOJA, 1 AS PERMITE_ALTERAR_NO_TERMINAL,	0 AS ENVIA_PARA_REPRESENTANTE,	0 AS PERMITE_POR_REPRESENTANTE, 0 AS PERMITE_ALTERAR_NO_REPRESENTANTE

IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = 'OMNI_TAB_PRECO')
	INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
	SELECT	'OMNI_TAB_PRECO' AS PARAMETRO, CAST(0 AS DATETIME) PENULT_ATUALIZACAO, '' AS VALOR_DEFAULT, GETDATE() AS ULT_ATUALIZACAO, 
			'' AS VALOR_ATUAL, '' AS DESC_PARAMETRO, 'C' AS TIPO_DADO, '' AS RANGE_VALOR_ATUAL, 1 AS GLOBAL, '' AS NOTA_PROGRAMADOR,
			0 AS ESCOPO, 0 AS POR_USUARIO_OK, 0 AS PERMITE_POR_EMPRESA,	1 AS ENVIA_PARA_LOJA,	1 AS PERMITE_POR_LOJA,	1 AS PERMITE_POR_TERMINAL,
			1 AS PERMITE_ALTERAR_NA_LOJA, 1 AS PERMITE_ALTERAR_NO_TERMINAL,	0 AS ENVIA_PARA_REPRESENTANTE,	0 AS PERMITE_POR_REPRESENTANTE, 0 AS PERMITE_ALTERAR_NO_REPRESENTANTE

IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = 'OMNI_SAIDA_TR')
	INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
	SELECT	'OMNI_SAIDA_TR' AS PARAMETRO, CAST(0 AS DATETIME) PENULT_ATUALIZACAO, '' AS VALOR_DEFAULT, GETDATE() AS ULT_ATUALIZACAO, 
			'' AS VALOR_ATUAL, '' AS DESC_PARAMETRO, 'C' AS TIPO_DADO, '' AS RANGE_VALOR_ATUAL, 1 AS GLOBAL, '' AS NOTA_PROGRAMADOR,
			0 AS ESCOPO, 0 AS POR_USUARIO_OK, 0 AS PERMITE_POR_EMPRESA,	1 AS ENVIA_PARA_LOJA,	1 AS PERMITE_POR_LOJA,	1 AS PERMITE_POR_TERMINAL,
			1 AS PERMITE_ALTERAR_NA_LOJA, 1 AS PERMITE_ALTERAR_NO_TERMINAL,	0 AS ENVIA_PARA_REPRESENTANTE,	0 AS PERMITE_POR_REPRESENTANTE, 0 AS PERMITE_ALTERAR_NO_REPRESENTANTE

IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = 'OMNI_SERIE_TR')
	INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
	SELECT	'OMNI_SERIE_TR' AS PARAMETRO, CAST(0 AS DATETIME) PENULT_ATUALIZACAO, '' AS VALOR_DEFAULT, GETDATE() AS ULT_ATUALIZACAO, 
			'' AS VALOR_ATUAL, '' AS DESC_PARAMETRO, 'C' AS TIPO_DADO, '' AS RANGE_VALOR_ATUAL, 1 AS GLOBAL, '' AS NOTA_PROGRAMADOR,
			0 AS ESCOPO, 0 AS POR_USUARIO_OK, 0 AS PERMITE_POR_EMPRESA,	1 AS ENVIA_PARA_LOJA,	1 AS PERMITE_POR_LOJA,	1 AS PERMITE_POR_TERMINAL,
			1 AS PERMITE_ALTERAR_NA_LOJA, 1 AS PERMITE_ALTERAR_NO_TERMINAL,	0 AS ENVIA_PARA_REPRESENTANTE,	0 AS PERMITE_POR_REPRESENTANTE, 0 AS PERMITE_ALTERAR_NO_REPRESENTANTE

IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = 'OMNI_NAT_TR')
	INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
	SELECT	'OMNI_NAT_TR' AS PARAMETRO, CAST(0 AS DATETIME) PENULT_ATUALIZACAO, '' AS VALOR_DEFAULT, GETDATE() AS ULT_ATUALIZACAO, 
			'' AS VALOR_ATUAL, '' AS DESC_PARAMETRO, 'C' AS TIPO_DADO, '' AS RANGE_VALOR_ATUAL, 1 AS GLOBAL, '' AS NOTA_PROGRAMADOR,
			0 AS ESCOPO, 0 AS POR_USUARIO_OK, 0 AS PERMITE_POR_EMPRESA,	1 AS ENVIA_PARA_LOJA,	1 AS PERMITE_POR_LOJA,	1 AS PERMITE_POR_TERMINAL,
			1 AS PERMITE_ALTERAR_NA_LOJA, 1 AS PERMITE_ALTERAR_NO_TERMINAL,	0 AS ENVIA_PARA_REPRESENTANTE,	0 AS PERMITE_POR_REPRESENTANTE, 0 AS PERMITE_ALTERAR_NO_REPRESENTANTE

IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = 'OMNI_ENT_TR')
	INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
	SELECT	'OMNI_ENT_TR' AS PARAMETRO, CAST(0 AS DATETIME) PENULT_ATUALIZACAO, '' AS VALOR_DEFAULT, GETDATE() AS ULT_ATUALIZACAO, 
			'' AS VALOR_ATUAL, '' AS DESC_PARAMETRO, 'C' AS TIPO_DADO, '' AS RANGE_VALOR_ATUAL, 1 AS GLOBAL, '' AS NOTA_PROGRAMADOR,
			0 AS ESCOPO, 0 AS POR_USUARIO_OK, 0 AS PERMITE_POR_EMPRESA,	1 AS ENVIA_PARA_LOJA,	1 AS PERMITE_POR_LOJA,	1 AS PERMITE_POR_TERMINAL,
			1 AS PERMITE_ALTERAR_NA_LOJA, 1 AS PERMITE_ALTERAR_NO_TERMINAL,	0 AS ENVIA_PARA_REPRESENTANTE,	0 AS PERMITE_POR_REPRESENTANTE, 0 AS PERMITE_ALTERAR_NO_REPRESENTANTE

IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = 'OMNI_SAIDA_REM')
	INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
	SELECT	'OMNI_SAIDA_REM' AS PARAMETRO, CAST(0 AS DATETIME) PENULT_ATUALIZACAO, '' AS VALOR_DEFAULT, GETDATE() AS ULT_ATUALIZACAO, 
			'' AS VALOR_ATUAL, '' AS DESC_PARAMETRO, 'C' AS TIPO_DADO, '' AS RANGE_VALOR_ATUAL, 1 AS GLOBAL, '' AS NOTA_PROGRAMADOR,
			0 AS ESCOPO, 0 AS POR_USUARIO_OK, 0 AS PERMITE_POR_EMPRESA,	1 AS ENVIA_PARA_LOJA,	1 AS PERMITE_POR_LOJA,	1 AS PERMITE_POR_TERMINAL,
			1 AS PERMITE_ALTERAR_NA_LOJA, 1 AS PERMITE_ALTERAR_NO_TERMINAL,	0 AS ENVIA_PARA_REPRESENTANTE,	0 AS PERMITE_POR_REPRESENTANTE, 0 AS PERMITE_ALTERAR_NO_REPRESENTANTE

IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = 'OMNI_SERIE_REM')
	INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
	SELECT	'OMNI_SERIE_REM' AS PARAMETRO, CAST(0 AS DATETIME) PENULT_ATUALIZACAO, '' AS VALOR_DEFAULT, GETDATE() AS ULT_ATUALIZACAO, 
			'' AS VALOR_ATUAL, '' AS DESC_PARAMETRO, 'C' AS TIPO_DADO, '' AS RANGE_VALOR_ATUAL, 1 AS GLOBAL, '' AS NOTA_PROGRAMADOR,
			0 AS ESCOPO, 0 AS POR_USUARIO_OK, 0 AS PERMITE_POR_EMPRESA,	1 AS ENVIA_PARA_LOJA,	1 AS PERMITE_POR_LOJA,	1 AS PERMITE_POR_TERMINAL,
			1 AS PERMITE_ALTERAR_NA_LOJA, 1 AS PERMITE_ALTERAR_NO_TERMINAL,	0 AS ENVIA_PARA_REPRESENTANTE,	0 AS PERMITE_POR_REPRESENTANTE, 0 AS PERMITE_ALTERAR_NO_REPRESENTANTE

IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = 'OMNI_NAT_REM')
	INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
	SELECT	'OMNI_NAT_REM' AS PARAMETRO, CAST(0 AS DATETIME) PENULT_ATUALIZACAO, '' AS VALOR_DEFAULT, GETDATE() AS ULT_ATUALIZACAO, 
			'' AS VALOR_ATUAL, '' AS DESC_PARAMETRO, 'C' AS TIPO_DADO, '' AS RANGE_VALOR_ATUAL, 1 AS GLOBAL, '' AS NOTA_PROGRAMADOR,
			0 AS ESCOPO, 0 AS POR_USUARIO_OK, 0 AS PERMITE_POR_EMPRESA,	1 AS ENVIA_PARA_LOJA,	1 AS PERMITE_POR_LOJA,	1 AS PERMITE_POR_TERMINAL,
			1 AS PERMITE_ALTERAR_NA_LOJA, 1 AS PERMITE_ALTERAR_NO_TERMINAL,	0 AS ENVIA_PARA_REPRESENTANTE,	0 AS PERMITE_POR_REPRESENTANTE, 0 AS PERMITE_ALTERAR_NO_REPRESENTANTE

IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = 'VITRINE_TAB_PRECO')
	INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
	SELECT	'VITRINE_TAB_PRECO' AS PARAMETRO, CAST(0 AS DATETIME) PENULT_ATUALIZACAO, '' AS VALOR_DEFAULT, GETDATE() AS ULT_ATUALIZACAO, 
			'' AS VALOR_ATUAL, '' AS DESC_PARAMETRO, 'C' AS TIPO_DADO, '' AS RANGE_VALOR_ATUAL, 1 AS GLOBAL, '' AS NOTA_PROGRAMADOR,
			0 AS ESCOPO, 0 AS POR_USUARIO_OK, 0 AS PERMITE_POR_EMPRESA,	1 AS ENVIA_PARA_LOJA,	1 AS PERMITE_POR_LOJA,	1 AS PERMITE_POR_TERMINAL,
			1 AS PERMITE_ALTERAR_NA_LOJA, 1 AS PERMITE_ALTERAR_NO_TERMINAL,	0 AS ENVIA_PARA_REPRESENTANTE,	0 AS PERMITE_POR_REPRESENTANTE, 0 AS PERMITE_ALTERAR_NO_REPRESENTANTE



