

CREATE VIEW [dbo].[W_NOTAS_FISCAIS_PENDENTES]
AS
--DM50578 - #2# - 08/11/2017 - Edson Filenti - Solicitado inclusão dos filtros Status_nfe no segundo select. View estava retornando documentos autorizados como pendentes.
--DM35699 - #1# - 23/06/2017 - Giedson Silva - Melhoria de Performance (Replicação Wendel/Crispim).
SELECT * FROM (
				SELECT LOJA_NOTA_FISCAL.STATUS_NFE, LOJA_NOTA_FISCAL.LOG_STATUS_NFE,
						CASE WHEN L.NUMERO_MODELO_FISCAL = '55' THEN 'NF-E' WHEN L.NUMERO_MODELO_FISCAL = '65' THEN 'NFC-E' ELSE 'NÃO É NF-E' END AS TIPO_DOC_FISCAL,
						CASE WHEN LOJA_NOTA_FISCAL.STATUS_NFE = 1 AND LOJA_NOTA_FISCAL.LOG_STATUS_NFE = 0	THEN 'NÃO ENVIADA'
						WHEN LOJA_NOTA_FISCAL.STATUS_NFE = 2 AND LOJA_NOTA_FISCAL.LOG_STATUS_NFE = 0	THEN 'AGUARDANDO ENVIO'
						WHEN LOJA_NOTA_FISCAL.STATUS_NFE = 2 AND LOJA_NOTA_FISCAL.LOG_STATUS_NFE = 99	THEN 'ERRO AO VALIDAR'
						WHEN LOJA_NOTA_FISCAL.STATUS_NFE = 3 AND LOJA_NOTA_FISCAL.LOG_STATUS_NFE = 0	THEN 'ENVIADA'
						WHEN LOJA_NOTA_FISCAL.STATUS_NFE = 4 AND LOJA_NOTA_FISCAL.LOG_STATUS_NFE = 99	THEN 'REJEITADA'
						WHEN LOJA_NOTA_FISCAL.STATUS_NFE = 42 AND LOJA_NOTA_FISCAL.LOG_STATUS_NFE = 0   THEN 'CANCELAMENTO AGUARDANDO ENVIO'
						WHEN LOJA_NOTA_FISCAL.STATUS_NFE = 42 AND LOJA_NOTA_FISCAL.LOG_STATUS_NFE = 99	THEN 'CANCELAMENTO COM ERRO'
						WHEN LOJA_NOTA_FISCAL.STATUS_NFE = 52 AND LOJA_NOTA_FISCAL.LOG_STATUS_NFE = 0	THEN 'INUTILIZAÇÃO AGUARDANDO ENVIO'
						WHEN LOJA_NOTA_FISCAL.STATUS_NFE = 3 AND LOJA_NOTA_FISCAL.LOG_STATUS_NFE = 99	THEN 'INUTILIZAÇÃO COM ERRO'
						WHEN LOJA_NOTA_FISCAL.STATUS_NFE = 70 AND LOJA_NOTA_FISCAL.LOG_STATUS_NFE = 0	THEN 'USO DENEGADO'
						ELSE 'OUTROS' END AS DESC_STATUS_NFE,
						CASE WHEN LOJA_NOTA_FISCAL.TIPO_EMISSAO_NFE = 2 THEN 'FS-IA'
						WHEN LOJA_NOTA_FISCAL.TIPO_EMISSAO_NFE = 4 THEN 'EPEC'
						WHEN LOJA_NOTA_FISCAL.TIPO_EMISSAO_NFE = 5 THEN 'FS-DA'
						WHEN LOJA_NOTA_FISCAL.TIPO_EMISSAO_NFE = 6 THEN 'SVC-AN'
						WHEN LOJA_NOTA_FISCAL.TIPO_EMISSAO_NFE = 7 THEN 'SVC-RS'
						WHEN LOJA_NOTA_FISCAL.TIPO_EMISSAO_NFE = 9 THEN 'OFF-LINE'
						ELSE '' END AS DESCTIPOEMISSAONFE,
						LOJA_NOTA_FISCAL.CODIGO_FILIAL, LOJA_NOTA_FISCAL.NF_NUMERO, LOJA_NOTA_FISCAL.SERIE_NF, LOJA_NOTA_FISCAL.EMISSAO, LOJA_NOTA_FISCAL.QTDE_TOTAL,
						LOJA_NOTA_FISCAL.VALOR_TOTAL, LOJA_NOTA_FISCAL.NOTA_IMPRESSA, C.DESCRICAO AS DESCRICAO_SERIE, LOJA_NOTA_FISCAL.PROTOCOLO_AUTORIZACAO_NFE,
						LOJA_NOTA_FISCAL.TIPO_EMISSAO_NFE, LOJA_NOTA_FISCAL.CHAVE_NFE,
						CASE WHEN  L.NUMERO_MODELO_FISCAL = '65' THEN
						ISNULL(CASE WHEN LOJA_NOTA_FISCAL.STATUS_NFE = '52' AND LOJA_NOTA_FISCAL.LOG_STATUS_NFE = '0' THEN 'I'
						WHEN LOJA_NOTA_FISCAL.STATUS_NFE = '52' AND LOJA_NOTA_FISCAL.LOG_STATUS_NFE = '99' THEN 'I'
						WHEN LOJA_NOTA_FISCAL.STATUS_NFE = '3' AND LOJA_NOTA_FISCAL.LOG_STATUS_NFE  = '99' THEN 'I'
						WHEN LOJA_NOTA_FISCAL.STATUS_NFE = '42' AND LOJA_NOTA_FISCAL.LOG_STATUS_NFE = '0' THEN 'C'
						WHEN LOJA_NOTA_FISCAL.STATUS_NFE = '42' AND LOJA_NOTA_FISCAL.LOG_STATUS_NFE = '99' THEN 'C'
						WHEN LOJA_NOTA_FISCAL.STATUS_NFE = '1' AND LOJA_NOTA_FISCAL.LOG_STATUS_NFE = '0' THEN 'A'
						WHEN LOJA_NOTA_FISCAL.STATUS_NFE = '1' AND LOJA_NOTA_FISCAL.LOG_STATUS_NFE = '99' THEN 'A'
						WHEN LOJA_NOTA_FISCAL.STATUS_NFE = '3' AND LOJA_NOTA_FISCAL.LOG_STATUS_NFE = '0' THEN 'A'
						WHEN LOJA_NOTA_FISCAL.STATUS_NFE = '2' AND LOJA_NOTA_FISCAL.LOG_STATUS_NFE = '99' THEN 'R'
						WHEN LOJA_NOTA_FISCAL.STATUS_NFE = '4' THEN 'R'
						END,'') END AS ACAO_POS, LOJA_NOTA_FISCAL.DATA_AUTORIZACAO_NFE, LOJA_NOTA_FISCAL.JUSTIFICATIVA_CONTINGENCIA, LOJA_NOTA_FISCAL.DATA_CONTINGENCIA, CAST('' AS VARCHAR(255)) AS XMOTIVO, 0 AS PROCESSADA,DATA_CANCELAMENTO, PROTOCOLO_CANCELAMENTO_NFE, 
						ISNULL(COALESCE(LX_STATUS_NFCE_MSG.MSG_DETALHE_2,		            LX_STATUS_NFCE_MSG.MSG_1,					LX_STATUS_NFCE_MSG.MSG_PRINCIPAL) ,'')AS MSG, LOJA_NOTA_FISCAL.TIPO_ORIGEM , DATA_SAIDA, ULT_STATUS_ACAO,L.NUMERO_MODELO_FISCAL
				FROM DBO.LOJA_NOTA_FISCAL (NOLOCK)
				INNER JOIN DBO.SERIES_NF (NOLOCK) C ON DBO.LOJA_NOTA_FISCAL.SERIE_NF = C.SERIE_NF
				INNER JOIN DBO.LOJAS_NATUREZA_OPERACAO (NOLOCK) F ON DBO.LOJA_NOTA_FISCAL.NATUREZA_OPERACAO_CODIGO = F.NATUREZA_OPERACAO_CODIGO
				LEFT JOIN DBO.CTB_ESPECIE_SERIE (NOLOCK) L ON C.ESPECIE_SERIE = L.ESPECIE_SERIE
				LEFT JOIN  (
								SELECT CODIGO_FILIAL,NF_NUMERO, SERIE_NF, ULT_STATUS_RET_CONSULTA, EDI_REFERENCIA_ARQUIVO,LX_STATUS, ULT_STATUS_ACAO
								FROM DBO.EDI_ARQUIVO (NOLOCK)
							)AS EDI_ARQUIVO  
							ON  DBO.LOJA_NOTA_FISCAL.CODIGO_FILIAL = EDI_ARQUIVO.CODIGO_FILIAL
							AND DBO.LOJA_NOTA_FISCAL.NF_NUMERO =  EDI_ARQUIVO.NF_NUMERO
							AND DBO.LOJA_NOTA_FISCAL.SERIE_NF = EDI_ARQUIVO.SERIE_NF 
				LEFT JOIN DBO.LX_STATUS_NFCE_MSG (NOLOCK) LX_STATUS_NFCE_MSG
				--ON EDI_ARQUIVO.ULT_STATUS_RET_CONSULTA = LTRIM(RTRIM(LX_STATUS_NFCE_MSG.CODIGO_STATUS_RET)) --#1#
				ON EDI_ARQUIVO.ULT_STATUS_RET_CONSULTA = LX_STATUS_NFCE_MSG.CODIGO_STATUS_RET --#1#
				WHERE 
				 (	LOJA_NOTA_FISCAL.STATUS_NFE NOT IN (5,49,59,70) AND
					L.NUMERO_MODELO_FISCAL IN ('55','65') AND
					LOJA_NOTA_FISCAL.DATA_HORA_EMISSAO BETWEEN GETDATE()-40 AND DATEADD(MINUTE,-10,GETDATE()))

		UNION all
		SELECT * FROM (
				SELECT LOJA_NOTA_FISCAL.STATUS_NFE, LOJA_NOTA_FISCAL.LOG_STATUS_NFE,
				CASE WHEN L.NUMERO_MODELO_FISCAL = '55' THEN 'NF-E' WHEN L.NUMERO_MODELO_FISCAL = '65' THEN 'NFC-E' ELSE 'NÃO É NF-E' END AS TIPO_DOC_FISCAL,
				CASE WHEN LOJA_NOTA_FISCAL.STATUS_NFE = 1 AND LOJA_NOTA_FISCAL.LOG_STATUS_NFE = 0	   THEN 'NÃO ENVIADA'
				WHEN LOJA_NOTA_FISCAL.STATUS_NFE = 2 AND LOJA_NOTA_FISCAL.LOG_STATUS_NFE = 0	       THEN 'AGUARDANDO ENVIO'
				WHEN LOJA_NOTA_FISCAL.STATUS_NFE = 2 AND LOJA_NOTA_FISCAL.LOG_STATUS_NFE = 99	       THEN 'ERRO AO VALIDAR'
				WHEN LOJA_NOTA_FISCAL.STATUS_NFE = 3 AND LOJA_NOTA_FISCAL.LOG_STATUS_NFE = 0	       THEN 'ENVIADA'
				WHEN LOJA_NOTA_FISCAL.STATUS_NFE = 4 AND LOJA_NOTA_FISCAL.LOG_STATUS_NFE = 99	       THEN 'REJEITADA'
				WHEN LOJA_NOTA_FISCAL.STATUS_NFE = 42 AND LOJA_NOTA_FISCAL.LOG_STATUS_NFE = 0          THEN 'CANCELAMENTO AGUARDANDO ENVIO'
				WHEN LOJA_NOTA_FISCAL.STATUS_NFE = 42 AND LOJA_NOTA_FISCAL.LOG_STATUS_NFE = 99	       THEN 'CANCELAMENTO COM ERRO'
				WHEN LOJA_NOTA_FISCAL.STATUS_NFE = 52 AND LOJA_NOTA_FISCAL.LOG_STATUS_NFE = 0	       THEN 'INUTILIZAÇÃO AGUARDANDO ENVIO'
				WHEN LOJA_NOTA_FISCAL.STATUS_NFE = 3 AND LOJA_NOTA_FISCAL.LOG_STATUS_NFE = 99	       THEN 'INUTILIZAÇÃO COM ERRO'
				WHEN LOJA_NOTA_FISCAL.STATUS_NFE = 70 AND LOJA_NOTA_FISCAL.LOG_STATUS_NFE = 0	       THEN 'USO DENEGADO'
				ELSE 'OUTROS' END AS DESC_STATUS_NFE,
				CASE WHEN LOJA_NOTA_FISCAL.TIPO_EMISSAO_NFE = 2 THEN 'FS-IA'
				WHEN LOJA_NOTA_FISCAL.TIPO_EMISSAO_NFE = 4 THEN 'EPEC'
				WHEN LOJA_NOTA_FISCAL.TIPO_EMISSAO_NFE = 5 THEN 'FS-DA'
				WHEN LOJA_NOTA_FISCAL.TIPO_EMISSAO_NFE = 6 THEN 'SVC-AN'
				WHEN LOJA_NOTA_FISCAL.TIPO_EMISSAO_NFE = 7 THEN 'SVC-RS'
				WHEN LOJA_NOTA_FISCAL.TIPO_EMISSAO_NFE = 9 THEN 'OFF-LINE'
				ELSE '' END AS DESCTIPOEMISSAONFE,
				LOJA_NOTA_FISCAL.CODIGO_FILIAL, LOJA_NOTA_FISCAL.NF_NUMERO, LOJA_NOTA_FISCAL.SERIE_NF, LOJA_NOTA_FISCAL.EMISSAO, LOJA_NOTA_FISCAL.QTDE_TOTAL,
				LOJA_NOTA_FISCAL.VALOR_TOTAL, LOJA_NOTA_FISCAL.NOTA_IMPRESSA, C.DESCRICAO AS DESCRICAO_SERIE, LOJA_NOTA_FISCAL.PROTOCOLO_AUTORIZACAO_NFE,
				LOJA_NOTA_FISCAL.TIPO_EMISSAO_NFE, LOJA_NOTA_FISCAL.CHAVE_NFE,
				CASE WHEN  L.NUMERO_MODELO_FISCAL = '65' THEN
				CASE WHEN LOJA_NOTA_FISCAL.STATUS_NFE = '52' AND LOJA_NOTA_FISCAL.LOG_STATUS_NFE = '0' THEN 'I'
				WHEN LOJA_NOTA_FISCAL.STATUS_NFE = '52' AND LOJA_NOTA_FISCAL.LOG_STATUS_NFE = '99' THEN 'I'
				WHEN LOJA_NOTA_FISCAL.STATUS_NFE = '42' AND LOJA_NOTA_FISCAL.LOG_STATUS_NFE = '0' THEN 'C'
				WHEN LOJA_NOTA_FISCAL.STATUS_NFE = '42' AND LOJA_NOTA_FISCAL.LOG_STATUS_NFE = '99' THEN 'C'
				WHEN LOJA_NOTA_FISCAL.STATUS_NFE = '1' AND LOJA_NOTA_FISCAL.LOG_STATUS_NFE = '0' THEN 'A'
				WHEN LOJA_NOTA_FISCAL.STATUS_NFE = '2' AND LOJA_NOTA_FISCAL.LOG_STATUS_NFE = '99' THEN 'R'
				WHEN LOJA_NOTA_FISCAL.STATUS_NFE = '5' AND LOJA_NOTA_FISCAL.LOG_STATUS_NFE = '0' THEN 'A'
				END END AS ACAO_POS, LOJA_NOTA_FISCAL.DATA_AUTORIZACAO_NFE, LOJA_NOTA_FISCAL.JUSTIFICATIVA_CONTINGENCIA, LOJA_NOTA_FISCAL.DATA_CONTINGENCIA, CAST('' AS VARCHAR(255)) AS XMOTIVO, 0 AS PROCESSADA,DATA_CANCELAMENTO, PROTOCOLO_CANCELAMENTO_NFE, 
				ISNULL(COALESCE(LX_STATUS_NFCE_MSG.MSG_DETALHE_2,		            LX_STATUS_NFCE_MSG.MSG_1,					LX_STATUS_NFCE_MSG.MSG_PRINCIPAL) ,'')AS MSG, LOJA_NOTA_FISCAL.TIPO_ORIGEM , DATA_SAIDA, ULT_STATUS_ACAO,L.NUMERO_MODELO_FISCAL
			FROM DBO.LOJA_NOTA_FISCAL (NOLOCK)
			INNER JOIN DBO.SERIES_NF (NOLOCK) C ON DBO.LOJA_NOTA_FISCAL.SERIE_NF = C.SERIE_NF
			INNER JOIN DBO.LOJAS_NATUREZA_OPERACAO (NOLOCK) F ON DBO.LOJA_NOTA_FISCAL.NATUREZA_OPERACAO_CODIGO = F.NATUREZA_OPERACAO_CODIGO
			LEFT JOIN DBO.CTB_ESPECIE_SERIE (NOLOCK) L ON C.ESPECIE_SERIE = L.ESPECIE_SERIE
			LEFT JOIN 
			(
				SELECT CODIGO_FILIAL,NF_NUMERO, SERIE_NF, ULT_STATUS_RET_CONSULTA, EDI_REFERENCIA_ARQUIVO,LX_STATUS, ULT_STATUS_ACAO
				FROM DBO.EDI_ARQUIVO (NOLOCK)
			)AS EDI_ARQUIVO  
			ON  DBO.LOJA_NOTA_FISCAL.CODIGO_FILIAL = EDI_ARQUIVO.CODIGO_FILIAL
			AND DBO.LOJA_NOTA_FISCAL.NF_NUMERO =  EDI_ARQUIVO.NF_NUMERO
			AND DBO.LOJA_NOTA_FISCAL.SERIE_NF = EDI_ARQUIVO.SERIE_NF 
			LEFT JOIN DBO.LX_STATUS_NFCE_MSG (NOLOCK) LX_STATUS_NFCE_MSG
			  ON EDI_ARQUIVO.ULT_STATUS_RET_CONSULTA = LX_STATUS_NFCE_MSG.CODIGO_STATUS_RET -- #1#
			--ON EDI_ARQUIVO.ULT_STATUS_RET_CONSULTA = LTRIM(RTRIM(LX_STATUS_NFCE_MSG.CODIGO_STATUS_RET)) #1#
			WHERE 
			 (	LOJA_NOTA_FISCAL.STATUS_NFE NOT IN (5,49,59,70) AND --#3#
				L.NUMERO_MODELO_FISCAL ='65' AND LOJA_NOTA_FISCAL.DATA_HORA_EMISSAO BETWEEN GETDATE()-40 AND DATEADD(MINUTE,-10,GETDATE())) 
		) TMP 
		WHERE TMP.ACAO_POS is not null and TMP.ULT_STATUS_ACAO is not null and  TMP.ACAO_POS <> TMP.ULT_STATUS_ACAO
 
 ) PENDENTES
GROUP BY PENDENTES.ACAO_POS, PENDENTES.CHAVE_NFE , PENDENTES.CODIGO_FILIAL  ,PENDENTES.DATA_AUTORIZACAO_NFE , PENDENTES.DATA_CANCELAMENTO,
PENDENTES.DATA_CONTINGENCIA , PENDENTES.DATA_SAIDA , PENDENTES.DESC_STATUS_NFE , PENDENTES.DESCRICAO_SERIE , PENDENTES.DESCTIPOEMISSAONFE,
PENDENTES.EMISSAO, PENDENTES.JUSTIFICATIVA_CONTINGENCIA, PENDENTES.LOG_STATUS_NFE, PENDENTES.MSG, PENDENTES.NF_NUMERO, PENDENTES.NF_NUMERO,
PENDENTES.NOTA_IMPRESSA, PENDENTES.NUMERO_MODELO_FISCAL , PENDENTES.PROCESSADA , PENDENTES.PROTOCOLO_AUTORIZACAO_NFE, PENDENTES.PROTOCOLO_CANCELAMENTO_NFE,
PENDENTES.QTDE_TOTAL, PENDENTES.SERIE_NF, PENDENTES.STATUS_NFE, PENDENTES.TIPO_DOC_FISCAL , PENDENTES.TIPO_EMISSAO_NFE,
PENDENTES.TIPO_ORIGEM, PENDENTES.ULT_STATUS_ACAO, PENDENTES.VALOR_TOTAL , PENDENTES.XMOTIVO