IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CREDENCIADORA_CARTAO') 
	AND NOT EXISTS (SELECT * FROM CREDENCIADORA_CARTAO WHERE COD_CREDENCIADORA = '999')
		INSERT INTO [dbo].[CREDENCIADORA_CARTAO]
           ([COD_CREDENCIADORA],[NOME_CREDENCIADORA],[CNPJ_CREDENCIADORA],[INATIVO],[DATA_PARA_TRANSFERENCIA])
			VALUES  ('999','Outros','',0,GETDATE())