IF  NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.CONSTRAINT_TABLE_USAGE 
				WHERE TABLE_NAME = 'LOJA_VENDA_PARCELAS_MFE' AND CONSTRAINT_NAME = 'XFK10001_LOJA_VENDA_PARCELAS_MFE')
	begin 
		ALTER TABLE [dbo].[LOJA_VENDA_PARCELAS_MFE]  WITH CHECK ADD  CONSTRAINT [XFK10001_LOJA_VENDA_PARCELAS_MFE] FOREIGN KEY([TERMINAL], [LANCAMENTO_CAIXA], [CODIGO_FILIAL], [PARCELA])
		REFERENCES [dbo].[LOJA_VENDA_PARCELAS] ([TERMINAL], [LANCAMENTO_CAIXA], [CODIGO_FILIAL], [PARCELA])
	end

 