

IF NOT EXISTS ( SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LX_NFS_PENDENTES' AND COLUMN_NAME = 'LJ_LX_ID_ACAO_PDV' )
	ALTER TABLE LX_NFS_PENDENTES ADD LJ_LX_ID_ACAO_PDV char(2) NULL 