IF NOT EXISTS ( SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_VENDA_PROMOCAO' AND COLUMN_NAME = 'ITEM' )
BEGIN
	ALTER TABLE LOJA_VENDA_PROMOCAO ADD ITEM char(04) NULL
END;

IF NOT EXISTS ( SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_VENDA_PROMOCAO' AND COLUMN_NAME = 'DESC_PROMOCAO' )
BEGIN
	ALTER TABLE LOJA_VENDA_PROMOCAO ADD DESC_PROMOCAO VARCHAR(60) NULL
END;

IF NOT EXISTS ( SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_VENDA_PROMOCAO_CUPOM' AND COLUMN_NAME = 'DATA_VENDA' )
BEGIN
	ALTER TABLE LOJA_VENDA_PROMOCAO_CUPOM ADD DATA_VENDA DATETIME NULL
END;