IF EXISTS ( SELECT 1 FROM LOJA_VENDA_PROMOCAO WHERE ITEM is null )
BEGIN
	UPDATE LOJA_VENDA_PROMOCAO SET ITEM = '0000' WHERE ITEM is null
END;

IF EXISTS ( SELECT 1 FROM LOJA_VENDA_PROMOCAO_CUPOM WHERE DATA_VENDA is null )
BEGIN
	UPDATE LOJA_VENDA_PROMOCAO_CUPOM SET DATA_VENDA = convert(char(10), DATA_HORA, 112) WHERE DATA_VENDA is null
END;