IF EXISTS ( SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_VENDA_PROMOCAO_CUPOM' AND COLUMN_NAME = 'DATA_VENDA' AND IS_NULLABLE = 'YES')
BEGIN
	ALTER TABLE LOJA_VENDA_PROMOCAO_CUPOM ALTER COLUMN DATA_VENDA DATETIME NOT NULL
END;
	
IF EXISTS ( SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_VENDA_PROMOCAO' AND COLUMN_NAME = 'ITEM' AND IS_NULLABLE = 'YES')
BEGIN
	ALTER TABLE LOJA_VENDA_PROMOCAO ALTER COLUMN ITEM char(04) NOT NULL;
END;