IF NOT EXISTS ( SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_CF_SAT' AND COLUMN_NAME = 'URL_ENVIO'  )
	ALTER TABLE LOJA_CF_SAT ADD URL_ENVIO varchar(100) NULL
IF NOT EXISTS ( SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_CF_SAT_LOG' AND COLUMN_NAME = 'URL_ENVIO'  )
	ALTER TABLE LOJA_CF_SAT_LOG ADD URL_ENVIO varchar(100) NULL