IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_CICLO_CONSERTO' AND COLUMN_NAME = 'SERIE_NF_SAIDA_TERCEIRO_') AND EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_CICLO_CONSERTO' AND COLUMN_NAME = 'SERIE_NF_SAIDA_TERCEIRO')
	BEGIN		
		ALTER TABLE LOJA_CICLO_CONSERTO DROP COLUMN SERIE_NF_SAIDA_TERCEIRO_
	END
ELSE
	BEGIN
		DECLARE @QUERYUPDATE VARCHAR(150)

		SET @QUERYUPDATE = 'UPDATE DBO.LOJA_CICLO_CONSERTO SET LOJA_CICLO_CONSERTO.SERIE_NF_SAIDA_TERCEIRO = LOJA_CICLO_CONSERTO.SERIE_NF_SAIDA_TERCEIRO_'

		IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_CICLO_CONSERTO' AND COLUMN_NAME = 'SERIE_NF_SAIDA_TERCEIRO')
			BEGIN			
				ALTER TABLE LOJA_CICLO_CONSERTO ADD SERIE_NF_SAIDA_TERCEIRO CHAR (6)
			END

		IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_CICLO_CONSERTO' AND COLUMN_NAME = 'SERIE_NF_SAIDA_TERCEIRO_')
			BEGIN			
				IF EXISTS ( SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_CICLO_CONSERTO' AND COLUMN_NAME = 'SERIE_NF_SAIDA_TERCEIRO')	
					BEGIN
						EXEC (@QUERYUPDATE)
					END
		
				ALTER TABLE LOJA_CICLO_CONSERTO DROP COLUMN SERIE_NF_SAIDA_TERCEIRO_
			END
	END



