CREATE FUNCTION [dbo].[FX_GTIN_BARCODE_SEEK] (@CODIGO_ITEM VARCHAR(50), @AGRUPAMENTO_ITENS SMALLINT, @REFERENCIA_PEDIDO VARCHAR(12) , @REFERENCIA VARCHAR(50) = NULL, @REFERENCIA_ITEM VARCHAR(12) = NULL)
RETURNS VARCHAR(25)
AS
  -- 27/08/2018 - Eder Silva - DM 89499 - #2# - Retornar somente códigos de barras que estão ativos.
  /*DM 58430 - Diego Moreno - #1# - (20/09/2017) - Adequacao NFE 4.00. Remoção do tratamento anterior esta function irá retornar conteudo vázio. 
  Melhoria para atender ao layout 4.0, conforme o novo Layout quando a informação referente ao GTIN não for informada devérá ser preenchido com o texto SEM GTIN.*/
BEGIN
	DECLARE @CODIGO_BARRA VARCHAR(25)
	
	SET @CODIGO_BARRA = NULL

	IF @AGRUPAMENTO_ITENS  = 2
		IF @REFERENCIA is not null and @REFERENCIA_ITEM is not null
			SELECT TOP 1 @CODIGO_BARRA = CODIGO_BARRA FROM PRODUTOS_BARRA (NOLOCK)
			WHERE PRODUTO = @REFERENCIA
			AND RTRIM(COR_PRODUTO)+RTRIM(GRADE) = @REFERENCIA_ITEM
			AND TIPO_COD_BAR = 1
			AND INATIVO = 0  --#2#
		ELSE
			SELECT TOP 1 @CODIGO_BARRA = CODIGO_BARRA FROM PRODUTOS_BARRA (NOLOCK)
			WHERE RTRIM(PRODUTO)+RTRIM(COR_PRODUTO)+RTRIM(GRADE) = @CODIGO_ITEM
			AND TIPO_COD_BAR = 1
			AND INATIVO = 0  --#2#
		
	IF @AGRUPAMENTO_ITENS = 5
		BEGIN 	

			SELECT TOP 1 @CODIGO_BARRA = CODIGO_BARRA FROM PRODUTOS_BARRA (NOLOCK)
			WHERE RTRIM(@REFERENCIA_PEDIDO)+RTRIM(PRODUTO)+RTRIM(COR_PRODUTO)+RTRIM(GRADE) = @CODIGO_ITEM
			AND TIPO_COD_BAR = 1
			AND INATIVO = 0  --#2#
		END
		
	RETURN RTRIM(ISNULL(@CODIGO_BARRA,'')) --#1#
END