if not exists(select * from PARAMETROS where parametro = 'PERMITE_DESC_COM_MOTOR')
begin
	insert into PARAMETROS (PARAMETRO,PENULT_ATUALIZACAO,VALOR_DEFAULT,ULT_ATUALIZACAO,VALOR_ATUAL,DESC_PARAMETRO,
TIPO_DADO,RANGE_VALOR_ATUAL,GLOBAL,NOTA_PROGRAMADOR,ESCOPO,POR_USUARIO_OK,PERMITE_POR_EMPRESA,ENVIA_PARA_LOJA,PERMITE_POR_LOJA,
PERMITE_POR_TERMINAL,PERMITE_ALTERAR_NA_LOJA,PERMITE_ALTERAR_NO_TERMINAL,ENVIA_PARA_REPRESENTANTE,PERMITE_POR_REPRESENTANTE,
PERMITE_ALTERAR_NO_REPRESENTANTE,DATA_PARA_TRANSFERENCIA)
	 values ( 'PERMITE_DESC_COM_MOTOR', '2014-05-05 00:00:00.000','.F.', '2014-05-05 00:00:00.000',	'.F.' ,'Permite desconto com motor de promoções Linx',  	'L'	,'',  	0,	NULL,	0,	0,	0,	1,	1,	1,	1	,1,	0,	0,	0,	'2014-05-05 10:48:40.000')
end


if not exists(select * from PARAMETROS where parametro = 'PERMITE_TROCA_COM_MOTOR')
begin
       insert into PARAMETROS (PARAMETRO,PENULT_ATUALIZACAO,VALOR_DEFAULT,ULT_ATUALIZACAO,VALOR_ATUAL,DESC_PARAMETRO,
TIPO_DADO,RANGE_VALOR_ATUAL,GLOBAL,NOTA_PROGRAMADOR,ESCOPO,POR_USUARIO_OK,PERMITE_POR_EMPRESA,ENVIA_PARA_LOJA,PERMITE_POR_LOJA,
PERMITE_POR_TERMINAL,PERMITE_ALTERAR_NA_LOJA,PERMITE_ALTERAR_NO_TERMINAL,ENVIA_PARA_REPRESENTANTE,PERMITE_POR_REPRESENTANTE,
PERMITE_ALTERAR_NO_REPRESENTANTE,DATA_PARA_TRANSFERENCIA)
	    values ( 'PERMITE_TROCA_COM_MOTOR', '2014-05-05 00:00:00.000','.F.', '2014-05-05 00:00:00.000', '.F.' ,'Permite troca na venda mesmo quando houver promocoes aplicadas',         'L'    ,'',  0,     NULL,  0,     0,     0,     1,     1,     1,     1      ,1,    0,     0,       0,     '2014-05-05 10:48:40.000')
end 

 
if not exists(select * from PARAMETROS where parametro = 'PERMITE_VALE_P_COM_MOTOR')
begin
       insert into PARAMETROS (PARAMETRO,PENULT_ATUALIZACAO,VALOR_DEFAULT,ULT_ATUALIZACAO,VALOR_ATUAL,DESC_PARAMETRO,
TIPO_DADO,RANGE_VALOR_ATUAL,GLOBAL,NOTA_PROGRAMADOR,ESCOPO,POR_USUARIO_OK,PERMITE_POR_EMPRESA,ENVIA_PARA_LOJA,PERMITE_POR_LOJA,
PERMITE_POR_TERMINAL,PERMITE_ALTERAR_NA_LOJA,PERMITE_ALTERAR_NO_TERMINAL,ENVIA_PARA_REPRESENTANTE,PERMITE_POR_REPRESENTANTE,
PERMITE_ALTERAR_NO_REPRESENTANTE,DATA_PARA_TRANSFERENCIA)
	    values ( 'PERMITE_VALE_P_COM_MOTOR', '2014-05-05 00:00:00.000','.F.', '2014-05-05 00:00:00.000', '.F.' ,'Permite vale produto na venda mesmo quando houver promocoes aplicadas',  'L'    ,'',  0,     NULL,  0,     0,     0,     1,     1,     1,     1      ,1,    0,       0,     0,     '2014-05-05 10:48:40.000')
end 


if not exists(select * from PARAMETROS where parametro = 'EXIBIR_BOTAO_CUPOM_PROMO')
begin
       insert into PARAMETROS (PARAMETRO,PENULT_ATUALIZACAO,VALOR_DEFAULT,ULT_ATUALIZACAO,VALOR_ATUAL,DESC_PARAMETRO,
TIPO_DADO,RANGE_VALOR_ATUAL,GLOBAL,NOTA_PROGRAMADOR,ESCOPO,POR_USUARIO_OK,PERMITE_POR_EMPRESA,ENVIA_PARA_LOJA,PERMITE_POR_LOJA,
PERMITE_POR_TERMINAL,PERMITE_ALTERAR_NA_LOJA,PERMITE_ALTERAR_NO_TERMINAL,ENVIA_PARA_REPRESENTANTE,PERMITE_POR_REPRESENTANTE,
PERMITE_ALTERAR_NO_REPRESENTANTE,DATA_PARA_TRANSFERENCIA)
	    values ( 'EXIBIR_BOTAO_CUPOM_PROMO', '2014-05-05 00:00:00.000','.T.', '2014-05-05 00:00:00.000', '.T.' ,'Indica se será exibido o botão para inclusão de cupom promocional na tela de vendas (sale)',  'L'    ,'',  0,     NULL,  0,     0,     0,     1,     1,     1,     1      ,1,    0,       0,     0,     '2014-05-05 10:48:40.000')
end 