
IF NOT EXISTS(SELECT PARAMETRO FROM PARAMETROS WHERE PARAMETRO = 'HABILITA_CHAT_LINX')
INSERT INTO PARAMETROS(PARAMETRO, DESC_PARAMETRO, PENULT_ATUALIZACAO, ULT_ATUALIZACAO, TIPO_DADO, VALOR_DEFAULT, 
		VALOR_ATUAL, GLOBAL, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, NOTA_PROGRAMADOR)
VALUES('HABILITA_CHAT_LINX','HABILITA A EXIBIÇÃO DE BOTÃO PARA ATENDIMENTO VIA CHAT NO PDV.','20180212','20180212','L','.F.','.F.',0,1,1,0,0,0,'PARÂMETRO CRIADO PARA HABILITAR UTILIZAÇÃO DO CHAT LINX')


IF NOT EXISTS(SELECT PARAMETRO FROM PARAMETROS WHERE PARAMETRO = 'URL_CHAT_LINX')
INSERT INTO PARAMETROS(PARAMETRO, DESC_PARAMETRO, PENULT_ATUALIZACAO, ULT_ATUALIZACAO, TIPO_DADO, VALOR_DEFAULT, 
		VALOR_ATUAL, GLOBAL, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, NOTA_PROGRAMADOR)
VALUES('URL_CHAT_LINX','URL UTILIZADA PARA ACESSAR UM ATENDIMENTO NO SUPORTE LINX VIA CHAT.','20180212','20180212','C','http://cliente.linx.com.br/atendimento','http://cliente.linx.com.br/atendimento',0,1,1,0,0,0,'PARÂMETRO CRIADO PARA UTILIZAÇÃO DO CHAT LINX')
ELSE
UPDATE PARAMETROS SET VALOR_ATUAL = 'http://cliente.linx.com.br/atendimento', VALOR_DEFAULT = 'http://cliente.linx.com.br/atendimento' WHERE PARAMETRO = 'URL_CHAT_LINX'


IF NOT EXISTS(SELECT PARAMETRO FROM PARAMETROS WHERE PARAMETRO = 'SEGMENTO_CHAT_LINX')
INSERT INTO PARAMETROS(PARAMETRO, DESC_PARAMETRO, PENULT_ATUALIZACAO, ULT_ATUALIZACAO, TIPO_DADO, VALOR_DEFAULT, 
		VALOR_ATUAL, GLOBAL, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, NOTA_PROGRAMADOR)
VALUES('SEGMENTO_CHAT_LINX','URL UTILIZADA PARA ACESSAR UM ATENDIMENTO NO SUPORTE LINX VIA CHAT.','20180212','20180212','C','MODA','MODA',0,1,1,0,0,0,'PARÂMETRO CRIADO PARA UTILIZAÇÃO DO CHAT LINX')


IF NOT EXISTS(SELECT PARAMETRO FROM PARAMETROS WHERE PARAMETRO = 'PRODUTO_CHAT_LINX')
INSERT INTO PARAMETROS(PARAMETRO, DESC_PARAMETRO, PENULT_ATUALIZACAO, ULT_ATUALIZACAO, TIPO_DADO, VALOR_DEFAULT, 
		VALOR_ATUAL, GLOBAL, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, NOTA_PROGRAMADOR)
VALUES('PRODUTO_CHAT_LINX','URL UTILIZADA PARA ACESSAR UM ATENDIMENTO NO SUPORTE LINX VIA CHAT.','20180212','20180212','C','Linx%POS','Linx%POS',0,1,1,0,0,0,'PARÂMETRO CRIADO PARA UTILIZAÇÃO DO CHAT LINX')


IF NOT EXISTS(SELECT PARAMETRO FROM PARAMETROS WHERE PARAMETRO = 'CONTEXTO_CHAT_LINX')
INSERT INTO PARAMETROS(PARAMETRO, DESC_PARAMETRO, PENULT_ATUALIZACAO, ULT_ATUALIZACAO, TIPO_DADO, VALOR_DEFAULT, 
		VALOR_ATUAL, GLOBAL, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, NOTA_PROGRAMADOR)
VALUES('CONTEXTO_CHAT_LINX','URL UTILIZADA PARA ACESSAR UM ATENDIMENTO NO SUPORTE LINX VIA CHAT.','20180212','20180212','C','Nota%Fiscal','Nota%Fiscal',0,1,1,0,0,0,'PARÂMETRO CRIADO PARA UTILIZAÇÃO DO CHAT LINX')