
IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'LOJA_PEDIDO'
                      AND COLUMN_NAME = 'ID_PEDIDO_ORIGEM')
  ALTER TABLE [dbo].[LOJA_PEDIDO]
    ADD ID_PEDIDO_ORIGEM VARCHAR(20) 
