
IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'LOJA_PEDIDO'
                      AND COLUMN_NAME = 'SITUACAO_OMS')
  ALTER TABLE [dbo].[LOJA_PEDIDO]
    ADD SITUACAO_OMS TINYINT 
