
IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'LOJA_PEDIDO_PRODUTO'
                      AND COLUMN_NAME = 'SEQ_ENTREGA')
  ALTER TABLE [dbo].[LOJA_PEDIDO_PRODUTO]
    ADD SEQ_ENTREGA TINYINT 
