IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'LOJA_PEDIDO_ENTREGA'
                      AND COLUMN_NAME = 'FRETE')
  ALTER TABLE [dbo].[LOJA_PEDIDO_ENTREGA]
    ADD FRETE NUMERIC(14,2) NULL 
