IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_VENDA_PROMOCAO' AND COLUMN_NAME = 'CAMPANHA')
	ALTER TABLE LOJA_VENDA_PROMOCAO ADD CAMPANHA VARCHAR(100)

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_VENDA_PROMOCAO' AND COLUMN_NAME = 'PRECO_UNITARIO')
	ALTER TABLE LOJA_VENDA_PROMOCAO ADD PRECO_UNITARIO NUMERIC(9,2)	

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_VENDA_PROMOCAO' AND COLUMN_NAME = 'VALOR_DESCONTO')
	ALTER TABLE LOJA_VENDA_PROMOCAO ADD VALOR_DESCONTO NUMERIC(9,2)	

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_VENDA_PROMOCAO' AND COLUMN_NAME = 'ID_BENEFICIO')
	ALTER TABLE LOJA_VENDA_PROMOCAO ADD ID_BENEFICIO SMALLINT NOT NULL DEFAULT  (0)
	
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_VENDA_PROMOCAO' AND COLUMN_NAME = 'VERSAO_MAPA')
	ALTER TABLE LOJA_VENDA_PROMOCAO ADD VERSAO_MAPA SMALLINT NOT NULL DEFAULT  (0)

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_VENDA_PROMOCAO' AND COLUMN_NAME = 'QTDE')
	ALTER TABLE LOJA_VENDA_PROMOCAO ADD QTDE SMALLINT NULL DEFAULT  (0)

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_VENDA_PROMOCAO' AND COLUMN_NAME = 'BASE_CALCULO')
	ALTER TABLE LOJA_VENDA_PROMOCAO ADD BASE_CALCULO NUMERIC(9,2)	