IF EXISTS (SELECT PARAMETRO FROM PARAMETROS WHERE PARAMETRO = 'UTILIZA_PROMO_OMNI')
	BEGIN
		UPDATE	PARAMETROS
		SET		DESC_PARAMETRO   = 'HABILITA A INTERFACE DE MOTOR DE PROMOÇÃO DO LINX UX.',
				NOTA_PROGRAMADOR = 'PARÂMETRO PARA HABILITAR A OPÇÃO DE UTILIZAR A FUNCIONALIDADE DE MOTOR DE PROMOÇÃO DO LINX UX.' 
		WHERE	PARAMETRO = 'UTILIZA_PROMO_OMNI'
	END
