
IF NOT EXISTS(SELECT PARAMETRO FROM PARAMETROS WHERE PARAMETRO = 'HABILITA_VISITA_VIRTUAL')
INSERT INTO PARAMETROS(PARAMETRO, DESC_PARAMETRO, PENULT_ATUALIZACAO, ULT_ATUALIZACAO, TIPO_DADO, VALOR_DEFAULT, 
		VALOR_ATUAL, GLOBAL, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, NOTA_PROGRAMADOR)
VALUES('HABILITA_VISITA_VIRTUAL','HABILITA A EXIBIÇÃO DE BOTÃO PARA VISITA VIRTUAL NO PDV.','20180212','20180212','L','.F.','.F.',0,1,1,0,0,0,'PARÂMETRO CRIADO PARA HABILITAR UTILIZAÇÃO DO VISITA VIRTUAL')





