IF NOT EXISTS(SELECT PARAMETRO FROM PARAMETROS WHERE PARAMETRO = 'ETL_ON_DEMAND_TP171_DAY')
	INSERT INTO PARAMETROS (PARAMETRO, DESC_PARAMETRO, PENULT_ATUALIZACAO, ULT_ATUALIZACAO, TIPO_DADO, VALOR_DEFAULT,VALOR_ATUAL, GLOBAL, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL)
	VALUES ('ETL_ON_DEMAND_TP171_DAY','Configura o numero de dias utilizado como filtro de busca no ETL On Demand para o tipo 171','20170501','20170501','I','45','45',0,1,1,0,0,0)

IF NOT EXISTS(SELECT PARAMETRO FROM PARAMETROS WHERE PARAMETRO = 'ETL_QTD_REQUEST')
	INSERT INTO PARAMETROS (PARAMETRO, DESC_PARAMETRO, PENULT_ATUALIZACAO, ULT_ATUALIZACAO, TIPO_DADO, VALOR_DEFAULT, VALOR_ATUAL, GLOBAL, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL)
	VALUES ('ETL_QTD_REQUEST','Configura a quantidade maxima de requisições do mesmo tipo no ETL On Demand','20170501','20170501','I','5','5',0,1,1,0,0,0)