IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'LOJA_ENTRADAS'
                      AND COLUMN_NAME = 'UTILIZA_PRECO_ORIGEM')				                     
	BEGIN
		ALTER TABLE [DBO].[LOJA_ENTRADAS]
		ADD UTILIZA_PRECO_ORIGEM BIT NOT NULL DEFAULT 0 
	END