
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE  TABLE_NAME = 'LOJA_VENDA_TROCA_OMS') BEGIN
    
	CREATE TABLE LOJA_VENDA_TROCA_OMS
	(
	    TICKET            CHAR(8)     NOT NULL,
        CODIGO_FILIAL     CHAR(6)     NOT NULL,
        ITEM              CHAR(4)     NOT NULL,
        DATA_VENDA        DATETIME    NOT NULL,
        CHANNELID         VARCHAR(32) NOT NULL,
        ID_PEDIDO_ORIGEM  VARCHAR(20) NOT NULL,
        ID_ENTREGA_ORIGEM VARCHAR(20) NOT NULL,
        SKU               VARCHAR(25) NOT NULL
	)
	
	ALTER TABLE LOJA_VENDA_TROCA_OMS ADD CONSTRAINT PK_LOJA_VENDA_TROCA_OMS PRIMARY KEY(TICKET, CODIGO_FILIAL, ITEM, DATA_VENDA)
	
END

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'LOJA_VENDA_TROCA_OMS'
                      AND COLUMN_NAME = 'FRETE_SAC')
  ALTER TABLE [dbo].[LOJA_VENDA_TROCA_OMS]
    ADD FRETE_SAC  NUMERIC(14,2) NULL


IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'LOJA_VENDA_TROCA_OMS'
                      AND COLUMN_NAME = 'FRETE')
  ALTER TABLE [dbo].[LOJA_VENDA_TROCA_OMS]
    ADD FRETE  NUMERIC(14,2) NULL


IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'LOJA_VENDA_TROCA_OMS'
                      AND COLUMN_NAME = 'QTDE_DEVOLVIDA')
  ALTER TABLE [dbo].[LOJA_VENDA_TROCA_OMS]
    ADD QTDE_DEVOLVIDA INT NULL

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'LOJA_VENDA_TROCA_OMS'
                      AND COLUMN_NAME = 'QTDE_AVARIA')
  ALTER TABLE [dbo].[LOJA_VENDA_TROCA_OMS]
    ADD QTDE_AVARIA INT NULL
	
IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'LOJA_VENDA_TROCA_OMS'
                      AND COLUMN_NAME = 'QTDE_RECUSADA')
  ALTER TABLE [dbo].[LOJA_VENDA_TROCA_OMS]
    ADD QTDE_RECUSADA INT NULL
	
IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'LOJA_VENDA_TROCA_OMS'
                      AND COLUMN_NAME = 'QTDE_NAO_DEVOLVIDA')
  ALTER TABLE [dbo].[LOJA_VENDA_TROCA_OMS]
    ADD QTDE_NAO_DEVOLVIDA INT NULL
	
	
	IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'LOJA_VENDA_TROCA_OMS'
                      AND COLUMN_NAME = 'ID_EXCEPTION')
  ALTER TABLE [dbo].[LOJA_VENDA_TROCA_OMS]
    ADD ID_EXCEPTION VARCHAR(20) NULL
	
	IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'LOJA_VENDA_TROCA_OMS'
                      AND COLUMN_NAME = 'INDICA_DEVOLUCAO')
  ALTER TABLE [dbo].[LOJA_VENDA_TROCA_OMS]
    ADD INDICA_DEVOLUCAO BIT NULL
