 IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[LOJA_VALE_TRANSACAO]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[LOJA_VALE_TRANSACAO](
	[ID_TRANSACAO] [INT] IDENTITY(1,1) NOT NULL,
	[CODIGO_FILIAL] [CHAR](6) NOT NULL,
	[TICKET] [CHAR](8) NOT NULL,
	[DATA_VENDA] [DATETIME] NOT NULL,
	[NUMERO_CARTAO] [VARCHAR](40) NOT NULL,
	[CNPJ] [VARCHAR](16) NOT NULL,
	[TIPO_REQUISICAO] [INT] NOT NULL,
	[VALOR] [NUMERIC](14, 2) NOT NULL,
	[PIN] [VARCHAR](20) NULL,
	[CODIGO_TRANSACAO] [VARCHAR](30) NULL,
	[DATA_HORA_TRANSACAO] [DATETIME] NULL,
	[PROTOCOLO_OFFLINE] [VARCHAR](50) NULL,
	[NSU] [VARCHAR](20) NULL,
	[NSU_HOST] [VARCHAR](20) NULL,
	[TRANSACAO_INICIADA] [BIT] NOT NULL,
	[TRANSACAO_CONCLUIDA] [BIT] NOT NULL,
	[ENVIADA_OMNI] [BIT] NOT NULL
) ON [PRIMARY]
end


