CREATE FUNCTION [dbo].[FX_GERA_N_TICKET](@NUM_SEQ_ECF INT, @COO INT) RETURNS CHAR(8)
-- 22/05/2014 - Roberto Beda - TP 6527721 - #1 - Criação da function. Gera número de ticket fictício a partir do seq do ECF e do COO do cupom fiscal
BEGIN
	DECLARE @VALOR INT, @RESULT VARCHAR(20), @RESTO INT, @RETORNO CHAR(8)
	
	SET @VALOR = @NUM_SEQ_ECF * 1000000 + @COO
	SET @RESULT = ''
	WHILE @VALOR > 0
	BEGIN
		SET @RESTO = @VALOR % 16
		SET @RESULT = CASE WHEN @RESTO < 10 THEN CAST(@RESTO AS CHAR(1)) ELSE CHAR(@RESTO + 55) END + @RESULT 
		SET @VALOR = @VALOR / 16
	END
	SET @RETORNO = 'X' + RIGHT('0000000' + @RESULT, 7)
	
	RETURN @RETORNO
END


