CREATE VIEW [dbo].[W_INFORMACAO_PAGAMENTO]
-- PRODSHOP-10794 - Eder Silva			  - #32# - 03/08/2021 - Alterada a regra para exibição do troco na NF-e quando tiver item do Vitrine na venda.
-- PRODSHOP-7305  - Eder Silva			  - #31# - 03/08/2021 - Alterada a regra para exibição do troco na NF-e quando tiver item do Vitrine na venda.
-- MODASP-12077   - Daiana Medeiros(GSF)  - #30# - 30/06/2021 - Implementação do processo de pedido de entrega futura.
-- PRODSHOP-6546  - Eder Silva			  - #29# - 04/06/2021 - Tratamento para nota de venda à ordem (Vitrine).
-- POSSP-5157     - Gilvano Santos		  - #28# - 31/03/2021 - Nota Técnica 2020.006 somente para NFC-e ou NF-e
-- SUSTSP-2145    - Fábio Cunha/Fillipi/Wendel - #27# - 21/01/2021 - Tratamento para venda mista
-- SUSTSP-1949    - Wendel Crespigio      - #26# - 07/12/2020 - Tratamento para venda mista com troco V5
-- SUSTSP-1709    - Fillipi Ramos/Wendel  -      - 06/11/2020 - Incluído terminal nas tabelas onde se precisava e também incluído GUID_VENDA_SAT no tipo V5 pra em nenhuma hipotese pegar LANCAMENTO_CAIXA repetidos.
-- POSSP-3855     - ANDRE ARTUZO          - #25# - 19/09/2020 - Correcao em nota fiscal de venda com troca e devolucao em dinheiro. 
-- SUSTSP-475     - ANDRE ARTUZO		  - #24# - 11/06/2020 - Ajuste pois gerou efeito colateral na correÃ§Ã£o #23# 	
-- POSSP-3251     - ANDRE ARTUZO		  - #23# - 08/06/2020 - CorreÃ§Ã£o para nÃ£o gerar valor do Frete no pagamento em Ship sem Frete. 	
-- MD 8409        - EDER SILVA		      - #22# - 18/11/2019 - CorreÃ§Ã£o emissÃ£o de nota com Vitrine - com e sem 'venda a ordem'.
-- MD 2853        - DIEGO MORENO		  - #21# - 07/06/2019 - Melhoria do tratamento anterior devido a ter gerado efeito colateral.
-- MD 2595        - Wendel Crespigio      - #20# - 05/06/2019 - InclusÃ£o de codigo para emissÃ£o de Venda Ã  Ordem.
-- MD 1800        - Wesley Batista        - #19# - 22/05/2019 - Ajuste para evitar lanÃ§ar troco incorreto em uma nota de venda onde existe uma troca e o produto trocado e com valor acima do que estÃ£o sendo levados pelo cliente. - Efetuada uma alteraÃ§Ã£o retirando impacto de outras modificaÃ§Ãµes na view - acordado entre Wendel/Diego/Edson/Wesley
-- DM 113415      - Gilvano Santos        - #18# - 23/03/2019 - Reconhecer a forma de pagamento Vale Troca como Credito Loja
-- DM 109532      - Eder Silva            - #17# - 14/02/2019 - NF-e 4.0 - Removido o meio de pagamento 14 (Duplicata Mercantil) conforme NT 2016.002 VersÃ£o 1.61 e alinhado com Roberto Beda.
-- DM 98241       - Eder Silva            - #16# - 23/10/2018 - NF-e 4.0 - CorreÃ§Ã£o no vinculo entre notas de venda e notas vinculadas (natureza 5929). 
-- DM 76917       - Wendel Crespigio      - #15# - 28/05/2018 - NF-e 4.0 - Tratamento para melhoria de performace 
-- DM 73654       - Fabio Santos/Artuzo   - #14# - 09/05/2018 - NF-e 4.0 - Ajuste para incluir a sÃ©rie da nota nos joins.  
-- DM 72869       - Eder Silva            - #13# - 02/05/2018 - NF-e 4.0 - CorreÃ§Ã£o para informar o cÃ³digo correto da BANDEIRA.  
-- DM 70256       - Wendel Crespigio      - #12# - 12/04/2018 - NF-e 4.0 - CORREÃ‡ÃƒO PARA TROCA MAIOR QUE A VENDA valor troco  
-- DM 70256       - Wendel Crespigio      - #11# - 12/04/2018 - NF-e 4.0 - CORREÃ‡ÃƒO PARA TROCA MAIOR QUE A VENDA valor troco  
-- DM 70256       - Wendel Crespigio      - #10# - 12/04/2018 - NF-e 4.0 - Verificando valores negatios para mais tipos de pagamentos   
-- DM 70547       - Wendel Crespigio      - #9#  - 11/04/2018 - NF-e 4.0 - Nota fiscal com troca     
-- DM 68765       - Wendel Crespigio      - #8#  - 28/03/2018 - NF-e 4.0 - Nota com arredontar o arredondar tem que entrar como troco conforme verificaÃ§Ã£o SEFAZ  
-- DM 67298       - Wendel Crespigio      - #7#  - 14/03/2018 - NF-e 4.0 - NFCe - Acima de 20 mil retorno de NFe (Valor do troco incorreto)  
-- DM 66767       - Wendel Crespigio      - #6#  - 13/03/2018 - NF-e 4.0 - Tratamento para quando o parametro Utilizar ticket como nÃºmero de cupom estiver habilidato   
-- DM 62953       - Diego Moreno          - #5#  - 20/02/2018 - NF-e 4.0 - Melhoria para considerar vendas com o parÃ¢metro "Utilizar ticket como nÃºmero de cupom" onde a coluna NUMERO_CUPOM_FISCAL fica preenchida para uma NF-e de uma NFC-e.  
-- DM 61973       - Wendel Crespigio      - #4#  - 09/02/2018 - NF-e 4.0 - CorreÃ§Ã£o para nota fiscal de transferencia.    
-- DM 62619       - Wendel Crespigio      - #3#  - 09/02/2018 - NF-e 4.0 - CorreÃ§Ã£o na validaÃ§Ã£o de notas vinculadas para NFC-e e Sat para geraÃ§Ã£o das tags de pagamento.  
-- DM 61554       - Wendel Crespigio      - #2#  - 06/02/2018 - NF-e 4.0 - Melhoria para que cada tipo de nota seja identificado no filtro da view.  
-- DM 58430       - Diego Moreno          - #1#  - 02/01/2018 - NF-e 4.0 - CriaÃ§Ã£o da view para isolar a identificaÃ§Ã£o das informaÃ§Ãµes das parcelas de venda para NF-e.      
AS      
/********************************************* NOTA FISCAL DE VENDA VINCULADA*****************************************************/    
SELECT   
 'V1' AS TIPO_NOTA,  /*#4#*/  
 LOJA.FILIAL,PGTO.NUMERO_FISCAL_VINCULADA AS NF, PGTO.SERIE_NF_VINCULADA AS SERIE_NF, PARCELA.PARCELA,      
 (CASE 
	WHEN PARCELA.TIPO_PGTO IN ('D','M')		THEN '01'      
	WHEN PARCELA.TIPO_PGTO IN ('C','P')     THEN '02'      
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I') THEN '03'      
	WHEN PARCELA.TIPO_PGTO IN ('E','K')     THEN '04'      
	--WHEN PARCELA.TIPO_PGTO IN ('#','@','N','>') THEN '05'      --#18# --#28#
	WHEN PARCELA.TIPO_PGTO IN ('#','N','>') THEN '05' --#28#
	WHEN PARCELA.TIPO_PGTO = '@'			THEN '12' --#28#
	--WHEN PARCELA.TIPO_PGTO = '&'			THEN '12' --#28#  
	WHEN PARCELA.TIPO_PGTO = '&'			THEN '15' --#28# 
  --WHEN PARCELA.TIPO_PGTO = 'J'			THEN '14'      -- #17#
    when PARCELA.TIPO_PGTO = '+' and (GETDATE() < CONVERT(DATETIME, Q.VALOR_ATUAL,103)) THen '05' --#28#
	WHEN PARCELA.TIPO_PGTO = '+' AND C.MODALIDADE_QR = 3 THEN '17' --#28#
	WHEN PARCELA.TIPO_PGTO = '+' AND C.MODALIDADE_QR != 3 THEN '18' --#28#
	WHEN PARCELA.TIPO_PGTO = 'T'			THEN '90'      
	--ELSE '99' -- #28#
	ELSE '05'   --#28#    
 END) AS INFO_PGTO,  
 CASE WHEN PARCELA.VALOR > 0 THEN PARCELA.VALOR ELSE 0 END AS VALOR,  --#8# 
 CASE WHEN NOTA.PGTO_INTERMEDIADOR = 1 AND R.ID_INTERMEDIADOR IS NOT NULL 
	THEN R.CNPJ ELSE D.CNPJ_CREDENCIADORA END AS CNPJ_CREDENCIADORA, --#28#           
 (CASE WHEN PARCELA.TIPO_PGTO IN ('K','I')  THEN 1       
   WHEN PARCELA.TIPO_PGTO IN ('E','B','A')  THEN 2       
   ELSE NULL   
 END) AS TIPO_INTEGRA,       
  -- #13# - InÃ­cio  
  -- Passou a validar o nome da Administradora da tabela 'LX_ADMINISTRADORAS_CARTAO'  
 (CASE 
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%VISA%'				THEN '01'      
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%MASTERCARD%'			THEN '02'       
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%AMERICAN EXPRESS%'	THEN '03'      
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%SOROCRED%'			THEN '04'      
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%DINERS%'				THEN '05'       
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%ELO%'				THEN '06'       
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%HIPERCARD%'			THEN '07'       
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%AURA%'				THEN '08'       
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%CABAL%'				THEN '09'       
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K')														THEN '99'       
	ELSE NULL   
 END) BANDEIRA,      
  -- #13# - Fim    
    (CASE WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') THEN PARCELA.NUMERO_APROVACAO_CARTAO ELSE NULL END) AS AUTORIZACAO,      
    ISNULL((PARCELA.TROCO ),0) +   
  CASE WHEN PARCELA.TIPO_PGTO IN ('^','&','@','R','V','>') AND PARCELA.VALOR < 0 AND PARCELA.TROCO = 0 THEN ABS(PARCELA.VALOR)     --#18#
    WHEN PARCELA.TIPO_PGTO IN ('D') AND PARCELA.VALOR < 0 AND PARCELA.TROCO = 0                 THEN ABS(PARCELA.VALOR) -- AND PARCELA.VALOR = > 0 AND PARCELA.TROCO = 0  
    ELSE 0   
  END AS TROCO  --#8# #10# #11#    
FROM LOJA_VENDA_PGTO PGTO  with (nolock)  --#15#  
  INNER JOIN LOJA_VENDA_PARCELAS PARCELA   with (nolock)   --#15#
     ON PGTO.CODIGO_FILIAL = PARCELA.CODIGO_FILIAL  AND     
                       PGTO.LANCAMENTO_CAIXA = PARCELA.LANCAMENTO_CAIXA AND   
                       PGTO.TERMINAL = PARCELA.TERMINAL      
  INNER JOIN LOJAS_VAREJO LOJA  with (nolock) --#15#      
                    ON PARCELA.CODIGO_FILIAL = LOJA.CODIGO_FILIAL      
  LEFT JOIN ADMINISTRADORAS_CARTAO C  with (nolock) --#15#   
                    ON C.CODIGO_ADMINISTRADORA = PARCELA.CODIGO_ADMINISTRADORA      
  LEFT JOIN CREDENCIADORA_CARTAO D with (nolock)  --#15#
                    ON D.COD_CREDENCIADORA = PARCELA.COD_CREDENCIADORA      
  INNER JOIN LOJA_NOTA_FISCAL NOTA   with (nolock) --#15#
                    ON NOTA.CODIGO_FILIAL = PGTO.CODIGO_FILIAL AND  
                       NOTA.NF_NUMERO = PGTO.NUMERO_FISCAL_VINCULADA AND  
                       NOTA.SERIE_NF = PGTO.SERIE_NF_VINCULADA  
  LEFT JOIN LX_ADMINISTRADORAS_CARTAO E  with (nolock) -- #13#  #15#
     ON LTRIM(RTRIM(C.LX_COD_ADMINISTRADORA)) = LTRIM(RTRIM(E.LX_COD_ADMINISTRADORA))  -- #13#  
  inner join W_PARAMETROS_LOJA Q WITH (NOLOCK) on PGTO.CODIGO_FILIAL = Q.CODIGO_FILIAL and PARAMETRO = 'DATA_INI_NT2020_006' --#28#
  LEFT JOIN LOJA_INTERMEDIADORES_TRANSACAO R WITH (NOLOCK) --#28#
			ON NOTA.ID_INTERMEDIADOR = R.ID_INTERMEDIADOR AND R.INATIVO = 0 --#28#

          /*#2#*/  
WHERE ((PGTO.NUMERO_CUPOM_FISCAL IS NOT NULL AND  
          PGTO.NUMERO_FISCAL_VENDA IS  NULL AND --#3#  
          PGTO.NUMERO_FISCAL_VINCULADA IS NOT NULL AND  
          ISNULL(PGTO.ID_EQUIPAMENTO , '') = '')  
          OR  
          /*#2#*/  
          (PGTO.NUMERO_CUPOM_FISCAL IS NULL AND  
          PGTO.NUMERO_FISCAL_VENDA IS NOT NULL AND   
          PGTO.NUMERO_FISCAL_VINCULADA IS NOT NULL AND   
          ISNULL(PGTO.ID_EQUIPAMENTO , '') = '')  
          OR  
          (PGTO.NUMERO_CUPOM_FISCAL IS NOT NULL AND --#5#  
          PGTO.NUMERO_FISCAL_VENDA IS  NOT NULL AND --#3#  
          PGTO.NUMERO_FISCAL_VINCULADA IS NOT NULL AND --#5#  
          ISNULL(PGTO.ID_EQUIPAMENTO , '') = '') --#5#  
          )  
          
/********************************************* NOTA FISCAL DE VENDA VINCULADA*****************************************************/    
UNION  ALL 
  
SELECT   
 'V2' as TIPO_NOTA,  /*#4#*/  
 LOJA.FILIAL,PGTO.NUMERO_FISCAL_VENDA AS NF, PGTO.SERIE_NF_SAIDA AS SERIE_NF, PARCELA.PARCELA, -- #15#     
 (CASE 
	WHEN PARCELA.TIPO_PGTO IN ('D','M')		THEN '01'      
	WHEN PARCELA.TIPO_PGTO IN ('C','P')		THEN '02'      
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I') THEN '03'      
	WHEN PARCELA.TIPO_PGTO IN ('E','K')		THEN '04'      
	WHEN PARCELA.TIPO_PGTO IN ('#','N','>') THEN '05' --#28#
	WHEN PARCELA.TIPO_PGTO = '@'			THEN '12' --#28#
	--WHEN PARCELA.TIPO_PGTO = '&'			THEN '12' --#28#  
	WHEN PARCELA.TIPO_PGTO = '&'			THEN '15' --#28# 
	--WHEN PARCELA.TIPO_PGTO = 'J'			THEN '14' --#17#
	when PARCELA.TIPO_PGTO = '+' and (GETDATE() < CONVERT(DATETIME, Q.VALOR_ATUAL,103)) THen '05' --#28#
	WHEN PARCELA.TIPO_PGTO = '+' AND C.MODALIDADE_QR = 3 THEN '17' --#28#
	WHEN PARCELA.TIPO_PGTO = '+' AND C.MODALIDADE_QR != 3 THEN '18' --#28#
	WHEN PARCELA.TIPO_PGTO = 'T'			THEN '90'      
	--ELSE '99' -- #28#
	ELSE '05'   --#28#       
 END) AS INFO_PGTO,       
 CASE WHEN PARCELA.VALOR > 0 THEN PARCELA.VALOR ELSE 0 END AS VALOR, --#8#          
 --(D.CNPJ_CREDENCIADORA) AS CNPJ_CREDENCIADORA,   --#28#
 CASE WHEN NOTA.PGTO_INTERMEDIADOR = 1 AND R.ID_INTERMEDIADOR IS NOT NULL 
	THEN R.CNPJ ELSE D.CNPJ_CREDENCIADORA END AS CNPJ_CREDENCIADORA, --#28#        
 (CASE WHEN PARCELA.TIPO_PGTO IN ('K','I')  THEN 1       
   WHEN PARCELA.TIPO_PGTO IN ('E','B','A') THEN 2       
   ELSE NULL   
 END) AS TIPO_INTEGRA,  
  -- #13# - InÃ­cio  
  -- Passou a validar o nome da Administradora da tabela 'LX_ADMINISTRADORAS_CARTAO'  
 (CASE 
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%VISA%'				THEN '01'      
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%MASTERCARD%'			THEN '02'       
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%AMERICAN EXPRESS%'	THEN '03'      
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%SOROCRED%'			THEN '04'      
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%DINERS%'				THEN '05'       
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%ELO%'				THEN '06'       
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%HIPERCARD%'			THEN '07'       
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%AURA%'				THEN '08'       
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%CABAL%'				THEN '09'       
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K')														THEN '99'       
	ELSE NULL   
   END) BANDEIRA,      
  -- #13# - Fim  
 (CASE WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') THEN PARCELA.NUMERO_APROVACAO_CARTAO ELSE NULL END) AS AUTORIZACAO,      
 ISNULL((PARCELA.TROCO ),0) +   
  CASE WHEN PARCELA.TIPO_PGTO IN ('^','&','@','R','V','>') AND PARCELA.VALOR < 0 AND PARCELA.TROCO = 0 THEN ABS(PARCELA.VALOR)     --#18#
    WHEN PARCELA.TIPO_PGTO IN ('D') AND PARCELA.VALOR < 0 AND PARCELA.TROCO = 0     THEN ABS(PARCELA.VALOR) -- AND PARCELA.VALOR = > 0 AND PARCELA.TROCO = 0  
    ELSE 0   
  END AS TROCO --#8#  #10# #11#    
FROM LOJA_VENDA_PGTO PGTO   with (nolock)  --#15# 
  INNER JOIN LOJA_VENDA_PARCELAS PARCELA  with (nolock)  --#15#
     ON PGTO.CODIGO_FILIAL = PARCELA.CODIGO_FILIAL  AND     
     PGTO.LANCAMENTO_CAIXA = PARCELA.LANCAMENTO_CAIXA AND   
     PGTO.TERMINAL = PARCELA.TERMINAL    
  INNER JOIN LOJA_VENDA VENDA  with (nolock)  --#25#  
     ON PGTO.CODIGO_FILIAL = VENDA.CODIGO_FILIAL  AND       
     PGTO.LANCAMENTO_CAIXA = VENDA.LANCAMENTO_CAIXA AND     
     PGTO.TERMINAL = VENDA.TERMINAL      	   
  INNER JOIN LOJAS_VAREJO LOJA with (nolock)     --#15#
     ON PARCELA.CODIGO_FILIAL = LOJA.CODIGO_FILIAL      
  LEFT JOIN ADMINISTRADORAS_CARTAO C  with (nolock) --#15#
     ON C.CODIGO_ADMINISTRADORA = PARCELA.CODIGO_ADMINISTRADORA      
  LEFT JOIN CREDENCIADORA_CARTAO D   with (nolock) --#15#
     ON D.COD_CREDENCIADORA = PARCELA.COD_CREDENCIADORA       
  INNER JOIN LOJA_NOTA_FISCAL NOTA  with (nolock)  --#15#
                    ON NOTA.CODIGO_FILIAL = PGTO.CODIGO_FILIAL AND  
     NOTA.NF_NUMERO = PGTO.NUMERO_FISCAL_VENDA AND  
     NOTA.SERIE_NF = PGTO.SERIE_NF_SAIDA  
  LEFT JOIN LX_ADMINISTRADORAS_CARTAO E  with (nolock)-- #13#  
     ON LTRIM(RTRIM(C.LX_COD_ADMINISTRADORA)) = LTRIM(RTRIM(E.LX_COD_ADMINISTRADORA))  -- #13#  
    /*#2#*/ 
    /*#SUSTSP-1709# - Início*/
	--LEFT JOIN (Select A.LANCAMENTO_CAIXA ,UV.CODIGO_FILIAL,UV.TICKET,UV.DATA_VENDA,VALOR_ORIGINAL_PEDIDO,CONFIRMADO,CANCELADO
	 LEFT JOIN (Select A.TERMINAL,A.LANCAMENTO_CAIXA ,UV.CODIGO_FILIAL,UV.TICKET,UV.DATA_VENDA,VALOR_ORIGINAL_PEDIDO,CONFIRMADO,CANCELADO
	   DESCONTO_LOJA,CANCELADO,FRETE From UNICO_VITRINE_PEDIDO UV  with (nolock)
       INNER JOIN LOJA_VENDA A with (nolock)
	on A.TICKET = UV.TICKET 
	   And A.DATA_VENDA = UV.DATA_VENDA 
	   And A.CODIGO_FILIAL =UV.CODIGO_FILIAL ) VV --#20#
	on PARCELA.LANCAMENTO_CAIXA = VV.LANCAMENTO_CAIXA  
	   --and PARCELA.CODIGO_FILIAL =  VV.CODIGO_FILIAL
	   and PARCELA.CODIGO_FILIAL =  VV.CODIGO_FILIAL and PARCELA.TERMINAL = VV.TERMINAL
	inner join W_PARAMETROS_LOJA Q WITH (NOLOCK) on PGTO.CODIGO_FILIAL = Q.CODIGO_FILIAL and PARAMETRO = 'DATA_INI_NT2020_006' --#28#
	LEFT JOIN LOJA_INTERMEDIADORES_TRANSACAO R WITH (NOLOCK) --#28#
			ON NOTA.ID_INTERMEDIADOR = R.ID_INTERMEDIADOR AND R.INATIVO = 0 --#28#
/*#SUSTSP-1709# - Fim*/
WHERE ((PGTO.ID_EQUIPAMENTO IS NOT NULL AND  
    PGTO.NUMERO_FISCAL_VENDA IS NOT NULL AND  
          PGTO.NUMERO_CUPOM_FISCAL IS NOT NULL )  
          OR  
          (PGTO.NUMERO_FISCAL_VENDA IS NOT NULL AND   
          ISNULL(PGTO.ID_EQUIPAMENTO , '') = '' AND   
          --PGTO.NUMERO_CUPOM_FISCAL IS NULL AND  #6#  
          PGTO.NUMERO_FISCAL_VINCULADA IS NULL))
		  AND isnull(VV.VALOR_ORIGINAL_PEDIDO,0) = 0  --#20# #21#
		  AND ISNULL(PARCELA.CHEQUE_DIGITO,'') <> 'N' --#23# #24#
		  AND ISNULL(VENDA.VALOR_TIKET,0) > 0 --#25#
    /*#2#*/  
UNION ALL  
     
SELECT     
 'O'			AS TIPO_NOTA,  /*#4#*/   
 B.FILIAL,       
 A.NF_NUMERO	AS NF,       
 A.SERIE_NF, 1	AS PARCELA,
-- #30# - Início --
	   CASE WHEN A.TIPO_ORIGEM = 17  THEN '05' 			  					 
			ELSE '90'		     						
	   END  AS INFO_PGTO,  
-- #30# - Fim --     
 A.VALOR_TOTAL	AS VALOR,      
 ''				AS CNPJ_CREDENCIADORA,      
 '2'			AS TIPO_INTEGRA,       
 '99'			AS BANDEIRA,      
 ''				AS AUTORIZACAO,      
 0				AS TROCO        
FROM LOJA_NOTA_FISCAL A with (nolock)     --#15#
  INNER JOIN LOJAS_VAREJO B with (nolock)     --#15#
     ON A.CODIGO_FILIAL = B.CODIGO_FILIAL      
  LEFT JOIN LOJA_VENDA_PGTO  C  with (nolock)   --#15# 
     ON A.CODIGO_FILIAL = C.CODIGO_FILIAL AND    
     -- #16# - InÃ­cio
	 --(A.NF_NUMERO = C.NUMERO_FISCAL_VENDA OR A.NF_NUMERO = C.NUMERO_FISCAL_VINCULADA ) AND  
     --(A.SERIE_NF = C.SERIE_NF_VINCULADA OR A.SERIE_NF = C.SERIE_NF_SAIDA) --#14#  
	 (A.NF_NUMERO = C.NUMERO_FISCAL_VENDA     and A.SERIE_NF = C.SERIE_NF_SAIDA) or   
	 (A.NF_NUMERO = C.NUMERO_FISCAL_VINCULADA and A.SERIE_NF = C.SERIE_NF_VINCULADA)  
     -- #16# - Fim
WHERE C.NUMERO_FISCAL_VINCULADA IS NULL AND    
  C.NUMERO_FISCAL_VENDA     IS NULL AND  --#7#    
  --C.NUMERO_FISCAL_VINCULADA IS NULL   AND #7#  
  A.TIPO_ORIGEM <> 1 /*#2#*/  
  
UNION ALL -- TRATAMENTO PARA FAZER O VALOR DA TROCA COM DINHEIRO COM TIPO OUTROS #9#  
  
SELECT     
 'V3'			AS TIPO_NOTA,  /*#4#*/   
 B.FILIAL,       
 A.NF_NUMERO	AS NF,       
 A.SERIE_NF,  
 PARCELA.PARCELA +1 AS PARCELA,  
--'99'			AS INFO_PGTO, --#28#    
 '05'			AS INFO_PGTO, --#28#        
 CASE WHEN D.VALOR_TIKET < 0 THEN D.VALOR_VENDA_BRUTA  ELSE D.VALOR_TROCA END AS VALOR,  --#19# 
 --D.VALOR_VENDA_BRUTA  AS VALOR ,      
 NULL			AS CNPJ_CREDENCIADORA,      
 NULL			AS TIPO_INTEGRA,       
 NULL			AS BANDEIRA,      
 NULL			AS AUTORIZACAO,      
 0				AS TROCO        
FROM LOJA_NOTA_FISCAL A  with (nolock)   --#15# 
  INNER JOIN LOJAS_VAREJO B  with (nolock) --#15#     
     ON A.CODIGO_FILIAL = B.CODIGO_FILIAL      
  LEFT JOIN LOJA_VENDA_PGTO  C with (nolock)   --#15#  
     ON A.CODIGO_FILIAL = C.CODIGO_FILIAL AND
     -- #16# - InÃ­cio	     
	 --(A.NF_NUMERO = C.NUMERO_FISCAL_VENDA OR A.NF_NUMERO = C.NUMERO_FISCAL_VINCULADA ) AND  
     --(A.SERIE_NF = C.SERIE_NF_VINCULADA OR A.SERIE_NF = C.SERIE_NF_SAIDA) --#14#  
	 (A.NF_NUMERO = C.NUMERO_FISCAL_VENDA     and A.SERIE_NF = C.SERIE_NF_SAIDA) or   
	 (A.NF_NUMERO = C.NUMERO_FISCAL_VINCULADA and A.SERIE_NF = C.SERIE_NF_VINCULADA)  
     -- #16# - Fim
  INNER JOIN LOJA_VENDA D   with (nolock) --#15#
     ON A.CODIGO_FILIAL = D.CODIGO_FILIAL AND   
     C.LANCAMENTO_CAIXA = D.LANCAMENTO_CAIXA AND   
     C.TERMINAL = D.TERMINAL  
  INNER JOIN (SELECT MAX(PARCELA) AS PARCELA ,CODIGO_FILIAL,LANCAMENTO_CAIXA,TERMINAL   
      FROM LOJA_VENDA_PARCELAS with (nolock) /*#12#  #15#  */ GROUP BY CODIGO_FILIAL,TERMINAL,LANCAMENTO_CAIXA ) AS PARCELA  
     ON D.CODIGO_FILIAL = PARCELA.CODIGO_FILIAL   AND     
     D.LANCAMENTO_CAIXA = PARCELA.LANCAMENTO_CAIXA AND   
     D.TERMINAL = PARCELA.TERMINAL
  /*#SUSTSP-1709# - Início*/
  --LEFT JOIN (Select A.LANCAMENTO_CAIXA ,UV.CODIGO_FILIAL,UV.TICKET,UV.DATA_VENDA,VALOR_ORIGINAL_PEDIDO,CONFIRMADO,CANCELADO
  LEFT JOIN (Select A.TERMINAL,A.LANCAMENTO_CAIXA ,UV.CODIGO_FILIAL,UV.TICKET,UV.DATA_VENDA,VALOR_ORIGINAL_PEDIDO,CONFIRMADO,CANCELADO
		DESCONTO_LOJA,CANCELADO,FRETE 
	FROM UNICO_VITRINE_PEDIDO UV WITH (NOLOCK)
  INNER JOIN LOJA_VENDA A WITH (NOLOCK)
	on A.TICKET = UV.TICKET 
	  And A.DATA_VENDA = UV.DATA_VENDA 
	  And A.CODIGO_FILIAL =UV.CODIGO_FILIAL
	  And A.DATA_VENDA BETWEEN CONVERT(CHAR(8),GETDATE()-30,112) AND CONVERT(CHAR(8),GETDATE(),112)) VV --#20#
	on PARCELA.LANCAMENTO_CAIXA =VV.LANCAMENTO_CAIXA 
	  And PARCELA.CODIGO_FILIAL=VV.CODIGO_FILIAL 
	  --And D.DATA_VENDA = VV.DATA_VENDA    
	  And D.DATA_VENDA = VV.DATA_VENDA and D.TERMINAL = VV.TERMINAL
/*#SUSTSP-1709# - Fim*/   
	WHERE D.VALOR_TROCA > 0 
	   AND isnull(VV.VALOR_ORIGINAL_PEDIDO,0) = 0 --#20# #21#

/************************************************ NOTA FISCAL DE VENDA À ORDEM (VITRINE) ********************************************************************************/

UNION ALL --#20#
   
SELECT 
	A.TIPO_NOTA, FILIAL, NF, SERIE_NF, PARCELA, INFO_PGTO, VALOR, MAX(CNPJ_CREDENCIADORA) AS CNPJ_CREDENCIADORA, 
	MAX(TIPO_INTEGRA) AS TIPO_INTEGRA, MAX(BANDEIRA) AS BANDEIRA, MAX(AUTORIZACAO) AS AUTORIZACAO, MAX(TROCO) AS TROCO
FROM(
	SELECT 
		'V4' AS TIPO_NOTA, 
		--LOJA.FILIAL, PGTO.NUMERO_FISCAL_VENDA AS NF, PGTO.SERIE_NF_SAIDA AS SERIE_NF, '01' AS PARCELA, --#29#
		LOJA.FILIAL, PGTO.NUMERO_NF_ORDEM AS NF, PGTO.SERIE_NF_ORDEM AS SERIE_NF, --'01' AS PARCELA , --#29# #32#
		PARCELA_ECOM.PARCELA AS PARCELA, --#32#
		--'99' AS INFO_PGTO, --#28#    		
		--#29# - Início
		--'05' AS INFO_PGTO, --#28#  
		CASE 
			WHEN PARCELA_ECOM.TIPO_PGTO IN ('D','M')	THEN '01' --#32#     
			WHEN PARCELA_ECOM.TIPO_PGTO IN ('C','P')    THEN '02' --#32#     
			WHEN PARCELA_ECOM.TIPO_PGTO IN ('A','B','I')THEN '03' --#32#
			WHEN PARCELA_ECOM.TIPO_PGTO IN ('E','K')    THEN '04' --#32#     
			WHEN PARCELA_ECOM.TIPO_PGTO IN ('#','N','>')THEN '05' --#32#
			WHEN PARCELA_ECOM.TIPO_PGTO = '@'			THEN '12' --#32#
			WHEN PARCELA_ECOM.TIPO_PGTO = '&'			THEN '15' --#32#
			WHEN PARCELA_ECOM.TIPO_PGTO = '+' AND (GETDATE() < CONVERT(DATETIME, Q.VALOR_ATUAL,103)) THEN '05' --#32#
			WHEN PARCELA_ECOM.TIPO_PGTO = '+' AND C.MODALIDADE_QR = 3								 THEN '17' --#32#
			WHEN PARCELA_ECOM.TIPO_PGTO = '+' AND C.MODALIDADE_QR != 3								 THEN '18' --#32#
			--WHEN PARCELA_ECOM.TIPO_PGTO = 'T'			THEN '90' --#32# 
			ELSE '05'
		END AS INFO_PGTO,		
		--VALOR_ORIGINAL_PEDIDO - ISNULL(NOTA.DESCONTO,0) VALOR, 
		--PGTO.TOTAL_VENDA + VALOR_ORIGINAL_PEDIDO - ISNULL(NOTA.DESCONTO,0) VALOR, --#32#
		PARCELA_ECOM.VALOR AS VALOR, --#32#
		--#29# - Fim
		--(D.CNPJ_CREDENCIADORA) AS CNPJ_CREDENCIADORA, #28#
		CASE 
			WHEN NOTA.PGTO_INTERMEDIADOR = 1 AND R.ID_INTERMEDIADOR IS NOT NULL THEN R.CNPJ 
			ELSE D.CNPJ_CREDENCIADORA 
		END AS CNPJ_CREDENCIADORA, --#28#       
		CASE 
			WHEN PARCELA.TIPO_PGTO IN ('K','I')		THEN 1       
			WHEN PARCELA.TIPO_PGTO IN ('E','B','A')	THEN 2       
			ELSE NULL   
		END AS TIPO_INTEGRA,  
		CASE 
			WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%VISA%'				THEN '01'      
			WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%MASTERCARD%'			THEN '02'       
			WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%AMERICAN EXPRESS%'	THEN '03'      
			WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%SOROCRED%'			THEN '04'      
			WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%DINERS%'				THEN '05'       
			WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%ELO%'				THEN '06'       
			WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%HIPERCARD%'			THEN '07'       
			WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%AURA%'				THEN '08'       
			WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%CABAL%'				THEN '09'       
			WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K')														THEN '99'       
			ELSE NULL   
		END AS BANDEIRA,      
		CASE 
			WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') THEN PARCELA.NUMERO_APROVACAO_CARTAO 
			ELSE NULL 
		END AS AUTORIZACAO,      
		
		--#32# - Início
		--ISNULL((PARCELA.TROCO ),0) +   
		--CASE			
		--	WHEN PARCELA.TIPO_PGTO IN ('^','&','@','R','V','>') AND PARCELA.VALOR < 0 AND PARCELA.TROCO = 0 THEN ABS(PARCELA.VALOR)     --#18#
		--	WHEN PARCELA.TIPO_PGTO IN ('D') AND PARCELA.VALOR < 0 AND PARCELA.TROCO = 0						THEN ABS(PARCELA.VALOR) 	
		--	WHEN PARCELA.VALOR > PGTO.TOTAL_VENDA															THEN PGTO.TOTAL_VENDA 				
		--	ELSE 0   
		--END AS TROCO 		
		PARCELA_ECOM.TROCO AS TROCO
		--#32# - Fim
	FROM 
		LOJA_VENDA_PGTO PGTO					WITH (NOLOCK)  
		--#32# - Início				
		INNER JOIN LOJA_VENDA_PARCELAS_ECOMMERCE PARCELA_ECOM	WITH (NOLOCK)  
			ON PARCELA_ECOM.CODIGO_FILIAL = PGTO.CODIGO_FILIAL AND     
			PARCELA_ECOM.LANCAMENTO_CAIXA = PGTO.LANCAMENTO_CAIXA AND   
			PARCELA_ECOM.TERMINAL = PGTO.TERMINAL			
		--INNER JOIN LOJA_VENDA_PARCELAS PARCELA	WITH (NOLOCK)  					
		LEFT JOIN LOJA_VENDA_PARCELAS PARCELA	WITH (NOLOCK)  
		--#32# - Fim
			ON PGTO.CODIGO_FILIAL = PARCELA.CODIGO_FILIAL AND     
			PGTO.LANCAMENTO_CAIXA = PARCELA.LANCAMENTO_CAIXA AND   
			PGTO.TERMINAL = PARCELA.TERMINAL AND
			PARCELA.TIPO_PGTO <> '\'  --#29# - Desconsidera parcelas do Vitrine, pois valor já está contido nas outras parcelas			
		INNER JOIN LOJAS_VAREJO LOJA			WITH (NOLOCK)     
			--ON PARCELA.CODIGO_FILIAL = LOJA.CODIGO_FILIAL --#32#
			ON PARCELA_ECOM.CODIGO_FILIAL = LOJA.CODIGO_FILIAL --#32#
		LEFT JOIN ADMINISTRADORAS_CARTAO C		WITH (NOLOCK) 
			ON C.CODIGO_ADMINISTRADORA = PARCELA.CODIGO_ADMINISTRADORA      
		LEFT JOIN CREDENCIADORA_CARTAO D		WITH (NOLOCK) 
			ON D.COD_CREDENCIADORA = PARCELA.COD_CREDENCIADORA       
		INNER JOIN LOJA_NOTA_FISCAL NOTA		WITH (NOLOCK)  
			ON NOTA.CODIGO_FILIAL = PGTO.CODIGO_FILIAL AND 			
			--NOTA.NF_NUMERO = PGTO.NUMERO_FISCAL_VENDA AND --#29# 
			--NOTA.SERIE_NF = PGTO.SERIE_NF_SAIDA AND --#29#
			NOTA.NF_NUMERO = PGTO.NUMERO_NF_ORDEM AND --#29#
			NOTA.SERIE_NF = PGTO.SERIE_NF_ORDEM AND --#29#			
			NOTA.NATUREZA_OPERACAO_CODIGO IN ('5120','5.120','6120','6.120')  --#22# SOMENTE NOTAS VENDA À ORDEM
		LEFT JOIN LX_ADMINISTRADORAS_CARTAO E	WITH (NOLOCK)
			ON LTRIM(RTRIM(C.LX_COD_ADMINISTRADORA)) = LTRIM(RTRIM(E.LX_COD_ADMINISTRADORA))  
		/*#SSSUSTSP-170901# - INÍCIO*/
		--LEFT JOIN (SELECT A.LANCAMENTO_CAIXA ,UV.CODIGO_FILIAL,UV.TICKET,UV.DATA_VENDA,VALOR_ORIGINAL_PEDIDO,(VALOR_ORIGINAL_PEDIDO - ISNULL(DESCONTO_LOJA,0)) VALOR_TOTAL ,CONFIRMADO,CANCELADO
		INNER JOIN ( 
					SELECT 
						A.TERMINAL, A.LANCAMENTO_CAIXA, UV.CODIGO_FILIAL, UV.TICKET, UV.DATA_VENDA, VALOR_ORIGINAL_PEDIDO,
						(VALOR_ORIGINAL_PEDIDO - ISNULL(DESCONTO_LOJA,0)) VALOR_TOTAL, CONFIRMADO, CANCELADO
						DESCONTO_LOJA, CANCELADO, FRETE 
					FROM 
						UNICO_VITRINE_PEDIDO UV WITH (NOLOCK)
						INNER JOIN LOJA_VENDA A  WITH (NOLOCK)
							ON  A.TICKET = UV.TICKET AND 
							A.DATA_VENDA = UV.DATA_VENDA AND 
							A.CODIGO_FILIAL = UV.CODIGO_FILIAL AND 					
							A.DATA_VENDA BETWEEN CONVERT(CHAR(8),GETDATE()-30,112) AND CONVERT(CHAR(8),GETDATE(),112)						
				  ) VV
			--ON PARCELA.LANCAMENTO_CAIXA = VV.LANCAMENTO_CAIXA 
			--#32# - Início
			--ON PARCELA.CODIGO_FILIAL = VV.CODIGO_FILIAL AND 
			--PARCELA.TERMINAL = VV.TERMINAL AND 
			--PARCELA.LANCAMENTO_CAIXA = VV.LANCAMENTO_CAIXA 
			ON PARCELA_ECOM.CODIGO_FILIAL = VV.CODIGO_FILIAL AND 
			PARCELA_ECOM.TERMINAL = VV.TERMINAL AND 
			PARCELA_ECOM.LANCAMENTO_CAIXA = VV.LANCAMENTO_CAIXA 
			--#32# - Fim
		INNER JOIN W_PARAMETROS_LOJA Q WITH (NOLOCK) --#29# - Faltou replicar este trecho do #28# para este select
			ON PGTO.CODIGO_FILIAL = Q.CODIGO_FILIAL AND 
			PARAMETRO = 'DATA_INI_NT2020_006' 
		LEFT JOIN LOJA_INTERMEDIADORES_TRANSACAO R WITH (NOLOCK) --#28#
			ON NOTA.ID_INTERMEDIADOR = R.ID_INTERMEDIADOR AND --#28#
			R.INATIVO = 0 --#28#
		/*#SUSTSP-1709# - FIM*/

	WHERE 
		--((PGTO.ID_EQUIPAMENTO IS NOT NULL AND PGTO.NUMERO_FISCAL_VENDA IS NOT NULL AND  PGTO.NUMERO_CUPOM_FISCAL IS NOT NULL) OR  --#29#
		-- (PGTO.NUMERO_FISCAL_VENDA IS NOT NULL AND   ISNULL(PGTO.ID_EQUIPAMENTO , '') = '' AND   PGTO.NUMERO_FISCAL_VINCULADA IS NULL))  --#29#
		PGTO.NUMERO_NF_ORDEM IS NOT NULL AND  --#29#
		PGTO.SERIE_NF_ORDEM  IS NOT NULL AND  --#29#
		ISNULL(VV.VALOR_ORIGINAL_PEDIDO,0) > 0  --#20#
	) A 
GROUP BY 
	A.TIPO_NOTA, FILIAL,NF, SERIE_NF, PARCELA, INFO_PGTO, VALOR --#20# #21#

/************************************************ NOTA FISCAL SEM VENDA ORDEM (5120,6120)  ********************************************************************************/
UNION ALL 
   
SELECT 
	A.TIPO_NOTA,FILIAL, NF, SERIE_NF, PARCELA, INFO_PGTO, VALOR, MAX(CNPJ_CREDENCIADORA) AS CNPJ_CREDENCIADORA, 
	MAX(TIPO_INTEGRA) AS TIPO_INTEGRA, MAX(BANDEIRA) AS BANDEIRA, MAX(AUTORIZACAO) AS AUTORIZACAO, MAX(TROCO) AS TROCO
FROM(
	SELECT 'V5' AS TIPO_NOTA,  --#22#
		LOJA.FILIAL, PGTO.NUMERO_FISCAL_VENDA AS NF, PGTO.SERIE_NF_SAIDA AS SERIE_NF, '01' AS PARCELA, 
		--'99' AS INFO_PGTO, --#28#    
		--#29# - Início
		--'05' AS INFO_PGTO, --#28#  
		CASE 
			WHEN PARCELA.TIPO_PGTO IN ('D','M')		THEN '01'      
			WHEN PARCELA.TIPO_PGTO IN ('C','P')     THEN '02'      
			WHEN PARCELA.TIPO_PGTO IN ('A','B','I') THEN '03'      
			WHEN PARCELA.TIPO_PGTO IN ('E','K')     THEN '04'      
			WHEN PARCELA.TIPO_PGTO IN ('#','N','>') THEN '05'
			WHEN PARCELA.TIPO_PGTO = '@'			THEN '12'
			WHEN PARCELA.TIPO_PGTO = '&'			THEN '15'
			WHEN PARCELA.TIPO_PGTO = '+' AND (GETDATE() < CONVERT(DATETIME, Q.VALOR_ATUAL,103)) THEN '05'
			WHEN PARCELA.TIPO_PGTO = '+' AND C.MODALIDADE_QR = 3								THEN '17'
			WHEN PARCELA.TIPO_PGTO = '+' AND C.MODALIDADE_QR != 3								THEN '18'
			WHEN PARCELA.TIPO_PGTO = 'T'			THEN '90'      
			ELSE '05'
		END AS INFO_PGTO,		
		--#29# - Fim
		--(VALOR_ORIGINAL_PEDIDO - ISNULL(NOTA.DESCONTO,0)) VALOR, --#22#
		--VV.VALOR_PAGO AS VALOR,  --#22#	--#31#	
		S.VALOR AS VALOR,  --#31#
		--(D.CNPJ_CREDENCIADORA) AS CNPJ_CREDENCIADORA, 
		CASE 
			WHEN NOTA.PGTO_INTERMEDIADOR = 1 AND R.ID_INTERMEDIADOR IS NOT NULL THEN R.CNPJ 
			ELSE D.CNPJ_CREDENCIADORA 
		END AS CNPJ_CREDENCIADORA, --#28#        
		CASE 
			WHEN PARCELA.TIPO_PGTO IN ('K','I')		THEN 1       
			WHEN PARCELA.TIPO_PGTO IN ('E','B','A')	THEN 2       
			ELSE NULL   
		END AS TIPO_INTEGRA,  
		CASE 
			WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%VISA%'				THEN '01'      
			WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%MASTERCARD%'			THEN '02'       
			WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%AMERICAN EXPRESS%'	THEN '03'      
			WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%SOROCRED%'			THEN '04'      
			WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%DINERS%'				THEN '05'       
			WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%ELO%'				THEN '06'       
			WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%HIPERCARD%'			THEN '07'       
			WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%AURA%'				THEN '08'       
			WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%CABAL%'				THEN '09'       
			WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K')														THEN '99'       
			ELSE NULL   
		END AS BANDEIRA,      
		CASE 
			WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') THEN PARCELA.NUMERO_APROVACAO_CARTAO 
			ELSE NULL 
		END AS AUTORIZACAO,      
		ISNULL((PARCELA.TROCO ),0) +   
			CASE 
				WHEN PARCELA.TIPO_PGTO IN ('^','&','@','R','V','>') AND PARCELA.VALOR < 0 AND PARCELA.TROCO = 0		THEN ABS(PARCELA.VALOR)     --#18#
				WHEN PARCELA.TIPO_PGTO IN ('D') AND PARCELA.VALOR < 0 AND PARCELA.TROCO = 0							THEN ABS(PARCELA.VALOR) 
				--WHEN VV.VALOR_TOTAL > 0 AND VV.VALOR_PAGO > 0														THEN VV.VALOR_TOTAL - VV.VALOR_PAGO  --#22# --#29#
				--WHEN VV.VALOR_TOTAL > 0																			THEN VV.VALOR_TOTAL  --#29# - Se tiver venda Vitrine, lança o valor como troco --#31#
				WHEN S.TROCO > 0																					THEN S.TROCO  --#31#
				ELSE 0   
			END AS TROCO 

	FROM 
		LOJA_VENDA_PGTO PGTO					WITH (NOLOCK)  
		INNER JOIN LOJA_VENDA_PARCELAS PARCELA  WITH (NOLOCK)  
			ON PGTO.CODIGO_FILIAL = PARCELA.CODIGO_FILIAL AND     
			PGTO.LANCAMENTO_CAIXA = PARCELA.LANCAMENTO_CAIXA AND   
			PGTO.TERMINAL = PARCELA.TERMINAL AND
			PARCELA.TIPO_PGTO <> '\' --#29# - Desconsidera parcelas do Vitrine, pois valor já está contido nas outras parcelas
		INNER JOIN LOJAS_VAREJO LOJA			WITH (NOLOCK)     
			ON PARCELA.CODIGO_FILIAL = LOJA.CODIGO_FILIAL      
		LEFT JOIN ADMINISTRADORAS_CARTAO C		WITH (NOLOCK) 
			ON C.CODIGO_ADMINISTRADORA = PARCELA.CODIGO_ADMINISTRADORA      
		LEFT JOIN CREDENCIADORA_CARTAO D		WITH (NOLOCK) 
			ON D.COD_CREDENCIADORA = PARCELA.COD_CREDENCIADORA       
		INNER JOIN LOJA_NOTA_FISCAL NOTA		WITH (NOLOCK)  
			ON NOTA.CODIGO_FILIAL = PGTO.CODIGO_FILIAL AND  
			NOTA.NF_NUMERO = PGTO.NUMERO_FISCAL_VENDA AND  
			NOTA.SERIE_NF = PGTO.SERIE_NF_SAIDA  AND
			NOTA.NATUREZA_OPERACAO_CODIGO NOT IN ('5120','5.120','6120','6.120')  --#22# NÃO SELECIONAR NOTAS DE VENDA À ORDEM
		LEFT JOIN LX_ADMINISTRADORAS_CARTAO E	WITH (NOLOCK)
			ON LTRIM(RTRIM(C.LX_COD_ADMINISTRADORA)) = LTRIM(RTRIM(E.LX_COD_ADMINISTRADORA))  		
		------LEFT JOIN (SELECT A.LANCAMENTO_CAIXA ,UV.CODIGO_FILIAL,UV.TICKET,UV.DATA_VENDA,VALOR_ORIGINAL_PEDIDO,(VALOR_ORIGINAL_PEDIDO - ISNULL(DESCONTO_LOJA,0)) VALOR_TOTAL ,CONFIRMADO,CANCELADO  --#22#
		--#31# - Início
		----LEFT JOIN ( SELECT A.LANCAMENTO_CAIXA, UV.CODIGO_FILIAL, UV.TICKET, UV.DATA_VENDA, VALOR_ORIGINAL_PEDIDO, 
		----				--VALOR_ORIGINAL_PEDIDO AS VALOR_PAGO, VALOR_ORIGINAL_PEDIDO AS VALOR_TOTAL, CONFIRMADO, CANCELADO --#22# ,#26#
		----				B.VALOR_PAGO AS VALOR_PAGO, VALOR_ORIGINAL_PEDIDO AS VALOR_TOTAL, CONFIRMADO, CANCELADO --#22# ,#26#
		----				DESCONTO_LOJA, CANCELADO, FRETE 
		----			FROM UNICO_VITRINE_PEDIDO UV WITH (NOLOCK)
		----				INNER JOIN LOJA_VENDA A WITH (NOLOCK)
		----					ON  A.TICKET = UV.TICKET AND 
		----					A.DATA_VENDA = UV.DATA_VENDA AND 
		----					A.CODIGO_FILIAL = UV.CODIGO_FILIAL AND 
		----					A.DATA_VENDA BETWEEN CONVERT(CHAR(8),GETDATE()-30,112) AND CONVERT(CHAR(8),GETDATE(),112)
		----				--#29# - Início
		----				INNER JOIN(
		----							SELECT VALOR, CODIGO_FILIAL, TERMINAL, LANCAMENTO_CAIXA
		----							FROM LOJA_VENDA_PARCELAS WITH (NOLOCK)
		----							WHERE TIPO_PGTO <> '\'
		----							GROUP BY CODIGO_FILIAL, TERMINAL, LANCAMENTO_CAIXA
		----					) B							
		----					ON A.CODIGO_FILIAL = B.CODIGO_FILIAL AND 
		----					A.TERMINAL = B.TERMINAL AND
		----					A.LANCAMENTO_CAIXA = B.LANCAMENTO_CAIXA							
		----				--#29# - Fim
		----		  ) VV
		----ON PARCELA.LANCAMENTO_CAIXA = VV.LANCAMENTO_CAIXA
		--#31# - Fim
		INNER JOIN W_PARAMETROS_LOJA Q WITH (NOLOCK) --#29# - Faltou replicar este trecho do #28# para este select
			ON PGTO.CODIGO_FILIAL = Q.CODIGO_FILIAL AND 
			PARAMETRO = 'DATA_INI_NT2020_006' 
		LEFT JOIN LOJA_INTERMEDIADORES_TRANSACAO R WITH (NOLOCK) --#28#
			ON NOTA.ID_INTERMEDIADOR = R.ID_INTERMEDIADOR AND R.INATIVO = 0 --#28#

		--#31# - Início
		INNER JOIN	LOJA_VENDA_PARCELAS_ECOMMERCE S  WITH (NOLOCK)
					ON	PARCELA.CODIGO_FILIAL = S.CODIGO_FILIAL AND
						PARCELA.TERMINAL = S.TERMINAL AND
						PARCELA.LANCAMENTO_CAIXA = S.LANCAMENTO_CAIXA AND								
						PARCELA.PARCELA = S.PARCELA
		--#31# - Fim
	WHERE(
			(PGTO.ID_EQUIPAMENTO IS NOT NULL AND  
			 PGTO.NUMERO_FISCAL_VENDA IS NOT NULL AND  
			 PGTO.NUMERO_CUPOM_FISCAL IS NOT NULL)  
			OR  
			(PGTO.NUMERO_FISCAL_VENDA IS NOT NULL AND   
			 ISNULL(PGTO.ID_EQUIPAMENTO , '') = '' AND   
			 PGTO.NUMERO_FISCAL_VINCULADA IS NULL)
		 ) --AND 
		 --ISNULL(VV.VALOR_ORIGINAL_PEDIDO,0) > 0 --#31#
		 --VV.VALOR_ORIGINAL_PEDIDO <= NOTA.VALOR_TOTAL  --#20# #27# --#31#
	) A 


GROUP BY A.TIPO_NOTA, FILIAL, NF, SERIE_NF, PARCELA, INFO_PGTO, VALOR --#20# #21#

