IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[LOJA_PROCESSOS_SP]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[LOJA_PROCESSOS_SP](
	[CODIGO_FILIAL] [char](6) NOT NULL,
	[ID] [int] IDENTITY NOT NULL,
	[DATA_ATUALIZACAO] [datetime] NOT NULL,
	[APLICACAO] [VARCHAR] (200) NOT NULL,
	[STATUS] [TINYINT],
	[USUARIO] [VARCHAR](30) NOT NULL,
	[VERSAO] [SMALLINT] NOT NULL,
	[BUILD] [TINYINT] NOT NULL,
	[HOTFIX] [TINYINT]  NULL,
	[DATA_PARA_TRANSFERENCIA] [datetime] NULL
 CONSTRAINT [XPKLOJA_PROCESSOS_SP] PRIMARY KEY NONCLUSTERED 
(
	[CODIGO_FILIAL] ASC,
	[ID] ASC
)ON [PRIMARY]
) ON [PRIMARY]
END