CREATE VIEW [dbo].[W_LINXPAY_FORMAS_PGTO]    
AS
	SELECT	D.OPERACAO_VENDA, 
			A.COD_FORMA_PGTO, 
			B.TIPO_PGTO, 
			C.CODIGO_ADMINISTRADORA, 
			C.ADMINISTRADORA, 
			C.COD_ADM_LINXPAY
	FROM LOJA_FORMAS_PGTO A 
	INNER JOIN LOJA_FORMAS_PARCELAS B ON A.COD_FORMA_PGTO = B.COD_FORMA_PGTO AND B.TIPO_PGTO IN ('A','E') AND B.PARCELA = 1
	INNER JOIN ( SELECT CASE WHEN TIPO_CARTAO = 0 THEN 'A' 
	                         WHEN TIPO_CARTAO = 1 THEN 'E'
					ELSE '' END AS TIPO_PGTO, CODIGO_ADMINISTRADORA, ADMINISTRADORA, COD_ADM_LINXPAY   
					FROM ADMINISTRADORAS_CARTAO WHERE COD_ADM_LINXPAY IS NOT NULL 
					AND TIPO_CARTAO IN (0,1) and INATIVO = 0 ) AS C ON B.TIPO_PGTO = C.TIPO_PGTO
	INNER JOIN LOJA_OPERACOES_PGTOS D ON A.COD_FORMA_PGTO = D.COD_FORMA_PGTO
	WHERE ISNULL(A.ATIVAR_EM, DATEADD(D, -1, getdate())) <= getdate() 
	AND ISNULL(A.DESATIVAR_EM, DATEADD(D, 1, getdate())) >= getdate()
	AND A.COD_FORMA_PGTO NOT IN ('##') --POSSP-7435