--NOVAS COLUNAS (LOJA)
IF NOT EXISTS(SELECT NAME FROM SYS.COLUMNS WHERE  OBJECT_ID = Object_id('DBO.CLIENTE_VAR_CONCEITOS') AND NAME = 'LIMITE_CREDITO')
BEGIN
    ALTER TABLE CLIENTE_VAR_CONCEITOS ADD LIMITE_CREDITO NUMERIC(14,2) NULL DEFAULT 'DEFAULT_0';
	exec('UPDATE CLIENTE_VAR_CONCEITOS SET LIMITE_CREDITO=0 WHERE LIMITE_CREDITO IS NULL') 
end; 
  

IF NOT EXISTS(SELECT NAME FROM   SYS.COLUMNS WHERE  OBJECT_ID = Object_id('DBO.LOJA_CAIXA_CONFERENCIA') AND NAME = 'VENDEDOR')  
begin
      ALTER TABLE LOJA_CAIXA_CONFERENCIA ADD VENDEDOR CHAR(4) NULL
end; 
