IF NOT EXISTS(SELECT PARAMETRO FROM PARAMETROS WHERE PARAMETRO = 'TKT_PRESENTE_OBRIGATORIO')
INSERT INTO PARAMETROS(PARAMETRO, DESC_PARAMETRO, PENULT_ATUALIZACAO, ULT_ATUALIZACAO, TIPO_DADO, VALOR_DEFAULT, 
		VALOR_ATUAL, GLOBAL, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, NOTA_PROGRAMADOR)
VALUES('TKT_PRESENTE_OBRIGATORIO','HABILITA A FUNÇÃO DE IMPRESSÃO DO TICKET PRESENTE EM TODAS AS VENDAS DA LOJA','20180212','20180212','L','.F.','.F.',0,1,1,0,0,0,'PARÂMETRO CRIADO PARA HABILITAR A UTILIZAÇÃO DE IMPRESSÃO DO TICKET PRESENTE EM TODAS AS VENDAS DA LOJA')

