IF NOT EXISTS(SELECT PARAMETRO FROM PARAMETROS WHERE PARAMETRO = 'TKT_ENVIA_EMAIL')
INSERT INTO PARAMETROS(PARAMETRO, DESC_PARAMETRO, PENULT_ATUALIZACAO, ULT_ATUALIZACAO, TIPO_DADO, VALOR_DEFAULT, 
		VALOR_ATUAL, GLOBAL, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, NOTA_PROGRAMADOR)
VALUES('TKT_ENVIA_EMAIL','HABILITA A FUN플O DE ENVIO DE E-MAIL DO TICKET PRESENTE','20180212','20180212','L','.F.','.F.',0,1,1,0,0,0,'PAR헜ETRO CRIADO PARA HABILITA A FUN플O DE ENVIO DE E-MAIL DO TICKET PRESENTE')


IF NOT EXISTS(SELECT PARAMETRO FROM PARAMETROS WHERE PARAMETRO = 'TKT_EMAIL_SMTP_SERVER')
INSERT INTO PARAMETROS(PARAMETRO, DESC_PARAMETRO, PENULT_ATUALIZACAO, ULT_ATUALIZACAO, TIPO_DADO, VALOR_DEFAULT, 
		VALOR_ATUAL, GLOBAL, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, NOTA_PROGRAMADOR)
VALUES('TKT_EMAIL_SMTP_SERVER','CONFIGURA플O DO SMTP PARA ENVIO DO TICKET PRESENTE POR E-MAIL.','20180212','20180212','C','','',0,1,1,0,0,0,'CONFIGURA플O DO SMTP PARA ENVIO DO TICKET PRESENTE POR E-MAIL')



IF NOT EXISTS(SELECT PARAMETRO FROM PARAMETROS WHERE PARAMETRO = 'TKT_EMAIL_SMTP_PORT')
INSERT INTO PARAMETROS(PARAMETRO, DESC_PARAMETRO, PENULT_ATUALIZACAO, ULT_ATUALIZACAO, TIPO_DADO, VALOR_DEFAULT, 
		VALOR_ATUAL, GLOBAL, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, NOTA_PROGRAMADOR)
VALUES('TKT_EMAIL_SMTP_PORT','CONFIGURA플O DA PORTA SMTP PARA ENVIO DO TICKET PRESENTE POR E-MAIL.','20180212','20180212','C','','',0,1,1,0,0,0,'CONFIGURA플O DA PORTA SMTP PARA ENVIO DO TICKET PRESENTE POR E-MAIL.')



IF NOT EXISTS(SELECT PARAMETRO FROM PARAMETROS WHERE PARAMETRO = 'TKT_EMAIL_FROM')
INSERT INTO PARAMETROS(PARAMETRO, DESC_PARAMETRO, PENULT_ATUALIZACAO, ULT_ATUALIZACAO, TIPO_DADO, VALOR_DEFAULT, 
		VALOR_ATUAL, GLOBAL, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, NOTA_PROGRAMADOR)
VALUES('TKT_EMAIL_FROM','CONFIGURA플O PARA O ENVIO DO TICKET PRESENTE POR E-MAIL.','20180212','20180212','C','','',0,1,1,0,0,0,'CONFIGURA플O PARA O ENVIO DO TICKET PRESENTE POR E-MAIL.')



IF NOT EXISTS(SELECT PARAMETRO FROM PARAMETROS WHERE PARAMETRO = 'TKT_EMAIL_USER')
INSERT INTO PARAMETROS(PARAMETRO, DESC_PARAMETRO, PENULT_ATUALIZACAO, ULT_ATUALIZACAO, TIPO_DADO, VALOR_DEFAULT, 
		VALOR_ATUAL, GLOBAL, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, NOTA_PROGRAMADOR)
VALUES('TKT_EMAIL_USER','CONFIGURA플O PARA O ENVIO DO TICKET PRESENTE POR E-MAIL.','20180212','20180212','C','','',0,1,1,0,0,0,'CONFIGURA플O PARA O ENVIO DO TICKET PRESENTE POR E-MAIL.')



IF NOT EXISTS(SELECT PARAMETRO FROM PARAMETROS WHERE PARAMETRO = 'TKT_EMAIL_PASSWORD')
INSERT INTO PARAMETROS(PARAMETRO, DESC_PARAMETRO, PENULT_ATUALIZACAO, ULT_ATUALIZACAO, TIPO_DADO, VALOR_DEFAULT, 
		VALOR_ATUAL, GLOBAL, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, NOTA_PROGRAMADOR)
VALUES('TKT_EMAIL_PASSWORD','CONFIGURA플O PARA O ENVIO DO TICKET PRESENTE POR E-MAIL.','20180212','20180212','C','','',0,1,1,0,0,0,'CONFIGURA플O PARA O ENVIO DO TICKET PRESENTE POR E-MAIL.')



IF NOT EXISTS(SELECT PARAMETRO FROM PARAMETROS WHERE PARAMETRO = 'TKT_EMAIL_USE_SSL')
INSERT INTO PARAMETROS(PARAMETRO, DESC_PARAMETRO, PENULT_ATUALIZACAO, ULT_ATUALIZACAO, TIPO_DADO, VALOR_DEFAULT, 
		VALOR_ATUAL, GLOBAL, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, NOTA_PROGRAMADOR)
VALUES('TKT_EMAIL_USE_SSL','CONFIGURA플O PARA O ENVIO DO TICKET PRESENTE POR E-MAIL.','20180212','20180212','C','','',0,1,1,0,0,0,'CONFIGURA플O PARA O ENVIO DO TICKET PRESENTE POR E-MAIL.')




