

IF EXISTS (SELECT 1
			FROM   [INFORMATION_SCHEMA].[COLUMNS]
			WHERE  [TABLE_NAME] = 'LOJA_VENDA_PARCELAS'
					AND [COLUMN_NAME] = 'CHEQUE_CARTAO'
					AND CHARACTER_MAXIMUM_LENGTH < 36)
BEGIN 
	ALTER TABLE [DBO].[LOJA_VENDA_PARCELAS] ALTER COLUMN CHEQUE_CARTAO VARCHAR(36) 
END

IF EXISTS (SELECT 1
			FROM   [INFORMATION_SCHEMA].[COLUMNS]
			WHERE  [TABLE_NAME] = 'LOJA_VENDA_PARCELAS'
					AND [COLUMN_NAME] = 'NUMERO_TITULO'
					AND CHARACTER_MAXIMUM_LENGTH < 36)
BEGIN 
	ALTER TABLE [DBO].[LOJA_VENDA_PARCELAS] ALTER COLUMN NUMERO_TITULO VARCHAR(36) 
END
