
IF NOT EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_PROCESSOS_SP' AND COLUMN_NAME = 'HOTFIX')
BEGIN
       ALTER TABLE LOJA_PROCESSOS_SP ADD HOTFIX TINYINT  NULL
       
END

IF EXISTS (SELECT COUNT(*) FROM SYS.COLUMNS SC JOIN SYS.OBJECTS SO ON SC.OBJECT_ID = SO.OBJECT_ID 
WHERE SC.NAME = 'VERSAO' AND SO.NAME = 'LOJA_PROCESSOS_SP' AND MAX_LENGTH = '1') 
BEGIN

ALTER TABLE LOJA_PROCESSOS_SP ALTER COLUMN VERSAO SMALLINT 

END 