IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_SAIDAS' AND COLUMN_NAME = 'CODIGO_CLIENTE') BEGIN
    ALTER TABLE [dbo].[LOJA_SAIDAS] ADD CODIGO_CLIENTE VARCHAR(14) NULL
END
