
IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = 'OMS_SHW_CLI')
	INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
	SELECT	'OMS_SHW_CLI' AS PARAMETRO,	CAST(0 AS DATETIME) PENULT_ATUALIZACAO,	'' AS VALOR_DEFAULT, GETDATE() AS ULT_ATUALIZACAO,	'' AS VALOR_ATUAL,
			'URL BÁSICA PARA LOCALIZAÇÃO CLIENTE' AS DESC_PARAMETRO,
			'C' AS TIPO_DADO,'' AS RANGE_VALOR_ATUAL,0 AS GLOBAL,'UTILIZADO NA INTEGRAÇÃO DO SHOWROOMING COM O LINX OMS' AS NOTA_PROGRAMADOR,
			0 AS ESCOPO,0 AS POR_USUARIO_OK,0 AS PERMITE_POR_EMPRESA,	1 AS ENVIA_PARA_LOJA,	1 AS PERMITE_POR_LOJA,	0 AS PERMITE_POR_TERMINAL,
			1 AS PERMITE_ALTERAR_NA_LOJA, 0 AS PERMITE_ALTERAR_NO_TERMINAL,	0 AS ENVIA_PARA_REPRESENTANTE,	0 AS PERMITE_POR_REPRESENTANTE,
			0 AS PERMITE_ALTERAR_NO_REPRESENTANTE

IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = 'OMS_SHW_CLI_CHN')
	INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
	SELECT	'OMS_SHW_CLI_CHN' AS PARAMETRO,	CAST(0 AS DATETIME) PENULT_ATUALIZACAO,	'' AS VALOR_DEFAULT,GETDATE() AS ULT_ATUALIZACAO,'' AS VALOR_ATUAL,
			'URL BÁSICA PARA LOCALIZAÇÃO CLIENTE' AS DESC_PARAMETRO,'C' AS TIPO_DADO,'' AS RANGE_VALOR_ATUAL,0 AS GLOBAL,
			'UTILIZADO NA INTEGRAÇÃO DO SHOWROOMING COM O LINX OMS' AS NOTA_PROGRAMADOR,0 AS ESCOPO,0 AS POR_USUARIO_OK,0 AS PERMITE_POR_EMPRESA,
			1 AS ENVIA_PARA_LOJA,1 AS PERMITE_POR_LOJA,	1 AS PERMITE_POR_TERMINAL,	1 AS PERMITE_ALTERAR_NA_LOJA,	1 AS PERMITE_ALTERAR_NO_TERMINAL,
			0 AS ENVIA_PARA_REPRESENTANTE,0 AS PERMITE_POR_REPRESENTANTE,	0 AS PERMITE_ALTERAR_NO_REPRESENTANTE

IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = 'OMS_SHW_CLI_PSW')
	INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
	SELECT	'OMS_SHW_CLI_PSW' AS PARAMETRO,	CAST(0 AS DATETIME) PENULT_ATUALIZACAO,	'' AS VALOR_DEFAULT,GETDATE() AS ULT_ATUALIZACAO,'' AS VALOR_ATUAL,
			'URL BÁSICA PARA LOCALIZAÇÃO CLIENTE' AS DESC_PARAMETRO,'C' AS TIPO_DADO,'' AS RANGE_VALOR_ATUAL,0 AS GLOBAL,
			'UTILIZADO NA INTEGRAÇÃO DO SHOWROOMING COM O LINX OMS' AS NOTA_PROGRAMADOR,0 AS ESCOPO,0 AS POR_USUARIO_OK,0 AS PERMITE_POR_EMPRESA,
			1 AS ENVIA_PARA_LOJA,1 AS PERMITE_POR_LOJA,	1 AS PERMITE_POR_TERMINAL,	1 AS PERMITE_ALTERAR_NA_LOJA,1 AS PERMITE_ALTERAR_NO_TERMINAL,
			0 AS ENVIA_PARA_REPRESENTANTE,0 AS PERMITE_POR_REPRESENTANTE,0 AS PERMITE_ALTERAR_NO_REPRESENTANTE


IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = 'OMS_SHW_CLI_USR')
	INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
	SELECT	'OMS_SHW_CLI_USR' AS PARAMETRO,	CAST(0 AS DATETIME) PENULT_ATUALIZACAO,	'' AS VALOR_DEFAULT,GETDATE() AS ULT_ATUALIZACAO,'' AS VALOR_ATUAL,
			'URL BÁSICA PARA LOCALIZAÇÃO CLIENTE' AS DESC_PARAMETRO,'C' AS TIPO_DADO,'' AS RANGE_VALOR_ATUAL,0 AS GLOBAL,'UTILIZADO NA INTEGRAÇÃO DO SHOWROOMING COM O LINX OMS' AS NOTA_PROGRAMADOR,
			0 AS ESCOPO,0 AS POR_USUARIO_OK,0 AS PERMITE_POR_EMPRESA,1 AS ENVIA_PARA_LOJA,1 AS PERMITE_POR_LOJA,1 AS PERMITE_POR_TERMINAL,
			1 AS PERMITE_ALTERAR_NA_LOJA,1 AS PERMITE_ALTERAR_NO_TERMINAL,0 AS ENVIA_PARA_REPRESENTANTE,0 AS PERMITE_POR_REPRESENTANTE,	0 AS PERMITE_ALTERAR_NO_REPRESENTANTE

IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = 'OMS_SHW_URL_IMG')
	INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
	SELECT	'OMS_SHW_URL_IMG' AS PARAMETRO,	CAST(0 AS DATETIME) PENULT_ATUALIZACAO,	'' AS VALOR_DEFAULT,GETDATE() AS ULT_ATUALIZACAO,'' AS VALOR_ATUAL,
			'URL DO PROXY PARA CAPTURA DE IMAGENS' AS DESC_PARAMETRO,'C' AS TIPO_DADO,'' AS RANGE_VALOR_ATUAL,0 AS GLOBAL,'UTILIZADO NA INTEGRAÇÃO DO SHOWROOMING COM O LINX OMS' AS NOTA_PROGRAMADOR,
			0 AS ESCOPO,0 AS POR_USUARIO_OK,0 AS PERMITE_POR_EMPRESA,1 AS ENVIA_PARA_LOJA,1 AS PERMITE_POR_LOJA,1 AS PERMITE_POR_TERMINAL,
			1 AS PERMITE_ALTERAR_NA_LOJA,1 AS PERMITE_ALTERAR_NO_TERMINAL,0 AS ENVIA_PARA_REPRESENTANTE,0 AS PERMITE_POR_REPRESENTANTE,
			0 AS PERMITE_ALTERAR_NO_REPRESENTANTE

IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = 'OMS_SH_PRECO_LOJA')
	INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
	SELECT	'OMS_SH_PRECO_LOJA' AS PARAMETRO,CAST(0 AS DATETIME) PENULT_ATUALIZACAO,'.T.' AS VALOR_DEFAULT,	GETDATE() AS ULT_ATUALIZACAO,'.T.' AS VALOR_ATUAL,  
			'Indica se os preços dos itens de showrooming devem ser obtidos da tabela de preços da loja ou não' AS DESC_PARAMETRO,	'L' AS TIPO_DADO,
			'' AS RANGE_VALOR_ATUAL,0 AS GLOBAL,'Se não obter da tabela de preços da loja, deve obter do serviço do Linx OMS' AS NOTA_PROGRAMADOR,
			0 AS ESCOPO,0 AS POR_USUARIO_OK,0 AS PERMITE_POR_EMPRESA,1 AS ENVIA_PARA_LOJA,1 AS PERMITE_POR_LOJA,0 AS PERMITE_POR_TERMINAL,
			0 AS PERMITE_ALTERAR_NA_LOJA,0 AS PERMITE_ALTERAR_NO_TERMINAL,0 AS ENVIA_PARA_REPRESENTANTE,0 AS PERMITE_POR_REPRESENTANTE,	0 AS PERMITE_ALTERAR_NO_REPRESENTANTE

IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = 'OMS_SHW_URL_CAD')
	INSERT INTO PARAMETROS (PARAMETRO,PENULT_ATUALIZACAO,VALOR_DEFAULT,ULT_ATUALIZACAO,VALOR_ATUAL,DESC_PARAMETRO,TIPO_DADO,RANGE_VALOR_ATUAL,GLOBAL,NOTA_PROGRAMADOR,ESCOPO,POR_USUARIO_OK,PERMITE_POR_EMPRESA,ENVIA_PARA_LOJA,PERMITE_POR_LOJA,PERMITE_POR_TERMINAL,PERMITE_ALTERAR_NA_LOJA,PERMITE_ALTERAR_NO_TERMINAL,ENVIA_PARA_REPRESENTANTE,PERMITE_POR_REPRESENTANTE,PERMITE_ALTERAR_NO_REPRESENTANTE,DATA_PARA_TRANSFERENCIA)
	VALUES('OMS_SHW_URL_CAD',GETDATE(),'',GETDATE(), '' ,'URL DO PROXY PARA CONSULTA CADASTRO DE CLIENTES','C','',0,'UTILIZADO NA INTEGRAÇÃO DO SHOWROOMING COM O LINX OMS',0,0,0,1,1,1,1,1,0,0,0,GETDATE())

IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = 'OMS_SHW_PWD_CAD')
	INSERT INTO PARAMETROS (PARAMETRO,PENULT_ATUALIZACAO,VALOR_DEFAULT,ULT_ATUALIZACAO,VALOR_ATUAL,DESC_PARAMETRO,TIPO_DADO,RANGE_VALOR_ATUAL,GLOBAL,NOTA_PROGRAMADOR,ESCOPO,POR_USUARIO_OK,PERMITE_POR_EMPRESA,ENVIA_PARA_LOJA,PERMITE_POR_LOJA,PERMITE_POR_TERMINAL,PERMITE_ALTERAR_NA_LOJA,PERMITE_ALTERAR_NO_TERMINAL,ENVIA_PARA_REPRESENTANTE,PERMITE_POR_REPRESENTANTE,PERMITE_ALTERAR_NO_REPRESENTANTE,DATA_PARA_TRANSFERENCIA)
	VALUES('OMS_SHW_PWD_CAD',GETDATE(),'',GETDATE(), '' ,'SENHA DE ACESSO AO PROXY PARA CONSULTA CADASTRO DE CLIENTES','C','',0,'UTILIZADO NA INTEGRAÇÃO DO SHOWROOMING COM O LINX OMS',0,0,0,1,1,1,1,1,0,0,0,GETDATE())

IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = 'OMS_SHW_UPD_CAD')
	INSERT INTO PARAMETROS (PARAMETRO,PENULT_ATUALIZACAO,VALOR_DEFAULT,ULT_ATUALIZACAO,VALOR_ATUAL,DESC_PARAMETRO,TIPO_DADO,RANGE_VALOR_ATUAL,GLOBAL,NOTA_PROGRAMADOR,ESCOPO,POR_USUARIO_OK,PERMITE_POR_EMPRESA,ENVIA_PARA_LOJA,PERMITE_POR_LOJA,PERMITE_POR_TERMINAL,PERMITE_ALTERAR_NA_LOJA,PERMITE_ALTERAR_NO_TERMINAL,ENVIA_PARA_REPRESENTANTE,PERMITE_POR_REPRESENTANTE,PERMITE_ALTERAR_NO_REPRESENTANTE,DATA_PARA_TRANSFERENCIA)
	VALUES('OMS_SHW_UPD_CAD',GETDATE(),'.T.',GETDATE(),'.T.','Indica se cadastro do cliente de showrooming devem ser obtidos do cadastro local ou do site','L','',0,'Se não obter da tabela de preços da loja, deve obter do serviço do Linx OMS',0,0,0,1,1,1,1,1,0,0,0,GETDATE())


IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = 'OMS_SHW_MODALIDADES')
	INSERT INTO PARAMETROS (PARAMETRO,PENULT_ATUALIZACAO,VALOR_DEFAULT,ULT_ATUALIZACAO,VALOR_ATUAL,DESC_PARAMETRO,TIPO_DADO,RANGE_VALOR_ATUAL,GLOBAL,NOTA_PROGRAMADOR,ESCOPO,POR_USUARIO_OK,PERMITE_POR_EMPRESA,ENVIA_PARA_LOJA,PERMITE_POR_LOJA,PERMITE_POR_TERMINAL,PERMITE_ALTERAR_NA_LOJA,PERMITE_ALTERAR_NO_TERMINAL,ENVIA_PARA_REPRESENTANTE,PERMITE_POR_REPRESENTANTE,PERMITE_ALTERAR_NO_REPRESENTANTE,DATA_PARA_TRANSFERENCIA)
	VALUES('OMS_SHW_MODALIDADES',GETDATE(),'',GETDATE(), '' ,'MODALIDADES HABILITADAS PARA A COTAÇÃO DO SHOWROOMING','C','',0,'MODALIDADES HABILITADAS PARA A COTAÇÃO DO SHOWROOMING',0,0,0,1,1,1,1,1,0,0,0,GETDATE())

IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = 'OMS_SHW_USA_PROMOCAO')
	INSERT INTO PARAMETROS (PARAMETRO,PENULT_ATUALIZACAO,VALOR_DEFAULT,ULT_ATUALIZACAO,VALOR_ATUAL,DESC_PARAMETRO,TIPO_DADO,RANGE_VALOR_ATUAL,GLOBAL,NOTA_PROGRAMADOR,ESCOPO,POR_USUARIO_OK,PERMITE_POR_EMPRESA,ENVIA_PARA_LOJA,PERMITE_POR_LOJA,PERMITE_POR_TERMINAL,PERMITE_ALTERAR_NA_LOJA,PERMITE_ALTERAR_NO_TERMINAL,ENVIA_PARA_REPRESENTANTE,PERMITE_POR_REPRESENTANTE,PERMITE_ALTERAR_NO_REPRESENTANTE,DATA_PARA_TRANSFERENCIA)
	VALUES('OMS_SHW_USA_PROMOCAO',GETDATE(),'.F.',GETDATE(), '.F.' ,'HABILITAR PROMOCAO SHOWROOMING','L','',0,'HABILITAR PROMOCAO SHOWROOMING',0,0,0,1,1,1,1,1,0,0,0,GETDATE())
	
IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = 'OMS_SHW_IMG_SITE')
	INSERT INTO PARAMETROS (PARAMETRO,PENULT_ATUALIZACAO,VALOR_DEFAULT,ULT_ATUALIZACAO,VALOR_ATUAL,DESC_PARAMETRO,TIPO_DADO,RANGE_VALOR_ATUAL,GLOBAL,NOTA_PROGRAMADOR,ESCOPO,POR_USUARIO_OK,PERMITE_POR_EMPRESA,ENVIA_PARA_LOJA,PERMITE_POR_LOJA,PERMITE_POR_TERMINAL,PERMITE_ALTERAR_NA_LOJA,PERMITE_ALTERAR_NO_TERMINAL,ENVIA_PARA_REPRESENTANTE,PERMITE_POR_REPRESENTANTE,PERMITE_ALTERAR_NO_REPRESENTANTE,DATA_PARA_TRANSFERENCIA)
	VALUES('OMS_SHW_IMG_SITE',GETDATE(),'.F.',GETDATE(), '.T.' ,'EXIBE IMAGEM DO PRODUTO DO SITE','L','',0,'EXIBE IMAGEM DO PRODUTO DO SITE',0,0,0,1,1,1,1,1,0,0,0,GETDATE())
	
IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = 'OMS_SHW_EXIBE_IMAGEM')
	INSERT INTO PARAMETROS (PARAMETRO,PENULT_ATUALIZACAO,VALOR_DEFAULT,ULT_ATUALIZACAO,VALOR_ATUAL,DESC_PARAMETRO,TIPO_DADO,RANGE_VALOR_ATUAL,GLOBAL,NOTA_PROGRAMADOR,ESCOPO,POR_USUARIO_OK,PERMITE_POR_EMPRESA,ENVIA_PARA_LOJA,PERMITE_POR_LOJA,PERMITE_POR_TERMINAL,PERMITE_ALTERAR_NA_LOJA,PERMITE_ALTERAR_NO_TERMINAL,ENVIA_PARA_REPRESENTANTE,PERMITE_POR_REPRESENTANTE,PERMITE_ALTERAR_NO_REPRESENTANTE,DATA_PARA_TRANSFERENCIA)
	VALUES('OMS_SHW_EXIBE_IMAGEM',GETDATE(),'.F.',GETDATE(), '.T.' ,'HABILITA EXIBIÇÃO IMAGEM DOS PRODUTOS','L','',0,'HABILITA EXIBIÇÃO IMAGEM DOS PRODUTOS',0,0,0,1,1,1,1,1,0,0,0,GETDATE())
