-- POSSP-5157  - Gilvano Santos - (31/03/2021) - Nota Técnica 2020.006
IF NOT EXISTS(SELECT PARAMETRO FROM PARAMETROS WHERE PARAMETRO = 'UTILIZA_INTERMEDIADOR')
BEGIN
	Insert into parametros (PARAMETRO,PENULT_ATUALIZACAO,VALOR_DEFAULT, ULT_ATUALIZACAO ,VALOR_ATUAL, DESC_PARAMETRO,  
	TIPO_DADO,RANGE_VALOR_ATUAL, GLOBAL,NOTA_PROGRAMADOR,ESCOPO,POR_USUARIO_OK,	PERMITE_POR_EMPRESA,ENVIA_PARA_LOJA, PERMITE_POR_LOJA,
	PERMITE_POR_TERMINAL,PERMITE_ALTERAR_NA_LOJA,PERMITE_ALTERAR_NO_TERMINAL,
	ENVIA_PARA_REPRESENTANTE,PERMITE_POR_REPRESENTANTE,PERMITE_ALTERAR_NO_REPRESENTANTE,DATA_PARA_TRANSFERENCIA) 
	values('UTILIZA_INTERMEDIADOR',GETDATE(),'.F.', GETDATE(),'.F.','Habilita preenchimento do intemerdiador na NFe / NFC-e',	
		'L','',0,'Este parametro permite usuario habilitar o preenchimento do Intermediador na emissão da NF-e ou NFC-e',
		0,0,1,1,1,0,1,0	,0,0,0,GETDATE())
END


