IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[LJ_PROD_ICMS_PAF_NFCE]') AND type in (N'U'))
BEGIN
	CREATE TABLE [dbo].[LJ_PROD_ICMS_PAF_NFCE](
		ID_PROD_ICMS_PAF_NFCE	[INT] IDENTITY,
		DATA_PAF_NFCE			[DATE] NOT NULL,
		CODIGO_FILIAL			[char] (6) COLLATE DATABASE_DEFAULT NOT NULL,
		ID_EXCECAO_IMPOSTO		[int] NOT NULL,
		PRODUTO					[varchar] (12) COLLATE DATABASE_DEFAULT,
		TAXA_IMPOSTO			[numeric],
		TRIBUT_ICMS				[char] (03) COLLATE DATABASE_DEFAULT,
		PONTUACAO				[int],
		LX_HASH					[varbinary] (16),
	CONSTRAINT [XPKLJ_PROD_ICMS_PAF_NFCE] PRIMARY KEY CLUSTERED 
	(
		[ID_PROD_ICMS_PAF_NFCE] ASC
	)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	)
END
