Create PROCEDURE [DBO].[LX_LIMPEZA_ESTOQUE_PAF_NFCE] ( @CODIGO_FILIAL VARCHAR(6))
AS   
BEGIN
	 declare @dtFiscal as date
	 
	 SELECT @dtFiscal = CAST(MAX(DATA_PAF_NFCE) AS DATE)     
	 FROM LJ_ESTOQUE_PAF_NFCE   
     WHERE CODIGO_FILIAL = @CODIGO_FILIAL 

	 IF @dtFiscal is not null
	 BEGIN
		DELETE FROM LJ_ESTOQUE_PAF_NFCE  
		WHERE CODIGO_FILIAL = @CODIGO_FILIAL  
			AND  DATA_PAF_NFCE < @dtFiscal;
				
		DELETE FROM LJ_PROD_ICMS_PAF_NFCE
		WHERE CODIGO_FILIAL = @CODIGO_FILIAL  
			AND  DATA_PAF_NFCE < @dtFiscal;
	 END





end
