IF NOT EXISTS (SELECT * FROM sysindexes WHERE name = 'XIE1LJ_PROD_ICMS_PAF_NFCE' AND id = object_id('LJ_PROD_ICMS_PAF_NFCE'))
begin
	CREATE NONCLUSTERED INDEX [XIE1LJ_PROD_ICMS_PAF_NFCE]
	ON [dbo].[LJ_PROD_ICMS_PAF_NFCE] ([DATA_PAF_NFCE],[CODIGO_FILIAL],[ID_EXCECAO_IMPOSTO])
	INCLUDE ([ID_PROD_ICMS_PAF_NFCE])
end
