IF NOT EXISTS( SELECT 1 FROM SYS.sysobjects WHERE NAME = 'SENHA_HISTORICO' )
				BEGIN

CREATE TABLE SENHA_HISTORICO
(
	VENDEDOR        				CHAR(4)				NOT NULL, 
	SENHA							SYSNAME 			NULL, 
	DATA_SENHA						DATETIME			NOT NULL

	CONSTRAINT [XPKSENHA_HISTORICO] PRIMARY KEY CLUSTERED 
	(
		[VENDEDOR] ASC,
		[DATA_SENHA] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	)	

END				
		
