IF NOT EXISTS(SELECT PARAMETRO FROM PARAMETROS WHERE PARAMETRO = 'OBRIGA_IDENTIF_TROCA')
INSERT INTO PARAMETROS(PARAMETRO, DESC_PARAMETRO, PENULT_ATUALIZACAO, ULT_ATUALIZACAO, TIPO_DADO, VALOR_DEFAULT, 
		VALOR_ATUAL, GLOBAL, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, NOTA_PROGRAMADOR)
VALUES('OBRIGA_IDENTIF_TROCA','Obriga a identificar a venda de origem na troca.','20220110','20220110','L','.F.','.F.',0,1,1,0,0,0,'Este parâmetro indica se é obrigatório identificar a venda de origem nos itens de troca e devolução.')


IF EXISTS(SELECT PARAMETRO FROM PARAMETROS WHERE PARAMETRO = 'OBRIGA_IDENTIF_TROCA')
UPDATE PARAMETROS SET DESC_PARAMETRO = 'DESATIVADO', VALOR_ATUAL = '.F.' WHERE PARAMETRO = 'OBRIGA_IDENTIF_TROCA'