-- PRODSHOP-7221  - EDER / WENDEL    - 16/07/2021 - Tabela criada para auxiliar na composição das parcelas e troco no documento fiscal quando tiver item do Vitrine na venda.

IF NOT EXISTS( SELECT 1 FROM SYS.SYSOBJECTS WHERE NAME = 'LOJA_VENDA_PARCELAS_ECOMMERCE' )
	BEGIN
		CREATE TABLE LOJA_VENDA_PARCELAS_ECOMMERCE (TERMINAL CHAR(3), LANCAMENTO_CAIXA CHAR(7), CODIGO_FILIAL CHAR(6), PARCELA CHAR(2), TIPO_PGTO CHAR(1), VALOR NUMERIC(14,2), TROCO NUMERIC(14,2)) 
	END
