ALTER PROCEDURE [dbo].[sp_GetNextTicket] (@StoreCode char(6), @Type tinyint, @bUpdate int = 1, @Ticket char(8) = null)
AS
BEGIN
	IF @Ticket IS NULL
		IF @Type = 1
		BEGIN
			SELECT @Ticket = RIGHT(REPLICATE('0', 8) + CONVERT(VARCHAR, CONVERT(INT, ISNULL(CASE WHEN ISNUMERIC(SEQUENCIA_TICKET) = 1 THEN SEQUENCIA_TICKET ELSE (SELECT MAX(TICKET) FROM LOJA_VENDA WHERE CODIGO_FILIAL = @StoreCode AND ISNUMERIC(TICKET) = 1) END, '0')) + 1), 8) 
			FROM LOJAS_VAREJO (UPDLOCK) 
			WHERE CODIGO_FILIAL = @StoreCode

			WHILE EXISTS(SELECT 1 FROM LOJA_VENDA (NOLOCK) WHERE CODIGO_FILIAL = @StoreCode AND TICKET = @Ticket)
				SET @Ticket = RIGHT(REPLICATE('0', 8) + CONVERT(VARCHAR, CONVERT(INT, @Ticket) + 1), 8)
		END
		ELSE
		BEGIN
			SET @Ticket = RIGHT('00' + CONVERT(VARCHAR, DAY(GETDATE())), 2) + RIGHT('00' + CONVERT(VARCHAR, DATEPART(HH, GETDATE())), 2) + RIGHT('00' + CONVERT(VARCHAR, DATEPART(MI, GETDATE())), 2)  + RIGHT('00' + CONVERT(VARCHAR, DATEPART(MILLISECOND, GETDATE())), 2)

			WHILE EXISTS(SELECT 1 FROM LOJA_VENDA (NOLOCK) WHERE CODIGO_FILIAL = @StoreCode AND TICKET = @Ticket)
				SET @Ticket = RIGHT('00' + CONVERT(VARCHAR, DAY(GETDATE())), 2) + RIGHT('00' + CONVERT(VARCHAR, DATEPART(HH, GETDATE())), 2) + RIGHT('00' + CONVERT(VARCHAR, DATEPART(MI, GETDATE())), 2)  + RIGHT('00' + CONVERT(VARCHAR, DATEPART(MILLISECOND, GETDATE())), 2)
		END

	IF @bUpdate = 1	
		UPDATE LOJAS_VAREJO WITH (UPDLOCK) SET SEQUENCIA_TICKET = @Ticket WHERE CODIGO_FILIAL = @StoreCode

	SELECT @Ticket as TICKET
END



