IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'LOJA_VENDA_DADOS_CARTAO')
CREATE TABLE [dbo].[LOJA_VENDA_DADOS_CARTAO](
	[TERMINAL]				[char](3) NOT NULL,
	[LANCAMENTO_CAIXA]		[char](7) NOT NULL,
	[CODIGO_FILIAL]			[char](6) NOT NULL,
	[PARCELA]				[char](2) NOT NULL,
	[NUMERO_INICIAL_CARTAO] [char](6) NULL,
	[NUMERO_FINAL_CARTAO]	[char](4) NULL,
	[TITULAR_CARTAO]		[char](32) NULL,
	[DATA_EXPIRACAO_CARTAO] [char](4) NULL,
	[DATA_PARA_TRANSFERENCIA] [datetime] NULL DEFAULT ('DATA_ATUAL')
 CONSTRAINT [XPKLOJA_VENDA_DADOS_CARTAO] PRIMARY KEY CLUSTERED 
(
	[TERMINAL] ASC,
	[LANCAMENTO_CAIXA] ASC,
	[CODIGO_FILIAL] ASC,
	[PARCELA] ASC
)
) ON [PRIMARY]