-- Demanda 30125 - Vívian Domingues (16/08/2017) - Criação do campo Fabricante 
IF NOT EXISTS ( SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_CF_SAT_PARAMETROS' AND COLUMN_NAME = 'FABRICANTE'  )
	ALTER TABLE LOJA_CF_SAT_PARAMETROS ADD FABRICANTE varchar(60) NULL
