if object_id('XPKLOJA_VENDA_PROMOCAO') is null
BEGIN
	ALTER TABLE [dbo].[LOJA_VENDA_PROMOCAO] 
	ADD CONSTRAINT [XPKLOJA_VENDA_PROMOCAO] PRIMARY KEY CLUSTERED ([CODIGO_FILIAL], [TICKET], [DATA_VENDA], [ID_PROMOCAO], [ITEM]) ON [PRIMARY]
END;

if object_id('XPKLOJA_VENDA_PROMOCAO_CUPOM') is null
BEGIN
	ALTER TABLE [dbo].[LOJA_VENDA_PROMOCAO_CUPOM] 
	ADD CONSTRAINT [XPKLOJA_VENDA_PROMOCAO_CUPOM] PRIMARY KEY CLUSTERED ([CODIGO_FILIAL], [TICKET], [DATA_VENDA], [ID_PROMOCAO], [CODIGO_CUPOM]) ON [PRIMARY]
END;