CREATE FUNCTION [DBO].[FX_CALCULA_RATEIO_PARCELAS] (@QTDE_PARCELAS INT, @VALOR NUMERIC(9,2))
	RETURNS @TABELA TABLE(PARCELA INT,VALOR NUMERIC(9,2))
AS
-- DM 58430	- Diego Moreno	   - #1# - (20/09/2017) - Adequacao NFE 4.00. Criação da function para tratar a divisão entre as parcelas quando for necessário gerar as tags de imposto ICMS-ST e ICMS-STR na proc LX_GERA_NFE_SEFAZ_4_00.
BEGIN 
		DECLARE @CNT INT = 0;
		DECLARE @VALOR_PARCELA NUMERIC(9,2);
		DECLARE @SUM_VALOR NUMERIC(9,2);
		DECLARE @DIF NUMERIC(9,2);

		SET @VALOR_PARCELA = (@VALOR /@QTDE_PARCELAS)
		WHILE @CNT < @QTDE_PARCELAS
		BEGIN
		INSERT INTO @TABELA--(PARCELA,VALOR)
		VALUES(@CNT + 1,@VALOR_PARCELA)
		SET @CNT = @CNT + 1;
		
		---VERIFICAR A DIFERENÇA
		END;
		SELECT @SUM_VALOR = SUM(VALOR) FROM @TABELA

		SELECT @DIF = @VALOR - @SUM_VALOR
		
		UPDATE @TABELA SET VALOR = VALOR + CASE 
							WHEN @SUM_VALOR > @VALOR THEN - ABS(@DIF) ELSE + ABS(@DIF) END WHERE PARCELA = '01'
		RETURN 
END
	
