IF NOT EXISTS(	SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
					WHERE TABLE_NAME = 'LOJA_PEDIDO_PRODUTO' AND COLUMN_NAME = 'EMBRULHA_PRESENTE')
BEGIN
	ALTER TABLE dbo.LOJA_PEDIDO_PRODUTO ADD EMBRULHA_PRESENTE bit NULL
END;

