/*Vívian Domingues - Data 10/10/2017 - DM 44698 - Adicionado restrição ao campo para não receber valor nulo e default GETDATE()*/
IF EXISTS ( SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LX_SCHEMA_XML_MSG' AND COLUMN_NAME = 'DATA_PARA_TRANSFERENCIA')
	UPDATE LX_SCHEMA_XML_MSG SET DATA_PARA_TRANSFERENCIA = GETDATE() where DATA_PARA_TRANSFERENCIA IS NULL
	ALTER TABLE LX_SCHEMA_XML_MSG ALTER COLUMN DATA_PARA_TRANSFERENCIA DATETIME NOT NULL 

--Cria o valor default
IF NOT EXISTS (  SELECT 1 FROM SYS.objects WHERE name = 'XDF10001_LX_SCHEMA_XML_MSG')
	ALTER TABLE [dbo].[LX_SCHEMA_XML_MSG] ADD  CONSTRAINT [XDF10001_LX_SCHEMA_XML_MSG]  DEFAULT (getdate()) FOR [DATA_PARA_TRANSFERENCIA]





 

	