IF OBJECT_ID('DBO.LOJA_PEDIDO_ENTREGA','U')  IS NULL BEGIN

CREATE TABLE DBO.LOJA_PEDIDO_ENTREGA
(
    CODIGO_FILIAL_ORIGEM	CHAR(6) NOT NULL,
    PEDIDO	                INT NOT NULL    ,
    SEQ_ENTREGA	            TINYINT NOT NULL,
    ITEM_ENDERECO	        CHAR(18)        ,
    DADOS_RESERVA	        VARCHAR(4000)   ,
    DADOS_CONSULTA	        VARCHAR(4000)	,
	DATA_PARA_TRANSFERENCIA DATETIME NULL DEFAULT getdate()
)

ALTER TABLE DBO.LOJA_PEDIDO_ENTREGA ADD CONSTRAINT  XPKLOJA_PEDIDO_ENTREGA PRIMARY KEY (CODIGO_FILIAL_ORIGEM, PEDIDO, SEQ_ENTREGA)

END