
IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'LOJA_PEDIDO_ENTREGA'
                      AND COLUMN_NAME = 'OPCAO_ENTREGA')
  ALTER TABLE [dbo].[LOJA_PEDIDO_ENTREGA]
    ADD OPCAO_ENTREGA VARCHAR(50) NULL 
