IF OBJECT_ID('DBO.LOJA_PEDIDO_DEVOLUCAO','U')  IS NULL BEGIN

CREATE TABLE DBO.LOJA_PEDIDO_DEVOLUCAO
(
    CODIGO_FILIAL_ORIGEM	   CHAR(6)  NOT NULL,
    PEDIDO	                   INT NOT  NULL    ,
    TICKET                     CHAR(8)  NULL    ,
    DATA_VENDA                 DATETIME NULL    ,
    NF_NUMERO                  CHAR(15) NULL    ,
    SERIE_NF                   CHAR(6)  NULL	,
	DATA_PARA_TRANSFERENCIA	   DATETIME NULL DEFAULT getdate()
)

ALTER TABLE DBO.LOJA_PEDIDO_DEVOLUCAO ADD CONSTRAINT  XPKLOJA_PEDIDO_DEVOLUCAO PRIMARY KEY (CODIGO_FILIAL_ORIGEM, PEDIDO)

END