IF OBJECT_ID('DBO.OMS_CHANGE_TRACKING','U') IS NULL
BEGIN
	CREATE TABLE DBO.OMS_CHANGE_TRACKING
	(
	[ID]					[smallint]	IDENTITY(1,1)	NOT	NULL,
	[SYS_CHANGE_VERSION]	[bigint]					NOT	NULL,
	[CHANELID]				[varchar]	(50)				NULL,
	[OPERATOR_ID]			[varchar]	(5)				NOT NULL,
	[STATUS]				[varchar]	(50)				NULL,
	[CLIENTID]				[varchar]	(6)				NOT NULL,
	[PROCESSEDAT]			[datetime]					NOT NULL,
	[ID_FULFILLMENT]		[varchar]	(5)				NULL,
	[ORDERID]				[VARCHAR]	(20)
	)
	ALTER TABLE DBO.OMS_CHANGE_TRACKING ADD CONSTRAINT XPKOMS_CHANGE_TRACKING PRIMARY KEY (ID)
END
	IF	NOT	EXISTS	(SELECT	1 FROM	INFORMATION_SCHEMA.COLUMNS	WHERE	TABLE_NAME='OMS_CHANGE_TRACKING'	AND	COLUMN_NAME	=	'ORDERID')
	BEGIN
		ALTER TABLE	[DBO].[OMS_CHANGE_TRACKING]	ADD	ORDERID	VARCHAR(20)
	END