-- Insere parâmetros do Linx Omni Promo
IF NOT EXISTS(SELECT PARAMETRO FROM PARAMETROS WHERE PARAMETRO = 'UTILIZA_LINX_OMNI_PROMO')
	INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
	SELECT	'UTILIZA_LINX_OMNI_PROMO' AS PARAMETRO,
			CAST(0 AS DATETIME) PENULT_ATUALIZACAO,
			'.F.' AS VALOR_DEFAULT,
			GETDATE() AS ULT_ATUALIZACAO,
			'.F.' AS VALOR_ATUAL,
			'HABILITA A INTERFACE DE MOTOR DE PROMOÇÃO DO LINX OMNI PROMO.' AS DESC_PARAMETRO,
			'L' AS TIPO_DADO,
			'' AS RANGE_VALOR_ATUAL,
			0 AS GLOBAL,
			'PARÂMETRO PARA HABILITAR A OPÇÃO DE UTILIZAR A FUNCIONALIDADE DE MOTOR DE PROMOÇÃO DO LINX OMNI PROMO.' AS NOTA_PROGRAMADOR,
			0 AS ESCOPO,
			0 AS POR_USUARIO_OK,
			0 AS PERMITE_POR_EMPRESA,
			1 AS ENVIA_PARA_LOJA,
			1 AS PERMITE_POR_LOJA,
			0 AS PERMITE_POR_TERMINAL,
			0 AS PERMITE_ALTERAR_NA_LOJA,
			0 AS PERMITE_ALTERAR_NO_TERMINAL,
			0 AS ENVIA_PARA_REPRESENTANTE,
			0 AS PERMITE_POR_REPRESENTANTE,
			0 AS PERMITE_ALTERAR_NO_REPRESENTANTE


IF NOT EXISTS(SELECT PARAMETRO FROM PARAMETROS WHERE PARAMETRO = 'LINX_OMNI_PROMO_URL')
	INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
	SELECT	'LINX_OMNI_PROMO_URL' AS PARAMETRO,
			CAST(0 AS DATETIME) PENULT_ATUALIZACAO,
			'' AS VALOR_DEFAULT,
			GETDATE() AS ULT_ATUALIZACAO,
			'' AS VALOR_ATUAL,
			'DEFINE A URL QUE SERÁ UTILIZADA NAS CONFIGURAÇÕES DE COMUNICAÇÃO DO LINX OMNI PROMO.' AS DESC_PARAMETRO,
			'C' AS TIPO_DADO,
			'' AS RANGE_VALOR_ATUAL,
			0 AS GLOBAL,
			'URL PARA COMUNICAÇÃO COM A INTERFACE DE PROMOÇÃO DO LINX OMNI PROMO.' AS NOTA_PROGRAMADOR,
			0 AS ESCOPO,
			0 AS POR_USUARIO_OK,
			0 AS PERMITE_POR_EMPRESA,
			1 AS ENVIA_PARA_LOJA,
			1 AS PERMITE_POR_LOJA,
			0 AS PERMITE_POR_TERMINAL,
			0 AS PERMITE_ALTERAR_NA_LOJA,
			0 AS PERMITE_ALTERAR_NO_TERMINAL,
			0 AS ENVIA_PARA_REPRESENTANTE,
			0 AS PERMITE_POR_REPRESENTANTE,
			0 AS PERMITE_ALTERAR_NO_REPRESENTANTE

	IF NOT EXISTS(SELECT PARAMETRO FROM PARAMETROS WHERE PARAMETRO = 'EXIBE_TELA_OPCOES_PROMO')
	INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
	SELECT	'EXIBE_TELA_OPCOES_PROMO' AS PARAMETRO,
			CAST(0 AS DATETIME) PENULT_ATUALIZACAO,
			'.F.' AS VALOR_DEFAULT,
			GETDATE() AS ULT_ATUALIZACAO,
			'.F.' AS VALOR_ATUAL,
			'DEFINE SE EXIBE A TELA DE ESCOLHA DE PROMOÇÕES QUANDO HOUVER APENAS UMA OPÇÃO DE SELEÇÃO.' AS DESC_PARAMETRO,
			'L' AS TIPO_DADO,
			'' AS RANGE_VALOR_ATUAL,
			0 AS GLOBAL,
			'DEFINE SE EXIBE A TELA DE ESCOLHA DE PROMOÇÕES QUANDO HOUVER APENAS UMA OPÇÃO DE SELEÇÃO' AS NOTA_PROGRAMADOR,
			0 AS ESCOPO,
			0 AS POR_USUARIO_OK,
			0 AS PERMITE_POR_EMPRESA,
			1 AS ENVIA_PARA_LOJA,
			1 AS PERMITE_POR_LOJA,
			0 AS PERMITE_POR_TERMINAL,
			0 AS PERMITE_ALTERAR_NA_LOJA,
			0 AS PERMITE_ALTERAR_NO_TERMINAL,
			0 AS ENVIA_PARA_REPRESENTANTE,
			0 AS PERMITE_POR_REPRESENTANTE,
			0 AS PERMITE_ALTERAR_NO_REPRESENTANTE	

IF NOT EXISTS(SELECT PARAMETRO FROM PARAMETROS WHERE PARAMETRO = 'DESC_MOTOR_SOMA_DESC_ITEM')
	INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
	SELECT	'DESC_MOTOR_SOMA_DESC_ITEM' AS PARAMETRO,
			CAST(0 AS DATETIME) PENULT_ATUALIZACAO,
			'.F.' AS VALOR_DEFAULT,
			GETDATE() AS ULT_ATUALIZACAO,
			'.F.' AS VALOR_ATUAL,
			'DEFINE SE SOMARÁ O DESCONTO MANUAL DO ITEM COM O DESCONTO NO ITEM DE MOTOR DE PROMOÇÃO.' AS DESC_PARAMETRO,
			'L' AS TIPO_DADO,
			'' AS RANGE_VALOR_ATUAL,
			0 AS GLOBAL,
			'QUANDO .T. SOMA O DESCONTO JÁ CONCEDIDO NO ITEM COM O DESCONTO CALCULADO POR MOTOR DE PROMOÇÃO' AS NOTA_PROGRAMADOR,
			0 AS ESCOPO,
			0 AS POR_USUARIO_OK,
			0 AS PERMITE_POR_EMPRESA,
			1 AS ENVIA_PARA_LOJA,
			1 AS PERMITE_POR_LOJA,
			0 AS PERMITE_POR_TERMINAL,
			0 AS PERMITE_ALTERAR_NA_LOJA,
			0 AS PERMITE_ALTERAR_NO_TERMINAL,
			0 AS ENVIA_PARA_REPRESENTANTE,
			0 AS PERMITE_POR_REPRESENTANTE,
			0 AS PERMITE_ALTERAR_NO_REPRESENTANTE	

IF NOT EXISTS(SELECT PARAMETRO FROM PARAMETROS WHERE PARAMETRO = 'LINX_OMNI_PROMO_COMP_ID')
	INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
	SELECT	'LINX_OMNI_PROMO_COMP_ID' AS PARAMETRO,
			CAST(0 AS DATETIME) PENULT_ATUALIZACAO,
			'' AS VALOR_DEFAULT,
			GETDATE() AS ULT_ATUALIZACAO,
			'mod' AS VALOR_ATUAL,
			'HABILITA A INTERFACE DE MOTOR DE PROMOÇÃO DO LINX OMNI PROMO.' AS DESC_PARAMETRO,
			'C' AS TIPO_DADO,
			'' AS RANGE_VALOR_ATUAL,
			0 AS GLOBAL,
			'PARÂMETRO PARA INFORMAR O COMPANT ID QUE SERÁ UTILIZADO NO MOTOR DE PROMOÇÃO DO LINX OMNI PROMO.' AS NOTA_PROGRAMADOR,
			0 AS ESCOPO,
			0 AS POR_USUARIO_OK,
			0 AS PERMITE_POR_EMPRESA,
			1 AS ENVIA_PARA_LOJA,
			1 AS PERMITE_POR_LOJA,
			0 AS PERMITE_POR_TERMINAL,
			0 AS PERMITE_ALTERAR_NA_LOJA,
			0 AS PERMITE_ALTERAR_NO_TERMINAL,
			0 AS ENVIA_PARA_REPRESENTANTE,
			0 AS PERMITE_POR_REPRESENTANTE,
			0 AS PERMITE_ALTERAR_NO_REPRESENTANTE

 --Ajuste no parametro UTILIZA_PROMO_OMNI 
  --Ajuste no parametro UTILIZA_PROMO_OMNI 
IF EXISTS ( SELECT 1 FROM PARAMETROS WHERE PARAMETRO = 'UTILIZA_PROMO_OMNI')
BEGIN
	IF EXISTS(SELECT 1 FROM PARAMETROS WHERE PARAMETRO = 'UTILIZA_PROMO_OMNI' AND (PERMITE_ALTERAR_NO_TERMINAL <> 0 OR PERMITE_POR_TERMINAL <> 0)) 
	BEGIN
		UPDATE PARAMETROS SET PERMITE_ALTERAR_NO_TERMINAL = 0, PERMITE_POR_TERMINAL = 0  WHERE PARAMETRO = 'UTILIZA_PROMO_OMNI'
	END
	DELETE PARAMETROS_LOJA_TERMINAL WHERE PARAMETRO = 'UTILIZA_PROMO_OMNI'	
END

 
 
 
-- IF EXISTS ( SELECT 1 FROM PARAMETROS WHERE PARAMETRO = 'UTILIZA_PROMO_OMNI')
-- BEGIN
	-- IF EXISTS(SELECT 1 FROM PARAMETROS_LOJA WHERE PARAMETRO = 'UTILIZA_PROMO_OMNI' AND VALOR_ATUAL = '.T.') 
	-- BEGIN 
		-- UPDATE PARAMETROS SET PERMITE_ALTERAR_NO_TERMINAL = 0, PERMITE_POR_TERMINAL = 0, VALOR_ATUAL = '.T.'  WHERE PARAMETRO = 'UTILIZA_PROMO_OMNI'
	-- END
	-- ELSE
	-- BEGIN
	-- IF EXISTS(SELECT 1 FROM PARAMETROS WHERE PARAMETRO = 'UTILIZA_PROMO_OMNI' AND VALOR_ATUAL = '.T.') 
	-- BEGIN
		-- UPDATE PARAMETROS SET PERMITE_ALTERAR_NO_TERMINAL = 0, PERMITE_POR_TERMINAL = 0 ,VALOR_ATUAL = '.T.'  WHERE PARAMETRO = 'UTILIZA_PROMO_OMNI'
	-- END
	-- ELSE 
	   -- UPDATE PARAMETROS SET PERMITE_ALTERAR_NO_TERMINAL = 0, PERMITE_POR_TERMINAL = 0 ,VALOR_ATUAL = '.F.'  WHERE PARAMETRO = 'UTILIZA_PROMO_OMNI'
	-- END
		-- DELETE PARAMETROS_LOJA WHERE PARAMETRO = 'UTILIZA_PROMO_OMNI'
		-- DELETE PARAMETROS_LOJA_TERMINAL WHERE PARAMETRO = 'UTILIZA_PROMO_OMNI'	
-- END