IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_VENDA_PROMOCAO_CUPOM' AND COLUMN_NAME = 'VOUCHER_NUMBER')
	ALTER TABLE LOJA_VENDA_PROMOCAO_CUPOM ADD VOUCHER_NUMBER VARCHAR(150) NULL 

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_VENDA_PROMOCAO_CUPOM' AND COLUMN_NAME = 'COUPON_ID')
	ALTER TABLE LOJA_VENDA_PROMOCAO_CUPOM ADD COUPON_ID VARCHAR(150) NULL