---63094 - Inclusão da novas melhorias do Linx Update no produto LinxPOS 
IF NOT EXISTS(SELECT PARAMETRO FROM PARAMETROS WHERE PARAMETRO = 'AUTOUPDATER_DB_USERNAME')
	INSERT INTO PARAMETROS (PARAMETRO, DESC_PARAMETRO, PENULT_ATUALIZACAO, ULT_ATUALIZACAO, TIPO_DADO, VALOR_DEFAULT, VALOR_ATUAL, 
							GLOBAL, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL)
	VALUES ('AUTOUPDATER_DB_USERNAME','Informe o usuário com privilégios sysadmin que será utilizado no atualizador automático','20170401','20170401','C','','',0,1,1,0,0,0)

IF NOT EXISTS(SELECT PARAMETRO FROM PARAMETROS WHERE PARAMETRO = 'AUTOUPDATER_DB_PASSWORD')
	INSERT INTO PARAMETROS (PARAMETRO, DESC_PARAMETRO, PENULT_ATUALIZACAO, ULT_ATUALIZACAO, TIPO_DADO, VALOR_DEFAULT, VALOR_ATUAL, 
							GLOBAL, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL)
	VALUES ('AUTOUPDATER_DB_PASSWORD','Informe a senha do usuário cadastrado no parâmetro AUTOUPDATER_DB_PASSWORD para utilização do atualizador automático','20170401','20170401',
	'C','','',0,1,1,0,0,0)
