IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_PEDIDO_DEVOLUCAO' AND COLUMN_NAME = 'DATA_PARA_TRANSFERENCIA')
	ALTER TABLE LOJA_PEDIDO_DEVOLUCAO ADD DATA_PARA_TRANSFERENCIA DATETIME NULL DEFAULT GETDATE()

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_PEDIDO_ENTREGA' AND COLUMN_NAME = 'DATA_PARA_TRANSFERENCIA')
	ALTER TABLE LOJA_PEDIDO_ENTREGA ADD DATA_PARA_TRANSFERENCIA DATETIME NULL DEFAULT GETDATE()