if exists( select 1 from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = 'LOJA_CONTROLE_TEF' 
	AND COLUMN_NAME = 'ID_TEF' AND CHARACTER_MAXIMUM_LENGTH <> -1)
BEGIN
		ALTER TABLE LOJA_CONTROLE_TEF ALTER COLUMN ID_TEF VARCHAR(MAX)
END

if NOT exists( select 1 from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = 'LOJA_CONTROLE_TEF' 
	AND COLUMN_NAME = 'LX_HASH')
BEGIN
		ALTER TABLE LOJA_CONTROLE_TEF ADD LX_HASH VARCHAR(100)
END

if NOT exists( select 1 from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = 'LOJA_CONTROLE_TEF' 
	AND COLUMN_NAME = 'LICENCA_TEF')
BEGIN
		ALTER TABLE LOJA_CONTROLE_TEF ADD LICENCA_TEF VARCHAR(100)
END