CREATE FUNCTION [DBO].[FX_ENDERECO_CLIENTE_PEDIDO] (@PEDIDO INT, @CODIGO_FILIAL_ORIGEM INT)
	RETURNS @TABELA TABLE(CIDADE VARCHAR(35),UF CHAR(2))
AS
BEGIN

DECLARE @CODIGO_CLIENTE CHAR(14);
DECLARE @UF CHAR(2), @CIDADE VARCHAR(35);


SELECT @CODIGO_CLIENTE = (
							SELECT TOP 1 
							CODIGO_CLIENTE 
							FROM LOJA_PEDIDO (NOLOCK) 
							WHERE PEDIDO = @PEDIDO AND 												
							CODIGO_FILIAL_ORIGEM = @CODIGO_FILIAL_ORIGEM
						)

IF @CODIGO_CLIENTE IS NOT NULL
BEGIN
	SELECT @CIDADE = DBO.Fx_replace_caracter_especial_nfe(DEFAULT, CVE.CIDADE), @UF = CVE.UF
	FROM LOJA_PEDIDO LP (NOLOCK)
	LEFT JOIN LOJA_PEDIDO_ENTREGA LPE 
	ON LPE.PEDIDO = LP.PEDIDO AND LPE.CODIGO_FILIAL_ORIGEM = LP.CODIGO_FILIAL_ORIGEM	
	LEFT JOIN CLIENTE_VAR_ENDERECOS CVE
	ON LP.CODIGO_CLIENTE = CVE.CODIGO_CLIENTE AND LPE.ITEM_ENDERECO = CVE.ITEM_ENDERECO 
	WHERE LP.PEDIDO = @PEDIDO 

END

IF @CIDADE IS NULL OR @UF IS NULL
BEGIN
	SELECT @CIDADE = DBO.Fx_replace_caracter_especial_nfe(DEFAULT, CV.CIDADE), @UF = CV.UF
	FROM LOJA_PEDIDO LP
	INNER JOIN CLIENTES_VAREJO CV
	ON LP.CODIGO_CLIENTE = CV.CODIGO_CLIENTE 
	WHERE LP.PEDIDO = @PEDIDO 
	AND LP.CODIGO_FILIAL_ORIGEM = @CODIGO_FILIAL_ORIGEM
END

INSERT INTO @TABELA (CIDADE , UF) VALUES (@CIDADE ,  @UF)

RETURN
END