 IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[LJ_VALE_TROCA_OMNI]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[LJ_VALE_TROCA_OMNI](
	[ID_TRANSACAO] [int] IDENTITY(1,1) NOT NULL,
	[CODIGO_FILIAL] [char](6) NOT NULL,
	[TICKET] [char](8) NOT NULL,
	[DATA_VENDA] [datetime] NOT NULL,
	[TIPO_REQUISICAO] [int] NOT NULL,
	[DATA_HORA_TRANSACAO] [datetime] NULL,
	[TRANSACAO_INICIADA] [bit] NOT NULL,
	[TRANSACAO_CONCLUIDA] [bit] NOT NULL,
	[NUMERO_VALE_TROCA] [varchar](40) NOT NULL,
	[VALOR] [numeric](14, 2) NOT NULL,
	[NSU_CLIENTE] [varchar](20) NULL,
	[NSU_HOST] [varchar](20) NULL,
	[RESULTADO] [int] NOT NULL,
	[MENSAGEM_ERRO] [varchar](250) NULL
) ON [PRIMARY]
END



