IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[LX_CONFIG_BLOCOX]') AND TYPE IN (N'U'))

BEGIN
CREATE TABLE [DBO].[LX_CONFIG_BLOCOX](
	[UF] [CHAR](2) NOT NULL,
	[DATA_INICIO] DATE NOT NULL,
	[URL_ENVIO] [VARCHAR](MAX) NOT NULL,
	[URL_CONSULTA] [VARCHAR](MAX) NULL,
	[INATIVO] [BIT] NOT NULL DEFAULT 0,
	[DATA_PARA_TRANSFERENCIA] [DATETIME] NULL,
 CONSTRAINT [XPKLX_CONFIG_BLOCOX] PRIMARY KEY CLUSTERED 
(
	[UF]  ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

END;