CREATE TRIGGER [dbo].[LXU_FATURAMENTO_SEQUENCIAIS_AUDITORIA] ON [dbo].[FATURAMENTO_SEQUENCIAIS] FOR UPDATE NOT FOR REPLICATION 
AS 
--MODASP-2983 - Criação da trigger
DECLARE @SEQUENCIAL_ORIGINAL VARCHAR(50) , @SEQUENCIAL_ALTERADA VARCHAR(50),@DATA_CRIACAO DATETIME, @DATA_ALTERACAO DATETIME , @FILIAL VARCHAR(25) , @SERIE_NF VARCHAR(6)
SET @SEQUENCIAL_ORIGINAL = ''
SET @SEQUENCIAL_ALTERADA = ''
set @FILIAL = ''
set @SERIE_NF = ''
set @DATA_CRIACAO = ''
set @DATA_ALTERACAO = ''

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'FATURAMENTO_SEQUENCIAIS_AUDITORIA')
BEGIN 
	CREATE TABLE FATURAMENTO_SEQUENCIAIS_AUDITORIA (APLICATIVO VARCHAR(200) , USUARIO VARCHAR(300) ,DATA_CRIACAO DATETIME ,  
	DATA_ALTERACAO DATETIME , SEQUENCIAL_ORIGINAL VARCHAR (50) , SEQUENCIAL_ALTERADA VARCHAR(50), FILIAL varchar(25), SERIE_NF varchar(6) )  
END 
IF UPDATE(SEQUENCIAL)
BEGIN

Select @SEQUENCIAL_ORIGINAL = DELETED.SEQUENCIAL , @SEQUENCIAL_ALTERADA = INSERTED.SEQUENCIAL From INSERTED, FATURAMENTO_SEQUENCIAIS, DELETED 


IF (CAST(@SEQUENCIAL_ALTERADA AS INT) - CAST(@SEQUENCIAL_ORIGINAL AS INT)) > 1
	BEGIN 
  
		Select @SEQUENCIAL_ORIGINAL = DELETED.SEQUENCIAL , @SEQUENCIAL_ALTERADA = INSERTED.SEQUENCIAL , @SERIE_NF = INSERTED.SERIE_NF, @FILIAL = INSERTED.FILIAL 
		From INSERTED, FATURAMENTO_SEQUENCIAIS, DELETED 
		INSERT INTO FATURAMENTO_SEQUENCIAIS_AUDITORIA VALUES (APP_NAME(),USER_NAME(), @DATA_CRIACAO,  GETDATE() ,@SEQUENCIAL_ORIGINAL , @SEQUENCIAL_ALTERADA ,@FILIAL, @SERIE_NF )

	END 
END 