IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'FATURAMENTO_SEQUENCIAIS_AUDITORIA')
BEGIN 
	CREATE TABLE FATURAMENTO_SEQUENCIAIS_AUDITORIA (APLICATIVO VARCHAR(200) , USUARIO VARCHAR(300) ,DATA_CRIACAO DATETIME ,  
	DATA_ALTERACAO DATETIME , SEQUENCIAL_ORIGINAL VARCHAR (50) , SEQUENCIAL_ALTERADA VARCHAR(50), FILIAL varchar(25), SERIE_NF varchar(6) )  
END 
