
CREATE VIEW [dbo].[W_IMPRESSAO_NFE_LOG]
AS
--	 TP5639147	- GILVANO SANTOS - #1# - (26/06/2015) - IMPLANTAÇÃO CF-E SAT, INCLUSÃO DO "UNION ALL" PARA VIEW RECONHECER AS INFORMAÇÕES DAS TABELAS LOJA_CF_SAT...
--	MODASP-2773	- DBA\Artuzo	 - #02# - Ajuste de performance no código.

SELECT	A.CODIGO_FILIAL, A.NF_NUMERO, A.SERIE_NF, 
		A.EDI_REFERENCIA_ARQUIVO ,
		C.DESC_LAYOUT, A.COD_LAYOUT, 
		A.LX_STATUS, A.ID_EDI_ARQUIVO, D.ID_EDI_ARQUIVO_LOG, D.ID_PROCESSO, D.ITEM_PROCESSO, 
		E.NOME_PROCESSO, F.DATA_INICIO, F.DATA_FIM, 
		REPLACE(REPLACE(F.MENSAGEM, CHAR(13) + CHAR(10) + 'Error: 30002 Message: ', ''), 'Proc: ' + RTRIM(E.NOME_PROCESSO), '') AS MENSAGEM, 
		F.STATUS_PROCESSO, A.GUID_VENDA_SAT 
FROM EDI_ARQUIVO A (NOLOCK) 
INNER JOIN LOJA_NOTA_FISCAL b (NOLOCK) 
	ON A.CODIGO_FILIAL = B.CODIGO_FILIAL AND A.NF_NUMERO = B.NF_NUMERO AND A.SERIE_NF = B.SERIE_NF
INNER JOIN EDI_LAYOUT C (NOLOCK) 
	ON A.COD_LAYOUT = C.COD_LAYOUT 
INNER JOIN EDI_ARQUIVO_LOG D (NOLOCK) 
	ON A.ID_EDI_ARQUIVO = D.ID_EDI_ARQUIVO 
INNER JOIN PROCESSOS_SISTEMA E (NOLOCK) 
	ON D.ID_PROCESSO = E.ID_PROCESSO 
INNER JOIN PROCESSOS_SISTEMA_ATIVIDADES F (NOLOCK) 
	ON D.ID_PROCESSO = F.ID_PROCESSO AND D.ITEM_PROCESSO = F.ITEM_PROCESSO 
WHERE CHAVE_NFE IS NULL

UNION ALL
 
SELECT	A.CODIGO_FILIAL, A.NF_NUMERO, A.SERIE_NF, A.EDI_REFERENCIA_ARQUIVO, C.DESC_LAYOUT, A.COD_LAYOUT, 
		A.LX_STATUS, A.ID_EDI_ARQUIVO, D.ID_EDI_ARQUIVO_LOG, D.ID_PROCESSO, D.ITEM_PROCESSO, 
		E.NOME_PROCESSO, F.DATA_INICIO, F.DATA_FIM, 
		REPLACE(REPLACE(F.MENSAGEM, CHAR(13) + CHAR(10) + 'Error: 30002 Message: ', ''), 'Proc: ' + RTRIM(E.NOME_PROCESSO), '') AS MENSAGEM, 
		F.STATUS_PROCESSO, A.GUID_VENDA_SAT
FROM EDI_ARQUIVO A (NOLOCK) 
INNER JOIN LOJA_NOTA_FISCAL b (NOLOCK) 
	ON A.EDI_REFERENCIA_ARQUIVO = B.CHAVE_NFE 
INNER JOIN EDI_LAYOUT C (NOLOCK) 
	ON A.COD_LAYOUT = C.COD_LAYOUT 
INNER JOIN EDI_ARQUIVO_LOG D (NOLOCK) ON A.ID_EDI_ARQUIVO = D.ID_EDI_ARQUIVO 
INNER JOIN PROCESSOS_SISTEMA E (NOLOCK) ON D.ID_PROCESSO = E.ID_PROCESSO 
INNER JOIN PROCESSOS_SISTEMA_ATIVIDADES F (NOLOCK) ON D.ID_PROCESSO = F.ID_PROCESSO AND D.ITEM_PROCESSO = F.ITEM_PROCESSO

UNION ALL

SELECT	A.CODIGO_FILIAL, A.NF_NUMERO, A.SERIE_NF, A.EDI_REFERENCIA_ARQUIVO, C.DESC_LAYOUT, A.COD_LAYOUT, 
		A.LX_STATUS, A.ID_EDI_ARQUIVO, D.ID_EDI_ARQUIVO_LOG, D.ID_PROCESSO, D.ITEM_PROCESSO, 
		E.NOME_PROCESSO, F.DATA_INICIO, F.DATA_FIM, 
		REPLACE(REPLACE(F.MENSAGEM, CHAR(13) + CHAR(10) + 'Error: 30002 Message: ', ''), 'Proc: ' + RTRIM(E.NOME_PROCESSO), '') AS MENSAGEM, 
		F.STATUS_PROCESSO, A.GUID_VENDA_SAT
FROM EDI_ARQUIVO A (NOLOCK) 
INNER JOIN LOJA_CF_SAT b (NOLOCK) --#02# 
	ON A.GUID_VENDA_SAT = B.GUID_VENDA_SAT AND A.CODIGO_FILIAL = B.CODIGO_FILIAL --#02# 
INNER JOIN EDI_LAYOUT C (NOLOCK)
	ON A.COD_LAYOUT = C.COD_LAYOUT 
INNER JOIN EDI_ARQUIVO_LOG D (NOLOCK) 
	ON A.ID_EDI_ARQUIVO = D.ID_EDI_ARQUIVO 
INNER JOIN PROCESSOS_SISTEMA E (NOLOCK) 
	ON D.ID_PROCESSO = E.ID_PROCESSO 
INNER JOIN PROCESSOS_SISTEMA_ATIVIDADES F (NOLOCK) 
	ON D.ID_PROCESSO = F.ID_PROCESSO AND D.ITEM_PROCESSO = F.ITEM_PROCESSO
