
IF NOT EXISTS (SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID('DBO.EDI_ARQUIVO') AND NAME = 'IX1001_EDI_ARQUIVO')
CREATE INDEX IX1001_EDI_ARQUIVO
ON EDI_ARQUIVO (CODIGO_FILIAL, NF_NUMERO, SERIE_NF, EDI_REFERENCIA_ARQUIVO )
INCLUDE (COD_LAYOUT,LX_STATUS)

IF NOT EXISTS (SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID('DBO.EDI_ARQUIVO') AND NAME = 'IX1002_EDI_ARQUIVO')
CREATE NONCLUSTERED INDEX IX1002_EDI_ARQUIVO
ON [DBO].[EDI_ARQUIVO] ([EDI_REFERENCIA_ARQUIVO])
INCLUDE (COD_LAYOUT,LX_STATUS,CODIGO_FILIAL, NF_NUMERO,SERIE_NF)

IF NOT EXISTS (SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID('DBO.EDI_ARQUIVO_LOG') AND NAME = 'IX1001_EDI_ARQUIVO_LOG')
CREATE NONCLUSTERED INDEX [IX1001_EDI_ARQUIVO_LOG]
ON [DBO].[EDI_ARQUIVO_LOG] ([ID_EDI_ARQUIVO])
INCLUDE ([ID_EDI_ARQUIVO_LOG],[ID_PROCESSO],[ITEM_PROCESSO])

IF NOT EXISTS (SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID('DBO.LOJA_NOTA_FISCAL') AND NAME = 'IX1002_LOJA_NOTA_FISCAL')
CREATE NONCLUSTERED INDEX [IX1002_LOJA_NOTA_FISCAL]
ON [DBO].[LOJA_NOTA_FISCAL] ([CHAVE_NFE])
