--13/11/2019 - MODASP-3386 replicação para SPK2 #1#
CREATE VIEW W_PENDENCIAS_MFE AS       
(      
SELECT     
A.TERMINAL,    
A.LANCAMENTO_CAIXA,    
A.CODIGO_FILIAL,    
A.PARCELA,    
A.ID_PAGAMENTO,    
A.ID_FILA,    
A.ID_REFERENCIA_CLIENT,    
A.RETORNO,    
A.INDICA_CARTAO_CONCILIADO,    
ISNULL(A.CSTAT,'') AS CSTAT,    
A.ID_PAGAMENTO_FINAL,     
A.PENDENTE,        
A.ID_REFERENCIA_CLIENT_INICIAL,                                                                                                                                                                                                                                
  
                       
C.CHAVE_CFE AS CHAVE_ACESSO ,     
C.CF_NUMERO ,C.SERIE_NF,     
CONVERT(VARCHAR(10), C.DATA_HORA_EMISSAO, 103) AS EMISSAO     
FROM LOJA_VENDA_PARCELAS_MFE A (NOLOCK)      
INNER JOIN LOJA_VENDA B (NOLOCK) ON B.LANCAMENTO_CAIXA = A.LANCAMENTO_CAIXA AND A.TERMINAL = B.TERMINAL AND A.CODIGO_FILIAL = B.CODIGO_FILIAL      
INNER JOIN LOJA_CF_SAT C (NOLOCK) ON C.LANCAMENTO_CAIXA = A.LANCAMENTO_CAIXA AND A.TERMINAL = C.TERMINAL AND A.CODIGO_FILIAL = C.CODIGO_FILIAL      
WHERE A.PENDENTE  = 1 AND B.VALOR_CANCELADO = 0 AND B.TOTAL_QTDE_CANCELADA = 0  AND CF_NUMERO IS NOT NULL AND CHAVE_CFE IS NOT NULL
AND C.STATUS_CFE NOT IN (5,49,59) -- #1#
)
 