--CREATE TRIGGER [dbo].[LXUC_PARAMETROS_LOJA_TERMINAL] 
--			ON [dbo].[PARAMETROS_LOJA_TERMINAL] 
-- WITH ENCRYPTION 
--   AFTER UPDATE  
--       AS
--       BEGIN
             
                    
--      IF PROGRAM_NAME() NOT IN ('LINXPOS','LINXPOWS','LINXPOS MANAGER', 'LINXPOS.SERVICEPACK', 'DATASYNC', 'LINX-ETL')
            

--            DECLARE @MSG1 VARCHAR(MAX), @PARAMETRO1 VARCHAR(MAX)
--            DECLARE @MSG2 VARCHAR(MAX), @PARAMETRO2 VARCHAR(MAX)
--			DECLARE @MSG3 VARCHAR(MAX), @PARAMETRO3 VARCHAR(MAX)


			
--        BEGIN      
			  
		
--			IF EXISTS(SELECT A.VALOR_ATUAL FROM INSERTED AS A 
--			INNER JOIN PARAMETROS B ON A.PARAMETRO = B.PARAMETRO 
--			WHERE B.TIPO_DADO = 'L' AND(UPPER(A.VALOR_ATUAL) NOT IN('.F.','.T.')))
			
--			SET @PARAMETRO1 = (SELECT TOP(1) A.PARAMETRO FROM INSERTED AS A 
--			INNER JOIN PARAMETROS B ON A.PARAMETRO = B.PARAMETRO 
--			WHERE B.TIPO_DADO = 'L' AND(UPPER(A.VALOR_ATUAL) NOT IN('.F.','.T.')))
		
--            SET @MSG1 = 'ERRO AO ATUALIZAR O ('+ @PARAMETRO1 +'), O TIPO DE DADO É LOGICO E NÃO PODE SER PREENCHIDO COM VALOR DIFERENTE DE .T. OU .F. .'
--                    RAISERROR(@MSG1, 16,1);
--		END
       

--	    BEGIN
		       
--       IF EXISTS(SELECT A.VALOR_ATUAL FROM INSERTED AS A 
--				INNER JOIN PARAMETROS B 
--				ON A.PARAMETRO = B.PARAMETRO 
--				WHERE B.TIPO_DADO = 'N' 
--					AND (ISNUMERIC(A.VALOR_ATUAL) = 0
--					OR A.VALOR_ATUAL like '% %' 
--					OR A.VALOR_ATUAL like '%,%' 
--					OR A.VALOR_ATUAL = ''))
					
--				SET @PARAMETRO2 = (SELECT TOP(1) A.PARAMETRO FROM INSERTED AS A 
--				INNER JOIN PARAMETROS B 
--				ON A.PARAMETRO = B.PARAMETRO 
--				WHERE B.TIPO_DADO = 'N' 
--					AND (ISNUMERIC(A.VALOR_ATUAL) = 0
--					OR A.VALOR_ATUAL like '% %' 
--					OR A.VALOR_ATUAL like '%,%' 
--					OR A.VALOR_ATUAL = ''))

--		  SET @MSG2 = 'ERRO AO ATUALIZAR O ('+ @PARAMETRO2 +'), O TIPO DE DADO NUMERICO NÃO PODE CONTER CARACTERES.'
		  
--                    RAISERROR(@MSG2, 16,1);
--		END



--		BEGIN

--				IF EXISTS(SELECT A.VALOR_ATUAL FROM INSERTED AS A 
--				INNER JOIN PARAMETROS B 
--				ON A.PARAMETRO = B.PARAMETRO 
--				 WHERE B.TIPO_DADO = 'I' 
--						AND (ISNUMERIC(A.VALOR_ATUAL) = 0
--						OR A.VALOR_ATUAL like '% %' 
--					    OR A.VALOR_ATUAL like '%,%'  
--						OR A.VALOR_ATUAL like '%.%'
--						OR A.VALOR_ATUAL like '%-%'
--						OR A.VALOR_ATUAL = ''))	
					

--			SET @PARAMETRO3 =(SELECT TOP(1) A.PARAMETRO FROM INSERTED AS A 
--				INNER JOIN PARAMETROS B 
--				ON A.PARAMETRO = B.PARAMETRO 
--				 WHERE B.TIPO_DADO = 'I' 
--						AND (ISNUMERIC(A.VALOR_ATUAL) = 0
--						OR A.VALOR_ATUAL like '% %' 
--					    OR A.VALOR_ATUAL like '%,%'  
--						OR A.VALOR_ATUAL like '%.%'
--						OR A.VALOR_ATUAL like '%-%'
--						OR A.VALOR_ATUAL = ''))

--		SET @MSG3 = 'ERRO AO ATUALIZAR O ('+ @PARAMETRO3 +'), O TIPO DE DADO INTEIRO NÃO PODE CONTER CARACTERES.'
--					RAISERROR(@MSG3, 16,1);
--		END	


--   END    
