

IF EXISTS (SELECT 1
			FROM   [INFORMATION_SCHEMA].[COLUMNS]
			WHERE  [TABLE_NAME] = 'LOJA_PEDIDO_PGTO'
					AND [COLUMN_NAME] = 'CHEQUE_CARTAO'
					AND CHARACTER_MAXIMUM_LENGTH < 36)
BEGIN 
	ALTER TABLE [DBO].[LOJA_PEDIDO_PGTO] ALTER COLUMN CHEQUE_CARTAO VARCHAR(36) 
END

