Create PROCEDURE [dbo].[LX_LJ_CONSULTA_PRECO] (@FILIAL VARCHAR(25), @CODIGO_TAB_PRECO VARCHAR(2), @CODIGO_BARRA VARCHAR(25) = NULL, @PRODUTO VARCHAR(12) = NULL, @COR_PRODUTO VARCHAR(10) = NULL, @DATA DATETIME = NULL, @FILTRO_PRODUTO VARCHAR(2000) = NULL, @EXIBE_DETALHE BIT = 0)
AS

-- 15/06/2020 - Wendel  Crespigio - SUSTSP-485 - #4# - Tratamento para valores incorretos de campanhar desativadas. 
-- 07/01/2016 - Eder Silva        - DM 1186    - #3# - Inclusas colunas Inicio e Fim_Promocao para tratar a pesquisa por 'descrição do produto' na tela. 
-- 12/11/2014 - Victor Kajiyama   - TP7054016  - #2# - Caso não haja período de fim, o sistema deve prorrogar a promoção indefinidamente. Caso não haja período de início, a promoção tem que entrar em vigor na hora. Também estaremos validando códigos de barras. 
-- 20/08/2014 - Victor Kajiyama   - TP6014651  - #1# - Inserindo a validação da data início e fim de promoções configuradas na retaguarda. 

BEGIN
	SET NOCOUNT ON
	
	DECLARE @TAMANHO TINYINT, @SELECT1 VARCHAR(8000), @SELECT2 VARCHAR(8000), @SELECT3 VARCHAR(8000), 
	@SELECT4 VARCHAR(8000), @SELECT5 VARCHAR(8000), @DETALHES VARCHAR(1000), 
	@FILTRO VARCHAR(500), @JOIN VARCHAR(100), @FILTRO_DATA VARCHAR(12), 
	@SELECTLIQ1 VARCHAR(8000), @SELECTLIQ2 VARCHAR(8000), @SELECTLIQ3 VARCHAR(8000), @SELECTLIQ4 VARCHAR(8000), @SELECTLIQ5 VARCHAR(8000), @PROMOCAO_PRODUTOS_PRECOS BIT, @PROMOCAO_PRODUTOS_PRECO_COR BIT , @PROMOCAO_PRODUTOS_PRECO_FILIAL BIT,
	@FIM_DATA DATETIME , @PRECO_LIQUIDO1 AS NUMERIC (14,2),@PRECO_LIQUIDO2 AS NUMERIC (14,2),@PRECO_LIQUIDO3 AS NUMERIC (14,2) , @PRECO_LIQUIDO4  AS NUMERIC (14,2)--#3# #4#

	SELECT @TAMANHO = 1, @SELECT1 = '', @SELECT2 = '', @SELECT3 = '', @SELECT4 = '', 
		@SELECT5 = '', @DETALHES = '', @FILTRO = '', @JOIN = '', 
		@FILTRO_DATA = CONVERT(VARCHAR(12), ISNULL(@DATA, GETDATE())), 
		@SELECTLIQ1 = '', @SELECTLIQ2 = '', @SELECTLIQ3 = '', @SELECTLIQ4 = '', @SELECTLIQ5 = '',
		@PROMOCAO_PRODUTOS_PRECOS = 0, @PROMOCAO_PRODUTOS_PRECO_COR = 0, @PROMOCAO_PRODUTOS_PRECO_FILIAL = 0,
		@FIM_DATA = GETDATE() + DAY(0) --#3#
		
	IF EXISTS (	SELECT	1 -- #1 - Veficando se a data atual está entre data de início e fim da promoção na tabela PRODUTOS_PRECOS
				FROM	PRODUTOS_PRECOS
				WHERE	GETDATE() BETWEEN isnull(INICIO_PROMOCAO, '19000101') AND ISNULL(FIM_PROMOCAO,GETDATE()+DAY(0)) AND -- #2 - Caso não hajam datas, o sistema deve atribuir uma automaticamente. 
						PRODUTO = @PRODUTO AND
						CODIGO_TAB_PRECO = @CODIGO_TAB_PRECO AND
						(PROMOCAO_DESCONTO IS NOT NULL OR PROMOCAO_DESCONTO <> 0)
				union all
				SELECT	1 -- #2 - Efetuando a busca do produto via código de barras. 
				FROM	PRODUTOS_PRECOS
				join	produtos_barra on produtos_precos.PRODUTO = PRODUTOS_BARRA.PRODUTO
				WHERE	GETDATE() BETWEEN isnull(INICIO_PROMOCAO, '19000101') AND ISNULL(FIM_PROMOCAO,GETDATE()+DAY(0)) AND -- #2 - Caso não hajam datas, o sistema deve atribuir uma automaticamente. 
						CODIGO_BARRA = @CODIGO_BARRA AND
						CODIGO_TAB_PRECO = @CODIGO_TAB_PRECO AND
						(PROMOCAO_DESCONTO IS NOT NULL OR PROMOCAO_DESCONTO <> 0)) 
	BEGIN
		SET @PROMOCAO_PRODUTOS_PRECOS = 1 -- #1 Caso a promoção estiver ativa, atribui o valor "1" à variável. 
	END
	
	IF EXISTS (	SELECT	1 -- #1 - Veficando se a data atual está entre data de início e fim da promoção na tabela PRODUTOS_PRECOS_COR
				FROM	PRODUTOS_PRECO_COR
				WHERE	GETDATE() BETWEEN isnull(INICIO_PROMOCAO, '19000101') AND ISNULL(FIM_PROMOCAO,GETDATE()+DAY(0)) AND -- #2 - Caso não hajam datas, o sistema deve atribuir uma automaticamente. 
						PRODUTO = @PRODUTO AND
						CODIGO_TAB_PRECO = @CODIGO_TAB_PRECO AND
						INICIO_PROMOCAO IS NOT NULL AND
						FIM_PROMOCAO IS NOT NULL 
				union all
				SELECT	1 -- #1 - Veficando se a data atual está entre data de início e fim da promoção na tabela PRODUTOS_PRECOS
				FROM	PRODUTOS_PRECO_COR
				join	produtos_barra on PRODUTOS_PRECO_COR.PRODUTO = PRODUTOS_BARRA.PRODUTO
				WHERE	GETDATE() BETWEEN isnull(INICIO_PROMOCAO, '19000101') AND ISNULL(FIM_PROMOCAO,GETDATE()+DAY(0)) AND -- #2 - Caso não hajam datas, o sistema deve atribuir uma automaticamente. 
						CODIGO_BARRA = @CODIGO_BARRA AND
						CODIGO_TAB_PRECO = @CODIGO_TAB_PRECO AND
						INICIO_PROMOCAO IS NOT NULL AND
						FIM_PROMOCAO IS NOT NULL ) 
	BEGIN
		SET @PROMOCAO_PRODUTOS_PRECO_COR = 1 -- #1 Caso a promoção estiver ativa, atribui o valor "1" à variável. 
	END
	
	IF EXISTS (	SELECT	1
				FROM	PRODUTOS_PRECO_FILIAL -- #1 - Veficando se a data atual está entre data de início e fim da promoção na tabela PRODUTOS_PRECO_FILIAL
				WHERE	GETDATE() BETWEEN isnull(INICIO_PROMOCAO, '19000101') AND ISNULL(FIM_PROMOCAO,GETDATE()+DAY(0)) AND -- #2 - Caso não hajam datas, o sistema deve atribuir uma automaticamente. 
						PRODUTO = @PRODUTO AND
						CODIGO_TAB_PRECO = @CODIGO_TAB_PRECO AND
						INICIO_PROMOCAO IS NOT NULL AND
						FIM_PROMOCAO IS NOT NULL 
				union all
				SELECT	1 -- #1 - Veficando se a data atual está entre data de início e fim da promoção na tabela PRODUTOS_PRECOS
				FROM	PRODUTOS_PRECO_FILIAL
				join	produtos_barra on PRODUTOS_PRECO_FILIAL.PRODUTO = PRODUTOS_BARRA.PRODUTO
				WHERE	GETDATE() BETWEEN isnull(INICIO_PROMOCAO, '19000101') AND ISNULL(FIM_PROMOCAO,GETDATE()+DAY(0)) AND -- #2 - Caso não hajam datas, o sistema deve atribuir uma automaticamente. 
						CODIGO_BARRA = @CODIGO_BARRA AND
						CODIGO_TAB_PRECO = @CODIGO_TAB_PRECO AND
						INICIO_PROMOCAO IS NOT NULL AND
						FIM_PROMOCAO IS NOT NULL ) 
	BEGIN
		SET @PROMOCAO_PRODUTOS_PRECO_FILIAL = 1 -- #1 Caso a promoção estiver ativa, atribui o valor "1" à variável. 
	END

	IF @CODIGO_BARRA IS NOT NULL
		SELECT 
			@JOIN = ' INNER JOIN PRODUTOS_BARRA H ON A.PRODUTO = H.PRODUTO AND B.COR_PRODUTO = H.COR_PRODUTO ', 
			@FILTRO = ' AND H.CODIGO_BARRA = ''' + @CODIGO_BARRA + ''''

	IF @PRODUTO IS NOT NULL
		SELECT 
			@FILTRO = @FILTRO + ' AND A.PRODUTO = ''' + @PRODUTO + ''''

	IF @COR_PRODUTO IS NOT NULL
		SELECT
			@FILTRO = @FILTRO + ' AND B.COR_PRODUTO = ''' + @COR_PRODUTO + ''''

	IF @FILTRO_PRODUTO IS NOT NULL
		SELECT 
			@FILTRO = @FILTRO + ' AND ' + @FILTRO_PRODUTO

	IF @EXIBE_DETALHE = 1
		SET @DETALHES = ', A.OBS '

		SELECT @PRECO_LIQUIDO1 =  case when FIM_PROMOCAO+DAY(0) > getdate() then PRECO_LIQUIDO1 else 0 end ,
		@PRECO_LIQUIDO2 = case when FIM_PROMOCAO+DAY(0) > getdate() then PRECO_LIQUIDO2 else 0 end,
		@PRECO_LIQUIDO3 = case when FIM_PROMOCAO+DAY(0) > getdate() then PRECO_LIQUIDO3 else 0 end,
		@PRECO_LIQUIDO4 = case when FIM_PROMOCAO+DAY(0) > getdate() then PRECO_LIQUIDO3 else 0 end FROM PRODUTOS_PRECO_FILIAL WHERE FILIAL = @FILIAL
		AND PRODUTO = @PRODUTO

UPDATE PRODUTOS_PRECO_FILIAL SET PRECO_LIQUIDO1 = @PRECO_LIQUIDO1 WHERE @PRECO_LIQUIDO1 <> PRECO_LIQUIDO1 
AND  FILIAL = @FILIAL
AND PRODUTO = @PRODUTO

UPDATE PRODUTOS_PRECO_FILIAL SET PRECO_LIQUIDO2 = @PRECO_LIQUIDO2 WHERE @PRECO_LIQUIDO2 <> PRECO_LIQUIDO2
AND  FILIAL = @FILIAL
AND PRODUTO = @PRODUTO

UPDATE PRODUTOS_PRECO_FILIAL SET PRECO_LIQUIDO3 = @PRECO_LIQUIDO3 WHERE @PRECO_LIQUIDO3 <> PRECO_LIQUIDO3 
AND  FILIAL = @FILIAL
AND PRODUTO = @PRODUTO

UPDATE PRODUTOS_PRECO_FILIAL SET PRECO_LIQUIDO4 = @PRECO_LIQUIDO4 WHERE @PRECO_LIQUIDO4 <> PRECO_LIQUIDO4 
AND  FILIAL = @FILIAL
AND PRODUTO = @PRODUTO

	WHILE @TAMANHO <= 10
	BEGIN
		IF @PROMOCAO_PRODUTOS_PRECOS = 0 AND @PROMOCAO_PRODUTOS_PRECO_COR = 0 AND @PROMOCAO_PRODUTOS_PRECO_FILIAL = 0 -- #1 - Caso a promoção NÃO esteja ativa em nenhuma tabela de preços. 
		BEGIN
			SELECT	@SELECTLIQ1 = @SELECTLIQ1 + ', PRECOLIQTAM' + CONVERT(VARCHAR, @TAMANHO) + ' = CONVERT(NUMERIC(14, 2), ISNULL(CASE WHEN ' + CONVERT(VARCHAR, @TAMANHO) + ' <= ISNULL(TAMANHOS_DIGITADOS, NUMERO_TAMANHOS) THEN CASE VARIA_PRECO_TAM WHEN 1 THEN CASE SUBSTRING(PONTEIRO_PRECO_TAM, ' + CONVERT(VARCHAR, @TAMANHO) + ', 1) WHEN 1 THEN ISNULL(E.PRECO1, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO1 ELSE C.PRECO1 END) WHEN 2 THEN ISNULL(E.PRECO2, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO2 ELSE C.PRECO2 END) WHEN 3 THEN ISNULL(E.PRECO3, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO3 ELSE C.PRECO3 END) WHEN 4 THEN ISNULL(E.PRECO4, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO4 ELSE C.PRECO4 END) END ELSE ISNULL(E.PRECO1, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO1 ELSE C.PRECO1 END) END ELSE CONVERT(NUMERIC(14, 2), 0) END, 0))'
		END
		
		IF @PROMOCAO_PRODUTOS_PRECOS = 1 OR @PROMOCAO_PRODUTOS_PRECO_COR = 1 OR @PROMOCAO_PRODUTOS_PRECO_FILIAL = 1 -- #1 - Caso a promoção ESTEJA ativa em nenhuma tabela de preços. 
		BEGIN
			SELECT	@SELECTLIQ1 = @SELECTLIQ1 + ', PRECOLIQTAM' + CONVERT(VARCHAR, @TAMANHO) + ' = CONVERT(NUMERIC(14, 2), ISNULL(CASE WHEN ' + CONVERT(VARCHAR, @TAMANHO) + ' <= ISNULL(TAMANHOS_DIGITADOS, NUMERO_TAMANHOS) THEN CASE VARIA_PRECO_TAM WHEN 1 THEN CASE SUBSTRING(PONTEIRO_PRECO_TAM, ' + CONVERT(VARCHAR, @TAMANHO) + ', 1) WHEN 1 THEN ISNULL(E.PRECO_LIQUIDO1, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO_LIQUIDO1 ELSE C.PRECO_LIQUIDO1 END) WHEN 2 THEN ISNULL(E.PRECO_LIQUIDO2, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO_LIQUIDO2 ELSE C.PRECO_LIQUIDO2 END) WHEN 3 THEN ISNULL(E.PRECO_LIQUIDO3, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO_LIQUIDO3 ELSE C.PRECO_LIQUIDO3 END) WHEN 4 THEN ISNULL(E.PRECO_LIQUIDO4, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO_LIQUIDO4 ELSE C.PRECO_LIQUIDO4 END) END ELSE ISNULL(E.PRECO_LIQUIDO1, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO_LIQUIDO1 ELSE C.PRECO_LIQUIDO1 END) END ELSE CONVERT(NUMERIC(14, 2), 0) END, 0))'
		END
		
		SELECT
			@SELECT1 = @SELECT1 + ', PRECOTAM' + CONVERT(VARCHAR, @TAMANHO) + ' = CONVERT(NUMERIC(14, 2), ISNULL(CASE WHEN ' + CONVERT(VARCHAR, @TAMANHO) + ' <= ISNULL(TAMANHOS_DIGITADOS, NUMERO_TAMANHOS) THEN CASE VARIA_PRECO_TAM WHEN 1 THEN CASE SUBSTRING(PONTEIRO_PRECO_TAM, ' + CONVERT(VARCHAR, @TAMANHO) + ', 1) WHEN 1 THEN ISNULL(E.PRECO1, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO1 ELSE C.PRECO1 END) WHEN 2 THEN ISNULL(E.PRECO2, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO2 ELSE C.PRECO2 END) WHEN 3 THEN ISNULL(E.PRECO3, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO3 ELSE C.PRECO3 END) WHEN 4 THEN ISNULL(E.PRECO4, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO4 ELSE C.PRECO4 END) END ELSE ISNULL(E.PRECO1, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO1 ELSE C.PRECO1 END) END ELSE CONVERT(NUMERIC(14, 2), 0) END, 0))', 
			@TAMANHO = @TAMANHO + 1
	END

	WHILE @TAMANHO <= 20
	BEGIN
		IF @PROMOCAO_PRODUTOS_PRECOS = 0 AND @PROMOCAO_PRODUTOS_PRECO_COR = 0 AND @PROMOCAO_PRODUTOS_PRECO_FILIAL = 0 -- #1 - Caso a promoção NÃO esteja ativa em nenhuma tabela de preços. 
		BEGIN
			SELECT	@SELECTLIQ2 = @SELECTLIQ2 + ', PRECOLIQTAM' + CONVERT(VARCHAR, @TAMANHO) + ' = CONVERT(NUMERIC(14, 2), ISNULL(CASE WHEN ' + CONVERT(VARCHAR, @TAMANHO) + ' <= ISNULL(TAMANHOS_DIGITADOS, NUMERO_TAMANHOS) THEN CASE VARIA_PRECO_TAM WHEN 1 THEN CASE SUBSTRING(PONTEIRO_PRECO_TAM, ' + CONVERT(VARCHAR, @TAMANHO) + ', 1) WHEN 1 THEN ISNULL(E.PRECO1, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO1 ELSE C.PRECO1 END) WHEN 2 THEN ISNULL(E.PRECO2, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO2 ELSE C.PRECO2 END) WHEN 3 THEN ISNULL(E.PRECO3, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO3 ELSE C.PRECO3 END) WHEN 4 THEN ISNULL(E.PRECO4, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO4 ELSE C.PRECO4 END) END ELSE ISNULL(E.PRECO1, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO1 ELSE C.PRECO1 END) END ELSE CONVERT(NUMERIC(14, 2), 0) END, 0))'
		END
		
		IF @PROMOCAO_PRODUTOS_PRECOS = 1 OR @PROMOCAO_PRODUTOS_PRECO_COR = 1 OR @PROMOCAO_PRODUTOS_PRECO_FILIAL = 1 -- #1 - Caso a promoção ESTEJA ativa em nenhuma tabela de preços. 
		BEGIN
			SELECT	@SELECTLIQ2 = @SELECTLIQ2 + ', PRECOLIQTAM' + CONVERT(VARCHAR, @TAMANHO) + ' = CONVERT(NUMERIC(14, 2), ISNULL(CASE WHEN ' + CONVERT(VARCHAR, @TAMANHO) + ' <= ISNULL(TAMANHOS_DIGITADOS, NUMERO_TAMANHOS) THEN CASE VARIA_PRECO_TAM WHEN 1 THEN CASE SUBSTRING(PONTEIRO_PRECO_TAM, ' + CONVERT(VARCHAR, @TAMANHO) + ', 1) WHEN 1 THEN ISNULL(E.PRECO_LIQUIDO1, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO_LIQUIDO1 ELSE C.PRECO_LIQUIDO1 END) WHEN 2 THEN ISNULL(E.PRECO_LIQUIDO2, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO_LIQUIDO2 ELSE C.PRECO_LIQUIDO2 END) WHEN 3 THEN ISNULL(E.PRECO_LIQUIDO3, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO_LIQUIDO3 ELSE C.PRECO_LIQUIDO3 END) WHEN 4 THEN ISNULL(E.PRECO_LIQUIDO4, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO_LIQUIDO4 ELSE C.PRECO_LIQUIDO4 END) END ELSE ISNULL(E.PRECO_LIQUIDO1, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO_LIQUIDO1 ELSE C.PRECO_LIQUIDO1 END) END ELSE CONVERT(NUMERIC(14, 2), 0) END, 0))'
		END
		
		SELECT
			@SELECT2 = @SELECT2 + ', PRECOTAM' + CONVERT(VARCHAR, @TAMANHO) + ' = CONVERT(NUMERIC(14, 2), ISNULL(CASE WHEN ' + CONVERT(VARCHAR, @TAMANHO) + ' <= ISNULL(TAMANHOS_DIGITADOS, NUMERO_TAMANHOS) THEN CASE VARIA_PRECO_TAM WHEN 1 THEN CASE SUBSTRING(PONTEIRO_PRECO_TAM, ' + CONVERT(VARCHAR, @TAMANHO) + ', 1) WHEN 1 THEN ISNULL(E.PRECO1, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO1 ELSE C.PRECO1 END) WHEN 2 THEN ISNULL(E.PRECO2, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO2 ELSE C.PRECO2 END) WHEN 3 THEN ISNULL(E.PRECO3, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO3 ELSE C.PRECO3 END) WHEN 4 THEN ISNULL(E.PRECO4, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO4 ELSE C.PRECO4 END) END ELSE ISNULL(E.PRECO1, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO1 ELSE C.PRECO1 END) END ELSE CONVERT(NUMERIC(14, 2), 0) END, 0))', 
			@TAMANHO = @TAMANHO + 1
	END

	WHILE @TAMANHO <= 30
	BEGIN
		IF @PROMOCAO_PRODUTOS_PRECOS = 0 AND @PROMOCAO_PRODUTOS_PRECO_COR = 0 AND @PROMOCAO_PRODUTOS_PRECO_FILIAL = 0 -- #1 - Caso a promoção NÃO esteja ativa em nenhuma tabela de preços. 
		BEGIN
			SELECT	@SELECTLIQ3 = @SELECTLIQ3 + ', PRECOLIQTAM' + CONVERT(VARCHAR, @TAMANHO) + ' = CONVERT(NUMERIC(14, 2), ISNULL(CASE WHEN ' + CONVERT(VARCHAR, @TAMANHO) + ' <= ISNULL(TAMANHOS_DIGITADOS, NUMERO_TAMANHOS) THEN CASE VARIA_PRECO_TAM WHEN 1 THEN CASE SUBSTRING(PONTEIRO_PRECO_TAM, ' + CONVERT(VARCHAR, @TAMANHO) + ', 1) WHEN 1 THEN ISNULL(E.PRECO1, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO1 ELSE C.PRECO1 END) WHEN 2 THEN ISNULL(E.PRECO2, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO2 ELSE C.PRECO2 END) WHEN 3 THEN ISNULL(E.PRECO3, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO3 ELSE C.PRECO3 END) WHEN 4 THEN ISNULL(E.PRECO4, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO4 ELSE C.PRECO4 END) END ELSE ISNULL(E.PRECO1, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO1 ELSE C.PRECO1 END) END ELSE CONVERT(NUMERIC(14, 2), 0) END, 0))'
		END
		
		IF @PROMOCAO_PRODUTOS_PRECOS = 1 OR @PROMOCAO_PRODUTOS_PRECO_COR = 1 OR @PROMOCAO_PRODUTOS_PRECO_FILIAL = 1  -- #1 - Caso a promoção ESTEJA ativa em alguma tabela de preços. 
		BEGIN
			SELECT	@SELECTLIQ3 = @SELECTLIQ3 + ', PRECOLIQTAM' + CONVERT(VARCHAR, @TAMANHO) + ' = CONVERT(NUMERIC(14, 2), ISNULL(CASE WHEN ' + CONVERT(VARCHAR, @TAMANHO) + ' <= ISNULL(TAMANHOS_DIGITADOS, NUMERO_TAMANHOS) THEN CASE VARIA_PRECO_TAM WHEN 1 THEN CASE SUBSTRING(PONTEIRO_PRECO_TAM, ' + CONVERT(VARCHAR, @TAMANHO) + ', 1) WHEN 1 THEN ISNULL(E.PRECO_LIQUIDO1, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO_LIQUIDO1 ELSE C.PRECO_LIQUIDO1 END) WHEN 2 THEN ISNULL(E.PRECO_LIQUIDO2, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO_LIQUIDO2 ELSE C.PRECO_LIQUIDO2 END) WHEN 3 THEN ISNULL(E.PRECO_LIQUIDO3, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO_LIQUIDO3 ELSE C.PRECO_LIQUIDO3 END) WHEN 4 THEN ISNULL(E.PRECO_LIQUIDO4, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO_LIQUIDO4 ELSE C.PRECO_LIQUIDO4 END) END ELSE ISNULL(E.PRECO_LIQUIDO1, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO_LIQUIDO1 ELSE C.PRECO_LIQUIDO1 END) END ELSE CONVERT(NUMERIC(14, 2), 0) END, 0))'
		END
		SELECT
			@SELECT3 = @SELECT3 + ', PRECOTAM' + CONVERT(VARCHAR, @TAMANHO) + ' = CONVERT(NUMERIC(14, 2), ISNULL(CASE WHEN ' + CONVERT(VARCHAR, @TAMANHO) + ' <= ISNULL(TAMANHOS_DIGITADOS, NUMERO_TAMANHOS) THEN CASE VARIA_PRECO_TAM WHEN 1 THEN CASE SUBSTRING(PONTEIRO_PRECO_TAM, ' + CONVERT(VARCHAR, @TAMANHO) + ', 1) WHEN 1 THEN ISNULL(E.PRECO1, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO1 ELSE C.PRECO1 END) WHEN 2 THEN ISNULL(E.PRECO2, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO2 ELSE C.PRECO2 END) WHEN 3 THEN ISNULL(E.PRECO3, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO3 ELSE C.PRECO3 END) WHEN 4 THEN ISNULL(E.PRECO4, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO4 ELSE C.PRECO4 END) END ELSE ISNULL(E.PRECO1, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO1 ELSE C.PRECO1 END) END ELSE CONVERT(NUMERIC(14, 2), 0) END, 0))', 
			@TAMANHO = @TAMANHO + 1
	END

	WHILE @TAMANHO <= 40
	BEGIN
		IF @PROMOCAO_PRODUTOS_PRECOS = 0 AND @PROMOCAO_PRODUTOS_PRECO_COR = 0 AND @PROMOCAO_PRODUTOS_PRECO_FILIAL = 0 -- #1 - Caso a promoção NÃO esteja ativa em nenhuma tabela de preços. 
		BEGIN
			SELECT	@SELECTLIQ4 = @SELECTLIQ4 + ', PRECOLIQTAM' + CONVERT(VARCHAR, @TAMANHO) + ' = CONVERT(NUMERIC(14, 2), ISNULL(CASE WHEN ' + CONVERT(VARCHAR, @TAMANHO) + ' <= ISNULL(TAMANHOS_DIGITADOS, NUMERO_TAMANHOS) THEN CASE VARIA_PRECO_TAM WHEN 1 THEN CASE SUBSTRING(PONTEIRO_PRECO_TAM, ' + CONVERT(VARCHAR, @TAMANHO) + ', 1) WHEN 1 THEN ISNULL(E.PRECO1, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO1 ELSE C.PRECO1 END) WHEN 2 THEN ISNULL(E.PRECO2, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO2 ELSE C.PRECO2 END) WHEN 3 THEN ISNULL(E.PRECO3, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO3 ELSE C.PRECO3 END) WHEN 4 THEN ISNULL(E.PRECO4, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO4 ELSE C.PRECO4 END) END ELSE ISNULL(E.PRECO1, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO1 ELSE C.PRECO1 END) END ELSE CONVERT(NUMERIC(14, 2), 0) END, 0))'
		END
		
		IF @PROMOCAO_PRODUTOS_PRECOS = 1 OR @PROMOCAO_PRODUTOS_PRECO_COR = 1 OR @PROMOCAO_PRODUTOS_PRECO_FILIAL = 1  -- #1 - Caso a promoção ESTEJA ativa em alguma tabela de preços. 
		BEGIN
			SELECT	@SELECTLIQ4 = @SELECTLIQ4 + ', PRECOLIQTAM' + CONVERT(VARCHAR, @TAMANHO) + ' = CONVERT(NUMERIC(14, 2), ISNULL(CASE WHEN ' + CONVERT(VARCHAR, @TAMANHO) + ' <= ISNULL(TAMANHOS_DIGITADOS, NUMERO_TAMANHOS) THEN CASE VARIA_PRECO_TAM WHEN 1 THEN CASE SUBSTRING(PONTEIRO_PRECO_TAM, ' + CONVERT(VARCHAR, @TAMANHO) + ', 1) WHEN 1 THEN ISNULL(E.PRECO_LIQUIDO1, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO_LIQUIDO1 ELSE C.PRECO_LIQUIDO1 END) WHEN 2 THEN ISNULL(E.PRECO_LIQUIDO2, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO_LIQUIDO2 ELSE C.PRECO_LIQUIDO2 END) WHEN 3 THEN ISNULL(E.PRECO_LIQUIDO3, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO_LIQUIDO3 ELSE C.PRECO_LIQUIDO3 END) WHEN 4 THEN ISNULL(E.PRECO_LIQUIDO4, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO_LIQUIDO4 ELSE C.PRECO_LIQUIDO4 END) END ELSE ISNULL(E.PRECO_LIQUIDO1, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO_LIQUIDO1 ELSE C.PRECO_LIQUIDO1 END) END ELSE CONVERT(NUMERIC(14, 2), 0) END, 0))'
		END
		SELECT
			@SELECT4 = @SELECT4 + ', PRECOTAM' + CONVERT(VARCHAR, @TAMANHO) + ' = CONVERT(NUMERIC(14, 2), ISNULL(CASE WHEN ' + CONVERT(VARCHAR, @TAMANHO) + ' <= ISNULL(TAMANHOS_DIGITADOS, NUMERO_TAMANHOS) THEN CASE VARIA_PRECO_TAM WHEN 1 THEN CASE SUBSTRING(PONTEIRO_PRECO_TAM, ' + CONVERT(VARCHAR, @TAMANHO) + ', 1) WHEN 1 THEN ISNULL(E.PRECO1, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO1 ELSE C.PRECO1 END) WHEN 2 THEN ISNULL(E.PRECO2, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO2 ELSE C.PRECO2 END) WHEN 3 THEN ISNULL(E.PRECO3, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO3 ELSE C.PRECO3 END) WHEN 4 THEN ISNULL(E.PRECO4, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO4 ELSE C.PRECO4 END) END ELSE ISNULL(E.PRECO1, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO1 ELSE C.PRECO1 END) END ELSE CONVERT(NUMERIC(14, 2), 0) END, 0))', 
			@TAMANHO = @TAMANHO + 1
	END

	WHILE @TAMANHO <= 48
	BEGIN
		IF @PROMOCAO_PRODUTOS_PRECOS = 0 AND @PROMOCAO_PRODUTOS_PRECO_COR = 0 AND @PROMOCAO_PRODUTOS_PRECO_FILIAL = 0 -- #1 - Caso a promoção NÃO esteja ativa em nenhuma tabela de preços. 
		BEGIN
			SELECT	@SELECTLIQ5 = @SELECTLIQ5 + ', PRECOLIQTAM' + CONVERT(VARCHAR, @TAMANHO) + ' = CONVERT(NUMERIC(14, 2), ISNULL(CASE WHEN ' + CONVERT(VARCHAR, @TAMANHO) + ' <= ISNULL(TAMANHOS_DIGITADOS, NUMERO_TAMANHOS) THEN CASE VARIA_PRECO_TAM WHEN 1 THEN CASE SUBSTRING(PONTEIRO_PRECO_TAM, ' + CONVERT(VARCHAR, @TAMANHO) + ', 1) WHEN 1 THEN ISNULL(E.PRECO1, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO1 ELSE C.PRECO1 END) WHEN 2 THEN ISNULL(E.PRECO2, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO2 ELSE C.PRECO2 END) WHEN 3 THEN ISNULL(E.PRECO3, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO3 ELSE C.PRECO3 END) WHEN 4 THEN ISNULL(E.PRECO4, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO4 ELSE C.PRECO4 END) END ELSE ISNULL(E.PRECO1, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO1 ELSE C.PRECO1 END) END ELSE CONVERT(NUMERIC(14, 2), 0) END, 0))'
		END
		
		IF @PROMOCAO_PRODUTOS_PRECOS = 1 OR @PROMOCAO_PRODUTOS_PRECO_COR = 1 OR @PROMOCAO_PRODUTOS_PRECO_FILIAL = 1  -- #1 - Caso a promoção ESTEJA ativa em alguma tabela de preços. 
		BEGIN
			SELECT	@SELECTLIQ5 = @SELECTLIQ5 + ', PRECOLIQTAM' + CONVERT(VARCHAR, @TAMANHO) + ' = CONVERT(NUMERIC(14, 2), ISNULL(CASE WHEN ' + CONVERT(VARCHAR, @TAMANHO) + ' <= ISNULL(TAMANHOS_DIGITADOS, NUMERO_TAMANHOS) THEN CASE VARIA_PRECO_TAM WHEN 1 THEN CASE SUBSTRING(PONTEIRO_PRECO_TAM, ' + CONVERT(VARCHAR, @TAMANHO) + ', 1) WHEN 1 THEN ISNULL(E.PRECO_LIQUIDO1, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO_LIQUIDO1 ELSE C.PRECO_LIQUIDO1 END) WHEN 2 THEN ISNULL(E.PRECO_LIQUIDO2, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO_LIQUIDO2 ELSE C.PRECO_LIQUIDO2 END) WHEN 3 THEN ISNULL(E.PRECO_LIQUIDO3, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO_LIQUIDO3 ELSE C.PRECO_LIQUIDO3 END) WHEN 4 THEN ISNULL(E.PRECO_LIQUIDO4, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO_LIQUIDO4 ELSE C.PRECO_LIQUIDO4 END) END ELSE ISNULL(E.PRECO_LIQUIDO1, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO_LIQUIDO1 ELSE C.PRECO_LIQUIDO1 END) END ELSE CONVERT(NUMERIC(14, 2), 0) END, 0))'
		END
		SELECT
			@SELECT5 = @SELECT5 + ', PRECOTAM' + CONVERT(VARCHAR, @TAMANHO) + ' = CONVERT(NUMERIC(14, 2), ISNULL(CASE WHEN ' + CONVERT(VARCHAR, @TAMANHO) + ' <= ISNULL(TAMANHOS_DIGITADOS, NUMERO_TAMANHOS) THEN CASE VARIA_PRECO_TAM WHEN 1 THEN CASE SUBSTRING(PONTEIRO_PRECO_TAM, ' + CONVERT(VARCHAR, @TAMANHO) + ', 1) WHEN 1 THEN ISNULL(E.PRECO1, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO1 ELSE C.PRECO1 END) WHEN 2 THEN ISNULL(E.PRECO2, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO2 ELSE C.PRECO2 END) WHEN 3 THEN ISNULL(E.PRECO3, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO3 ELSE C.PRECO3 END) WHEN 4 THEN ISNULL(E.PRECO4, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO4 ELSE C.PRECO4 END) END ELSE ISNULL(E.PRECO1, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO1 ELSE C.PRECO1 END) END ELSE CONVERT(NUMERIC(14, 2), 0) END, 0))', 
			@TAMANHO = @TAMANHO + 1
	END

	EXEC('
		SELECT 
			A.PRODUTO, A.DESC_PRODUTO, B.COR_PRODUTO, B.DESC_COR_PRODUTO, 
			A.VARIA_PRECO_COR, A.VARIA_PRECO_TAM, A.GRADE, A.PONTEIRO_PRECO_TAM' + @DETALHES + ' ' + 
			@SELECT1 + @SELECT2 + @SELECT3 + @SELECT4 + @SELECT5 + 
			@SELECTLIQ1 + @SELECTLIQ2 + @SELECTLIQ3 + @SELECTLIQ4 + @SELECTLIQ5 + ', 
			PRECO1 = ISNULL(E.PRECO1, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO1 ELSE C.PRECO1 END), 
			PRECO2 = ISNULL(E.PRECO2, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO1 ELSE C.PRECO1 END), 
			PRECO3 = ISNULL(E.PRECO3, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO1 ELSE C.PRECO1 END), 
			PRECO4 = ISNULL(E.PRECO4, CASE VARIA_PRECO_COR WHEN 1 THEN D.PRECO1 ELSE C.PRECO1 END), 
			PROMOCAO_DESCONTO = CASE WHEN ''' + @FILTRO_DATA + ''' BETWEEN ISNULL(E.INICIO_PROMOCAO, ISNULL(CASE WHEN VARIA_PRECO_COR = 1 THEN D.INICIO_PROMOCAO ELSE C.INICIO_PROMOCAO END, ''' + @FILTRO_DATA + ''')) AND ISNULL(E.FIM_PROMOCAO, ISNULL(CASE WHEN VARIA_PRECO_COR = 1 THEN D.FIM_PROMOCAO ELSE C.FIM_PROMOCAO END, ''' + @FILTRO_DATA + ''')) THEN ISNULL(E.PROMOCAO_DESCONTO, CASE WHEN VARIA_PRECO_COR = 1 THEN D.PROMOCAO_DESCONTO ELSE C.PROMOCAO_DESCONTO END) ELSE CONVERT(NUMERIC(8, 5), 0) END, 
			ISNULL(G.CONTEUDO_FOTO, ISNULL(G.THUMBNAIL_FOTO, G.PATH_FOTO)) AS PATH_FOTO, 
			INICIO_PROMOCAO = ISNULL(ISNULL(E.INICIO_PROMOCAO, CASE WHEN VARIA_PRECO_COR = 1 THEN D.INICIO_PROMOCAO ELSE C.INICIO_PROMOCAO END), ''19000101''), --#3#  #4#    
			FIM_PROMOCAO = ISNULL(ISNULL(E.FIM_PROMOCAO, CASE WHEN VARIA_PRECO_COR = 1 THEN D.FIM_PROMOCAO ELSE C.FIM_PROMOCAO END),  ''' +  @FIM_DATA + ''') --#3# #4#
		FROM 
			PRODUTOS A 
			INNER JOIN PRODUTO_CORES B ON A.PRODUTO = B.PRODUTO 
			INNER JOIN PRODUTOS_PRECOS C ON A.PRODUTO = C.PRODUTO 
			LEFT JOIN PRODUTOS_PRECO_COR D ON C.CODIGO_TAB_PRECO = D.CODIGO_TAB_PRECO AND C.PRODUTO = D.PRODUTO AND B.COR_PRODUTO = D.COR_PRODUTO 
			LEFT JOIN PRODUTOS_PRECO_FILIAL E ON C.CODIGO_TAB_PRECO = E.CODIGO_TAB_PRECO AND B.PRODUTO = E.PRODUTO AND B.COR_PRODUTO = E.COR_PRODUTO AND E.FILIAL = ''' + @FILIAL + ''' 
			INNER JOIN PRODUTOS_TAMANHOS F ON A.GRADE = F.GRADE 
			LEFT JOIN (SELECT A.PRODUTO, A.CONTEUDO_FOTO, A.THUMBNAIL_FOTO, A.PATH_FOTO FROM PRODUTOS_FOTO A INNER JOIN (SELECT PRODUTO, MIN(NUMERO_FOTO) AS NUMERO_FOTO FROM PRODUTOS_FOTO GROUP BY PRODUTO) B ON A.PRODUTO = B.PRODUTO AND A.NUMERO_FOTO = B.NUMERO_FOTO) G ON A.PRODUTO = G.PRODUTO 
			' + @JOIN + '
		WHERE 
			C.CODIGO_TAB_PRECO = ''' + @CODIGO_TAB_PRECO + '''' + @FILTRO + ' ORDER BY A.PRODUTO, B.COR_PRODUTO'
		)

	SET NOCOUNT OFF
END