
IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[LJ_VENDA_CONCLUSAO]') AND TYPE IN (N'U'))
begin

CREATE TABLE [dbo].[LJ_VENDA_CONCLUSAO](
	[CODIGO_FILIAL] [char](6) NOT NULL,
	[TICKET] [char](8) NOT NULL,
	[DATA_VENDA] [datetime] NOT NULL,
	[PONTO_CONCLUSAO] [char](8) NULL,
 CONSTRAINT [XPKLJ_VENDA_CONCLUSAO] PRIMARY KEY CLUSTERED 
(
	[DATA_VENDA] ASC,
	[CODIGO_FILIAL] ASC,
	[TICKET] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END 

