IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_PEDIDO' AND COLUMN_NAME = 'DATA_ENTREGA') BEGIN
    ALTER TABLE [dbo].[LOJA_PEDIDO] ADD DATA_ENTREGA DATETIME 
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_PEDIDO' AND COLUMN_NAME = 'STATUS_PEDIDO') BEGIN
    ALTER TABLE [dbo].[LOJA_PEDIDO] ADD STATUS_PEDIDO TINYINT 
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_PEDIDO' AND COLUMN_NAME = 'SITUACAO_PEDIDO') BEGIN
    ALTER TABLE [dbo].[LOJA_PEDIDO] ADD SITUACAO_PEDIDO TINYINT 
END 