IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_PEDIDO_PRODUTO' AND COLUMN_NAME = 'QTDE_CANCELADA') BEGIN
    ALTER TABLE [dbo].[LOJA_PEDIDO_PRODUTO] ADD QTDE_CANCELADA INT 
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_PEDIDO_PRODUTO' AND COLUMN_NAME = 'QTDE_PENDENTE_DE_REMESSA') BEGIN
    ALTER TABLE [dbo].[LOJA_PEDIDO_PRODUTO] ADD QTDE_PENDENTE_DE_REMESSA INT 
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_PEDIDO_PRODUTO' AND COLUMN_NAME = 'QTDE_ENTREGUE') BEGIN
    ALTER TABLE [dbo].[LOJA_PEDIDO_PRODUTO] ADD QTDE_ENTREGUE INT 
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_PEDIDO_PRODUTO' AND COLUMN_NAME = 'MOTIVO_CANCELAMENTO') BEGIN
    ALTER TABLE [dbo].[LOJA_PEDIDO_PRODUTO] ADD MOTIVO_CANCELAMENTO VARCHAR(255)
END