IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_ENTREGA_FUTURA_HST') BEGIN

	CREATE TABLE LOJA_ENTREGA_FUTURA_HST
	(
	   ID_HST                        INT          NOT NULL,
	   CODIGO_FILIAL_ORIGEM          CHAR(6)      NOT NULL,
	   PEDIDO                        INT          NOT NULL,
	   ITEM	                         INT          NOT NULL,
	   ROMANEIO_PRODUTO              CHAR(15)     NOT NULL,
	   NF_REMESSA                    CHAR(15)     NULL,
	   SERIE_NF_REMESSA              CHAR(6)      NULL,
	   ITEM_IMPRESSAO_REMESSA        CHAR(4)      NULL,
	   SUB_ITEM_TAMANHO_REMESSA      INT          NULL,
	   NF_CANCELAMENTO               CHAR(15)     NULL,
	   SERIE_NF_CANCELAMENTO         CHAR(6)      NULL,
	   ITEM_IMPRESSAO_CANCELAMENTO   CHAR(4)      NULL,
	   SUB_ITEM_TAMANHO_CANCELAMENTO INT          NULL,
	   STATUS_PEDIDO                 INT          NULL,
	   QTDE_CANCELADA                INT          NULL,
	   QTDE_ENTREGUE                 INT          NULL,
	   MOTIVO_CANCELAMENTO_PEDIDO    VARCHAR(255) NULL,
	   MOTIVO_CANCELAMENTO_ITEM      VARCHAR(255) NULL,
	   DATA_HST                      DATETIME     NULL,
	   USUARIO_HST                   VARCHAR(100) NULL,
	)
	
	ALTER TABLE [dbo].[LOJA_ENTREGA_FUTURA_HST] ADD CONSTRAINT PK_LOJA_ENTREGA_FUTURA_HST PRIMARY KEY (ID_HST, CODIGO_FILIAL_ORIGEM, PEDIDO, ROMANEIO_PRODUTO, ITEM)

END