------------------------------
-- DECLARACAO DAS VARIAVEIS --
------------------------------
DECLARE @PARAMETRO          VARCHAR(25)    = ''
DECLARE @VALOR_DEFAULT      VARCHAR(100)   = ''
DECLARE @VALOR_ATUAL        VARCHAR(100)   = ''
DECLARE @DESC_PARAMETRO     VARCHAR(100)   = ''
DECLARE @TIPO_DADO          VARCHAR(1)     = ''
DECLARE @NOTA_PROGRAMADOR   VARCHAR(8000)  = ''
DECLARE @PENULT_ATUALIZACAO DATETIME       = GETDATE()
DECLARE @ULT_ATUALIZACAO    DATETIME       = GETDATE()



--------------------------
-- CRIACAO DO PARAMETRO --
--------------------------
SELECT @PARAMETRO        = 'CFOP_FAT_ESTAB_UF',     
	   @VALOR_DEFAULT    = '',
	   @VALOR_ATUAL      = '5.922',
	   @DESC_PARAMETRO   = 'CFOP NF de simples faturamento de produto do estabelecimento dentro do estado.',
	   @TIPO_DADO        = 'C',
	   @NOTA_PROGRAMADOR = 'CFOP NF de simples faturamento de produto do estabelecimento dentro do estado.'

IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = @PARAMETRO ) BEGIN
INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
SELECT	@PARAMETRO            AS PARAMETRO,
		@PENULT_ATUALIZACAO   AS PENULT_ATUALIZACAO,
		@VALOR_DEFAULT        AS VALOR_DEFAULT,
		@ULT_ATUALIZACAO      AS ULT_ATUALIZACAO,
		@VALOR_ATUAL          AS VALOR_ATUAL,
		@DESC_PARAMETRO       AS DESC_PARAMETRO,
		@TIPO_DADO            AS TIPO_DADO,
		''                    AS RANGE_VALOR_ATUAL,
		0                     AS GLOBAL,
		@NOTA_PROGRAMADOR     AS NOTA_PROGRAMADOR,
		0                     AS ESCOPO,
		0                     AS POR_USUARIO_OK,
		0                     AS PERMITE_POR_EMPRESA,
		1                     AS ENVIA_PARA_LOJA,
		1                     AS PERMITE_POR_LOJA,
		1                     AS PERMITE_POR_TERMINAL,
		1                     AS PERMITE_ALTERAR_NA_LOJA,
		1                     AS PERMITE_ALTERAR_NO_TERMINAL,
		0                     AS ENVIA_PARA_REPRESENTANTE,
		0                     AS PERMITE_POR_REPRESENTANTE,
		0                     AS PERMITE_ALTERAR_NO_REPRESENTANTE
END



--------------------------
-- CRIACAO DO PARAMETRO --
--------------------------
SELECT @PARAMETRO        = 'CFOP_FAT_ESTAB_INTER_UF',     
	   @VALOR_DEFAULT    = '',
	   @VALOR_ATUAL      = '6.922',
	   @DESC_PARAMETRO   = 'CFOP NF de simples faturamento de produto do estabelecimento fora do estado.',
	   @TIPO_DADO        = 'C',
	   @NOTA_PROGRAMADOR = 'CFOP NF de simples faturamento de produto do estabelecimento fora do estado.'

IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = @PARAMETRO ) BEGIN
INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
SELECT	@PARAMETRO            AS PARAMETRO,
		@PENULT_ATUALIZACAO   AS PENULT_ATUALIZACAO,
		@VALOR_DEFAULT        AS VALOR_DEFAULT,
		@ULT_ATUALIZACAO      AS ULT_ATUALIZACAO,
		@VALOR_ATUAL          AS VALOR_ATUAL,
		@DESC_PARAMETRO       AS DESC_PARAMETRO,
		@TIPO_DADO            AS TIPO_DADO,
		''                    AS RANGE_VALOR_ATUAL,
		0                     AS GLOBAL,
		@NOTA_PROGRAMADOR     AS NOTA_PROGRAMADOR,
		0                     AS ESCOPO,
		0                     AS POR_USUARIO_OK,
		0                     AS PERMITE_POR_EMPRESA,
		1                     AS ENVIA_PARA_LOJA,
		1                     AS PERMITE_POR_LOJA,
		1                     AS PERMITE_POR_TERMINAL,
		1                     AS PERMITE_ALTERAR_NA_LOJA,
		1                     AS PERMITE_ALTERAR_NO_TERMINAL,
		0                     AS ENVIA_PARA_REPRESENTANTE,
		0                     AS PERMITE_POR_REPRESENTANTE,
		0                     AS PERMITE_ALTERAR_NO_REPRESENTANTE
END



--------------------------
-- CRIACAO DO PARAMETRO --
--------------------------
SELECT @PARAMETRO        = 'CFOP_REM_ESTAB_UF',     
	   @VALOR_DEFAULT    = '',
	   @VALOR_ATUAL      = '5.116',
	   @DESC_PARAMETRO   = 'CFOP NF de remessa de produto do estabelecimento para entrega futura dentro do estado.',
	   @TIPO_DADO        = 'C',
	   @NOTA_PROGRAMADOR = 'CFOP NF de remessa de produto do estabelecimento para entrega futura dentro do estado.'

IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = @PARAMETRO ) BEGIN
INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
SELECT	@PARAMETRO            AS PARAMETRO,
		@PENULT_ATUALIZACAO   AS PENULT_ATUALIZACAO,
		@VALOR_DEFAULT        AS VALOR_DEFAULT,
		@ULT_ATUALIZACAO      AS ULT_ATUALIZACAO,
		@VALOR_ATUAL          AS VALOR_ATUAL,
		@DESC_PARAMETRO       AS DESC_PARAMETRO,
		@TIPO_DADO            AS TIPO_DADO,
		''                    AS RANGE_VALOR_ATUAL,
		0                     AS GLOBAL,
		@NOTA_PROGRAMADOR     AS NOTA_PROGRAMADOR,
		0                     AS ESCOPO,
		0                     AS POR_USUARIO_OK,
		0                     AS PERMITE_POR_EMPRESA,
		1                     AS ENVIA_PARA_LOJA,
		1                     AS PERMITE_POR_LOJA,
		1                     AS PERMITE_POR_TERMINAL,
		1                     AS PERMITE_ALTERAR_NA_LOJA,
		1                     AS PERMITE_ALTERAR_NO_TERMINAL,
		0                     AS ENVIA_PARA_REPRESENTANTE,
		0                     AS PERMITE_POR_REPRESENTANTE,
		0                     AS PERMITE_ALTERAR_NO_REPRESENTANTE
END



--------------------------
-- CRIACAO DO PARAMETRO --
--------------------------
SELECT @PARAMETRO        = 'CFOP_REM_ESTAB_INTER_UF',     
	   @VALOR_DEFAULT    = '',
	   @VALOR_ATUAL      = '6.116',
	   @DESC_PARAMETRO   = 'CFOP NF de remessa de produto do estabelecimento para entrega futura fora do estado.',
	   @TIPO_DADO        = 'C',
	   @NOTA_PROGRAMADOR = 'CFOP NF de remessa de produto do estabelecimento para entrega futura fora do estado.'

IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = @PARAMETRO ) BEGIN
INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
SELECT	@PARAMETRO            AS PARAMETRO,
		@PENULT_ATUALIZACAO   AS PENULT_ATUALIZACAO,
		@VALOR_DEFAULT        AS VALOR_DEFAULT,
		@ULT_ATUALIZACAO      AS ULT_ATUALIZACAO,
		@VALOR_ATUAL          AS VALOR_ATUAL,
		@DESC_PARAMETRO       AS DESC_PARAMETRO,
		@TIPO_DADO            AS TIPO_DADO,
		''                    AS RANGE_VALOR_ATUAL,
		0                     AS GLOBAL,
		@NOTA_PROGRAMADOR     AS NOTA_PROGRAMADOR,
		0                     AS ESCOPO,
		0                     AS POR_USUARIO_OK,
		0                     AS PERMITE_POR_EMPRESA,
		1                     AS ENVIA_PARA_LOJA,
		1                     AS PERMITE_POR_LOJA,
		1                     AS PERMITE_POR_TERMINAL,
		1                     AS PERMITE_ALTERAR_NA_LOJA,
		1                     AS PERMITE_ALTERAR_NO_TERMINAL,
		0                     AS ENVIA_PARA_REPRESENTANTE,
		0                     AS PERMITE_POR_REPRESENTANTE,
		0                     AS PERMITE_ALTERAR_NO_REPRESENTANTE
END



--------------------------
-- CRIACAO DO PARAMETRO --
--------------------------
SELECT @PARAMETRO        = 'CFOP_REM_TERC_UF',     
	   @VALOR_DEFAULT    = '',
	   @VALOR_ATUAL      = '5.117',
	   @DESC_PARAMETRO   = 'CFOP NF de remessa de produto adquirido de terceiro para entrega futura dentro do estado.',
	   @TIPO_DADO        = 'C',
	   @NOTA_PROGRAMADOR = 'CFOP NF de remessa de produto adquirido de terceiro para entrega futura dentro do estado.'

IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = @PARAMETRO ) BEGIN
INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
SELECT	@PARAMETRO            AS PARAMETRO,
		@PENULT_ATUALIZACAO   AS PENULT_ATUALIZACAO,
		@VALOR_DEFAULT        AS VALOR_DEFAULT,
		@ULT_ATUALIZACAO      AS ULT_ATUALIZACAO,
		@VALOR_ATUAL          AS VALOR_ATUAL,
		@DESC_PARAMETRO       AS DESC_PARAMETRO,
		@TIPO_DADO            AS TIPO_DADO,
		''                    AS RANGE_VALOR_ATUAL,
		0                     AS GLOBAL,
		@NOTA_PROGRAMADOR     AS NOTA_PROGRAMADOR,
		0                     AS ESCOPO,
		0                     AS POR_USUARIO_OK,
		0                     AS PERMITE_POR_EMPRESA,
		1                     AS ENVIA_PARA_LOJA,
		1                     AS PERMITE_POR_LOJA,
		1                     AS PERMITE_POR_TERMINAL,
		1                     AS PERMITE_ALTERAR_NA_LOJA,
		1                     AS PERMITE_ALTERAR_NO_TERMINAL,
		0                     AS ENVIA_PARA_REPRESENTANTE,
		0                     AS PERMITE_POR_REPRESENTANTE,
		0                     AS PERMITE_ALTERAR_NO_REPRESENTANTE
END



--------------------------
-- CRIACAO DO PARAMETRO --
--------------------------
SELECT @PARAMETRO        = 'CFOP_REM_TERC_INTER_UF',     
	   @VALOR_DEFAULT    = '',
	   @VALOR_ATUAL      = '6.117',
	   @DESC_PARAMETRO   = 'CFOP NF de remessa de produto adquirido de terceiro para entrega futura fora do estado.',
	   @TIPO_DADO        = 'C',
	   @NOTA_PROGRAMADOR = 'CFOP NF de remessa de produto adquirido de terceiro para entrega futura fora do estado.'

IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = @PARAMETRO ) BEGIN
INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
SELECT	@PARAMETRO            AS PARAMETRO,
		@PENULT_ATUALIZACAO   AS PENULT_ATUALIZACAO,
		@VALOR_DEFAULT        AS VALOR_DEFAULT,
		@ULT_ATUALIZACAO      AS ULT_ATUALIZACAO,
		@VALOR_ATUAL          AS VALOR_ATUAL,
		@DESC_PARAMETRO       AS DESC_PARAMETRO,
		@TIPO_DADO            AS TIPO_DADO,
		''                    AS RANGE_VALOR_ATUAL,
		0                     AS GLOBAL,
		@NOTA_PROGRAMADOR     AS NOTA_PROGRAMADOR,
		0                     AS ESCOPO,
		0                     AS POR_USUARIO_OK,
		0                     AS PERMITE_POR_EMPRESA,
		1                     AS ENVIA_PARA_LOJA,
		1                     AS PERMITE_POR_LOJA,
		1                     AS PERMITE_POR_TERMINAL,
		1                     AS PERMITE_ALTERAR_NA_LOJA,
		1                     AS PERMITE_ALTERAR_NO_TERMINAL,
		0                     AS ENVIA_PARA_REPRESENTANTE,
		0                     AS PERMITE_POR_REPRESENTANTE,
		0                     AS PERMITE_ALTERAR_NO_REPRESENTANTE
END


--------------------------
-- CRIACAO DO PARAMETRO --
--------------------------
SELECT @PARAMETRO        = 'QTDE_DIAS_ENTRE_FUTURA',     
	   @VALOR_DEFAULT    = '',
	   @VALOR_ATUAL      = '30',
	   @DESC_PARAMETRO   = 'QUANTIDADE DE DIAS PARA ENTREGA FUTURA',
	   @TIPO_DADO        = 'N',
	   @NOTA_PROGRAMADOR = 'QUANTIDADE DE DIAS PARA ENTREGA FUTURA'

IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = @PARAMETRO ) BEGIN
INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
SELECT	@PARAMETRO            AS PARAMETRO,
		@PENULT_ATUALIZACAO   AS PENULT_ATUALIZACAO,
		@VALOR_DEFAULT        AS VALOR_DEFAULT,
		@ULT_ATUALIZACAO      AS ULT_ATUALIZACAO,
		@VALOR_ATUAL          AS VALOR_ATUAL,
		@DESC_PARAMETRO       AS DESC_PARAMETRO,
		@TIPO_DADO            AS TIPO_DADO,
		''                    AS RANGE_VALOR_ATUAL,
		0                     AS GLOBAL,
		@NOTA_PROGRAMADOR     AS NOTA_PROGRAMADOR,
		0                     AS ESCOPO,
		0                     AS POR_USUARIO_OK,
		0                     AS PERMITE_POR_EMPRESA,
		1                     AS ENVIA_PARA_LOJA,
		1                     AS PERMITE_POR_LOJA,
		1                     AS PERMITE_POR_TERMINAL,
		1                     AS PERMITE_ALTERAR_NA_LOJA,
		1                     AS PERMITE_ALTERAR_NO_TERMINAL,
		0                     AS ENVIA_PARA_REPRESENTANTE,
		0                     AS PERMITE_POR_REPRESENTANTE,
		0                     AS PERMITE_ALTERAR_NO_REPRESENTANTE
END

--------------------------
-- CRIACAO DO PARAMETRO --
--------------------------
SELECT @PARAMETRO        = 'ENTREGA_FUTURA_POS',     
	   @VALOR_DEFAULT    = '',
	   @VALOR_ATUAL      = '.F.',
	   @DESC_PARAMETRO   = 'HABILITA O PARAMETRO ENTREGA_FUTURA_POS',
	   @TIPO_DADO        = 'L',
	   @NOTA_PROGRAMADOR = 'HABILITA O PARAMETRO ENTREGA_FUTURA_POS'

IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = @PARAMETRO ) BEGIN
INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
SELECT	@PARAMETRO            AS PARAMETRO,
		@PENULT_ATUALIZACAO   AS PENULT_ATUALIZACAO,
		@VALOR_DEFAULT        AS VALOR_DEFAULT,
		@ULT_ATUALIZACAO      AS ULT_ATUALIZACAO,
		@VALOR_ATUAL          AS VALOR_ATUAL,
		@DESC_PARAMETRO       AS DESC_PARAMETRO,
		@TIPO_DADO            AS TIPO_DADO,
		''                    AS RANGE_VALOR_ATUAL,
		0                     AS GLOBAL,
		@NOTA_PROGRAMADOR     AS NOTA_PROGRAMADOR,
		0                     AS ESCOPO,
		0                     AS POR_USUARIO_OK,
		0                     AS PERMITE_POR_EMPRESA,
		1                     AS ENVIA_PARA_LOJA,
		1                     AS PERMITE_POR_LOJA,
		1                     AS PERMITE_POR_TERMINAL,
		1                     AS PERMITE_ALTERAR_NA_LOJA,
		1                     AS PERMITE_ALTERAR_NO_TERMINAL,
		0                     AS ENVIA_PARA_REPRESENTANTE,
		0                     AS PERMITE_POR_REPRESENTANTE,
		0                     AS PERMITE_ALTERAR_NO_REPRESENTANTE
END