IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_ENTREGA_FUTURA_HST' AND COLUMN_NAME = 'DATA_PARA_TRANSFERENCIA') BEGIN
    ALTER TABLE [dbo].[LOJA_ENTREGA_FUTURA_HST] ADD DATA_PARA_TRANSFERENCIA DATETIME DEFAULT GETDATE()
END