IF NOT EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LJ_LIMITE_PARCELAMENTO' AND COLUMN_NAME = 'INATIVO')
BEGIN
       ALTER TABLE LJ_LIMITE_PARCELAMENTO ADD INATIVO BIT DEFAULT 0
END