
IF NOT EXISTS 
(
   SELECT
      1 
   FROM
      INFORMATION_SCHEMA.COLUMNS 
   WHERE
      TABLE_NAME = 'LOJA_PEDIDO' 
      AND COLUMN_NAME = 'NOME_ENTREGA'
)
BEGIN
   ALTER TABLE [dbo].[LOJA_PEDIDO] ADD NOME_ENTREGA VARCHAR(255) NULL 
END

IF NOT EXISTS 
(
   SELECT
      1 
   FROM
      INFORMATION_SCHEMA.COLUMNS 
   WHERE
      TABLE_NAME = 'LOJA_PEDIDO' 
      AND COLUMN_NAME = 'MENSAGEM_CARTAO'
)
BEGIN
   ALTER TABLE [dbo].[LOJA_PEDIDO] ADD MENSAGEM_CARTAO VARCHAR(255) NULL 
END

IF NOT EXISTS 
(
   SELECT
      1 
   FROM
      INFORMATION_SCHEMA.COLUMNS 
   WHERE
      TABLE_NAME = 'LOJA_PEDIDO' 
      AND COLUMN_NAME = 'TRACKING'
)
BEGIN
   ALTER TABLE [dbo].[LOJA_PEDIDO] ADD TRACKING VARCHAR(255) NULL 
END

IF NOT EXISTS 
(
   SELECT
      1 
   FROM
      INFORMATION_SCHEMA.COLUMNS 
   WHERE
      TABLE_NAME = 'LOJA_PEDIDO' 
      AND COLUMN_NAME = 'CODIGO_SITE'
)
BEGIN
   ALTER TABLE [dbo].[LOJA_PEDIDO] ADD CODIGO_SITE VARCHAR(255) NULL 
END

IF NOT EXISTS 
(
   SELECT
      1 
   FROM
      INFORMATION_SCHEMA.COLUMNS 
   WHERE
      TABLE_NAME = 'LOJA_PEDIDO' 
      AND COLUMN_NAME = 'FORMA_ENVIO'
)
BEGIN
   ALTER TABLE [dbo].[LOJA_PEDIDO] ADD FORMA_ENVIO VARCHAR(255) NULL 
END

IF NOT EXISTS 
(
   SELECT
      1 
   FROM
      INFORMATION_SCHEMA.COLUMNS 
   WHERE
      TABLE_NAME = 'LOJA_PEDIDO' 
      AND COLUMN_NAME = 'B2C_LOJA'
)
BEGIN
   ALTER TABLE [dbo].[LOJA_PEDIDO] ADD B2C_LOJA BIT 
END

IF NOT EXISTS 
(
   SELECT
      1 
   FROM
      INFORMATION_SCHEMA.COLUMNS 
   WHERE
      TABLE_NAME = 'LOJA_PEDIDO' 
      AND COLUMN_NAME = 'MOTIVO_CANCELAMENTO'
)
BEGIN
   ALTER TABLE [dbo].[LOJA_PEDIDO] ADD MOTIVO_CANCELAMENTO INT 
END

IF NOT EXISTS 
(
   SELECT
      1 
   FROM
      INFORMATION_SCHEMA.COLUMNS 
   WHERE
      TABLE_NAME = 'LOJA_PEDIDO' 
      AND COLUMN_NAME = 'CONFERIDO'
)
BEGIN
   ALTER TABLE [dbo].[LOJA_PEDIDO] ADD CONFERIDO BIT 
END

IF NOT EXISTS 
(
   SELECT
      1 
   FROM
      INFORMATION_SCHEMA.COLUMNS 
   WHERE
      TABLE_NAME = 'LOJA_PEDIDO' 
      AND COLUMN_NAME = 'VOLUME'
)
BEGIN
   ALTER TABLE [dbo].[LOJA_PEDIDO] ADD VOLUME INT 
END

IF NOT EXISTS 
(
   SELECT
      1 
   FROM
      INFORMATION_SCHEMA.COLUMNS 
   WHERE
      TABLE_NAME = 'LOJA_PEDIDO' 
      AND COLUMN_NAME = 'PESO'
)
BEGIN
   ALTER TABLE [dbo].[LOJA_PEDIDO] ADD PESO NUMERIC(7, 3) 
END

IF NOT EXISTS 
(
   SELECT
      1 
   FROM
      INFORMATION_SCHEMA.COLUMNS 
   WHERE
      TABLE_NAME = 'LOJA_PEDIDO' 
      AND COLUMN_NAME = 'CHANNEL_ID'
)
BEGIN
   ALTER TABLE [dbo].[LOJA_PEDIDO] ADD CHANNEL_ID VARCHAR(100)
END

