IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'LOJA_VENDA_TROCA_TICKET'
                      AND COLUMN_NAME = 'QTDE_VIAS_IMPRESSAS')

  ALTER TABLE [dbo].[LOJA_VENDA_TROCA_TICKET]
    add QTDE_VIAS_IMPRESSAS INT NOT NULL default 0 