IF NOT EXISTS (SELECT 1 FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'ADMINISTRADORAS_CARTAO' AND COLUMN_NAME = 'MODALIDADE_QR')
BEGIN
	ALTER TABLE [dbo].[ADMINISTRADORAS_CARTAO] ADD MODALIDADE_QR TINYINT
END