IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[LOJA_PEDIDO_ENTREGA_LISTA]') AND type in (N'U'))
BEGIN

	CREATE TABLE [dbo].[LOJA_PEDIDO_ENTREGA_LISTA](
		[CODIGO_FILIAL_ORIGEM] [char](6) NOT NULL,
		[PEDIDO] [int] NOT NULL,
		[SEQ_ENTREGA] [tinyint] NOT NULL,
		[FULFILLMENTID] [varchar](10) NOT NULL,
		[OPCAO_ENTREGA] [varchar](8000) NULL,
		[ID_PEDIDO_ORIGEM] [varchar](20) NULL,
		[FRETE] [numeric](14,2) NULL,
		[VALOR_TOTAL] [numeric](14,2) NULL,
	 CONSTRAINT [PK_LOJA_PEDIDO_ENTREGA_LISTA] PRIMARY KEY CLUSTERED 
	(
		[CODIGO_FILIAL_ORIGEM] ASC,
		[PEDIDO] ASC,
		[SEQ_ENTREGA] ASC,
		[FULFILLMENTID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]

END
