IF NOT EXISTS( SELECT 1 FROM SYS.sysobjects WHERE NAME = 'CLIENTE_VAR_FINALIDADE' )
				BEGIN
					CREATE TABLE [dbo].[CLIENTE_VAR_FINALIDADE](
						[CODIGO_CLIENTE] [varchar](14) NOT NULL,
						[ID_FINALIDADE] [int]  NOT NULL,
						[CONSENTIDO] [BIT] NOT NULL,
						[DATA_PARA_TRANSFERENCIA]	DATETIME,
					 CONSTRAINT [XPKCLIENTE_VAR_FINALIDADE] PRIMARY KEY CLUSTERED 
					(
						[CODIGO_CLIENTE]  ASC, [ID_FINALIDADE] ASC
					)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
					) ON [PRIMARY]

					ALTER TABLE [dbo].[CLIENTE_VAR_FINALIDADE]  WITH NOCHECK ADD  CONSTRAINT [XFK10001_CLIENTE_VAR_FINALIDADE] FOREIGN KEY([ID_FINALIDADE])
					REFERENCES [dbo].[LGPD_FINALIDADE] ([ID_FINALIDADE])

					ALTER TABLE [dbo].[CLIENTE_VAR_FINALIDADE] CHECK CONSTRAINT [XFK10001_CLIENTE_VAR_FINALIDADE]

					ALTER TABLE [dbo].[CLIENTE_VAR_FINALIDADE]  WITH NOCHECK ADD  CONSTRAINT [XFK10002_CLIENTE_VAR_FINALIDADE] FOREIGN KEY([CODIGO_CLIENTE])
					REFERENCES [dbo].[CLIENTES_VAREJO] ([CODIGO_CLIENTE])
			
					ALTER TABLE [dbo].[CLIENTE_VAR_FINALIDADE] CHECK CONSTRAINT [XFK10002_CLIENTE_VAR_FINALIDADE]			

END;