IF NOT EXISTS(SELECT (1) FROM SYS.COLUMNS A JOIN SYS.TABLES B ON A.OBJECT_ID = B.OBJECT_ID WHERE A.NAME = 'FULFILLMENTID' AND B.NAME = 'LOJA_PEDIDO_PRODUTO' )
BEGIN 
ALTER TABLE LOJA_PEDIDO_PRODUTO ADD FULFILLMENTID VARCHAR(10) NULL
END 
