-- POSSP-5737 - Roberto Beda - (28/06/2021) - Parâmetros para considerar as hipóteses de tratamento em eliminação e anonimização (LGPD)
IF NOT EXISTS(SELECT 1 FROM PARAMETROS WHERE PARAMETRO = 'LGPD_DIAS_OBRIGA_FISCAL')
BEGIN
	INSERT INTO PARAMETROS (PARAMETRO,PENULT_ATUALIZACAO,VALOR_DEFAULT, ULT_ATUALIZACAO ,VALOR_ATUAL, DESC_PARAMETRO,  
	TIPO_DADO,RANGE_VALOR_ATUAL, GLOBAL,NOTA_PROGRAMADOR,
	ESCOPO,POR_USUARIO_OK,	PERMITE_POR_EMPRESA,ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL,
	PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE, DATA_PARA_TRANSFERENCIA) 
	values('LGPD_DIAS_OBRIGA_FISCAL',GETDATE(),'1827', GETDATE(),'1827','LGPD: dias para manter os dados de pessoa física necessários para obrigação acessória.', 
		'I','',0,'Este parametro indica o prazo para não permitir a eliminação de dados utilizados na geração de obrigação acessória (fiscal).',
		0,0,1,1,1,0,
		0,0,0,0,0,GETDATE())
END

IF NOT EXISTS(SELECT 1 FROM PARAMETROS WHERE PARAMETRO = 'LGPD_TEXTO_OBRIGA_FISCAL')
BEGIN
	INSERT INTO PARAMETROS (PARAMETRO,PENULT_ATUALIZACAO,VALOR_DEFAULT, 
	ULT_ATUALIZACAO ,VALOR_ATUAL, 
	DESC_PARAMETRO,  
	TIPO_DADO,RANGE_VALOR_ATUAL, GLOBAL,NOTA_PROGRAMADOR,
	ESCOPO,POR_USUARIO_OK,	PERMITE_POR_EMPRESA,ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL,
	PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE, DATA_PARA_TRANSFERENCIA) 
		values('LGPD_TEXTO_OBRIGA_FISCAL',GETDATE(),'Dados mantidos por obrigação legal acessória:', 
		GETDATE(),'Dados mantidos por obrigação legal acessória:',
		'LGPD: texto para não eliminação de dados de pessoa física necessários para obrigação acessória.', 
		'C','',0,'Este parametro indica o texto para o resultado da solicitação em função da não eliminação de dados utilizados na geração de obrigação acessória (fiscal).',
		0,0,1,1,1,0,
		0,0,0,0,0,GETDATE())
END

IF NOT EXISTS(SELECT 1 FROM PARAMETROS WHERE PARAMETRO = 'LGPD_DIAS_AUTORIZAR_NF')
BEGIN
	INSERT INTO PARAMETROS (PARAMETRO,PENULT_ATUALIZACAO,VALOR_DEFAULT, ULT_ATUALIZACAO ,VALOR_ATUAL, DESC_PARAMETRO,  
	TIPO_DADO,RANGE_VALOR_ATUAL, GLOBAL,NOTA_PROGRAMADOR,
	ESCOPO,POR_USUARIO_OK,	PERMITE_POR_EMPRESA,ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL,
	PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE, DATA_PARA_TRANSFERENCIA) 
	values('LGPD_DIAS_AUTORIZAR_NF',GETDATE(),'7', GETDATE(),'7','LGPD: dias para manter os dados de pessoa física necessários para nota fiscal.', 
		'I','',0,'Este parametro indica o prazo para não permitir a eliminação de dados utilizados na emissão de nota fiscal pendente de autorização.',
		0,0,1,1,1,0,
		0,0,0,0,0,GETDATE())
END

IF NOT EXISTS(SELECT 1 FROM PARAMETROS WHERE PARAMETRO = 'LGPD_TEXTO_AUTORIZAR_NF')
BEGIN
	INSERT INTO PARAMETROS (PARAMETRO,PENULT_ATUALIZACAO,VALOR_DEFAULT, 
	ULT_ATUALIZACAO ,VALOR_ATUAL, 
	DESC_PARAMETRO,  
	TIPO_DADO,RANGE_VALOR_ATUAL, GLOBAL,NOTA_PROGRAMADOR,
	ESCOPO,POR_USUARIO_OK,	PERMITE_POR_EMPRESA,ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL,
	PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE, DATA_PARA_TRANSFERENCIA) 
	values('LGPD_TEXTO_AUTORIZAR_NF',GETDATE(),'Dados mantidos por obrigação legal:', 
		GETDATE(),'Dados mantidos por obrigação legal:',
		'LGPD: texto para não eliminação de dados de pessoa física necessários nota fiscal.', 
		'C','',0,'Este parametro indica o texto para o resultado da solicitação em função da não eliminação de dados utilizados para autorização de nota fiscal pendente.',
		0,0,1,1,1,0,
		0,0,0,0,0,GETDATE())
END

IF NOT EXISTS(SELECT 1 FROM PARAMETROS WHERE PARAMETRO = 'LGPD_DIAS_PEDIDO_PEND')
BEGIN
	INSERT INTO PARAMETROS (PARAMETRO,PENULT_ATUALIZACAO,VALOR_DEFAULT, ULT_ATUALIZACAO ,VALOR_ATUAL, DESC_PARAMETRO,  
	TIPO_DADO,RANGE_VALOR_ATUAL, GLOBAL,NOTA_PROGRAMADOR,
	ESCOPO,POR_USUARIO_OK,	PERMITE_POR_EMPRESA,ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL,
	PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE, DATA_PARA_TRANSFERENCIA) 
	values('LGPD_DIAS_PEDIDO_PEND',GETDATE(),'31', GETDATE(),'31','LGPD: dias para manter os dados de pessoa física relacionados a pedidos pendentes.', 
		'I','',0,'Este parametro indica o prazo para não permitir a eliminação de dados relativos a pedidos pendentes.',
		0,0,1,1,1,0,
		0,0,0,0,0,GETDATE())
END

IF NOT EXISTS(SELECT 1 FROM PARAMETROS WHERE PARAMETRO = 'LGPD_TEXTO_PEDIDO_PEND')
BEGIN
	INSERT INTO PARAMETROS (PARAMETRO,PENULT_ATUALIZACAO,VALOR_DEFAULT, 
	ULT_ATUALIZACAO ,VALOR_ATUAL, 
	DESC_PARAMETRO,  
	TIPO_DADO,RANGE_VALOR_ATUAL, GLOBAL,NOTA_PROGRAMADOR,
	ESCOPO,POR_USUARIO_OK,	PERMITE_POR_EMPRESA,ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL,
	PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE, DATA_PARA_TRANSFERENCIA) 
	values('LGPD_TEXTO_PEDIDO_PEND',GETDATE(),'Dados mantidos por pedido pendente:', 
		GETDATE(),'Dados mantidos por pedido pendente:',
		'LGPD: texto para não eliminação de dados de pessoa física em pedidos pendentes.', 
		'C','',0,'Este parametro indica o texto para o resultado da solicitação em função da não eliminação de dados relacionados a pedidos pendentes.',
		0,0,1,1,1,0,
		0,0,0,0,0,GETDATE())
END

IF NOT EXISTS(SELECT 1 FROM PARAMETROS WHERE PARAMETRO = 'LGPD_DIAS_ENVIO_ERP')
BEGIN
	INSERT INTO PARAMETROS (PARAMETRO,PENULT_ATUALIZACAO,VALOR_DEFAULT, ULT_ATUALIZACAO ,VALOR_ATUAL, DESC_PARAMETRO,  
	TIPO_DADO,RANGE_VALOR_ATUAL, GLOBAL,NOTA_PROGRAMADOR,
	ESCOPO,POR_USUARIO_OK,	PERMITE_POR_EMPRESA,ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL,
	PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE, DATA_PARA_TRANSFERENCIA) 
	values('LGPD_DIAS_ENVIO_ERP',GETDATE(),'1', GETDATE(),'1','LGPD: dias para manter os dados de pessoa física para envio ao ERP.', 
		'I','',0,'Este parametro indica o prazo para não permitir a eliminação de dados que podem estar pendentes de envio ao ERP.',
		0,0,1,1,1,0,
		0,0,0,0,0,GETDATE())
END

IF NOT EXISTS(SELECT 1 FROM PARAMETROS WHERE PARAMETRO = 'LGPD_TEXTO_ENVIO_ERP')
BEGIN
	INSERT INTO PARAMETROS (PARAMETRO,PENULT_ATUALIZACAO,VALOR_DEFAULT, 
	ULT_ATUALIZACAO ,VALOR_ATUAL, 
	DESC_PARAMETRO,  
	TIPO_DADO,RANGE_VALOR_ATUAL, GLOBAL,NOTA_PROGRAMADOR,
	ESCOPO,POR_USUARIO_OK,	PERMITE_POR_EMPRESA,ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL,
	PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE, DATA_PARA_TRANSFERENCIA) 
	values('LGPD_TEXTO_ENVIO_ERP',GETDATE(),'Dados mantidos para processamento de operação recente:', 
		GETDATE(),'Dados mantidos para processamento de operação recente:',
		'LGPD: texto para não eliminação de dados de pessoa física para envio ao ERP.', 
		'C','',0,'Este parametro indica o texto para o resultado da solicitação em função da não eliminação de dados relacionados a operações que precisam ser enviadas ao ERP.',
		0,0,1,1,1,0,
		0,0,0,0,0,GETDATE())
END

IF NOT EXISTS(SELECT 1 FROM PARAMETROS WHERE PARAMETRO = 'LGPD_DIAS_CONSERTO_PEND')
BEGIN
	INSERT INTO PARAMETROS (PARAMETRO,PENULT_ATUALIZACAO,VALOR_DEFAULT, ULT_ATUALIZACAO ,VALOR_ATUAL, DESC_PARAMETRO,  
	TIPO_DADO,RANGE_VALOR_ATUAL, GLOBAL,NOTA_PROGRAMADOR,
	ESCOPO,POR_USUARIO_OK,	PERMITE_POR_EMPRESA,ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL,
	PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE, DATA_PARA_TRANSFERENCIA) 
	values('LGPD_DIAS_CONSERTO_PEND',GETDATE(),'31', GETDATE(),'31','LGPD: dias para manter os dados de pessoa física relacionados a consertos pendentes.', 
		'I','',0,'Este parametro indica o prazo para não permitir a eliminação de dados relativos a consertos pendentes.',
		0,0,1,1,1,0,
		0,0,0,0,0,GETDATE())
END

IF NOT EXISTS(SELECT 1 FROM PARAMETROS WHERE PARAMETRO = 'LGPD_TEXTO_CONSERTO_PEND')
BEGIN
	INSERT INTO PARAMETROS (PARAMETRO,PENULT_ATUALIZACAO,VALOR_DEFAULT, 
	ULT_ATUALIZACAO ,VALOR_ATUAL, 
	DESC_PARAMETRO,  
	TIPO_DADO,RANGE_VALOR_ATUAL, GLOBAL,NOTA_PROGRAMADOR,
	ESCOPO,POR_USUARIO_OK,	PERMITE_POR_EMPRESA,ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL,
	PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE, DATA_PARA_TRANSFERENCIA) 
	values('LGPD_TEXTO_CONSERTO_PEND',GETDATE(),'Dados mantidos por conserto pendente:', 
		GETDATE(),'Dados mantidos por conserto pendente:',
		'LGPD: texto para não eliminação de dados de pessoa física em consertos pendentes.', 
		'C','',0,'Este parametro indica o texto para o resultado da solicitação em função da não eliminação de dados relacionados a consertos pendentes.',
		0,0,1,1,1,0,
		0,0,0,0,0,GETDATE())
END
