IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[OMS_DADOS_RESERVA]') AND type in (N'U'))
BEGIN

	CREATE TABLE [dbo].[OMS_DADOS_RESERVA](
		[CODIGO_FILIAL_ORIGEM] [char](6) NOT NULL,
		[PEDIDO] [int] NOT NULL,
		[SEQ_ENTREGA] [tinyint] NOT NULL,
		[FULFILLMENTID] [varchar](10) NOT NULL,
		[ID_PEDIDO_ORIGEM] [varchar](20) NOT NULL,
		[ID_FRETE] [varchar](50) NULL,
		[QUOTE_ID] [varchar](50) NULL,
		[TYPE]	[varchar](50) NULL,
		[METHOD] [varchar](50) NULL, 
		[PRICE]	[numeric](14,2) NULL,
		[TIME] [int] NULL,
		[STATUS] [tinyint] NULL
	 CONSTRAINT [PK_OMS_DADOS_RESERVA] PRIMARY KEY CLUSTERED 
	(
		[CODIGO_FILIAL_ORIGEM] ASC,
		[PEDIDO] ASC,
		[SEQ_ENTREGA] ASC,
		[FULFILLMENTID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]

END
