IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[LJ_ESTOQUE_PAF_NFCE]') AND type in (N'U'))
BEGIN
	CREATE TABLE [dbo].[LJ_ESTOQUE_PAF_NFCE](
		DATA_PAF_NFCE			[DATE] NOT NULL,
		CODIGO_FILIAL			[char] (6) COLLATE DATABASE_DEFAULT NOT NULL,
		CODIGO_PRODUTO			[varchar] (25) COLLATE DATABASE_DEFAULT NOT NULL,
		CNPJ_ESTABELECIMENTO	[varchar] (14) COLLATE DATABASE_DEFAULT,
		DESCRICAO_PRODUTO		[varchar] (50) COLLATE DATABASE_DEFAULT, 
		DESCRICAO_UNIDADE		[varchar] (6)  COLLATE DATABASE_DEFAULT, 
		SALDO_ESTOQUE			[int],
		CODIGO_CEST				[varchar] (07) COLLATE DATABASE_DEFAULT,
		CLASSIF_FISCAL			[char] (10) COLLATE DATABASE_DEFAULT,
		LX_HASH					[varbinary] (16),
	CONSTRAINT [XPKLJ_ESTOQUE_PAF_NFCE] PRIMARY KEY CLUSTERED 
	(
		[DATA_PAF_NFCE] ASC,
		[CODIGO_FILIAL] ASC,
		[CODIGO_PRODUTO] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	)
END
