IF NOT EXISTS(SELECT PARAMETRO FROM PARAMETROS WHERE PARAMETRO = 'SENHA_VLD_TAMANHO')
INSERT INTO PARAMETROS(PARAMETRO, DESC_PARAMETRO, PENULT_ATUALIZACAO, ULT_ATUALIZACAO, TIPO_DADO, VALOR_DEFAULT, 
		VALOR_ATUAL, GLOBAL, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, NOTA_PROGRAMADOR)
VALUES('SENHA_VLD_TAMANHO','Validacao do tamanho minimo da senha.','20180212','20180212','I',0,0,0,1,1,0,0,0,'Este parametro indica o tamanho minimo que a senha do usuário pode ter.')

IF NOT EXISTS(SELECT PARAMETRO FROM PARAMETROS WHERE PARAMETRO = 'SENHA_VLD_PERIODO')
INSERT INTO PARAMETROS(PARAMETRO, DESC_PARAMETRO, PENULT_ATUALIZACAO, ULT_ATUALIZACAO, TIPO_DADO, VALOR_DEFAULT, 
		VALOR_ATUAL, GLOBAL, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, NOTA_PROGRAMADOR)
VALUES('SENHA_VLD_PERIODO','Validacao do periodo de tempo de expiracao da senha.','20180212','20180212','I',0,0,0,1,1,0,0,0,'Este parametro indica o prazo em dias para a expiracao da senha.')

IF NOT EXISTS(SELECT PARAMETRO FROM PARAMETROS WHERE PARAMETRO = 'SENHA_VLD_REPETICAO')
INSERT INTO PARAMETROS(PARAMETRO, DESC_PARAMETRO, PENULT_ATUALIZACAO, ULT_ATUALIZACAO, TIPO_DADO, VALOR_DEFAULT, 
		VALOR_ATUAL, GLOBAL, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, NOTA_PROGRAMADOR)
VALUES('SENHA_VLD_REPETICAO','Validacao da quantidade de senhas que e necessario validar a repeticao.','20180212','20180212','I',0,0,0,1,1,0,0,0,'Este parametro indica a quantidade de senhas que serao validadas para validar a repeticao de senha.')


IF NOT EXISTS(SELECT PARAMETRO FROM PARAMETROS WHERE PARAMETRO = 'SENHA_VLD_COMPLEXIDADE')
INSERT INTO PARAMETROS(PARAMETRO, DESC_PARAMETRO, PENULT_ATUALIZACAO, ULT_ATUALIZACAO, TIPO_DADO, VALOR_DEFAULT, 
		VALOR_ATUAL, GLOBAL, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, NOTA_PROGRAMADOR)
VALUES('SENHA_VLD_COMPLEXIDADE','Validacao da complexidade da senha que sera utilizada.','20180212','20180212','L','.F.','.F.',0,1,1,0,0,0,'Este parametro indica se a senha passa a conter um de cada dos seguintes caracteres: letra maiúscula, letra minúscula, caractere especial e número.')
