IF EXISTS (SELECT 1
			FROM   [INFORMATION_SCHEMA].[COLUMNS]
			WHERE  [TABLE_NAME] = 'LOJA_LX_CIDADES_DDD'
					AND [COLUMN_NAME] = 'CIDADE'
					 )
BEGIN 
	if exists ( select 1 from LOJA_LX_CIDADES_DDD where CIDADE = 'EMBU' )
	begin		
		UPDATE LOJA_LX_CIDADES_DDD SET CIDADE = 'EMBU DAS ARTES'  WHERE UF = 'SP' AND CIDADE = 'EMBU' 
	end
END
