	IF EXISTS	(	SELECT 1
					FROM	[INFORMATION_SCHEMA].[COLUMNS]
					WHERE	[TABLE_NAME] = 'LCF_LX_MUNICIPIO'
					AND		[COLUMN_NAME] = 'DESC_MUNICIPIO'
				)
	BEGIN 
		if exists ( select * from LCF_LX_MUNICIPIO where COD_MUNICIPIO_IBGE = '3515004' AND DESC_MUNICIPIO NOT IN ('EMBU DAS ARTES')  )
		begin		
			UPDATE LCF_LX_MUNICIPIO SET DESC_MUNICIPIO = 'EMBU DAS ARTES'  WHERE COD_MUNICIPIO_IBGE = '3515004' 
		end
	END
