-- POSSP-7623 - Leonardo Marques - 10/02/2021
IF NOT EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_VENDA_TROCA_ORIGEM' AND COLUMN_NAME = 'QTDE')
BEGIN
	ALTER TABLE LOJA_VENDA_TROCA_ORIGEM ADD QTDE int NULL
END
