IF NOT EXISTS(SELECT PARAMETRO FROM PARAMETROS WHERE PARAMETRO = 'IDENT_VENDA_ORIGEM_TROCA')
INSERT INTO PARAMETROS(PARAMETRO, DESC_PARAMETRO, PENULT_ATUALIZACAO, ULT_ATUALIZACAO, TIPO_DADO, VALOR_DEFAULT, 
		VALOR_ATUAL, GLOBAL, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, NOTA_PROGRAMADOR)
VALUES('IDENT_VENDA_ORIGEM_TROCA','Possibilita de forma mais precisa a identificação da venda de origem na troca.','20220315','20220315','L','.F.','.F.',0,1,1,0,0,0,'Possibilita uma identificação precisa da venda de origem nos itens de troca e controla os itens da troca por quantidade.')
