IF NOT EXISTS( SELECT B.NAME FROM SYS.TABLES A
				INNER JOIN SYS.COLUMNS B
				ON A.OBJECT_ID = B.OBJECT_ID 
				WHERE A.NAME ='CLIENTES_VAREJO' AND B.NAME = 'FIDELIDADE_PUC')
BEGIN 
	EXEC ('ALTER TABLE CLIENTES_VAREJO ADD FIDELIDADE_PUC BIT')
END

IF NOT EXISTS(SELECT * FROM SYS.TABLES A
			INNER JOIN SYS.COLUMNS B
			ON A.OBJECT_ID = B.OBJECT_ID 
			WHERE A.NAME ='CLIENTES_VAREJO' AND B.NAME = 'FIDELIDADE_HERING')
BEGIN
	EXEC ('ALTER TABLE CLIENTES_VAREJO ADD FIDELIDADE_HERING BIT')
END