IF NOT EXISTS( SELECT 1 FROM SYS.TABLES WHERE NAME ='HR_VENDA_TIPO_MODALIDADE')
	BEGIN 
		EXEC('
CREATE TABLE [dbo].[HR_VENDA_TIPO_MODALIDADE](
	[ID_TIPO_MODALIDADE] [smallint] NOT NULL,
	[DESC_TIPO_MODALIDADE] [varchar](50) NOT NULL,
	[DATA_PARA_TRANSFERENCIA] [datetime] NULL,
	[INATIVO] [bit] NULL,
 CONSTRAINT [XPKHR_VENDA_TIPO_MODALIDADE] PRIMARY KEY NONCLUSTERED 
(
	[ID_TIPO_MODALIDADE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]')
	END



