
IF NOT EXISTS(SELECT 1 FROM PARAMETROS WHERE PARAMETRO = 'HR_MOTOR_WS_URL_VOUCHER') 	
BEGIN
insert into PARAMETROS(PARAMETRO,PENULT_ATUALIZACAO,VALOR_DEFAULT,ULT_ATUALIZACAO,VALOR_ATUAL,DESC_PARAMETRO,TIPO_DADO,RANGE_VALOR_ATUAL,GLOBAL,NOTA_PROGRAMADOR,ESCOPO,POR_USUARIO_OK,PERMITE_POR_EMPRESA,ENVIA_PARA_LOJA,PERMITE_POR_LOJA,PERMITE_POR_TERMINAL,PERMITE_ALTERAR_NA_LOJA,PERMITE_ALTERAR_NO_TERMINAL,ENVIA_PARA_REPRESENTANTE,PERMITE_POR_REPRESENTANTE,PERMITE_ALTERAR_NO_REPRESENTANTE,DATA_PARA_TRANSFERENCIA) 
VALUES  ('HR_MOTOR_WS_URL_VOUCHER','2019-08-08 14:24:49','','2019-08-08 14:24:49','https://motorpromocaows.ciahering.com.br/','HERING URL WS MOTOR PROMOCAO PARA VOUCHER','C','','0','URL do servidor CRM da Hering','0','0','0','1','0','0','0','0','0','0','0','2019-08-08 14:24:49') 
END