IF NOT EXISTS(SELECT 1 FROM SYS.TABLES WHERE NAME ='HR_VENDA_TIPO_ORIGEM')
 BEGIN
  EXEC('
CREATE TABLE [dbo].[HR_VENDA_TIPO_ORIGEM](
	[ID_TIPO_ORIGEM] [smallint] NOT NULL,
	[DESC_TIPO_ORIGEM] [varchar](50) NOT NULL,
	[DATA_PARA_TRANSFERENCIA] [datetime] NULL,
	[INATIVO] [bit] NULL,
 CONSTRAINT [XPKHR_VENDA_TIPO_ORIGEM] PRIMARY KEY NONCLUSTERED 
(
	[ID_TIPO_ORIGEM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]')
END



