IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[HR_DEVOLUCAO_SUGESTAO]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[HR_DEVOLUCAO_SUGESTAO](
	[ARQUIVO] [varchar](50) NOT NULL,
	[ID] [int] NOT NULL,
	[PRODUTO] [varchar](10) NOT NULL,
	[COR_PRODUTO] [varchar](12) NOT NULL,
	[CODIGO_BARRA] [varchar](13) NOT NULL,
	[QTDE] [int] NULL,
	[FINALIZADO] [int] NULL,
	[NF_NUMERO] [varchar](9) NULL,
	[SERIE_NF] [varchar](6) NULL,
 CONSTRAINT [PK_HR_DEVOLUCAO_SUGESTAO] PRIMARY KEY CLUSTERED 
(
	[ARQUIVO] ASC,
	[ID] ASC,
	[PRODUTO] ASC,
	[COR_PRODUTO] ASC,
	[CODIGO_BARRA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END