
IF NOT EXISTS(SELECT 1
          FROM   INFORMATION_SCHEMA.COLUMNS
          WHERE  TABLE_NAME = 'HR_NFE_REFERENCIA'
                 AND COLUMN_NAME = 'ICMS')
BEGIN
  ALTER TABLE HR_NFE_REFERENCIA
    ADD [ICMS] [numeric](13, 2) NULL
END 

IF NOT EXISTS(SELECT 1
          FROM   INFORMATION_SCHEMA.COLUMNS
          WHERE  TABLE_NAME = 'HR_NFE_REFERENCIA'
                 AND COLUMN_NAME = 'GRADE')
BEGIN
  ALTER TABLE HR_NFE_REFERENCIA
    ADD [GRADE] [VARCHAR](15)
END 

IF NOT EXISTS(SELECT 1
          FROM   INFORMATION_SCHEMA.COLUMNS
          WHERE  TABLE_NAME = 'HR_NFE_REFERENCIA'
                 AND COLUMN_NAME = 'IPI')
BEGIN
  ALTER TABLE HR_NFE_REFERENCIA
    ADD [IPI] [numeric](13, 2) NULL
END 

IF NOT EXISTS(SELECT 1
          FROM   INFORMATION_SCHEMA.COLUMNS
          WHERE  TABLE_NAME = 'HR_NFE_REFERENCIA'
                 AND COLUMN_NAME = 'ICMST')
BEGIN
  ALTER TABLE HR_NFE_REFERENCIA
    ADD [ICMST] [numeric](13, 2) NULL
END 

IF NOT EXISTS(SELECT 1
          FROM   INFORMATION_SCHEMA.COLUMNS
          WHERE  TABLE_NAME = 'HR_NFE_REFERENCIA'
                 AND COLUMN_NAME = 'ROMANEIO_SAIDA')
BEGIN
  ALTER TABLE HR_NFE_REFERENCIA
    ADD [ROMANEIO_SAIDA] [VARCHAR](15)
END 


IF NOT EXISTS(SELECT 1
          FROM   INFORMATION_SCHEMA.COLUMNS
          WHERE  TABLE_NAME = 'HR_NFE_REFERENCIA'
                 AND COLUMN_NAME = 'SOBRA_GERADA')
BEGIN
  ALTER TABLE HR_NFE_REFERENCIA
    ADD [SOBRA_GERADA] [INT] NULL
END 


IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[LOJA_TRANSACAO_FISCAL]') AND name = N'XIE1LOJA_TRANSACAO_FISCAL')
DROP INDEX [XIE1LOJA_TRANSACAO_FISCAL] ON [dbo].[LOJA_TRANSACAO_FISCAL] WITH ( ONLINE = OFF )

IF EXISTS(SELECT 1
          FROM   INFORMATION_SCHEMA.COLUMNS
          WHERE  TABLE_NAME = 'LOJA_TRANSACAO_FISCAL'
                 AND COLUMN_NAME = 'DATA_TRANSACAO')
BEGIN
	ALTER TABLE LOJA_TRANSACAO_FISCAL ALTER COLUMN DATA_TRANSACAO DATETIME NULL
END 


CREATE NONCLUSTERED INDEX [XIE1LOJA_TRANSACAO_FISCAL] ON [dbo].[LOJA_TRANSACAO_FISCAL] 
(
	[GUID_DOC_FISCAL] ASC,
	[CODIGO_FILIAL] ASC
)
INCLUDE ( [DATA_TRANSACAO],
[TIPO_TRANSACAO],
[MODELO_FISCAL]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

