
IF NOT EXISTS (SELECT TOP 1 1 FROM LOJA_LX_EVENTOS_TIPOS WHERE TIPO_EVENTO ='98') 
BEGIN
INSERT INTO  LOJA_LX_EVENTOS_TIPOS (TIPO_EVENTO,DESCRICAO,MODULO_EVENTO)
VALUES('98','PROMOCAO 135 ANOS','2')
END

IF NOT EXISTS (SELECT TOP 1 1 FROM SERIES_NF WHERE SERIE_NF ='PRM') 
BEGIN
INSERT INTO SERIES_NF(SERIE_NF,USO_PROPRIO,UTILIZA_NO_RECIBO,DESCRICAO,DATA_INICIO,DATA_FIM,SERIE_EXPORTACAO,UTILIZA_NA_SAIDA,UTILIZA_NA_ENTRADA,SEQUENCIAL_POR_FILIAL,UTILIZA_ANO_FISCAL) 
VALUES ('PRM','0','0','PROMOCAO NAO USAR','2013-01-01 00:00:00','2013-01-01 00:00:00','0','0','0','1','0') 
END

