IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'HR_PESQUISA_PERGUNTAS')
CREATE TABLE [dbo].[HR_PESQUISA_PERGUNTAS](
	[ID_PESQUISA] [int] NOT NULL,
	[ID_PERGUNTA] [int] NOT NULL,
	[PERGUNTA] [varchar](120) NULL,
	[PERGUNTA_PINPAD] [varchar](33) NULL,
	[NOTA_MIN] [int] NOT NULL,
	[NOTA_MAX] [int] NOT NULL,
	[INATIVO] [bit] NULL,
 CONSTRAINT [PK_HR_PESQUISA_PERGUNTAS] PRIMARY KEY CLUSTERED 
(
	[ID_PESQUISA] ASC,
	[ID_PERGUNTA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
