-- Limpa Registros Incorretos

IF EXISTS(SELECT * FROM sys.objects where objects.type = 'U' and objects.name = 'PROP_LOJA_VENDA')
DELETE A
FROM PROP_LOJA_VENDA A
LEFT JOIN LOJA_VENDA B ON A.CODIGO_FILIAL = B.CODIGO_FILIAL
			  AND A.TICKET = B.TICKET
			  AND A.DATA_VENDA = B.DATA_VENDA
WHERE B.CODIGO_FILIAL IS NULL		

IF EXISTS(SELECT * FROM sys.objects where objects.type = 'U' and objects.name = 'PROP_LOJA_VENDA')
AND NOT EXISTS(SELECT * FROM sys.objects where NAME =  'XFKP2_PROP_LOJA_VENDA')
ALTER TABLE PROP_LOJA_VENDA ADD CONSTRAINT XFKP2_PROP_LOJA_VENDA FOREIGN KEY (DATA_VENDA, CODIGO_FILIAL, TICKET)   
REFERENCES LOJA_VENDA (DATA_VENDA, CODIGO_FILIAL, TICKET)  
ON DELETE  CASCADE  
ON UPDATE  CASCADE
