ALTER PROCEDURE [dbo].[sp_BarcodeQuery] (@strPriceTable VARCHAR(20) = '', @strBarCode VARCHAR(25) = NULL, @strProduct CHAR(12) = NULL, @strProductColor CHAR(10) = NULL, @strPedido varchar(08) = '', @strNF_SERIE varchar(22) = '' )
AS
SET NOCOUNT ON

DECLARE @strQuery VARCHAR(8000)

set @strQuery = 'SELECT F.CODIGO_BARRA, A.PRODUTO, B.COR_PRODUTO, F.GRADE, F.TAMANHO, DESCRICAO = RTRIM(A.DESC_PROD_NF) + '' - '' + RTRIM(B.DESC_COR_PRODUTO) + 
 '' - '' + RTRIM(F.GRADE), PRECO = CASE WHEN D.PRECO_LIQUIDO < D.PRECO and D.PRECO_LIQUIDO>0 and D.PRECO_LIQUIDO IS not null
 AND CONVERT(DATE,GETDATE()) >= ISNULL(D.INICIO_PROMOCAO,CONVERT(DATE,GETDATE())) 
 AND CONVERT(DATE,GETDATE()) <= ISNULL(D.FIM_PROMOCAO,CONVERT(DATE,GETDATE())) 
 THEN D.PRECO_LIQUIDO ELSE D.PRECO END, CONVERT(INTEGER, 0) AS BARCODES, A.DESC_PROD_NF, B.DESC_COR_PRODUTO
 FROM PRODUTOS A INNER JOIN PRODUTO_CORES B ON A.PRODUTO = B.PRODUTO
 LEFT JOIN W_LJ_PRECO_PRODUTO_BARRA D ON A.PRODUTO = D.PRODUTO AND B.COR_PRODUTO = D.COR_PRODUTO
 INNER JOIN PRODUTOS_TAMANHOS E ON A.GRADE = E.GRADE
 INNER JOIN PRODUTOS_BARRA F ON A.PRODUTO = F.PRODUTO AND B.COR_PRODUTO = F.COR_PRODUTO
 WHERE d.CODIGO_TAB_PRECO = ''' + @strPriceTable + ''' '

IF @strBarCode IS NOT NULL
 SET @strQuery = @strQuery + 'AND F.CODIGO_BARRA = ''' + @strBarCode + ''' '

IF @strProduct IS NOT NULL
 SET @strQuery = @strQuery + 'AND A.PRODUTO = ''' + @strProduct + ''' '

IF @strProductColor IS NOT NULL
 SET @strQuery = @strQuery + 'AND B.COR_PRODUTO = ''' + @strProductColor + ''' '

IF @strPedido IS NOT NULL
 SET @strQuery = @strQuery + 'AND ( A.PRODUTO + B.COR_PRODUTO) IN ( 
  SELECT DISTINCT PRODUTO + COR_PRODUTO 
  FROM LOJA_COMPRA_PRODUTO  
  WHERE PEDIDO = ''' + @strPedido + ''') '
  
IF @strNF_SERIE IS NOT NULL 
 SET @strQuery = @strQuery + 'AND ( A.PRODUTO + B.COR_PRODUTO) IN ( 
  SELECT DISTINCT H.PRODUTO + H.COR_PRODUTO 
  FROM LOJA_ENTRADAS G
  INNER JOIN LOJA_ENTRADAS_PRODUTO H ON G.ROMANEIO_PRODUTO = H.ROMANEIO_PRODUTO
     AND G.FILIAL = H.FILIAL
  WHERE RTRIM(RTRIM(G.NUMERO_NF_TRANSFERENCIA)) + 
    RTRIM(RTRIM(G.SERIE_NF_ENTRADA)) LIKE ' + CHAR(39) + '%' + @strNF_SERIE + '%' + CHAR(39) + ') '

SET @strQuery = @strQuery + 'ORDER BY A.PRODUTO, B.COR_PRODUTO, F.TAMANHO'

EXEC(@strQuery)



