IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FX_HR_BUSCA_VALOR_FECHAMENTO_CAIXA]'))
BEGIN
	EXEC('
CREATE FUNCTION [dbo].[FX_HR_BUSCA_VALOR_FECHAMENTO_CAIXA] (@CODIGO_FILIAL VARCHAR(6), @DATA DATETIME ) 
RETURNS TABLE
AS
RETURN 

SELECT 
CODIGO_FILIAL,
DATA,
MAX(ULTIMO_NFCE) AS ULTIMO_NFCE  ,
MAX(QTDE_NFCE)	 AS QTDE_NFCE  ,
MAX(ULTIMO_SAT)	 AS ULTIMO_SAT , 
MAX(QTDE_SAT)	 AS QTDE_SAT	  , 
MAX(QTDE_CCF)	 AS QTDE_CCF	  ,
MAX(QTDE_TICKET) AS QTDE_TICKET,
MAX(VALOR_BRUTO) AS VALOR_BRUTO

FROM(

SELECT 
COD_FILIAL AS CODIGO_FILIAL,
@DATA AS DATA,
''''				AS ULTIMO_NFCE,
0				AS QTDE_NFCE  ,
0				AS ULTIMO_SAT , 
0				AS QTDE_SAT	  , 
0				AS QTDE_CCF	  ,
0				AS QTDE_TICKET,
0.00			AS VALOR_BRUTO
FROM FILIAIS (NOLOCK)
WHERE  COD_FILIAL = @CODIGO_FILIAL


UNION ALL
SELECT 
CODIGO_FILIAL,
EMISSAO AS DATA,
ISNULL(MAX(NF_NUMERO),'''')	AS ULTIMO_NFCE,
COUNT(*)		AS QTDE_NFCE  ,
0			AS ULTIMO_SAT , 
0				AS QTDE_SAT	  , 
0				AS QTDE_CCF	  ,
0				AS QTDE_TICKET,
0.00			AS VALOR_BRUTO
FROM LOJA_NOTA_FISCAL (NOLOCK)
WHERE  EMISSAO  =@DATA AND SERIE_NF IN (''165'', ''65'')
GROUP BY CODIGO_FILIAL,EMISSAO
UNION ALL
SELECT 
CODIGO_FILIAL,
EMISSAO AS DATA,
'''' AS ULTIMO_NFCE,
0 AS QTDE_NFCE	 ,
ISNULL(MAX(CF_NUMERO),0) AS ULTIMO_SAT , 
COUNT(*) AS QTDE_SAT	 , 
0 AS QTDE_CCF	 ,
0 AS QTDE_TICKET ,
0.00 AS VALOR_BRUTO
FROM LOJA_CF_SAT (NOLOCK)  
WHERE  EMISSAO  =@DATA 
GROUP BY CODIGO_FILIAL,EMISSAO
UNION ALL
SELECT 
CODIGO_FILIAL,
DATA AS DATA,
'''' AS ULTIMO_NFCE,
0 AS QTDE_NFCE	 ,
0 AS ULTIMO_SAT , 
0 AS QTDE_SAT	 , 
COUNT(*) AS QTDE_CCF	 ,
0 AS QTDE_TICKET ,
0.00 AS VALOR_BRUTO
 FROM LOJA_VENDA_PGTO (NOLOCK) 
WHERE  DATA =@DATA
AND NUMERO_CUPOM_FISCAL IS NOT NULL AND ID_EQUIPAMENTO IS NOT NULL
GROUP BY CODIGO_FILIAL,DATA
UNION ALL
SELECT 
CODIGO_FILIAL,
DATA_VENDA AS DATA,
'''' AS ULTIMO_NFCE,
0 AS QTDE_NFCE	 ,
0 AS ULTIMO_SAT , 
0 AS QTDE_SAT	 , 
0 AS QTDE_CCF	 ,
COUNT(*)  AS QTDE_TICKET ,
SUM(VALOR_VENDA_BRUTA) AS VALOR_BRUTO
FROM LOJA_VENDA  (NOLOCK)
WHERE  DATA_VENDA =@DATA
GROUP BY CODIGO_FILIAL,DATA_VENDA 
) AS GERAL
GROUP BY CODIGO_FILIAL,DATA') 
END