IF NOT EXISTS ( SELECT 1 FROM SYS.OBJECTS WHERE NAME ='SP_HR_CRM_ATUALIZA_PROMOCAO_CLIENTE')
	BEGIN
		EXEC('
			CREATE PROCEDURE [dbo].[SP_HR_CRM_ATUALIZA_PROMOCAO_CLIENTE](    
			@ID_PROMOCAO INT,    
			@CPF_CLIENTE VARCHAR(20),    
			@DATA_HORA DATETIME,    
			@TIPO CHAR)        
			AS        
			BEGIN       
				/* verifica se ja existe a tabela do motor de promoção */  
				IF EXISTS ( SELECT 1 FROM SYS.objects WHERE objects.name = ''HR_PROMOCAO_CLIENTE'')    
				BEGIN    
     
				IF NOT EXISTS(SELECT 1 FROM HR_PROMOCAO_CLIENTE WHERE CPF_CLIENTE = @CPF_CLIENTE AND ID_PROMOCAO = @ID_PROMOCAO AND TIPO = @TIPO)    
				BEGIN     
				INSERT INTO HR_PROMOCAO_CLIENTE(ID_PROMOCAO,CPF_CLIENTE,DATA_HORA,TIPO)      
				VALUES (@ID_PROMOCAO, @CPF_CLIENTE, @DATA_HORA, UPPER(@TIPO))    
				END    
    
				END    
    
			END 
		')
	END
ELSE
	BEGIN
		EXEC('
				ALTER PROCEDURE [dbo].[SP_HR_CRM_ATUALIZA_PROMOCAO_CLIENTE](    
			@ID_PROMOCAO INT,    
			@CPF_CLIENTE VARCHAR(20),    
			@DATA_HORA DATETIME,    
			@TIPO CHAR)        
			AS        
			BEGIN       
				/* verifica se ja existe a tabela do motor de promoção */  
				IF EXISTS ( SELECT 1 FROM SYS.objects WHERE objects.name = ''HR_PROMOCAO_CLIENTE'')    
				BEGIN    
     
				IF NOT EXISTS(SELECT 1 FROM HR_PROMOCAO_CLIENTE WHERE CPF_CLIENTE = @CPF_CLIENTE AND ID_PROMOCAO = @ID_PROMOCAO AND TIPO = @TIPO)    
				BEGIN     
				INSERT INTO HR_PROMOCAO_CLIENTE(ID_PROMOCAO,CPF_CLIENTE,DATA_HORA,TIPO)      
				VALUES (@ID_PROMOCAO, @CPF_CLIENTE, @DATA_HORA, UPPER(@TIPO))    
				END    
    
				END    
    
			END 
		')
	END
