IF NOT EXISTS (SELECT 1 FROM LJ_ETL_TIPO_COMPONENTE WHERE ID_ETL_TIPO = '9115')
BEGIN 
insert into LJ_ETL_TIPO_COMPONENTE(ID_ETL_TIPO,DESC_EAD,DESC_EAD_DESTINO,VERSAO,INATIVO)  VALUES  ('9115','RetailSync.hr_sap_loja_nota','','3.1.1.0','0')
END