
IF NOT EXISTS 
(
   SELECT
      1 
   FROM
      INFORMATION_SCHEMA.COLUMNS 
   WHERE
      TABLE_NAME = 'LOJA_PEDIDO' 
      AND COLUMN_NAME = 'CHANNEL_ID'
)
BEGIN
   ALTER TABLE [dbo].[LOJA_PEDIDO] ADD CHANNEL_ID VARCHAR(100)
END


IF NOT EXISTS 
(
   SELECT
      1 
   FROM
      INFORMATION_SCHEMA.COLUMNS 
   WHERE
      TABLE_NAME = 'LOJA_PEDIDO' 
      AND COLUMN_NAME = 'NSU_FIDELIDADE'
)
BEGIN
   ALTER TABLE [dbo].[LOJA_PEDIDO] ADD NSU_FIDELIDADE VARCHAR(15)
END


