-- POSSP-5157  - Gilvano Santos - (31/03/2021) - Nota Técnica 2020.006
IF NOT EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_INTERMEDIADORES_TRANSACAO')
BEGIN
	CREATE TABLE [dbo].[LOJA_INTERMEDIADORES_TRANSACAO](
                [ID_INTERMEDIADOR] [int] NOT NULL,
                [CNPJ] [char](18) NOT NULL,
                [NOME_FANTASIA] [varchar](90) NOT NULL,
                [INATIVO] [bit] DEFAULT 0 NOT NULL,
                [ENVIA_LOJA_VAREJO] [bit] DEFAULT 0 NOT NULL,
                [DATA_PARA_TRANSFERENCIA] [datetime] NULL,
    CONSTRAINT [XPKLOJA_INTERMEDIADORES_TRANSACAO] PRIMARY KEY CLUSTERED 
    (
                [ID_INTERMEDIADOR] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
    CONSTRAINT [XAKLOJA_INTERMEDIADORES_TRANSACAO] UNIQUE NONCLUSTERED 
    (
		        [CNPJ] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
    ) ON [PRIMARY]
END