IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_VENDA_PROMOCAO' AND COLUMN_NAME = 'ITEM' AND COLUMN_DEFAULT IS NULL)
BEGIN
	IF object_id('DEFAULT_0000') is not null
		Execute SP_BINDEFAULT 'DEFAULT_0000', 'DBO.LOJA_VENDA_PROMOCAO.ITEM';
	else
		ALTER TABLE LOJA_VENDA_PROMOCAO ADD CONSTRAINT DEFAULT_0000 DEFAULT N'0000' FOR ITEM;
END;

if not exists( select 1 from sys.columns where name = 'DATA_VENDA' and
						OBJECT_NAME(object_id) = 'LOJA_VENDA_PROMOCAO_CUPOM' and
						is_nullable = 0 and default_object_id <> 0 )
BEGIN
	Execute SP_BINDEFAULT 'LXDF_DATA_ATUAL', 'DBO.LOJA_VENDA_PROMOCAO_CUPOM.DATA_VENDA'
END;