if not exists (select * from sys.indexes where object_id = object_id('dbo.CADCEP') and name = 'XIE1CADCEP')
	CREATE NONCLUSTERED INDEX [XIE1CADCEP] ON [dbo].[CADCEP] ([CEP8_LOG]) ON [PRIMARY]

if not exists (select * from sys.indexes where object_id = object_id('dbo.TABELA_ALIQUOTA_IMPOSTO_ITEM') and name = 'XIE1TABELA_ALIQUOTA_IMPOSTO_ITEM')
	CREATE NONCLUSTERED INDEX [XIE1TABELA_ALIQUOTA_IMPOSTO_ITEM] ON [dbo].[TABELA_ALIQUOTA_IMPOSTO_ITEM] (UF, INICIO_VIGENCIA, FIM_VIGENCIA);		
	
if not exists (select * from sys.indexes where object_id = object_id('dbo.LOJA_CF_SAT_XML') and name = 'XIE1LOJA_CF_SAT_XML')
	CREATE NONCLUSTERED INDEX [XIE1LOJA_CF_SAT_XML] ON [dbo].[LOJA_CF_SAT_XML] ([ID_LOJA_CF_SAT],[CODIGO_FILIAL]) INCLUDE ([EMAIL_RETORNO]);

if exists (select * from sys.indexes where object_id = object_id('dbo.LOJA_TRANSACAO_FISCAL') and name = 'XPKLOJA_TRANSACAO_FISCAL')
	ALTER TABLE [dbo].[LOJA_TRANSACAO_FISCAL] DROP CONSTRAINT [XPKLOJA_TRANSACAO_FISCAL]

if exists (select * from sys.indexes where object_id = object_id('dbo.LOJA_TRANSACAO_FISCAL') and name = 'XPK_LOJA_TRANSACAO_FISCAL')
	ALTER TABLE [dbo].[LOJA_TRANSACAO_FISCAL] DROP CONSTRAINT [XPK_LOJA_TRANSACAO_FISCAL]

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_TYPE = 'PRIMARY KEY' 
AND TABLE_NAME = 'LOJA_TRANSACAO_FISCAL' AND TABLE_SCHEMA ='dbo' AND CONSTRAINT_NAME = 'XPK_LOJA_TRANSACAO_FISCAL')
begin 
	ALTER TABLE [dbo].[LOJA_TRANSACAO_FISCAL] ADD  CONSTRAINT [XPKLOJA_TRANSACAO_FISCAL] PRIMARY KEY CLUSTERED  (ID_TRANSACAO_FISCAL)
 end 		

if not exists (select * from sys.indexes where object_id = object_id('dbo.LOJA_TRANSACAO_FISCAL') and name = 'XIE1LOJA_TRANSACAO_FISCAL')
	CREATE NONCLUSTERED INDEX [XIE1LOJA_TRANSACAO_FISCAL] ON dbo.LOJA_TRANSACAO_FISCAL (GUID_DOC_FISCAL, CODIGO_FILIAL) INCLUDE (DATA_TRANSACAO,TIPO_TRANSACAO,MODELO_FISCAL);

	
IF NOT EXISTS (SELECT * FROM sysindexes WHERE name = 'XIE6LOJA_VENDA_PGTO' AND id = object_id('LOJA_VENDA_PGTO'))
BEGIN
	CREATE NONCLUSTERED INDEX [XIE6LOJA_VENDA_PGTO] ON [dbo].[LOJA_VENDA_PGTO] (GUID_VENDA_SAT, CODIGO_FILIAL) INCLUDE (LANCAMENTO_CAIXA, TERMINAL, DATA) WITH (FILLFACTOR=90)
END;


IF NOT EXISTS (SELECT * FROM sysindexes WHERE name = 'XIE2LOJA_CF_SAT' AND id = object_id('LOJA_CF_SAT'))
BEGIN
	CREATE NONCLUSTERED INDEX XIE2LOJA_CF_SAT ON dbo.LOJA_CF_SAT (GUID_VENDA_SAT, CODIGO_FILIAL, TERMINAL, LANCAMENTO_CAIXA) INCLUDE (CF_NUMERO, SERIE_NF) WITH (FILLFACTOR=90)
END;
