CREATE VIEW [dbo].[W_REFERENCIA_ECF_NFE_DEV]    
AS  
-- DM 16569    - Wendel Crespigio - #6# - (10/01/2017) - Tratamento para quando o parâmetro usa ticket estiver desligado.   
-- DM 12721    - Eder Silva       - #5# - (25/11/2016) - Tratamento da coluna NF_ORIGEM.NUMERO_COO - Retirado 'convert(int)' e remoção dos espaços vazios.
-- DM 8029     - Vívian Domingues - #4# - (24/08/2016) - Correção para quando a NF-e for DENEGADA (STATUS 70), trazer somente a informação do COO.
-- TP 10857125 - Gilvano Santos   - #3# - (27/10/2015) - INCLUIR NO XML DA NF-E DE TROCA CHAVE_CFE DE VENDA (CF-E SAT). 
-- TP 10622549 - Roberto Beda     - #2# - (11/10/2015) - Correção do código da filial na subquery, para que o join funcione.
-- TP 10177394 - Edson Filenti    - #1# - (11/10/2015) - Ajuste na relação com o select NF_ORIGEM. Acrescentada COLUNA CODIGO_FILIAL.
SELECT	DISTINCT '2D' AS MODELO_FISCAL,   
		ISNULL((SELECT TOP 1 ECF FROM LOJA_CONTROLE_FISCAL WHERE ID_EQUIPAMENTO = B.ID_EQUIPAMENTO ORDER BY DATA_SISTEMA DESC), 1) AS NUMERO_ECF,   
		--CONVERT(Int, B.NUMERO_CUPOM_FISCAL) AS NUMERO_COO, --#1#  
		A.NF_NUMERO AS NF,   
		A.SERIE_NF AS SERIE,   
		E.FILIAL,   
		'S' AS ORIGEM_ENTRADA_SAIDA,
		NF_ORIGEM.NF_ORIGEM,
		NF_ORIGEM.SERIE_NF_ORIGEM,
		NF_ORIGEM.CHAVE_NFE_ORIGEM,
		ISNULL((SELECT TOP 1 ECF FROM LOJA_CONTROLE_FISCAL WHERE ID_EQUIPAMENTO = NF_ORIGEM.NUMERO_ECF ORDER BY DATA_SISTEMA DESC), 1) AS NUMERO_ECF_ORIGEM,   		   
		LTRIM(RTRIM(NF_ORIGEM.NUMERO_COO)) AS NUMERO_COO_ORIGEM  --#5#
FROM LOJA_NOTA_FISCAL A   
LEFT JOIN LOJA_VENDA_PGTO B ON A.NF_NUMERO = B.NUMERO_FISCAL_TROCA  AND A.SERIE_NF = B.SERIE_NF_ENTRADA  
INNER JOIN SERIES_NF C ON A.SERIE_NF = C.SERIE_NF   
LEFT JOIN CTB_ESPECIE_SERIE D ON C.ESPECIE_SERIE = D.ESPECIE_SERIE   
INNER JOIN LOJAS_VAREJO E ON A.CODIGO_FILIAL = E.CODIGO_FILIAL   
INNER JOIN (	
				SELECT  A.CODIGO_FILIAL, F.NF_NUMERO AS NF_ORIGEM, F.SERIE_NF AS SERIE_NF_ORIGEM,  F.CHAVE_NFE  AS CHAVE_NFE_ORIGEM,	-- #2#
						A.NUMERO_FISCAL_TROCA AS NF_TROCA, A.SERIE_NF_ENTRADA AS SERIE_NF_TROCA,
						'2D' AS MODELO_FISCAL, ISNULL(E.ID_EQUIPAMENTO, 1) AS NUMERO_ECF , 
						CASE WHEN ISNULL(CONVERT(Int, E.NUMERO_CUPOM_FISCAL),0) > 0 THEN CONVERT(Int, E.NUMERO_CUPOM_FISCAL) ELSE CONVERT(Int, E.NUMERO_FISCAL_VENDA) END AS NUMERO_COO  --#6# 
				FROM LOJA_VENDA_PGTO A
				INNER JOIN LOJA_VENDA B ON A.CODIGO_FILIAL = B.CODIGO_FILIAL AND A.TERMINAL = B.TERMINAL AND A.LANCAMENTO_CAIXA = B.LANCAMENTO_CAIXA 
				INNER JOIN LOJA_VENDA_TROCA_ORIGEM C ON C.CODIGO_FILIAL = B.CODIGO_FILIAL AND C.DATA_VENDA = B.DATA_VENDA AND C.TICKET = B.TICKET AND C.TICKET_ORIGEM <> B.TICKET 
				INNER JOIN LOJA_VENDA D ON D.CODIGO_FILIAL = C.CODIGO_FILIAL AND D.DATA_VENDA = C.DATA_VENDA_ORIGEM AND D.TICKET = C.TICKET_ORIGEM 
				INNER JOIN LOJA_VENDA_PGTO E ON E.CODIGO_FILIAL = D.CODIGO_FILIAL AND E.TERMINAL = D.TERMINAL AND E.LANCAMENTO_CAIXA = D.LANCAMENTO_CAIXA 
				LEFT JOIN LOJA_NOTA_FISCAL F ON F.CODIGO_FILIAL = E.CODIGO_FILIAL AND F.NF_NUMERO = E.NUMERO_FISCAL_VENDA AND F.SERIE_NF = E.SERIE_NF_SAIDA AND F.STATUS_NFE > = 5 and F.STATUS_NFE <> 70 --#4#
				WHERE ltrim(rtrim(isnull(E.ID_EQUIPAMENTO,''))) != '' --#3#

				UNION ALL
				
				SELECT  F.CODIGO_FILIAL, F.NF_NUMERO AS NF_ORIGEM, F.SERIE_NF AS SERIE_NF_ORIGEM,  NULL AS CHAVE_NFE_ORIGEM, 
						A.NUMERO_FISCAL_CANCELAMENTO AS NF_TROCA, A.SERIE_NF_CANCELAMENTO AS SERIE_NF_TROCA,
						'2D' AS MODELO_FISCAL, ISNULL(A.ID_EQUIPAMENTO, 1) AS NUMERO_ECF , 
						CASE WHEN ISNULL(CONVERT(Int, A.NUMERO_CUPOM_FISCAL),0) > 0 THEN CONVERT(Int, A.NUMERO_CUPOM_FISCAL) ELSE CONVERT(Int, A.NUMERO_FISCAL_VENDA) END AS NUMERO_COO --#6# 
				FROM LOJA_VENDA_PGTO A
				INNER JOIN LOJA_VENDA B ON A.CODIGO_FILIAL = B.CODIGO_FILIAL AND A.TERMINAL = B.TERMINAL AND A.LANCAMENTO_CAIXA = B.LANCAMENTO_CAIXA 
				INNER JOIN LOJA_NOTA_FISCAL F ON F.CODIGO_FILIAL = A.CODIGO_FILIAL AND F.NF_NUMERO = A.NUMERO_FISCAL_CANCELAMENTO AND F.SERIE_NF = A.SERIE_NF_CANCELAMENTO
				WHERE A.VENDA_FINALIZADA = 1 AND A.CANCELADO_FISCAL = 0
) AS NF_ORIGEM ON NF_ORIGEM.NF_TROCA = A.NF_NUMERO AND NF_ORIGEM.SERIE_NF_TROCA = A.SERIE_NF AND NF_ORIGEM.CODIGO_FILIAL = A.CODIGO_FILIAL 
WHERE A.STATUS_NFE NOT IN ('49','59') 