IF OBJECT_ID('DBO.LOJA_OMS_LOG','U')  IS NULL
BEGIN

CREATE TABLE DBO.LOJA_OMS_LOG(
	ID int IDENTITY(1,1) NOT NULL,
	CODIGO_FILIAL_ORIGEM char(6) NOT NULL,
	ID_PEDIDO_ORIGEM varchar(20) NOT NULL,
	ID_ENTREGA_ORIGEM varchar(20) NOT NULL,
	SKU varchar(5) NULL,
	DESCR_ERRO varchar(8000) NULL,
	ERRO_STACK varchar(8000) NULL,
	DATA_HORA SMALLDATETIME DEFAULT(GETDATE()),
 CONSTRAINT XPKLOJA_OMS_LOG PRIMARY KEY CLUSTERED
(
	ID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'LOJA_OMS_LOG'
                      AND COLUMN_NAME = 'ERRO_STACK')
BEGIN
		ALTER TABLE [dbo].[LOJA_OMS_LOG]
		ADD ERRO_STACK varchar(8000) NULL
END

IF EXISTS(select 1 FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'LOJA_OMS_LOG'
                      AND COLUMN_NAME = 'ERRO_STACK'
					  AND CHARACTER_MAXIMUM_LENGTH < 8000)
BEGIN
		ALTER TABLE [dbo].[LOJA_OMS_LOG]
		ALTER COLUMN  ERRO_STACK varchar(8000) NULL		
END

IF EXISTS(select 1 FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'LOJA_OMS_LOG'
                      AND COLUMN_NAME = 'DESCR_ERRO'
					  AND CHARACTER_MAXIMUM_LENGTH < 8000)
BEGIN
		ALTER TABLE [dbo].[LOJA_OMS_LOG]
		ALTER COLUMN  DESCR_ERRO varchar(8000) NULL
END