
IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'LOJA_PEDIDO'
                      AND COLUMN_NAME = 'LX_PEDIDO_ORIGEM')
  ALTER TABLE [dbo].[LOJA_PEDIDO]
    ADD LX_PEDIDO_ORIGEM TINYINT
