IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'LOJA_PEDIDO_PRODUTO'
                      AND COLUMN_NAME = 'DADOS_ADICIONAIS')
  ALTER TABLE [dbo].[LOJA_PEDIDO_PRODUTO]
    ADD DADOS_ADICIONAIS VARCHAR(1024) NULL 
