
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE  TABLE_NAME = 'LOJA_OMS_CANAL') BEGIN
    
	CREATE TABLE LOJA_OMS_CANAL
	(
	    CHANNELID      VARCHAR(32) NOT NULL,
        DESCRICAO      VARCHAR(32) NOT NULL,
        ORDEM_PESQUISA TINYINT     NOT NULL
	)
	
	ALTER TABLE LOJA_OMS_CANAL ADD CONSTRAINT PK_LOJA_OMS_CANAL PRIMARY KEY(CHANNELID)
	
	INSERT INTO LOJA_OMS_CANAL SELECT 'site' AS CHANNELID,'E-commerce' AS DESCRICAO,'1' AS ORDEM_PESQUISA
	
	INSERT INTO LOJA_OMS_CANAL SELECT 'showrooming' AS CHANNELID,'Showrooming' AS DESCRICAO,'0' AS ORDEM_PESQUISA
	
END