------------------------------
-- DECLARACAO DAS VARIAVEIS --
------------------------------
DECLARE @PARAMETRO          VARCHAR(25)    = ''
DECLARE @VALOR_DEFAULT      VARCHAR(100)   = ''
DECLARE @VALOR_ATUAL        VARCHAR(100)   = ''
DECLARE @DESC_PARAMETRO     VARCHAR(100)   = ''
DECLARE @TIPO_DADO          VARCHAR(1)     = ''
DECLARE @NOTA_PROGRAMADOR   VARCHAR(8000)  = ''
DECLARE @PENULT_ATUALIZACAO DATETIME       = GETDATE()
DECLARE @ULT_ATUALIZACAO    DATETIME       = GETDATE()

SELECT @PARAMETRO        = 'TROCA_ITEM_ORIGINARIO_OMS',     
	   @VALOR_DEFAULT    = '.F.',
	   @VALOR_ATUAL      = '.F.',
	   @DESC_PARAMETRO   = 'Indica se o botao para troca de item originario do OMS esta ou nao habilitado na tela de venda',
	   @TIPO_DADO        = 'L',
	   @NOTA_PROGRAMADOR = 'Indica se o botao para troca de item originario do OMS esta ou nao habilitado na tela de venda'

IF NOT EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = @PARAMETRO ) BEGIN
INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, NOTA_PROGRAMADOR, ESCOPO, POR_USUARIO_OK, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE)
SELECT	@PARAMETRO            AS PARAMETRO,
		@PENULT_ATUALIZACAO   AS PENULT_ATUALIZACAO,
		@VALOR_DEFAULT        AS VALOR_DEFAULT,
		@ULT_ATUALIZACAO      AS ULT_ATUALIZACAO,
		@VALOR_ATUAL          AS VALOR_ATUAL,
		@DESC_PARAMETRO       AS DESC_PARAMETRO,
		@TIPO_DADO            AS TIPO_DADO,
		''                    AS RANGE_VALOR_ATUAL,
		0                     AS GLOBAL,
		@NOTA_PROGRAMADOR     AS NOTA_PROGRAMADOR,
		0                     AS ESCOPO,
		0                     AS POR_USUARIO_OK,
		0                     AS PERMITE_POR_EMPRESA,
		1                     AS ENVIA_PARA_LOJA,
		1                     AS PERMITE_POR_LOJA,
		1                     AS PERMITE_POR_TERMINAL,
		1                     AS PERMITE_ALTERAR_NA_LOJA,
		1                     AS PERMITE_ALTERAR_NO_TERMINAL,
		0                     AS ENVIA_PARA_REPRESENTANTE,
		0                     AS PERMITE_POR_REPRESENTANTE,
		0                     AS PERMITE_ALTERAR_NO_REPRESENTANTE
END