CREATE FUNCTION fx_ObterConteudoUnicoJSON(@JSON VARCHAR(1024), @CONTEUDO AS VARCHAR(64), @TEXTO AS BIT)
RETURNS VARCHAR(64)
AS
BEGIN
	DECLARE @RETORNO VARCHAR(64)
	DECLARE @POSINI INT, @POSFIM INT, @PROCURA VARCHAR(128)

	SET @RETORNO = ''
	SET @PROCURA = '"' + @CONTEUDO + '":'
	IF (@TEXTO = 1)
		SET @PROCURA = @PROCURA + '"'
	SET @POSINI = CHARINDEX(@PROCURA, @JSON)
	IF (@POSINI > 0)
	BEGIN
		SET @POSINI = @POSINI + LEN(@PROCURA)
		IF (@TEXTO = 1)
			SET @PROCURA = '",'
		ELSE
			SET @PROCURA = ','
		SET @POSFIM = CHARINDEX(@PROCURA, @JSON, @POSINI)

		IF (@POSFIM > 0)
			SET @RETORNO = SUBSTRING(@JSON, @POSINI, @POSFIM - @POSINI)
	END


	RETURN @RETORNO
END