IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[BLOCOX_CERTIFICADO_DIGITAL]') AND 
type in (N'U')) and EXISTS(SELECT TOP 1 1 FROM SYS.IDENTITY_COLUMNS WHERE OBJECT_NAME(OBJECT_ID) = 'BLOCOX_CERTIFICADO_DIGITAL')
BEGIN
	IF (select count(1) FROM BLOCOX_CERTIFICADO_DIGITAL) = 0
	begin
		DROP TABLE BLOCOX_CERTIFICADO_DIGITAL
	end
	else
	begin
		IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[BLOCOX_CERTIFICADO_DIGITAL_TEMP]'))
		begin
			DROP TABLE BLOCOX_CERTIFICADO_DIGITAL_TEMP
			SELECT * INTO BLOCOX_CERTIFICADO_DIGITAL_TEMP FROM BLOCOX_CERTIFICADO_DIGITAL
			DROP TABLE BLOCOX_CERTIFICADO_DIGITAL							
		end
	end
END