IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[BLOCOX_CERTIFICADO_DIGITAL]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[BLOCOX_CERTIFICADO_DIGITAL](
       [ID] [int] NOT NULL,
       [CODIGO_FILIAL] [char](6) NULL,
       [CERTIFICADO] [text] NULL,
       [DATA_INI_VALIDADE] [datetime] NULL,
       [DATA_FIM_VALIDADE] [datetime] NULL,
       [INATIVO] [bit] NOT NULL,
       [DATA_PARA_TRANSFERENCIA] [datetime] NULL,
       CONSTRAINT [XPKBLOCOX_CERTIFICADO_DIGITAL] PRIMARY KEY CLUSTERED 
       (
             [ID] ASC
       )
) 
END
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[BLOCOX_CERTIFICADO_DIGITAL_TEMP]'))
begin
	INSERT INTO BLOCOX_CERTIFICADO_DIGITAL SELECT * FROM BLOCOX_CERTIFICADO_DIGITAL_TEMP
end