-- DM 118586 - Edson Filenti - 13/05/2019 - Ajuste de performance para emissão da NF-e

IF NOT EXISTS (SELECT * FROM SYS.INDEXES WHERE NAME = 'IX1001_LOJA_VENDA_PGTO')
BEGIN
	CREATE INDEX IX1001_LOJA_VENDA_PGTO
	ON LOJA_VENDA_PGTO (NUMERO_FISCAL_TROCA, SERIE_NF_ENTRADA, CODIGO_FILIAL)
	INCLUDE (LANCAMENTO_CAIXA)
END;

IF NOT EXISTS (SELECT * FROM SYS.INDEXES WHERE NAME = 'IX1001_LOJA_VENDA_TROCA_ORIGEM')
BEGIN
	CREATE INDEX IX1001_LOJA_VENDA_TROCA_ORIGEM
	ON LOJA_VENDA_TROCA_ORIGEM (CODIGO_FILIAL, TICKET, DATA_VENDA)
	INCLUDE (CODIGO_FILIAL_ORIGEM, TICKET_ORIGEM, DATA_VENDA_ORIGEM )
END;

IF NOT EXISTS (SELECT * FROM SYS.INDEXES WHERE NAME = 'IX1001_LOJA_NOTA_FISCAL_ITEM')
BEGIN
	CREATE INDEX IX1001_LOJA_NOTA_FISCAL_ITEM
	ON LOJA_NOTA_FISCAL_ITEM (NF_NUMERO, SERIE_NF, CODIGO_FILIAL, CODIGO_ITEM )
	INCLUDE (QTDE_ITEM, ID_EXCECAO_IMPOSTO)
END;

IF NOT EXISTS (SELECT * FROM SYS.INDEXES WHERE NAME = 'IX1001_LOJA_VENDA')
BEGIN
	CREATE NONCLUSTERED INDEX [IX1001_LOJA_VENDA]
	ON [DBO].[LOJA_VENDA] ([CODIGO_FILIAL],[LANCAMENTO_CAIXA], [TERMINAL])
	INCLUDE ([TICKET],[DATA_VENDA])
END;

IF NOT EXISTS (SELECT * FROM SYS.INDEXES WHERE NAME = 'IX1001_CLIENTE_VAREJO')
BEGIN
	CREATE NONCLUSTERED INDEX [IX1001_CLIENTE_VAREJO]
	ON [DBO].[CLIENTES_VAREJO] ([CODIGO_CLIENTE])
	INCLUDE ([CLIENTE_VAREJO],[EMAIL],[PAIS])
END;

IF NOT EXISTS (SELECT * FROM SYS.INDEXES WHERE NAME = 'IX1002_LOJA_VENDA_PGTO')
BEGIN
	CREATE NONCLUSTERED INDEX IX1002_LOJA_VENDA_PGTO
	ON [DBO].[LOJA_VENDA_PGTO] ([NUMERO_FISCAL_VINCULADA])
	INCLUDE ([NUMERO_CUPOM_FISCAL],[ID_EQUIPAMENTO],[NUMERO_FISCAL_VENDA],SERIE_NF_VINCULADA)
END


IF NOT EXISTS (SELECT * FROM SYS.INDEXES WHERE NAME = 'IX1001_LOJA_NOTA_FISCAL')
BEGIN
	CREATE INDEX IX1001_LOJA_NOTA_FISCAL
	ON LOJA_NOTA_FISCAL (CODIGO_FILIAL, NF_NUMERO, SERIE_NF)
END

IF NOT EXISTS (SELECT * FROM SYS.INDEXES WHERE NAME = 'IX1003_LOJA_VENDA_PGTO')
BEGIN
	CREATE NONCLUSTERED INDEX IX1003_LOJA_VENDA_PGTO
	ON [DBO].[LOJA_VENDA_PGTO] (CODIGO_FILIAL, NUMERO_FISCAL_VENDA, SERIE_NF_SAIDA, NUMERO_FISCAL_VINCULADA, SERIE_NF_VINCULADA)
END
