

IF EXISTS(SELECT TOP 1 1 FROM PARAMETROS WHERE PARAMETRO = 'OMS_TROCA_TOTAL_SAC')
	UPDATE PARAMETROS SET NOTA_PROGRAMADOR = 'DESATIVADO', DESC_PARAMETRO = 'DESATIVADO'
	WHERE PARAMETRO = 'OMS_TROCA_TOTAL_SAC'
