IF NOT EXISTS(	SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
					WHERE TABLE_NAME = 'ADMINISTRADORAS_CARTAO' AND COLUMN_NAME = 'COD_ADM_LINXPAY')
BEGIN
	ALTER TABLE dbo.ADMINISTRADORAS_CARTAO ADD COD_ADM_LINXPAY CHAR(03) NULL
END
