
--BASE DE DADOS DE LOJA
IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[ENTIDADES_CREDITO_CONSULTAS]') AND TYPE IN (N'U'))
	AND NOT EXISTS (SELECT * FROM SYS.tables WHERE NAME='CM_ESTOQUE_PA' AND TYPE='U')
BEGIN
    CREATE TABLE [dbo].[ENTIDADES_CREDITO_CONSULTAS](
	    [ID] [int] NOT NULL, --ATENÇÃO: NAO É IDENTIFY POIS OS DADOS VEM DA RETAGUARDA
	    [TIPO] [varchar](25) NULL,
	    [CODIGO_CLIENTE] [varchar](14) NULL,
	    [COD_FILIAL] [char](6) NULL,
	    [RETORNO_XML] [xml] NULL,
	    [DATA] [datetime] NULL,
	    [STATUS] [varchar](15) NULL,
	    [RESPOSTA] [int] NULL,
	    [MENSAGEM] [varchar](250) NULL,
	    [DOCUMENTO] [varchar](19) NULL,
     CONSTRAINT [PK_ENTIDADES_CREDITO_CONSULTAS] PRIMARY KEY CLUSTERED 
    (
	    [ID] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
    ) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

    ALTER TABLE [dbo].[ENTIDADES_CREDITO_CONSULTAS]  WITH NOCHECK ADD  CONSTRAINT [XFK12782_ENTIDADES_CREDITO_CONSULTAS] FOREIGN KEY([CODIGO_CLIENTE])
    REFERENCES [dbo].CLIENTES_vAREJO ([CODIGO_CLIENTE])
    NOT FOR REPLICATION 
    
    ALTER TABLE [dbo].[ENTIDADES_CREDITO_CONSULTAS] CHECK CONSTRAINT [XFK12782_ENTIDADES_CREDITO_CONSULTAS]

END

