-- Inclusão de Parâmetros 
-- Processo do cálculo do imposto da desoneração.  
IF NOT EXISTS(SELECT parametro 
              FROM   parametros 
              WHERE  parametro = 'UF_TEXTO_NF_SEM_FCP') 
  INSERT INTO dbo.parametros 
              (parametro, 
               penult_atualizacao, 
               valor_default, 
               ult_atualizacao, 
               valor_atual, 
               desc_parametro, 
               tipo_dado, 
               range_valor_atual, 
               global, 
               escopo, 
               por_usuario_ok, 
               nota_programador, 
               permite_por_empresa, 
               envia_para_loja, 
               permite_por_loja, 
               permite_por_terminal, 
               permite_alterar_na_loja, 
               permite_alterar_no_terminal, 
               envia_para_representante, 
               permite_por_representante, 
               permite_alterar_no_representante) 
  VALUES      ('UF_TEXTO_NF_SEM_FCP', 
               Getdate(), 
               'RJ', 
               Getdate(), 
               'RJ', 
				'Lista de UFs que exigem mensagem na NF relativa à ausência de FCP.', 
				'C', 
				'', 
				'0', 
				'0', 
				'0', 
				'Lista de UFs que exigem mensagem na NF relativa à ausência de FCP.', 
				'0', 
				'1', 
				'0', 
				'0', 
				'0', 
				'0', 
				'0', 
				'0', 
				'0' ) 

IF NOT EXISTS(SELECT parametro 
              FROM   parametros 
              WHERE  parametro = 'TEXTO_NF_SEM_FCP') 
  INSERT INTO dbo.parametros 
              (parametro, 
               penult_atualizacao, 
               valor_default, 
               ult_atualizacao, 
               valor_atual, 
               desc_parametro, 
               tipo_dado, 
               range_valor_atual, 
               global, 
               escopo, 
               por_usuario_ok, 
               nota_programador, 
               permite_por_empresa, 
               envia_para_loja, 
               permite_por_loja, 
               permite_por_terminal, 
               permite_alterar_na_loja, 
               permite_alterar_no_terminal, 
               envia_para_representante, 
               permite_por_representante, 
               permite_alterar_no_representante) 
  VALUES      ('TEXTO_NF_SEM_FCP', 
               Getdate(), 
'Não há cobrança do Adicional de Alíquotas (FCP) para os produtos constantes neste documento.' 
             , 
Getdate(), 
'Não há cobrança do Adicional de Alíquotas (FCP) para os produtos constantes neste documento.' 
             , 
'Texto de infAdFisco quando não há incidência de FCP na nota.', 
'C', 
'', 
'0', 
'0', 
'0', 
'Texto de infAdFisco quando não há incidência de FCP na nota.', 
'0', 
'1', 
'1', 
'0', 
'0', 
'0', 
'0', 
'0', 
'0' ) 

IF NOT EXISTS(SELECT parametro 
              FROM   parametros 
              WHERE  parametro = 'TEXTO_NF_PARCIAL_FCP') 
  INSERT INTO dbo.parametros 
              (parametro, 
               penult_atualizacao, 
               valor_default, 
               ult_atualizacao, 
               valor_atual, 
               desc_parametro, 
               tipo_dado, 
               range_valor_atual, 
               global, 
               escopo, 
               por_usuario_ok, 
               nota_programador, 
               permite_por_empresa, 
               envia_para_loja, 
               permite_por_loja, 
               permite_por_terminal, 
               permite_alterar_na_loja, 
               permite_alterar_no_terminal, 
               envia_para_representante, 
               permite_por_representante, 
               permite_alterar_no_representante) 
  VALUES      ('TEXTO_NF_PARCIAL_FCP', 
               Getdate(), 
'Para alguns produtos constantes neste documento, não há cobrança do Adicional de Alíquotas (FCP).'
             , 
Getdate(), 
'Para alguns produtos constantes neste documento, não há cobrança do Adicional de Alíquotas (FCP).'
             , 
'Texto de infAdFisco quando há incidência de FCP na nota, mas não para todos os itens.' 
             , 
'C', 
'', 
'0', 
'0', 
'0', 
'Texto de infAdFisco quando há incidência de FCP na nota, mas não para todos os itens.' 
             , 
'0', 
'1', 
'1', 
'0', 
'0', 
'0', 
'0', 
'0', 
'0' ) 

IF NOT EXISTS(SELECT parametro 
              FROM   parametros 
              WHERE  parametro = 'TEXTO_NF_ITEM_SEM_FCP') 
  INSERT INTO dbo.parametros 
              (parametro, 
               penult_atualizacao, 
               valor_default, 
               ult_atualizacao, 
               valor_atual, 
               desc_parametro, 
               tipo_dado, 
               range_valor_atual, 
               global, 
               escopo, 
               por_usuario_ok, 
               nota_programador, 
               permite_por_empresa, 
               envia_para_loja, 
               permite_por_loja, 
               permite_por_terminal, 
               permite_alterar_na_loja, 
               permite_alterar_no_terminal, 
               envia_para_representante, 
               permite_por_representante, 
               permite_alterar_no_representante) 
  VALUES      ('TEXTO_NF_ITEM_SEM_FCP', 
               Getdate(), 
'Não há cobrança do Adicional de Alíquotas (FCP) para o produto comercializado.' 
             , 
Getdate(), 
'Não há cobrança do Adicional de Alíquotas (FCP) para o produto comercializado.' 
             , 
'Texto de infAdProd quando não há incidência de FCP.', 
'C', 
'', 
'0', 
'0', 
'0', 
'Texto de infAdProd quando não há incidência de FCP.', 
'0', 
'1', 
'1', 
'0', 
'0', 
'0', 
'0', 
'0', 
'0' ) 