IF NOT EXISTS(SELECT PARAMETRO FROM PARAMETROS WHERE PARAMETRO='HAB_BOT_CON')
Begin
Insert into pARAMETROS (PARAMETRO,PENULT_ATUALIZACAO,VALOR_DEFAULT,ULT_ATUALIZACAO,VALOR_ATUAL,DESC_PARAMETRO,TIPO_DADO,RANGE_VALOR_ATUAL,GLOBAL,NOTA_PROGRAMADOR,ESCOPO,POR_USUARIO_OK,PERMITE_POR_EMPRESA,ENVIA_PARA_LOJA,PERMITE_POR_LOJA,PERMITE_POR_TERMINAL,PERMITE_ALTERAR_NA_LOJA,PERMITE_ALTERAR_NO_TERMINAL,ENVIA_PARA_REPRESENTANTE,PERMITE_POR_REPRESENTANTE,PERMITE_ALTERAR_NO_REPRESENTANTE,DATA_PARA_TRANSFERENCIA)
values('HAB_BOT_CON','20191210','','20191210','','HABILITA BOTÃO DE CONTINGENCIA NFCE PARA ESTADOS PERMITIDOS','L',0,0,'DESATIVADO',0,0,0,1,0,0,0,0,0,0,0,'20200206')
End