
IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[LJ_QR_LINX_PAGAMENTOS]') AND TYPE IN (N'U'))
begin
CREATE TABLE [DBO].[LJ_QR_LINX_PAGAMENTOS]
(
	[CODIGO_FILIAL] [char](6) NOT NULL,
	[TERMINAL] [char](3) NOT NULL,
	[LANCAMENTO_CAIXA] [char](7) NOT NULL,
	[PARCELA] [char](2) NOT NULL,
	[PAYMENT_ID] [uniqueidentifier] NULL,
	[ORDER_ID] [uniqueidentifier] NULL,
	[TRANSACTION_ID] [varchar](35) NULL,
	[WALLET_CNPJ] [char](14) NULL,
	[TRADING_NAME] [varchar](30) NULL,
	[VALUE] [numeric](14, 2) NULL,
	[DISCOUNT_VALUE] [numeric](14, 2) NULL,
	[STATUS_ID] [int] NULL,
	[NAME_STATUS] [varchar](50) NULL,
	[DATA_PAYMENT] [datetime] NULL,
	[DATA_PARA_TRANSFERENCIA] [DATETIME] NULL DEFAULT(GETDATE()),
	CONSTRAINT [PK_LJ_QR_LINX_PAGAMENTOS] PRIMARY KEY CLUSTERED 
	(
		[CODIGO_FILIAL], [TERMINAL], [LANCAMENTO_CAIXA], [PARCELA] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, 
	ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)  ON [PRIMARY],
)
END