Create VIEW W_NOTAS_NFE 
AS   
SELECT 0 AS MARCA, 'L' AS TIPO_DOC, CONVERT(VARCHAR(30), 'LOJA_NOTA_FISCAL') AS TABELA_STATUS,   
  LOJA_NOTA_FISCAL.NF_NUMERO AS NF, LOJA_NOTA_FISCAL.SERIE_NF,    LOJAS_VAREJO.FILIAL,   
  ISNULL(CONVERT(VARCHAR(40), CADASTRO_CLI_FOR.NOME_CLIFOR), CLIENTES_VAREJO.CLIENTE_VAREJO) AS NOME_CLIFOR,   
  LOJA_NOTA_FISCAL.EMISSAO,    LOJA_NOTA_FISCAL.TIPO_EMISSAO_NFE, LOJA_NOTA_FISCAL.FIN_EMISSAO_NFE,   
  LOJA_NOTA_FISCAL.STATUS_NFE, LOJA_NOTA_FISCAL.CHAVE_NFE, CONVERT(VARCHAR(23), 'LOJA') AS COD_TRANSACAO,   
  LOJA_NOTA_FISCAL.LOG_STATUS_NFE,    LOJA_NOTA_FISCAL.NOTA_CANCELADA ,   
  LOJA_NOTA_FISCAL.MOTIVO_CANCELAMENTO_NFE,   
  LOJA_NOTA_FISCAL.PROTOCOLO_AUTORIZACAO_NFE, LOJA_NOTA_FISCAL.DATA_AUTORIZACAO_NFE,   
  LOJA_NOTA_FISCAL.PROTOCOLO_CANCELAMENTO_NFE, LOJA_NOTA_FISCAL.DATA_CANCELAMENTO,   
  LOJA_NOTA_FISCAL.GERAR_AUTOMATICO,   
  LOJA_NOTA_FISCAL.REGISTRO_DPEC, LOJA_NOTA_FISCAL.DATA_REGISTRO_DPEC,   
  CONVERT(BIT, CASE WHEN TICKETS.TIPO = 1 THEN 1 ELSE 0 END) AS VENDA,   
  CONVERT(BIT, CASE WHEN TICKETS.TIPO = 2 THEN 1 ELSE 0 END) AS TROCA,   
  CONVERT(BIT, CASE WHEN TICKETS.TIPO = 3 THEN 1 ELSE 0 END) AS NOTA_CANCELAMENTO,   
  CONVERT(BIT, CASE WHEN LOJA_SAIDAS.NUMERO_NF_TRANSFERENCIA IS NOT NULL THEN 1 ELSE 0 END) AS NOTA_SAIDA,   
  ISNULL(TICKETS.VENDA_CANCELADA, 0) AS VENDA_CANCELADA,   
  ISNULL(LOJA_SAIDAS.SAIDA_CANCELADA, 0) AS SAIDA_CANCELADA,   
  TICKETS.QTDE_VENDAS 
FROM LOJA_NOTA_FISCAL (NOLOCK)   
LEFT JOIN LOJAS_VAREJO (NOLOCK) ON LOJA_NOTA_FISCAL.CODIGO_FILIAL = LOJAS_VAREJO.CODIGO_FILIAL   
LEFT JOIN CADASTRO_CLI_FOR (NOLOCK) ON LOJA_NOTA_FISCAL.COD_CLIFOR = CADASTRO_CLI_FOR.COD_CLIFOR   
LEFT JOIN CLIENTES_VAREJO (NOLOCK) ON LOJA_NOTA_FISCAL.CODIGO_CLIENTE = CLIENTES_VAREJO.CODIGO_CLIENTE   
LEFT JOIN LOJA_SAIDAS (NOLOCK) 
ON LOJA_SAIDAS.FILIAL = LOJAS_VAREJO.FILIAL 
AND LOJA_SAIDAS.NUMERO_NF_TRANSFERENCIA = LOJA_NOTA_FISCAL.NF_NUMERO 
AND LOJA_SAIDAS.SERIE_NF = LOJA_NOTA_FISCAL.SERIE_NF  
and LOJA_NOTA_FISCAL.EMISSAO =LOJA_SAIDAS.EMISSAO 
LEFT JOIN   
(  
 SELECT A.CODIGO_FILIAL, B.NUMERO_FISCAL_VENDA AS NF_NUMERO, B.SERIE_NF_SAIDA AS SERIE_NF,   
   Case When COUNT(*) = 1 Then Case When MAX(A.DATA_HORA_CANCELAMENTO) Is Null Then 0 Else 1 End Else 0 End AS VENDA_CANCELADA,   
   COUNT(*) AS QTDE_VENDAS, 1 AS TIPO   
 FROM LOJA_VENDA A (NOLOCK)   
 INNER JOIN LOJA_VENDA_PGTO B (NOLOCK) ON A.CODIGO_FILIAL_PGTO = B.CODIGO_FILIAL AND A.TERMINAL_PGTO = B.TERMINAL AND A.LANCAMENTO_CAIXA = B.LANCAMENTO_CAIXA   
 WHERE LEN(RTRIM(ISNULL(NUMERO_FISCAL_VENDA, ''))) > 0   
 GROUP BY A.CODIGO_FILIAL, B.NUMERO_FISCAL_VENDA, B.SERIE_NF_SAIDA   
 UNION ALL   
 SELECT A.CODIGO_FILIAL, B.NUMERO_FISCAL_TROCA AS NF_NUMERO, B.SERIE_NF_ENTRADA AS SERIE_NF,   
   Case When COUNT(*) = 1 Then Case When MAX(A.DATA_HORA_CANCELAMENTO) Is Null Then 0 Else 1 End Else 0 End AS VENDA_CANCELADA,   
   COUNT(*) AS QTDE_VENDAS, 2 AS TIPO   
 FROM LOJA_VENDA A (NOLOCK)   
 INNER JOIN LOJA_VENDA_PGTO B (NOLOCK) ON A.CODIGO_FILIAL_PGTO = B.CODIGO_FILIAL AND A.TERMINAL_PGTO = B.TERMINAL AND A.LANCAMENTO_CAIXA = B.LANCAMENTO_CAIXA   
 WHERE LEN(RTRIM(ISNULL(NUMERO_FISCAL_TROCA, ''))) > 0   
 GROUP BY A.CODIGO_FILIAL, B.NUMERO_FISCAL_TROCA, B.SERIE_NF_ENTRADA   
 UNION ALL   
 SELECT A.CODIGO_FILIAL, B.NUMERO_FISCAL_CANCELAMENTO AS NF_NUMERO, B.SERIE_NF_CANCELAMENTO AS SERIE_NF,   
   Case When COUNT(*) = 1 Then Case When MAX(A.DATA_HORA_CANCELAMENTO) Is Null Then 0 Else 1 End Else 0 End AS VENDA_CANCELADA,   
   COUNT(*) AS QTDE_VENDAS, 3 AS TIPO   
 FROM LOJA_VENDA A (NOLOCK)  
 INNER JOIN LOJA_VENDA_PGTO B (NOLOCK) ON A.CODIGO_FILIAL_PGTO = B.CODIGO_FILIAL AND A.TERMINAL_PGTO = B.TERMINAL AND A.LANCAMENTO_CAIXA = B.LANCAMENTO_CAIXA   
 WHERE LEN(RTRIM(ISNULL(NUMERO_FISCAL_CANCELAMENTO, ''))) > 0  
  GROUP BY A.CODIGO_FILIAL, B.NUMERO_FISCAL_CANCELAMENTO, B.SERIE_NF_CANCELAMENTO  
) TICKETS 
ON TICKETS.CODIGO_FILIAL = LOJA_NOTA_FISCAL.CODIGO_FILIAL 
AND TICKETS.NF_NUMERO = LOJA_NOTA_FISCAL.NF_NUMERO 
AND TICKETS.SERIE_NF = LOJA_NOTA_FISCAL.SERIE_NF  
WHERE (LOJA_NOTA_FISCAL.STATUS_NFE  > 0) AND LOJA_NOTA_FISCAL.SERIE_NF != 'E2'
