IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LJ_LISTA_PRESENTE_ITEM') BEGIN
CREATE TABLE LJ_LISTA_PRESENTE_ITEM(
 		CODIGO_FILIAL char(6) NOT NULL, 
		TICKET char(9) NOT NULL, 
		ITEM char(4) NOT NULL,
		QTDE int, 
		PRECO_LIQUIDO numeric(14,2), 
		DESCONTO_ITEM numeric(14,2), 
		CODIGO_BARRAS varchar(25), 
		DESCRICAO	varchar(50),	
		SKU varchar(30),
		SKU_ID INT,
		DATA_PARA_TRANSFERENCIA datetime
	  CONSTRAINT [XPKLJ_LISTA_PRESENTE_ITEM] PRIMARY KEY CLUSTERED 
(
	[CODIGO_FILIAL] ASC,
	[TICKET] ASC,
	[ITEM] ASC	
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] 
END