IF NOT EXISTS( SELECT 1 FROM SYS.sysobjects WHERE NAME = 'LGPD_FINALIDADE' )
				BEGIN
				CREATE TABLE [dbo].[LGPD_FINALIDADE](
						[ID_FINALIDADE] [int]  NOT NULL,
						[ID_AMBIENTE] [int] NOT NULL,
						[CODIGO] [varchar](40) NOT NULL,
						[DESCRICAO]	VARCHAR(256) NOT NULL,
						[ID_SERVER]	INT,
						[INATIVO]	BIT NOT NULL,	
						[DATA_PARA_TRANSFERENCIA]	DATETIME,
					CONSTRAINT [XPKRELGPD_FINALIDADE] PRIMARY KEY CLUSTERED 
					(
					[ID_FINALIDADE] ASC
					)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
					) ON [PRIMARY]
					
														
	END				
					



		