-- POSSP-5617 - Gilvano Santos - (08/06/2021) - Bloqueio do botão atualiza estoque
IF NOT EXISTS(SELECT PARAMETRO FROM PARAMETROS WHERE PARAMETRO = 'BLOQUEA_BTN_ATUALIZA_EST')
BEGIN
	Insert into parametros (PARAMETRO,PENULT_ATUALIZACAO,VALOR_DEFAULT, ULT_ATUALIZACAO ,VALOR_ATUAL, DESC_PARAMETRO,  
	TIPO_DADO,RANGE_VALOR_ATUAL, GLOBAL,NOTA_PROGRAMADOR,ESCOPO,POR_USUARIO_OK,	PERMITE_POR_EMPRESA,ENVIA_PARA_LOJA, PERMITE_POR_LOJA,
	PERMITE_POR_TERMINAL,PERMITE_ALTERAR_NA_LOJA,PERMITE_ALTERAR_NO_TERMINAL,
	ENVIA_PARA_REPRESENTANTE,PERMITE_POR_REPRESENTANTE,PERMITE_ALTERAR_NO_REPRESENTANTE,DATA_PARA_TRANSFERENCIA) 
	values('BLOQUEA_BTN_ATUALIZA_EST',GETDATE(),'.F.', GETDATE(),'.F.','Bloqueio do botão atualiza estoque on demand',	
		'L','',0,'Este parametro permite bloqueio do botão atualiza estoque on demand .',
		0,0,1,1,1,0,1,0	,0,0,0,GETDATE())
END