IF NOT EXISTS( SELECT 1 FROM SYS.sysobjects WHERE NAME = 'LGPD_SOLICITACAO_LOJA' )
				BEGIN

CREATE TABLE DBO.LGPD_SOLICITACAO_LOJA
(
	ID_LGPD_SOLICITACAO_LOJA		INT					NOT NULL, -- PK
	TIPO_SOLICITACAO				CHAR(1)				NOT NULL, -- (A anonimizacao, E eliminação)
	CODIGO_FILIAL					CHAR(6)				NOT NULL, -- FK
	DOCUMENTO						VARCHAR(200)		NOT NULL,
	TIPO_DOCUMENTO                  VARCHAR(200)		NOT NULL,
	ID_LGPD_STATUS_PROCESSAMENTO	INT,							-- 1,2,3 (PENDENTE, PARCIAL, FINALIZADO)
	MSG_RESULTADO_LOJA              VARCHAR(MAX),       
	DATA_SOLICITACAO				DATETIME			NOT NULL,
	DATA_PROCESSAMENTO				DATETIME,	
	DATA_PARA_TRANSFERENCIA			DATETIME,

	CONSTRAINT XPKLGPD_SOLICITACAO_LOJA PRIMARY KEY(ID_LGPD_SOLICITACAO_LOJA),
	CONSTRAINT XFKLGPD_SOLICITACAO_LOJA FOREIGN KEY(CODIGO_FILIAL) REFERENCES DBO.LOJAS_VAREJO(CODIGO_FILIAL)

)
					
														
	END				
					



		