-- POSSP-5737 - Roberto Beda - (28/06/2021) - Eliminação e anonimização preservando dados em função de hipóteses de tratamento
-- POSSP-5736 - Roberto Beda - (22/06/2021) - Criação da tabela LJ_LGPD_LOG (log de eliminação e anonimização de LGPD)
-- POSSP-5698 - Gilvano Santos - (20/06/2021) - Novos campos para LGPD (eliminação e anonimização)
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CLIENTES_VAREJO' AND COLUMN_NAME = 'LGPD_TRATAMENTO')
BEGIN 
	EXEC('ALTER TABLE CLIENTES_VAREJO ADD LGPD_TRATAMENTO INT NULL')

	EXEC sp_bindefault 'DEFAULT_0', 'CLIENTES_VAREJO.LGPD_TRATAMENTO'
END

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CLIENTES_VAREJO_LOG' AND COLUMN_NAME = 'LGPD_TRATAMENTO')
BEGIN 
	EXEC('ALTER TABLE CLIENTES_VAREJO_LOG ADD LGPD_TRATAMENTO INT NULL')

	EXEC sp_bindefault 'DEFAULT_0', 'CLIENTES_VAREJO_LOG.LGPD_TRATAMENTO'
END

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CADASTRO_CLI_FOR' AND COLUMN_NAME = 'LGPD_TRATAMENTO')
BEGIN 
	EXEC('ALTER TABLE CADASTRO_CLI_FOR ADD LGPD_TRATAMENTO INT NULL')

	EXEC sp_bindefault 'DEFAULT_0', 'CADASTRO_CLI_FOR.LGPD_TRATAMENTO'
END

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LOJA_VENDEDORES' AND COLUMN_NAME = 'LGPD_TRATAMENTO')
BEGIN 
	EXEC('ALTER TABLE LOJA_VENDEDORES ADD LGPD_TRATAMENTO INT NULL')

	EXEC sp_bindefault 'DEFAULT_0', 'LOJA_VENDEDORES.LGPD_TRATAMENTO'
END

IF NOT EXISTS (SELECT TOP 1 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'LJ_LGPD_LOG')
	CREATE TABLE DBO.LJ_LGPD_LOG
	(
		ID_LGPD_LOG						INT IDENTITY(1,1)	NOT NULL,
		ORIGEM_SOLICITACAO				TINYINT NOT NULL DEFAULT 3,	-- 1=ERP, 2=Pendência Linx POS, 3=Avulsa
		ID_LGPD_SOLICITACAO				INT	NULL,
		CODIGO_FILIAL					CHAR(6) NOT NULL,
		CODIGO_OCORRENCIA				TINYINT NOT NULL,	-- 1 = inicio do processamento da solicitação; 2 = erro no processamento da solicitação 3 = fim do processamento da solicitação; 255 = outros
		DESCRICAO						VARCHAR(1000),
		DATA_HORA_LOG					SMALLDATETIME NOT NULL,
		CONSTRAINT XPK_LJ_LGPD_LOG PRIMARY KEY(ID_LGPD_LOG),
	)

IF NOT EXISTS (SELECT TOP 1 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LJ_LGPD_LOG' AND COLUMN_NAME = 'ORIGEM_SOLICITACAO')
	ALTER TABLE DBO.LJ_LGPD_LOG ADD ORIGEM_SOLICITACAO				TINYINT NOT NULL DEFAULT 3	-- 1=ERP, 2=Pendência Linx POS, 3=Avulsa
