-- POSSP-5737 - Roberto Beda - (28/06/2021) - Eliminação e anonimização preservando dados em função de hipóteses de tratamento
IF NOT EXISTS( SELECT 1 FROM SYS.sysobjects WHERE NAME = 'LGPD_SOLICITACAO_RECEBIDA ' )
BEGIN
	CREATE TABLE DBO.LGPD_SOLICITACAO_RECEBIDA 
	(
		ID_LGPD_SOLICITACAO_LOJA		INT					NOT NULL, -- PK
		TIPO_SOLICITACAO				CHAR(1)				NOT NULL, -- (A anonimizacao, E eliminação)
		CODIGO_FILIAL					CHAR(6)				NOT NULL, -- FK
		DOCUMENTO						VARCHAR(200)		NOT NULL,
		ID_LGPD_TIPO_DOCUMENTO          INT					NOT NULL,-- (1-CPF, 2-RG...)
		ID_LGPD_STATUS_PROCESSAMENTO	INT,						 -- 1,2,3 (PENDENTE, PARCIAL, FINALIZADO)
		MSG_RESULTADO_LOJA              VARCHAR(MAX),       
		DATA_SOLICITACAO				DATETIME			NOT NULL,
		DATA_PROCESSAMENTO				DATETIME,	
		DATA_PARA_TRANSFERENCIA			DATETIME,

		CONSTRAINT XPKLGPD_SOLICITACAO_RECEBIDA  PRIMARY KEY(ID_LGPD_SOLICITACAO_LOJA ),
		CONSTRAINT XFKLGPD_SOLICITACAO_RECEBIDA  FOREIGN KEY(CODIGO_FILIAL) REFERENCES DBO.LOJAS_VAREJO(CODIGO_FILIAL)

	)
END				
					
IF NOT EXISTS( SELECT 1 FROM SYS.sysobjects WHERE NAME = 'LGPD_SOLICITACAO_PENDENTE' )
BEGIN
CREATE TABLE DBO.LGPD_SOLICITACAO_PENDENTE
(
	ID_LGPD_SOLICITACAO_PENDENTE	INT IDENTITY(1,1) NOT NULL,	-- PK
	ID_LGPD_SOLICITACAO_LOJA		INT,	-- FK
	TIPO_SOLICITACAO				CHAR(1) NOT NULL,	-- A=anonimização, E=eliminação
	CODIGO_FILIAL					CHAR(6) NOT NULL,		-- FK
	DOCUMENTO						VARCHAR(200) NOT NULL,
	ID_LGPD_TIPO_DOCUMENTO          INT					NOT NULL,-- (1-CPF, 2-RG...)
	ID_LGPD_STATUS_PROCESSAMENTO	INT,						 -- 1,2,3 (PENDENTE, PARCIAL, FINALIZADO)
	DATA_PREVISTA					DATETIME NOT NULL,
	DATA_PROCESSAMENTO				DATETIME,
	CONSTRAINT XPKLGPD_SOLICITACAO_PENDENTE PRIMARY KEY(ID_LGPD_SOLICITACAO_PENDENTE),
	CONSTRAINT XFKLGPD_SOLICITACAO_PENDENTE_LOJA FOREIGN KEY (CODIGO_FILIAL) REFERENCES DBO.LOJAS_VAREJO(CODIGO_FILIAL),
	CONSTRAINT XFKLGPD_SOLICITACAO_PENDENTE_REC FOREIGN KEY (ID_LGPD_SOLICITACAO_LOJA) REFERENCES DBO.LGPD_SOLICITACAO_RECEBIDA(ID_LGPD_SOLICITACAO_LOJA)
)
END
		