
CREATE VIEW [dbo].[W_IMPRESSAO_NFE_PGTO] 
AS

-- PRODSHOP-11262 - Fernando Marinho - #52# - 11/03/2022 - Correção para Valor do troco incorreto venda com Delivery + Gift Card
-- POSSP-7573     - André Artuzo     - #51# - 11/02/2022 - Correção para Venda + Troca + Showrooming. 
-- PRODSHOP-10458 - Wendel Crespigio - #50# - 27/01/2022 - Correção para Valor do troco incorreto venda com Vitrine + Troca + Arredondar.
-- PRODSHOP-10297 - Wendel Crespigio - #49# - 19/01/2022 - Correção para compatibilização com DTEF STONE. 
-- PRODSHOP-8472  - João Leite	     - #48# - 01/12/2021 - Correção processo de troca (Venda com troca + Arredondar)
-- PRODSHOP-8814  - Eder Silva	     - #47# - 19/11/2021 - Correção processo de troca (Item Vitrine + Item Loja + Item Devolução)
-- PRODSHOP-8814  - Fillipi Ramos    - #46# - 17/11/2021 - Correção na ORDEM 11 para respeitar todos os cenários dessa parte (NFc-e + TROCA + VITRINE)
-- POSSP-6214	  - Gilvano Santos   - #45# - 15/09/2021 - Correção para finalizar venda com item de troca
-- PRODSHOP-7942  - EDER SILVA       - #44# - 14/09/2021 - Tratamento para o processo de venda customizado do Vitrine na Reserva.
-- PRODSHOP-7635  -  FILLIPI RAMOS   - #43# - 03/09/2021 - Correção para vendas SAT com ARREDONDAR ou GIFT CARD.
-- PRODSHOP-7942  - EDER SILVA       - #42# - 26/08/2021 - Correção para exibir o valor do troco correto em processos de troca SEM Vitrine.
-- PRODSHOP-7907  - EDER SILVA       - #41# - 24/08/2021 - Correção para exibir o valor do troco correto em processos de troca COM Vitrine.
-- PRODSHOP-7261  - EDER SILVA       - #40# - 21/07/2021 - Alterada a regra para exibição do troco no SAT quando tiver item do Vitrine na venda.
-- PRODSHOP-7221  - EDER / WENDEL    - #39# - 16/07/2021 - Alterada a regra para exibição do troco na NFC-e quando tiver item do Vitrine na venda.
-- PRODSHOP-7058  - EDER / WENDEL    - #38# - 06/07/2021 - Tratamento para exibir a forma de pagamento correta e o troco quando tiver item do Vitrine.
-- POSSP-5157     - Gilvano Santos   - #37# - 31/03/2021 - Nota Técnica 2020.006 somente para NFC-e ou NF-e
-- MODASP-5078    - Wendel Crespigio - #36# - 16/10/2020 - Tratamento de venda com NFC-e + Vitrine + Frete.
-- POSSP-3210     - ANDRÉ ARTUZO	 - #35# - 05/06/2020 - AJUSTE NO VALOR DO TROCO QUANDO HOUVER ITEM DE ENTREGA FUTURA NO TICKET PARA ATENDER CENÁRIO COM DESCONTO. 
-- MODASP-5669    - WENDEL CRESPIGIO - #34# - 04/09/2019 - GERAR TROCO NA NFC-E QUANDO HOUVER ITEM DE ENTREGA FUTURA NO TICKET + TROCA.
-- MODASP-5669    - EDER SILVA       - #33# - 04/09/2019 - GERAR TROCO NA NFC-E QUANDO HOUVER ITEM DE ENTREGA FUTURA NO TICKET.
-- DM 113415      - GILVANO SANTOS   - #32# - 18/03/2019 - ADEQUAR O VALE TROCA A FORMA DE PAGAMENTO CREDITO LOJA
-- DM 108223      - EDER SILVA       - #31# - 01/02/2019 - TRATAMENTO PARA CREDENCIADORA COM CÓDIGO NEGATIVO.
-- DM 85373       - FABIO SANTOS     - #30# - 27/07/2018 FLUXO DE EXCEÇÃO OMS - TRATAMENTO PARA NÃO CONSIDERAR FRETE NA PARCELA (REPLICAÇÃO GILVANO SANTOS)
-- DM 80634       - WENDEL CRESPIGIO - #29# - 26/06/2018 - TRATAMENTO PARA MELHORIA DE PERFORMANCE NF-E 4.0
-- DM 72869       - EDER SILVA       - #28# - 02/05/2018 - NF-E 4.0 - CORREÇÃO PARA INFORMAR O CÓDIGO CORRETO DA BANDEIRA.
-- DM 70763	      - DIEGO MORENO     - #27# - 02/01/2018 - NF-E 4.0. VALIDAÇÃO PARA A GERAÇÃO DA TAG TBAND APENAS PARA AS NOVAS BANDEIRAS QUANDO FOR LAYOUT 4.00.
-- DM 58430	      - DIEGO MORENO     - #26# - 02/01/2018 - NF-E 4.0. CAPTURA DO VALOR DE TROCO E INFORMAÇÕES DE PAGAMENTO COM CARTÕES DE CRÉDITO.
-- SEM DM         - WENDEL CRESPIGIO - #25# - 22/12/2017 - MELHORIA DE PERFORMANCE.
-- DM 42894       -	WENDEL CRESPIGIO - #24# - 11/09/2017 - PODEM EXISTIR SITUAÇÕES ONDE O MODULO DO SITEF QUE RETORNAR OS DADOS DA CREDENCIADORA NÃO ESTEJA INSTALADO, COM ISTO O LINXPOS NÃO CONSEGUE GRAVAR OS CAMPOS NECESSÁRIOS
-- DM 37504       - GIEDSON SILVA    - #23# - 12/07/2017 - ALTERAÇÃO DE PONTOS PARA MELHORIA DE PERFORMANCE DA VIEW CONFORME ORIENTAÇÃO DA EQUIPE DE DBA.
--			      - CAMPOS: PARCELA(RETIRANDO ROW_NUMBER) E GUID_VENDA_SAT(RETIRANDO CAST) PARA QUE SEJA EFETUADO O TRATAMENTO FORA DA VIEW, ISTO É NO FOX OU DENTRO DA DLL NFCEFOXPRO.
-- SEM DM         - FILLIPI RAMOS 	 - #22# - TRATAMENTO PARA REALIZAR O PRENCHIMENTO CORRETAMENTE DA TAG CADMC.
-- DM 1162        - FILLIPI RAMOS 	 - #21# - PEGAR O COD_CREDENCIADORA DA LOJA_VENDA_PARCELAS.
-- DM 15857       - WENDEL CRESPIGIO - #20# - 21/12/2016 - CONFORME VISITA NO CLIENTE ALPARGATAS IDENTIFICAMOS PONTOS QUE OCASIONAVAM PROBLEMAS DE DEADLOCK
-- DM 9545	      - EDER SILVA       - #19# - 30/09/2016 - INCLUSAS AS FORMAS DE PAGAMENTO 'DÉBITO' (E,K) NO PREENCHIMENTO DA BANDEIRA DO CARTÃO.
-- DM 3747	      - GERSON PRADO	 - #18# - 22/06/2016 - PROGRAMAR A DESCRIÇÃO DAS FORMAS DE PAGAMENTO PARA VENDAS COM TROCA CF-E SAT
-- DM 2009        - VÍVIAN DOMINGUES - #17# - 30/05/2016 - TIRADO O AGRUPAMENTO DO TIPO DE PAGAMENTO EMITIDO  NO DANFE DO SAT.
-- DM 1361        - WENDEL CRESPIGIO - #16# - DEMANDA URGENTE CLIENTE HERING\TACO PROBLEMA COM SOMATORIO DO TOTAL DAS NOTAS DIFERE DO SOMATORIO DO TOTAL DAS VENDAS / PROBLEMA OCORRIA COM VENDA + TROCAS + DESCONTO , FOI FEITO TESTES COM DESCONTO + TROCA + ARREDONDAR PARA VERIFICAR SE NÃO VOLTAVA O PROBLEMA DO TRATAMENTO DO #11#
-- TP10657171     - JOAO GONZALES    - #15# - INSERIDO JOIN COM OS CAMPOS CHAVES ENTRE AS TABELAS, PARA EVITAR ERROS DE IMPRESSÃO NO SOMATÓRIO DA VENDA.
-- TP10589609     - GILVANO SANTOS   - #14# - ADEQUAÇÃO A NORMA TECNICA 2015.002 - FORMA DE PAGAMENTOS
-- TP10224759     - GILVANO SANTOS   - #13# - CORREÇÃO SELECT VENDAS CF-E S@T QUANDO OCORRER TROCA. ACRESCENTADO VALIDAÇÃO NO SELECT 1 PARA VERIFICAR SE VENDA POSSUI TROCA. 
-- TP9972235      - EDSON FILENTI    - #12# - CORREÇÃO SELECT VENDAS NFC-E QUANDO OCORRER TROCA. ACRESCENTADO VALIDAÇÃO NO SELECT 1 PARA VERIFICAR SE VENDA POSSUI TROCA. 
-- TP9735253      - GILVANO SANTOS   - #11# - CORREÇÃO DOS VALORES QUANDO OCORRER VENDA + TROCA + ( ARREDONDAR OU VALE PRESENTE ).
-- TP9357406      - GILVANO SANTOS   - #10# - PROGRAMAÇÃO DO LINXPOS PARA O PAF-ECF 2015 - INCLUSÃO DAS COLUNA VENDA_ECF QUE VALIDA SE A VENDA POSSUI UM CF GERADO PELO ECF.
-- TP9426371      - GILVANO SANTOS   - #9#  - INCLUSÃO DAS COLUNAS CNPJ_CREDENCIADORA, AUTORIZACAO E BANDEIRA NA EMISSAO DA NFC-E
-- TP8618647      - DIEGO MORENO     - #8#  - CORREÇÃO PARA QUE NÃO ENCONTRANDO INFORMAÇÃO DO COD_CREDENCIADORA DE CARTÃO PARA CF-E SAT PARA OS TIPOS DE PAGAMENTO 'A','B','E','I','K' EXIBA A INFORMAÇÃO '999'
-- TP8597168      - DIEGO MORENO     - #7#  - CORREÇÃO FORMAÇÃO DE PAGAMENTO S@T. DIFERENTE DA NFC-E, S@T SUPORTA EXCESSO DE PAGAMENTO (GERANDO TROCO AUTOMÁTICO)
-- TP5636147      - GILVANO SANTOS   - #6#  - CORREÇÃO DO TROCO NA OPERAÇÃO DE VENDA
-- TP5636147      - GILVANO SANTOS   - #5#  - ADEQUAÇÃO DA VIEW PARA EMISSÃO DO CF-E S@T
-- TP7068363      - DIEGO.MORENO/JORGE.DAMASCO - #4# - (18/11/2014) - CORREÇÃO NOS SELECT'S:
--                                                                          1) RETORNA O PGTO DAS VENDAS
--                                                                          2) RETORNA O PGTO DOS VALES
--                                                                          3) RETORNA O PGTO DAS TROCAS
-- TP6300918  - JORGE.DAMASCO    - #3#  - (07/10/2014) - CRIAÇÃO DE UM TERCEIRO SELECT (DO MEIO) PARA GENERALIZAÇÃO DAS PARCELAS
--                                                                          NEGATIVAS E IMPLEMENTAÇÃO DO CONTEXTO NO WHERE PARA TRATAMENTO DE TAIS
--                                                                          PARCELAS (PRIMEIRO E SEGUNDO SELECT).
-- 26/02/2014 - GILVANO SANTOS - TP 5112540 - #2# - INCLUSÃO DA COLUNA PARCELA DA TABELA LOJA_VENDA_PARCELA PARA PERMITIR INCLUSÃO CORRETO QUANDO A VENDA UTILIZAR MAIS DE 1 CARTÃO DE CRÉDITO.
-- 19/12/2013 - GILVANO SANTOS - TP 3996736 - #1# - CORREÇÃO PARA RECONHECER APENAS OS VALORES DA TROCA DE MERCADORIA QUANDO O TICKET CONTER TROCA E DEVOLUÇÃO NA MESMA OPERAÇÃO.
--==========================================================================================================================================================================================================
-- VENDAS NFC-E --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SELECT	
		1 AS ORDEM,
		A.CODIGO_FILIAL, --#5#
		D.FILIAL,
		A.NF_NUMERO AS NF,
		A.SERIE_NF	AS SERIE_NF,
		B.TERMINAL, 
		B.LANCAMENTO_CAIXA, --#5#
		B.GUID_VENDA_SAT, --#5#
		C.PARCELA	AS PARCELA,	 
		CASE	
			WHEN C.TIPO_PGTO IN ('D','M')			THEN '01'
			WHEN C.TIPO_PGTO IN ('C','P')			THEN '02'
			WHEN C.TIPO_PGTO IN ('A','B','I')		THEN '03'
			WHEN C.TIPO_PGTO IN ('E','K')			THEN '04'
			--WHEN C.TIPO_PGTO IN ('#','@','N','>')	THEN '05' --#37#
			--WHEN C.TIPO_PGTO = '&'				THEN '12' --#37#
			WHEN C.TIPO_PGTO IN ('#','N','>')		THEN '05' --#37#
			WHEN C.TIPO_PGTO = '@'					THEN '12' --#37#
			WHEN C.TIPO_PGTO = '&'					THEN '15' --#37#
			when C.TIPO_PGTO = '+' AND (GETDATE() < CONVERT(DATETIME, N.VALOR_ATUAL,103)) THEN '05' --#37#
			WHEN C.TIPO_PGTO = '+' AND E.MODALIDADE_QR = 3	THEN '17' --#37#
			WHEN C.TIPO_PGTO = '+' AND E.MODALIDADE_QR != 3 THEN '18' --#37#
			--ELSE '99' END AS TIPO_PAGAMENTO, --#37#
		ELSE '05' END AS TIPO_PAGAMENTO, --#37#
		C.CHEQUE_DIGITO, --#30#
		NULL AS COD_CREDENCIADORA, --#5#
		CASE
			WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_XML_NFE',   A.CODIGO_FILIAL), '0') < '4.00' AND K.NUMERO_MODELO_FISCAL = '55' THEN C.VALOR
			WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_JSON_NFCE', A.CODIGO_FILIAL), '0') < '4.00' AND K.NUMERO_MODELO_FISCAL = '65' THEN C.VALOR
			ELSE C.VALOR + C.TROCO END AS VALOR, --#26#		
		CASE
			WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_XML_NFE',   A.CODIGO_FILIAL), '0') < '4.00' AND K.NUMERO_MODELO_FISCAL = '55' THEN 0
			WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_JSON_NFCE', A.CODIGO_FILIAL), '0') < '4.00' AND K.NUMERO_MODELO_FISCAL = '65' THEN 0			
		ELSE C.TROCO END AS TROCO, --#26#
		CASE 
			WHEN C.TIPO_PGTO NOT IN ('A','B','I','E','K') THEN NULL ELSE
			( CASE WHEN A.PGTO_INTERMEDIADOR = 1 AND Q.ID_INTERMEDIADOR IS NOT NULL THEN Q.CNPJ --#37#
			       ELSE ISNULL(F.CNPJ_CREDENCIADORA,G.CNPJ_CREDENCIADORA) END) END AS CNPJ_CREDENCIADORA, --#9# #26#
		CASE 
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K')	THEN RIGHT(RTRIM(LTRIM(C.NUMERO_APROVACAO_CARTAO)),6)
			ELSE NULL END AS AUTORIZACAO, --#9# #49#
		-- #19# - INÍCIO #27#
		-- #28# - INÍCIO - PASSOU A VALIDAR O NOME DA ADMINISTRADORA DA TABELA 'LX_ADMINISTRADORAS_CARTAO'
		CASE 
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%VISA%'				THEN '01'
	        WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%MASTERCARD%'		THEN '02' 
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%AMERICAN EXPRESS%'	THEN '03'
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%SOROCRED%'			THEN '04'
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%DINERS%'			THEN 
				CASE 
					WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_JSON_NFCE', C.CODIGO_FILIAL), '0') < '4.00' 
					THEN '99' ELSE '05' END			
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%ELO%'				THEN 
				CASE 
					WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_JSON_NFCE', C.CODIGO_FILIAL), '0') < '4.00' 
					THEN '99' ELSE '06' END
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%HIPERCARD%'		THEN 
				CASE
					WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_JSON_NFCE', C.CODIGO_FILIAL), '0') < '4.00' 
					THEN '99' ELSE '07' END
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%AURA%'				THEN 
				CASE 
					WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_JSON_NFCE', C.CODIGO_FILIAL), '0') < '4.00' 
					THEN '99' ELSE '08' END
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%CABAL%'			THEN --'09' --#26#
				CASE 
					WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_JSON_NFCE', C.CODIGO_FILIAL), '0') < '4.00' 
					THEN '99' ELSE '09' END		
		-- #19# - FIM	#27# #28#
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') THEN '99' --#9#    			
			ELSE NULL END BANDEIRA, --#9# #27#
	   CASE 
			WHEN ISNULL(B.ID_EQUIPAMENTO,'') = '' THEN CONVERT(BIT, 0) 
			ELSE CONVERT(BIT, 1) END AS VENDA_ECF, --#10#
	   CASE 
			WHEN C.TIPO_PGTO IN ('K','I')		THEN 1 --#14#
			WHEN C.TIPO_PGTO IN ('E','B','A')	THEN 2 --#14#
			ELSE NULL END AS TIPO_INTEGRA --#14#

FROM	LOJA_NOTA_FISCAL A						WITH (NOLOCK) --#25#
		INNER JOIN	LOJA_VENDA_PGTO B			WITH (NOLOCK) --#25#
					ON	A.CODIGO_FILIAL = B.CODIGO_FILIAL AND
						A.SERIE_NF = B.SERIE_NF_SAIDA AND
						A.NF_NUMERO = B.NUMERO_FISCAL_VENDA 
		INNER JOIN	LOJA_VENDA_PARCELAS C		WITH (NOLOCK) --#25#
					ON	B.TERMINAL = C.TERMINAL AND
						B.LANCAMENTO_CAIXA= C.LANCAMENTO_CAIXA AND
						B.CODIGO_FILIAL = C.CODIGO_FILIAL 
		INNER JOIN	LOJAS_VAREJO D				WITH (NOLOCK) --#20# --#25#
					ON	A.CODIGO_FILIAL = D.CODIGO_FILIAL
		LEFT JOIN	ADMINISTRADORAS_CARTAO E	WITH (NOLOCK) --#25#
					ON	C.CODIGO_ADMINISTRADORA = E.CODIGO_ADMINISTRADORA --#9#
		LEFT JOIN	CREDENCIADORA_CARTAO F		WITH (NOLOCK) --#25#
					ON	C.COD_CREDENCIADORA = F.COD_CREDENCIADORA --#9##21#
		LEFT JOIN	CREDENCIADORA_CARTAO G		WITH (NOLOCK) --#25#
					ON	E.COD_CREDENCIADORA = G.COD_CREDENCIADORA --#9#
		INNER JOIN	LOJA_VENDA I				WITH (NOLOCK) --#12# --#25#
					ON	B.CODIGO_FILIAL = I.CODIGO_FILIAL_PGTO AND --#12#
						B.TERMINAL = I.TERMINAL_PGTO AND --#12#
						B.LANCAMENTO_CAIXA = I.LANCAMENTO_CAIXA --#12#
		INNER JOIN	SERIES_NF J					WITH (NOLOCK)  --#29#
					ON	J.SERIE_NF = A.SERIE_NF
		INNER JOIN	CTB_ESPECIE_SERIE K			WITH (NOLOCK) --#29#
					ON	K.ESPECIE_SERIE = J.ESPECIE_SERIE
		LEFT JOIN	LX_ADMINISTRADORAS_CARTAO L	WITH (NOLOCK) --#29# -- #28#
					ON	LTRIM(RTRIM(L.LX_COD_ADMINISTRADORA)) = LTRIM(RTRIM(E.LX_COD_ADMINISTRADORA))  -- #28#
		INNER JOIN	(	SELECT SUM(CONVERT(INT,INDICA_ENTREGA_FUTURA)) AS TEM_ENTREGA_FUTURA, CODIGO_FILIAL, TICKET, DATA_VENDA 
						FROM LOJA_VENDA_PRODUTO	WITH (NOLOCK)
						WHERE QTDE_CANCELADA = 0 
						GROUP BY CODIGO_FILIAL, TICKET, DATA_VENDA	) M
					ON  M.CODIGO_FILIAL = I.CODIGO_FILIAL AND
						M.TICKET = I.TICKET AND 
						M.DATA_VENDA = I.DATA_VENDA AND 
						M.TEM_ENTREGA_FUTURA = 0
		INNER JOIN	W_PARAMETROS_LOJA N			WITH (NOLOCK) --#37#
					ON	A.CODIGO_FILIAL = N.CODIGO_FILIAL AND --#37#
						PARAMETRO = 'DATA_INI_NT2020_006' --#37#
		LEFT JOIN	LOJA_INTERMEDIADORES_TRANSACAO Q WITH (NOLOCK) --#37#
					ON	A.ID_INTERMEDIADOR = Q.ID_INTERMEDIADOR AND --#37# 
						Q.INATIVO = 0 --#37#
WHERE	C.VALOR > 0 AND I.VALOR_TROCA = 0 AND --#12#
		C.LANCAMENTO_CAIXA NOT IN (	SELECT	LVP.LANCAMENTO_CAIXA 
									FROM	LOJA_VENDA_PARCELAS LVP WITH (NOLOCK) --#25#
									WHERE	C.TERMINAL = LVP.TERMINAL AND 
											C.LANCAMENTO_CAIXA = LVP.LANCAMENTO_CAIXA AND 
											C.CODIGO_FILIAL = LVP.CODIGO_FILIAL AND 
											LVP.VALOR < 0) -- #15#
											
UNION ALL

-- USO DO VALES NFC-E ----------------------------------------------------------------------------------
SELECT 
		2 AS ORDEM,
		A.CODIGO_FILIAL, --#5#
		D.FILIAL,
		A.NF_NUMERO AS NF,
		A.SERIE_NF AS SERIE_NF,   
		B.TERMINAL, B.LANCAMENTO_CAIXA, --#5#   
		B.GUID_VENDA_SAT,--ISNULL(CONVERT(CHAR(38), B.GUID_VENDA_SAT),'') AS GUID_VENDA_SAT, --#5##23#
		'01' AS PARCELA,
		--'99' TIPO_PAGAMENTO, --#37#
		'05' as TIPO_PAGAMENTO, -- #37#
		MAX(C.CHEQUE_DIGITO), --#30#
		NULL AS COD_CREDENCIADORA, --#5#
		--SUM(C.VALOR) + isnull(FRETE,0) AS VALOR, --#36#--#52#
		SUM(C.VALOR) AS VALOR, --#52#
		0 AS TROCO, --#5#
		NULL AS CNPJ_CREDENCIADORA, --#9#
		NULL AS AUTORIZACAO, --#9#
		NULL AS BANDEIRA, --#9#
		CASE WHEN ISNULL(B.ID_EQUIPAMENTO,'') = '' THEN CONVERT(BIT, 0) ELSE CONVERT(BIT, 1) END AS VENDA_ECF, --#10#
		NULL AS TIPO_INTEGRA --#14#
FROM	LOJA_NOTA_FISCAL A WITH (NOLOCK) --#25#
		INNER JOIN	LOJA_VENDA_PGTO B		WITH (NOLOCK) --#25#
					ON	A.CODIGO_FILIAL = B.CODIGO_FILIAL AND 
						A.SERIE_NF = B.SERIE_NF_SAIDA AND 
						A.NF_NUMERO = B.NUMERO_FISCAL_VENDA 
		INNER JOIN	LOJA_VENDA_PARCELAS C	WITH (NOLOCK) --#25#
					ON	B.TERMINAL = C.TERMINAL AND 
						B.LANCAMENTO_CAIXA= C.LANCAMENTO_CAIXA AND 
						B.CODIGO_FILIAL = C.CODIGO_FILIAL 
		INNER JOIN	LOJAS_VAREJO D			WITH (NOLOCK) --#20# --#25#
					ON  A.CODIGO_FILIAL = D.CODIGO_FILIAL
		INNER JOIN	LOJA_VENDA E			WITH (NOLOCK) --#25#
					ON	B.CODIGO_FILIAL = E.CODIGO_FILIAL_PGTO AND   
						B.TERMINAL = E.TERMINAL_PGTO AND 
						B.LANCAMENTO_CAIXA = E.LANCAMENTO_CAIXA 		
WHERE	C.LANCAMENTO_CAIXA IN (	SELECT	LVP.LANCAMENTO_CAIXA 
								FROM	LOJA_VENDA_PARCELAS LVP WITH (NOLOCK) --#25#
								WHERE	C.TERMINAL = LVP.TERMINAL AND 
										C.LANCAMENTO_CAIXA = LVP.LANCAMENTO_CAIXA AND 
										C.CODIGO_FILIAL = LVP.CODIGO_FILIAL AND 
										LVP.VALOR < 0 AND -- #15#
										LVP.TIPO_PGTO <> '\')  --#38#
		AND E.VALOR_TROCA = 0
GROUP BY A.CODIGO_FILIAL,A.NF_NUMERO,A.SERIE_NF,D.FILIAL, B.TERMINAL, B.LANCAMENTO_CAIXA, B.GUID_VENDA_SAT, B.ID_EQUIPAMENTO , FRETE-- #3# #10#


UNION ALL

-- TROCA NFC-E // ARREDONDAR // VENDA DE VALE ----------------------------------------------------------
SELECT	
		3 AS ORDEM,
		A.CODIGO_FILIAL, --#5#
		D.FILIAL,
		A.NF_NUMERO AS NF,
		A.SERIE_NF AS SERIE_NF,  
		B.TERMINAL, B.LANCAMENTO_CAIXA, --#5#
		B.GUID_VENDA_SAT,--ISNULL(CONVERT(CHAR(38), B.GUID_VENDA_SAT),'') AS GUID_VENDA_SAT, --#5##23#   
		'99' AS PARCELA,
		--CAST('99' AS VARCHAR(2)) AS TIPO_PAGAMENTO, --#37#
		CAST('05' AS VARCHAR(2)) AS TIPO_PAGAMENTO, --#37#
		'' AS CHEQUE_DIGITO, --#30#
		NULL AS COD_CREDENCIADORA, --#5#
		C.VALOR_TROCA + C.VALOR_PAGO AS VALOR_TROCA,    --#16#
		0 AS TROCO, --#5#
		NULL AS CNPJ_CREDENCIADORA, --#9#
		NULL AS AUTORIZACAO, --#9#
		NULL AS BANDEIRA, --#9#
		CASE WHEN ISNULL(B.ID_EQUIPAMENTO,'') = '' THEN CONVERT(BIT, 0) ELSE CONVERT(BIT, 1) END AS VENDA_ECF, --#10#
		NULL AS TIPO_INTEGRA --#14#

FROM	LOJA_NOTA_FISCAL A WITH (NOLOCK) --#25#
		INNER JOIN	LOJA_VENDA_PGTO B WITH (NOLOCK) --#25#
					ON	A.CODIGO_FILIAL = B.CODIGO_FILIAL AND         
						A.SERIE_NF = B.SERIE_NF_SAIDA AND         
						A.NF_NUMERO = B.NUMERO_FISCAL_VENDA 
		INNER JOIN	LOJA_VENDA C WITH (NOLOCK) --#25#
					ON	B.CODIGO_FILIAL = C.CODIGO_FILIAL_PGTO AND   
						B.TERMINAL = C.TERMINAL_PGTO AND 
						B.LANCAMENTO_CAIXA = C.LANCAMENTO_CAIXA 
		INNER JOIN	LOJAS_VAREJO D WITH (NOLOCK) --#20# --#25#
					ON	A.CODIGO_FILIAL = D.CODIGO_FILIAL
		INNER JOIN	(	SELECT SUM(CONVERT(INT,INDICA_ENTREGA_FUTURA)) AS TEM_ENTREGA_FUTURA, CODIGO_FILIAL, TICKET, DATA_VENDA 
						FROM LOJA_VENDA_PRODUTO  WITH (NOLOCK)
						WHERE QTDE_CANCELADA = 0 
						GROUP BY CODIGO_FILIAL, TICKET, DATA_VENDA	) E
					ON  E.CODIGO_FILIAL = C.CODIGO_FILIAL AND
						E.TICKET = C.TICKET AND 
						E.DATA_VENDA = C.DATA_VENDA AND 
						E.TEM_ENTREGA_FUTURA = 0
WHERE	C.VALOR_TROCA > 0 and C.VALOR_TIKET <= 0  --#42#
		--#41# - Início  --NÃO CARREGAR TROCAS COM VITRINE
		AND	B.LANCAMENTO_CAIXA NOT IN (	SELECT DISTINCT LVP.LANCAMENTO_CAIXA 
								FROM	LOJA_VENDA_PARCELAS LVP WITH (NOLOCK) --#25#
								WHERE	B.TERMINAL = LVP.TERMINAL AND 
										B.LANCAMENTO_CAIXA = LVP.LANCAMENTO_CAIXA AND 
										B.CODIGO_FILIAL = LVP.CODIGO_FILIAL AND 
										LVP.VALOR < 0 AND -- #15#
										LVP.TIPO_PGTO = '\')  --#38#
		--#41# - Fim


UNION ALL

/*INICIO #5#*/
-- VENDA CF-E S@T --------------------------------------------------------------------------------------
SELECT 
		4 AS ORDEM, 
		A.CODIGO_FILIAL,
		D.FILIAL,
		CAST(A.CF_NUMERO AS CHAR(15)) AS NF,
		A.SERIE_NF,
		A.TERMINAL, A.LANCAMENTO_CAIXA,
		A.GUID_VENDA_SAT,--CONVERT(CHAR(38), A.GUID_VENDA_SAT) AS GUID_VENDA_SAT, --#5##23#
		'XX' AS PARCELA,--CAST(ROW_NUMBER() OVER(PARTITION BY A.TERMINAL, A.LANCAMENTO_CAIXA ORDER BY A.TERMINAL, A.LANCAMENTO_CAIXA, C.TIPO_PGTO DESC) AS CHAR(02) ) AS PARCELA,--#23#
		CASE
			WHEN C.TIPO_PGTO IN ('D','M')			THEN '01'
			WHEN C.TIPO_PGTO IN ('C','P')			THEN '02'
			WHEN C.TIPO_PGTO IN ('A','B','I')		THEN '03'
			WHEN C.TIPO_PGTO IN ('E','K')			THEN '04'
			WHEN C.TIPO_PGTO IN ('#','@','N','>')	THEN '05'  --#32#
			WHEN C.TIPO_PGTO = '&'					THEN '12'
			ELSE '99'
		END AS TIPO_PAGAMENTO,
		C.CHEQUE_DIGITO, --#30#
		--INICIO - #22# #24#
		CASE 
			WHEN C.COD_CREDENCIADORA IS NOT NULL AND C.COD_CREDENCIADORA < 999 AND C.COD_CREDENCIADORA > 0 THEN RIGHT('000' + RTRIM(LTRIM(CAST(ISNULL(C.COD_CREDENCIADORA, '999') AS CHAR(03)))), 3)  
			WHEN C.COD_CREDENCIADORA IS NOT NULL AND C.COD_CREDENCIADORA > 999 OR C.COD_CREDENCIADORA < 0 AND C.TIPO_PGTO IN('A','B','E','I','K') THEN '999' --#8#
			WHEN ISNULL(C.COD_CREDENCIADORA,ISNULL(F.COD_CREDENCIADORA, E.COD_CREDENCIADORA)) IS NOT NULL THEN
				RIGHT('000' + RTRIM(LTRIM(CAST(ISNULL(F.COD_CREDENCIADORA, E.COD_CREDENCIADORA) AS CHAR(03)))), 3)  
			WHEN ISNULL(C.COD_CREDENCIADORA,ISNULL(F.COD_CREDENCIADORA, E.COD_CREDENCIADORA)) IS NULL AND C.TIPO_PGTO IN('A','B','E','I','K') THEN '999' --#8#
		-- FIM #23# #24#
		ELSE NULL END AS COD_CREDENCIADORA,
		--INICIO - #22#       
		C.VALOR + C.TROCO AS VALOR,--#17#
		CONVERT(NUMERIC(9,2) , 0) AS TROCO, --#5#
		NULL AS CNPJ_CREDENCIADORA, --#9#
		NULL AS AUTORIZACAO, --#9#
		NULL AS BANDEIRA, --#9#
		CONVERT(BIT, 0) AS VENDA_ECF, --#10#
		CASE 
			WHEN C.TIPO_PGTO IN ('K','I')		THEN 1 --#14#
			WHEN C.TIPO_PGTO IN ('E','B','A')	THEN 2 --#14#
		ELSE NULL END AS TIPO_INTEGRA --#14#

FROM	LOJA_CF_SAT A WITH (NOLOCK) --#25#
		INNER JOIN	LOJA_VENDA_PGTO B			WITH (NOLOCK) --#25#
					ON	A.GUID_VENDA_SAT = B.GUID_VENDA_SAT AND			
						A.CODIGO_FILIAL = B.CODIGO_FILIAL AND			
						A.TERMINAL = B.TERMINAL AND         
						A.LANCAMENTO_CAIXA = B.LANCAMENTO_CAIXA 
		INNER JOIN	LOJA_VENDA_PARCELAS C		WITH (NOLOCK) --#25#
					ON	B.TERMINAL = C.TERMINAL AND         
						B.LANCAMENTO_CAIXA = C.LANCAMENTO_CAIXA AND         
						B.CODIGO_FILIAL = C.CODIGO_FILIAL 
		LEFT JOIN	ADMINISTRADORAS_CARTAO E	WITH (NOLOCK) --#25#
					ON C.CODIGO_ADMINISTRADORA = E.CODIGO_ADMINISTRADORA
		LEFT JOIN	CREDENCIADORA_CARTAO_EXCESSAO F WITH (NOLOCK) --#25# 
					ON	E.CODIGO_ADMINISTRADORA = F.CODIGO_ADMINISTRADORA AND 
						A.CODIGO_FILIAL = F.CODIGO_FILIAL AND F.INATIVO = 0
		INNER JOIN	LOJAS_VAREJO D				WITH (NOLOCK) --#20# --#25#
					ON A.CODIGO_FILIAL = D.CODIGO_FILIAL
		INNER JOIN	LOJA_VENDA I				WITH (NOLOCK) --#13# --#25#
					ON	B.CODIGO_FILIAL = I.CODIGO_FILIAL_PGTO AND	--#13#
						B.TERMINAL = I.TERMINAL_PGTO AND				--#13#
						B.LANCAMENTO_CAIXA = I.LANCAMENTO_CAIXA		--#13#

WHERE	C.VALOR > 0 AND I.VALOR_TROCA = 0 --#13# 
		--#40# - Início (REPLICADO O MESMO TRATAMENTO DA NFC-E PARA EVITAR O PROBLEMA DO #13 
		--               E TAMBÉM PARA NÃO LISTAR AS PARCELAS COM VENDA VITRINE QUE SERÁ TRATADO NO ORDEM = 10)
		AND C.LANCAMENTO_CAIXA NOT IN (	SELECT	LVP.LANCAMENTO_CAIXA 
									FROM	LOJA_VENDA_PARCELAS LVP WITH (NOLOCK) --#25#
									WHERE	C.TERMINAL = LVP.TERMINAL AND 
											C.LANCAMENTO_CAIXA = LVP.LANCAMENTO_CAIXA AND 
											C.CODIGO_FILIAL = LVP.CODIGO_FILIAL AND 
											lvp.TIPO_PGTO not in ('@','^','&') and -- #43#
											( LVP.VALOR < 0 AND LVP.TIPO_PGTO = '\' ) ) -- #15# --#44#
		--#40# - Fim

UNION ALL

-- VENDA COM TROCA CF-E S@T ----------------------------------------------------------------------------
-- #18# INICIO CORREÇÃO
(	SELECT 
		5 AS ORDEM, 
		A.CODIGO_FILIAL,
		D.FILIAL,
		CAST(A.CF_NUMERO AS CHAR(15)) AS NF,
		A.SERIE_NF,  
		B.TERMINAL, B.LANCAMENTO_CAIXA,     
		A.GUID_VENDA_SAT,--CONVERT(CHAR(38), A.GUID_VENDA_SAT) AS GUID_VENDA_SAT,--#23# 
		'XX' AS PARCELA,--CAST(ROW_NUMBER() OVER(PARTITION BY A.TERMINAL, A.LANCAMENTO_CAIXA ORDER BY A.TERMINAL, A.LANCAMENTO_CAIXA, P.TIPO_PGTO DESC) AS CHAR(02) ) AS PARCELA,--#23#       
		CASE
			WHEN P.TIPO_PGTO IN ('D','M')			THEN '01'
			WHEN P.TIPO_PGTO IN ('C','P')			THEN '02'
			WHEN P.TIPO_PGTO IN ('A','B','I')		THEN '03'
			WHEN P.TIPO_PGTO IN ('E','K')			THEN '04'
			WHEN P.TIPO_PGTO IN ('#','@','N','>')	THEN '05'  --#32#
			WHEN P.TIPO_PGTO = '&'					THEN '12'
			ELSE '99'
		END AS TIPO_PAGAMENTO,
		P.CHEQUE_DIGITO, --#30#
		-- #31# - INÍCIO
		CASE 
			WHEN P.COD_CREDENCIADORA IS NOT NULL AND P.COD_CREDENCIADORA < 999 AND P.COD_CREDENCIADORA > 0 
				THEN RIGHT('000' + RTRIM(LTRIM(CAST(ISNULL(P.COD_CREDENCIADORA, '999') AS CHAR(03)))), 3)  
			WHEN P.COD_CREDENCIADORA IS NOT NULL AND P.COD_CREDENCIADORA > 999 OR P.COD_CREDENCIADORA < 0 AND P.TIPO_PGTO IN('A','B','E','I','K') 
				THEN '999'
			WHEN ISNULL(P.COD_CREDENCIADORA,ISNULL(F.COD_CREDENCIADORA, E.COD_CREDENCIADORA)) IS NOT NULL 
				THEN RIGHT('000' + RTRIM(LTRIM(CAST(ISNULL(F.COD_CREDENCIADORA, E.COD_CREDENCIADORA) AS CHAR(03)))), 3)  
			WHEN ISNULL(P.COD_CREDENCIADORA,ISNULL(F.COD_CREDENCIADORA, E.COD_CREDENCIADORA)) IS NULL AND P.TIPO_PGTO IN('A','B','E','I','K') 
				THEN '999'
		END AS COD_CREDENCIADORA,
	   -- #31# - FIM
		P.VALOR + P.TROCO AS VALOR,
		CONVERT(NUMERIC(9,2) , 0) AS TROCO,
		NULL AS CNPJ_CREDENCIADORA,
		NULL AS AUTORIZACAO,
		NULL AS BANDEIRA,
		CONVERT(BIT, 0) AS VENDA_ECF,
		CASE WHEN P.TIPO_PGTO IN ('K','I') THEN 1
			WHEN P.TIPO_PGTO IN ('E','B','A') THEN 2
		ELSE NULL END AS TIPO_INTEGRA	   
	FROM	LOJA_CF_SAT A WITH (NOLOCK) --#25#
			INNER JOIN LOJA_VENDA_PGTO B WITH (NOLOCK) --#25#
				ON  A.GUID_VENDA_SAT = B.GUID_VENDA_SAT AND	  
					A.CODIGO_FILIAL = B.CODIGO_FILIAL AND   
					A.TERMINAL = B.TERMINAL AND   
					A.LANCAMENTO_CAIXA = B.LANCAMENTO_CAIXA 
			INNER JOIN LOJA_VENDA C WITH (NOLOCK) --#25#
				ON	B.CODIGO_FILIAL = C.CODIGO_FILIAL_PGTO AND   
					B.TERMINAL = C.TERMINAL_PGTO AND   
					B.LANCAMENTO_CAIXA = C.LANCAMENTO_CAIXA AND	  
					B.DATA = C.DATA_VENDA
			INNER JOIN LOJA_VENDA_PARCELAS P WITH (NOLOCK) --#25#
				ON	C.TERMINAL = P.TERMINAL AND         
					C.LANCAMENTO_CAIXA= P.LANCAMENTO_CAIXA AND         
					C.CODIGO_FILIAL = P.CODIGO_FILIAL AND			
					P.TIPO_PGTO <> '^' AND P.VALOR > 0
			LEFT JOIN ADMINISTRADORAS_CARTAO E WITH (NOLOCK) --#25#
				ON	P.CODIGO_ADMINISTRADORA = E.CODIGO_ADMINISTRADORA
			LEFT JOIN CREDENCIADORA_CARTAO_EXCESSAO F WITH (NOLOCK) --#25#
				ON	E.CODIGO_ADMINISTRADORA = F.CODIGO_ADMINISTRADORA AND 
					C.CODIGO_FILIAL = F.CODIGO_FILIAL AND F.INATIVO = 0 
			INNER JOIN LOJAS_VAREJO D WITH (NOLOCK) --#20# --#25#
				ON A.CODIGO_FILIAL = D.CODIGO_FILIAL
	WHERE C.VALOR_TROCA > 0
	
	UNION ALL
	
	SELECT 
		6 AS ORDEM,
		LVT.CODIGO_FILIAL,  
		LVJ.FILIAL, 
		CAST(LCS.CF_NUMERO AS CHAR(15)) AS NF, 
		LCS.SERIE_NF, 
		LCS.TERMINAL, LCS.LANCAMENTO_CAIXA,
		LCS.GUID_VENDA_SAT,--CONVERT(CHAR(38), LCS.GUID_VENDA_SAT) AS GUID_VENDA_SAT,--#23#	 			
		(	SELECT 
				CAST(COUNT(*) + 1 AS CHAR(2)) 
			FROM LOJA_VENDA_PARCELAS LVL WITH (NOLOCK)	--#25#
			WHERE LVP.TERMINAL = LVL.TERMINAL 
			AND   LVP.LANCAMENTO_CAIXA = LVL.LANCAMENTO_CAIXA 
			AND   LVP.CODIGO_FILIAL = LVL.CODIGO_FILIAL 
			AND   LVL.TIPO_PGTO <> '^' AND LVL.VALOR > 0
		) AS PARCELAS,		
		'99' AS TIPO_PAGAMENTO,
		'' AS CHEQUE_DIGITO, --#30#
		NULL AS COD_CREDENCIADORA,		 
		LV.VALOR_TROCA,
		0 AS TROCO,
		NULL AS CNPJ_CREDENCIADORA,		 
		NULL AS AUTORIZACAO,
		NULL AS BANDEIRA,
		CONVERT(BIT, 0) AS VENDA_ECF,
		NULL AS TIPO_INTEGRA
	FROM	LOJA_VENDA_TROCA LVT WITH (NOLOCK) --#25#
		INNER JOIN LOJA_VENDA LV  WITH (NOLOCK) --#25#
			ON	LVT.CODIGO_FILIAL = LV.CODIGO_FILIAL AND		
				LVT.TICKET = LV.TICKET AND		
				LVT.DATA_VENDA = LV.DATA_VENDA 
		INNER JOIN LOJAS_VAREJO LVJ WITH (NOLOCK) --#20# --#25#
			ON LV.CODIGO_FILIAL = LVJ.CODIGO_FILIAL 
		INNER JOIN LOJA_VENDA_PGTO LVP WITH (NOLOCK) --#25#
			ON	LV.CODIGO_FILIAL = LVP.CODIGO_FILIAL AND		
				LV.DATA_VENDA = LVP.DATA AND		
				LV.TERMINAL = LVP.TERMINAL AND		
				LV.LANCAMENTO_CAIXA = LVP.LANCAMENTO_CAIXA
		INNER JOIN LOJA_CF_SAT LCS WITH (NOLOCK) --#25#
			ON	LCS.GUID_VENDA_SAT = LVP.GUID_VENDA_SAT
		WHERE
			LV.VALOR_TROCA > 0 
			AND LVT.QTDE > 0
		GROUP BY LVT.CODIGO_FILIAL, LVT.TICKET, LVJ.FILIAL, LCS.CF_NUMERO, LCS.SERIE_NF, LCS.TERMINAL, LCS.LANCAMENTO_CAIXA,
					LCS.GUID_VENDA_SAT, LVP.TERMINAL, LVP.LANCAMENTO_CAIXA, LVP.CODIGO_FILIAL, LV.VALOR_TROCA			
)
-- #18# FIM CORREÇÃO
--------------------------------------------------------------------------------------------------------------------------------------------------------
UNION ALL
-- #33# - INÍCIO
-- NFC-E COM VENDA FUTURA -----------------------------------------------------------------------------------------------------------------------------
SELECT 
		7 AS ORDEM,	
		A.CODIGO_FILIAL,
		D.FILIAL,
		A.NF_NUMERO AS NF,
		A.SERIE_NF	AS SERIE_NF,
		B.TERMINAL, 
		B.LANCAMENTO_CAIXA,
		B.GUID_VENDA_SAT,
		C.PARCELA	AS PARCELA,	 
		CASE	
			WHEN C.TIPO_PGTO IN ('D','M')			THEN '01'
			WHEN C.TIPO_PGTO IN ('C','P')			THEN '02'
			WHEN C.TIPO_PGTO IN ('A','B','I')		THEN '03'
			WHEN C.TIPO_PGTO IN ('E','K')			THEN '04'
			--WHEN C.TIPO_PGTO IN ('#','@','N','>')	THEN '05' --#37#
			--WHEN C.TIPO_PGTO = '&'				THEN '12' --#37#
			WHEN C.TIPO_PGTO IN ('#','N','>')		THEN '05' --#37#
			WHEN C.TIPO_PGTO = '@'					THEN '12' --#37#
			WHEN C.TIPO_PGTO = '&'					THEN '15' --#37#
			when C.TIPO_PGTO = '+' and (GETDATE() < CONVERT(DATETIME, Q.VALOR_ATUAL,103)) THen '05' --#37#
			WHEN C.TIPO_PGTO = '+' AND E.MODALIDADE_QR = 3 THEN '17' --#37#
			WHEN C.TIPO_PGTO = '+' AND E.MODALIDADE_QR != 3 THEN '18' --#37#
			--ELSE '99' END AS TIPO_PAGAMENTO, --#37#
		ELSE '05' END AS TIPO_PAGAMENTO, --#37#
		C.CHEQUE_DIGITO,
		NULL AS COD_CREDENCIADORA,
		CASE
			WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_XML_NFE',   A.CODIGO_FILIAL), '0') < '4.00' AND K.NUMERO_MODELO_FISCAL = '55' THEN C.VALOR
			WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_JSON_NFCE', A.CODIGO_FILIAL), '0') < '4.00' AND K.NUMERO_MODELO_FISCAL = '65' THEN C.VALOR
			ELSE C.VALOR + C.TROCO END AS VALOR,
		CASE
			WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_XML_NFE',   A.CODIGO_FILIAL), '0') < '4.00' AND K.NUMERO_MODELO_FISCAL = '55' THEN 0
			WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_JSON_NFCE', A.CODIGO_FILIAL), '0') < '4.00' AND K.NUMERO_MODELO_FISCAL = '65' THEN 0
			ELSE ISNULL(C.TROCO + O.PRECO_LIQUIDO,0)  END AS TROCO, --#35#
		CASE 
			WHEN C.TIPO_PGTO NOT IN ('A','B','I','E','K') THEN NULL ELSE
			( CASE WHEN A.PGTO_INTERMEDIADOR = 1 AND R.ID_INTERMEDIADOR IS NOT NULL THEN R.CNPJ --#37#
			       ELSE ISNULL(F.CNPJ_CREDENCIADORA,G.CNPJ_CREDENCIADORA) END) END AS CNPJ_CREDENCIADORA, --#9# #26#
		CASE 
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K')	THEN RIGHT(RTRIM(LTRIM(C.NUMERO_APROVACAO_CARTAO)),6)
			ELSE NULL END AS AUTORIZACAO,--#49#
		CASE 
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%VISA%'				THEN '01'
	        WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%MASTERCARD%'		THEN '02' 
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%AMERICAN EXPRESS%'	THEN '03'
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%SOROCRED%'			THEN '04'
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%DINERS%'			THEN 
				CASE 
					WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_JSON_NFCE', C.CODIGO_FILIAL), '0') < '4.00' 
					THEN '99' ELSE '05' END			
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%ELO%'				THEN 
				CASE 
					WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_JSON_NFCE', C.CODIGO_FILIAL), '0') < '4.00' 
					THEN '99' ELSE '06' END
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%HIPERCARD%'		THEN 
				CASE
					WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_JSON_NFCE', C.CODIGO_FILIAL), '0') < '4.00' 
					THEN '99' ELSE '07' END
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%AURA%'				THEN 
				CASE 
					WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_JSON_NFCE', C.CODIGO_FILIAL), '0') < '4.00' 
					THEN '99' ELSE '08' END
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%CABAL%'			THEN 
				CASE 
					WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_JSON_NFCE', C.CODIGO_FILIAL), '0') < '4.00' 
					THEN '99' ELSE '09' END				
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') THEN '99'
			ELSE NULL END BANDEIRA, 
	   CASE 
			WHEN ISNULL(B.ID_EQUIPAMENTO,'') = '' THEN CONVERT(BIT, 0) 
			ELSE CONVERT(BIT, 1) END AS VENDA_ECF, 
	   CASE 
			WHEN C.TIPO_PGTO IN ('K','I')		THEN 1 
			WHEN C.TIPO_PGTO IN ('E','B','A')	THEN 2 
			ELSE NULL END AS TIPO_INTEGRA 
FROM	LOJA_NOTA_FISCAL A						WITH (NOLOCK) 
		INNER JOIN	LOJA_VENDA_PGTO B			WITH (NOLOCK) 
					ON	A.CODIGO_FILIAL = B.CODIGO_FILIAL AND
						A.SERIE_NF = B.SERIE_NF_SAIDA AND
						A.NF_NUMERO = B.NUMERO_FISCAL_VENDA 
		INNER JOIN	LOJA_VENDA_PARCELAS C		WITH (NOLOCK) 
					ON	B.TERMINAL = C.TERMINAL AND
						B.LANCAMENTO_CAIXA= C.LANCAMENTO_CAIXA AND
						B.CODIGO_FILIAL = C.CODIGO_FILIAL 
		INNER JOIN	LOJAS_VAREJO D				WITH (NOLOCK) 
					ON	A.CODIGO_FILIAL = D.CODIGO_FILIAL
		LEFT JOIN	ADMINISTRADORAS_CARTAO E	WITH (NOLOCK) 
					ON	C.CODIGO_ADMINISTRADORA = E.CODIGO_ADMINISTRADORA 
		LEFT JOIN	CREDENCIADORA_CARTAO F		WITH (NOLOCK) 
					ON	C.COD_CREDENCIADORA = F.COD_CREDENCIADORA 
		LEFT JOIN	CREDENCIADORA_CARTAO G		WITH (NOLOCK) 
					ON	E.COD_CREDENCIADORA = G.COD_CREDENCIADORA
		INNER JOIN	LOJA_VENDA I				WITH (NOLOCK) 
					ON	B.CODIGO_FILIAL = I.CODIGO_FILIAL_PGTO AND
						B.TERMINAL = I.TERMINAL_PGTO AND 
						B.LANCAMENTO_CAIXA = I.LANCAMENTO_CAIXA 
		INNER JOIN	SERIES_NF J WITH (NOLOCK)  
					ON	J.SERIE_NF = A.SERIE_NF
		INNER JOIN	CTB_ESPECIE_SERIE K WITH (NOLOCK) 
					ON	K.ESPECIE_SERIE = J.ESPECIE_SERIE
		LEFT JOIN	LX_ADMINISTRADORAS_CARTAO L  WITH (NOLOCK) 
					ON	LTRIM(RTRIM(L.LX_COD_ADMINISTRADORA)) = LTRIM(RTRIM(E.LX_COD_ADMINISTRADORA))
		INNER JOIN	(	SELECT SUM(VALOR_ITEM) AS VALOR_ITEM, CODIGO_FILIAL, SERIE_NF, NF_NUMERO
						FROM LOJA_NOTA_FISCAL_ITEM 
						GROUP BY CODIGO_FILIAL, NF_NUMERO, SERIE_NF ) N
					ON  N.CODIGO_FILIAL = A.CODIGO_FILIAL AND
						N.SERIE_NF = A.SERIE_NF AND
						N.NF_NUMERO = A.NF_NUMERO  
		INNER JOIN ( SELECT '1' INDICA_ENTREGA_FUTURA, MAX(B.CODIGO_FILIAL) CODIGO_FILIAL, MAX(B.TICKET) TICKET, MAX(B.DATA_VENDA) DATA_VENDA, SUM(QTDE * PRECO_LIQUIDO) AS PRECO_LIQUIDO   --#35#
						FROM LOJA_VENDA_PRODUTO A JOIN LOJA_VENDA B
						ON A.CODIGO_FILIAL = B.CODIGO_FILIAL
						AND A.TICKET = B.TICKET 
						AND A.DATA_VENDA = B.DATA_VENDA 
						WHERE INDICA_ENTREGA_FUTURA = 1 AND QTDE_CANCELADA = 0 
						GROUP BY B.TICKET  ) O
					ON  O.CODIGO_FILIAL = I.CODIGO_FILIAL 
					AND O.TICKET = I.TICKET 
					AND O.DATA_VENDA = I.DATA_VENDA 
		inner join W_PARAMETROS_LOJA Q WITH (NOLOCK) on a.CODIGO_FILIAL = Q.CODIGO_FILIAL and PARAMETRO = 'DATA_INI_NT2020_006' --#37
		LEFT JOIN LOJA_INTERMEDIADORES_TRANSACAO R WITH (NOLOCK) --#37#
			ON A.ID_INTERMEDIADOR = R.ID_INTERMEDIADOR AND R.INATIVO = 0 --#37#
WHERE	C.VALOR > 0 AND I.VALOR_TROCA = 0 
		AND C.LANCAMENTO_CAIXA NOT IN ( SELECT LVP.LANCAMENTO_CAIXA 
										FROM LOJA_VENDA_PARCELAS LVP WITH (NOLOCK) 
										WHERE C.TERMINAL = LVP.TERMINAL AND C.LANCAMENTO_CAIXA = LVP.LANCAMENTO_CAIXA 
										AND C.CODIGO_FILIAL = LVP.CODIGO_FILIAL AND LVP.VALOR < 0  ) 
        AND O.INDICA_ENTREGA_FUTURA = 1										  
-- #33# - FIM
UNION ALL 
-------------------------------------------------------------------------------------------------------------------------------
--VENDA COM ENTREGA FUTURA + TROCA  #34#
-------------------------------------------------------------------------------------------------------------------------------
SELECT	
		8 AS ORDEM,
		A.CODIGO_FILIAL, 
		D.FILIAL,
		A.NF_NUMERO AS NF,
		A.SERIE_NF AS SERIE_NF,  
		B.TERMINAL, B.LANCAMENTO_CAIXA, 
		B.GUID_VENDA_SAT,
		'99' AS PARCELA,
		--CAST('99' AS VARCHAR(2)) AS TIPO_PAGAMENTO, --#37#
		CAST('05' AS VARCHAR(2)) AS TIPO_PAGAMENTO, --#37#
		'' AS CHEQUE_DIGITO, 
		NULL AS COD_CREDENCIADORA, 
		C.VALOR_TROCA + C.VALOR_PAGO AS VALOR_TROCA,  
		C.VALOR_TROCA + F.PRECO_LIQUIDO AS TROCO, --#35#
		NULL AS CNPJ_CREDENCIADORA, 
		NULL AS AUTORIZACAO, 
		NULL AS BANDEIRA, 
		CASE WHEN ISNULL(B.ID_EQUIPAMENTO,'') = '' THEN CONVERT(BIT, 0) ELSE CONVERT(BIT, 1) END AS VENDA_ECF, 
		NULL AS TIPO_INTEGRA 
FROM	LOJA_NOTA_FISCAL A WITH (NOLOCK) 
		INNER JOIN	LOJA_VENDA_PGTO B WITH (NOLOCK) 
					ON	A.CODIGO_FILIAL = B.CODIGO_FILIAL  AND         
						A.SERIE_NF = B.SERIE_NF_SAIDA      AND         
						A.NF_NUMERO = B.NUMERO_FISCAL_VENDA 
		INNER JOIN	LOJA_VENDA C WITH (NOLOCK) 
					ON	B.CODIGO_FILIAL = C.CODIGO_FILIAL_PGTO  AND   
						B.TERMINAL = C.TERMINAL_PGTO			AND 
						B.LANCAMENTO_CAIXA = C.LANCAMENTO_CAIXA 
		INNER JOIN	LOJAS_VAREJO D WITH (NOLOCK) 
					ON	A.CODIGO_FILIAL = D.CODIGO_FILIAL
			INNER JOIN	( SELECT SUM(VALOR_ITEM) AS VALOR_ITEM, CODIGO_FILIAL, SERIE_NF, NF_NUMERO
						FROM LOJA_NOTA_FISCAL_ITEM WITH (NOLOCK)
						GROUP BY CODIGO_FILIAL, NF_NUMERO, SERIE_NF ) E
					ON  E.CODIGO_FILIAL = A.CODIGO_FILIAL   AND
						E.SERIE_NF = A.SERIE_NF				AND
						E.NF_NUMERO = A.NF_NUMERO  
		INNER JOIN ( SELECT '1' INDICA_ENTREGA_FUTURA, MAX(CODIGO_FILIAL) CODIGO_FILIAL, MAX(TICKET) TICKET, MAX(DATA_VENDA) DATA_VENDA, SUM(QTDE * PRECO_LIQUIDO) AS PRECO_LIQUIDO    --#35#
						FROM LOJA_VENDA_PRODUTO WITH (NOLOCK)
						WHERE INDICA_ENTREGA_FUTURA = 1 AND 
						QTDE_CANCELADA = 0
						GROUP BY TICKET  ) F
					ON  F.CODIGO_FILIAL =C.CODIGO_FILIAL 
					AND F.TICKET =C.TICKET 
					AND F.DATA_VENDA =C.DATA_VENDA
WHERE C.VALOR_TROCA > 0 AND F.INDICA_ENTREGA_FUTURA = 1	

UNION ALL

-------------------------------------------------------------------------------------------------------------------------------
--VENDA COM NFCE + VITRINE #39#
-------------------------------------------------------------------------------------------------------------------------------
SELECT	
		9 AS ORDEM,
		A.CODIGO_FILIAL, --#5#
		D.FILIAL,
		A.NF_NUMERO AS NF,
		A.SERIE_NF	AS SERIE_NF,
		B.TERMINAL, 
		B.LANCAMENTO_CAIXA, --#5#
		B.GUID_VENDA_SAT, --#5#
		C.PARCELA	AS PARCELA,	 
		CASE	
			WHEN C.TIPO_PGTO IN ('D','M')			THEN '01'
			WHEN C.TIPO_PGTO IN ('C','P')			THEN '02'
			WHEN C.TIPO_PGTO IN ('A','B','I')		THEN '03'
			WHEN C.TIPO_PGTO IN ('E','K')			THEN '04'
			--WHEN C.TIPO_PGTO IN ('#','@','N','>')	THEN '05' --#37#
			--WHEN C.TIPO_PGTO = '&'				THEN '12' --#37#
			WHEN C.TIPO_PGTO IN ('#','N','>')		THEN '05' --#37#
			WHEN C.TIPO_PGTO = '@'					THEN '12' --#37#
			WHEN C.TIPO_PGTO = '&'					THEN '15' --#37#
			when C.TIPO_PGTO = '+' AND (GETDATE() < CONVERT(DATETIME, N.VALOR_ATUAL,103)) THEN '05' --#37#
			WHEN C.TIPO_PGTO = '+' AND E.MODALIDADE_QR = 3	THEN '17' --#37#
			WHEN C.TIPO_PGTO = '+' AND E.MODALIDADE_QR != 3 THEN '18' --#37#
			--ELSE '99' END AS TIPO_PAGAMENTO, --#37#
		ELSE '05' END AS TIPO_PAGAMENTO, --#37#
		C.CHEQUE_DIGITO, --#30#
		NULL AS COD_CREDENCIADORA, --#5#
		CASE
			WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_XML_NFE',   A.CODIGO_FILIAL), '0') < '4.00' AND K.NUMERO_MODELO_FISCAL = '55' THEN C.VALOR
			WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_JSON_NFCE', A.CODIGO_FILIAL), '0') < '4.00' AND K.NUMERO_MODELO_FISCAL = '65' THEN C.VALOR
			ELSE C.VALOR + C.TROCO END AS VALOR, --#26#		
		CASE
			WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_XML_NFE',   A.CODIGO_FILIAL), '0') < '4.00' AND K.NUMERO_MODELO_FISCAL = '55' THEN 0
			WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_JSON_NFCE', A.CODIGO_FILIAL), '0') < '4.00' AND K.NUMERO_MODELO_FISCAL = '65' THEN 0			
			--WHEN ISNULL(VV.VALOR_VITRINE, 0) > 0 AND VV.CODIGO_FILIAL = C.CODIGO_FILIAL AND VV.TERMINAL = C.TERMINAL AND VV.LANCAMENTO_CAIXA = C.LANCAMENTO_CAIXA AND VV.PARCELA = C.PARCELA THEN C.TROCO + ABS(VV.VALOR) --#38# #39#
			WHEN ISNULL(R.VALOR, 0) > 0 AND R.PARCELA = C.PARCELA THEN C.TROCO + ABS(R.TROCO) --#39#			
		ELSE C.TROCO END AS TROCO, --#26#
		CASE 
			WHEN C.TIPO_PGTO NOT IN ('A','B','I','E','K') THEN NULL ELSE
			( CASE WHEN A.PGTO_INTERMEDIADOR = 1 AND Q.ID_INTERMEDIADOR IS NOT NULL THEN Q.CNPJ --#37#
			       ELSE ISNULL(F.CNPJ_CREDENCIADORA,G.CNPJ_CREDENCIADORA) END) END AS CNPJ_CREDENCIADORA, --#9# #26#
		CASE 
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K')	THEN RIGHT(RTRIM(LTRIM(C.NUMERO_APROVACAO_CARTAO)),6) 
			ELSE NULL END AS AUTORIZACAO, --#9# #49#
		-- #19# - INÍCIO #27#
		-- #28# - INÍCIO - PASSOU A VALIDAR O NOME DA ADMINISTRADORA DA TABELA 'LX_ADMINISTRADORAS_CARTAO'
		CASE 
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%VISA%'				THEN '01'
	        WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%MASTERCARD%'		THEN '02' 
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%AMERICAN EXPRESS%'	THEN '03'
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%SOROCRED%'			THEN '04'
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%DINERS%'			THEN 
				CASE 
					WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_JSON_NFCE', C.CODIGO_FILIAL), '0') < '4.00' 
					THEN '99' ELSE '05' END			
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%ELO%'				THEN 
				CASE 
					WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_JSON_NFCE', C.CODIGO_FILIAL), '0') < '4.00' 
					THEN '99' ELSE '06' END
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%HIPERCARD%'		THEN 
				CASE
					WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_JSON_NFCE', C.CODIGO_FILIAL), '0') < '4.00' 
					THEN '99' ELSE '07' END
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%AURA%'				THEN 
				CASE 
					WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_JSON_NFCE', C.CODIGO_FILIAL), '0') < '4.00' 
					THEN '99' ELSE '08' END
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%CABAL%'			THEN --'09' --#26#
				CASE 
					WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_JSON_NFCE', C.CODIGO_FILIAL), '0') < '4.00' 
					THEN '99' ELSE '09' END		
		-- #19# - FIM	#27# #28#
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') THEN '99' --#9#    			
			ELSE NULL END BANDEIRA, --#9# #27#
	   CASE 
			WHEN ISNULL(B.ID_EQUIPAMENTO,'') = '' THEN CONVERT(BIT, 0) 
			ELSE CONVERT(BIT, 1) END AS VENDA_ECF, --#10#
	   CASE 
			WHEN C.TIPO_PGTO IN ('K','I')		THEN 1 --#14#
			WHEN C.TIPO_PGTO IN ('E','B','A')	THEN 2 --#14#
			ELSE NULL END AS TIPO_INTEGRA --#14#

FROM	LOJA_NOTA_FISCAL A						WITH (NOLOCK) --#25#
		INNER JOIN	LOJA_VENDA_PGTO B			WITH (NOLOCK) --#25#
					ON	A.CODIGO_FILIAL = B.CODIGO_FILIAL AND
						A.SERIE_NF = B.SERIE_NF_SAIDA AND
						A.NF_NUMERO = B.NUMERO_FISCAL_VENDA 
		INNER JOIN	LOJA_VENDA_PARCELAS C		WITH (NOLOCK) --#25#
					ON	B.TERMINAL = C.TERMINAL AND
						B.LANCAMENTO_CAIXA= C.LANCAMENTO_CAIXA AND
						B.CODIGO_FILIAL = C.CODIGO_FILIAL						
		INNER JOIN	LOJAS_VAREJO D				WITH (NOLOCK) --#20# --#25#
					ON	A.CODIGO_FILIAL = D.CODIGO_FILIAL
		LEFT JOIN	ADMINISTRADORAS_CARTAO E	WITH (NOLOCK) --#25#
					ON	C.CODIGO_ADMINISTRADORA = E.CODIGO_ADMINISTRADORA --#9#
		LEFT JOIN	CREDENCIADORA_CARTAO F		WITH (NOLOCK) --#25#
					ON	C.COD_CREDENCIADORA = F.COD_CREDENCIADORA --#9##21#
		LEFT JOIN	CREDENCIADORA_CARTAO G		WITH (NOLOCK) --#25#
					ON	E.COD_CREDENCIADORA = G.COD_CREDENCIADORA --#9#
		INNER JOIN	LOJA_VENDA I				WITH (NOLOCK) --#12# --#25#
					ON	B.CODIGO_FILIAL = I.CODIGO_FILIAL_PGTO AND --#12#
						B.TERMINAL = I.TERMINAL_PGTO AND --#12#
						B.LANCAMENTO_CAIXA = I.LANCAMENTO_CAIXA --#12#
		INNER JOIN	SERIES_NF J					WITH (NOLOCK)  --#29#
					ON	J.SERIE_NF = A.SERIE_NF
		INNER JOIN	CTB_ESPECIE_SERIE K			WITH (NOLOCK) --#29#
					ON	K.ESPECIE_SERIE = J.ESPECIE_SERIE
		LEFT JOIN	LX_ADMINISTRADORAS_CARTAO L	WITH (NOLOCK) --#29# -- #28#
					ON	LTRIM(RTRIM(L.LX_COD_ADMINISTRADORA)) = LTRIM(RTRIM(E.LX_COD_ADMINISTRADORA))  -- #28#
		INNER JOIN	(	SELECT SUM(CONVERT(INT,INDICA_ENTREGA_FUTURA)) AS TEM_ENTREGA_FUTURA, CODIGO_FILIAL, TICKET, DATA_VENDA 
						FROM LOJA_VENDA_PRODUTO	WITH (NOLOCK)
						WHERE QTDE_CANCELADA = 0 
						GROUP BY CODIGO_FILIAL, TICKET, DATA_VENDA	) M
					ON  M.CODIGO_FILIAL = I.CODIGO_FILIAL AND
						M.TICKET = I.TICKET AND 
						M.DATA_VENDA = I.DATA_VENDA AND 
						M.TEM_ENTREGA_FUTURA = 0
		INNER JOIN	W_PARAMETROS_LOJA N			WITH (NOLOCK) --#37#
					ON	A.CODIGO_FILIAL = N.CODIGO_FILIAL AND --#37#
						PARAMETRO = 'DATA_INI_NT2020_006' --#37#
		LEFT JOIN	LOJA_INTERMEDIADORES_TRANSACAO Q WITH (NOLOCK) --#37#
					ON	A.ID_INTERMEDIADOR = Q.ID_INTERMEDIADOR AND --#37# 
						Q.INATIVO = 0 --#37#
		--#38# #39 - INÍCIO		
		--LEFT JOIN	(	SELECT	A.CODIGO_FILIAL, A.TERMINAL, A.LANCAMENTO_CAIXA, '02' AS PARCELA, C.VALOR_ORIGINAL_PEDIDO AS VALOR_VITRINE, A.VALOR,
		--				FROM	LOJA_VENDA_PARCELAS A  WITH (NOLOCK)
		--						INNER JOIN	LOJA_VENDA B  WITH (NOLOCK)
		--									ON	A.CODIGO_FILIAL = B.CODIGO_FILIAL AND
		--										A.TERMINAL = B.TERMINAL AND
		--										A.LANCAMENTO_CAIXA = B.LANCAMENTO_CAIXA
		--						INNER JOIN	UNICO_VITRINE_PEDIDO C  WITH (NOLOCK)
		--									ON	B.TICKET = C.TICKET AND 
		--										B.DATA_VENDA = C.DATA_VENDA AND 
		--										B.CODIGO_FILIAL = C.CODIGO_FILIAL AND
		--										C.CANCELADO = 0							
		--				WHERE	A.TIPO_PGTO = '\' AND 
		--						A.VALOR < 0	 ) VV
		--			ON	C.LANCAMENTO_CAIXA = VV.LANCAMENTO_CAIXA AND 
		--				C.CODIGO_FILIAL =  VV.CODIGO_FILIAL AND 
		--				C.TERMINAL = VV.TERMINAL				
		INNER JOIN	LOJA_VENDA_PARCELAS_ECOMMERCE R  WITH (NOLOCK)
					ON	C.CODIGO_FILIAL = R.CODIGO_FILIAL AND
						C.TERMINAL = R.TERMINAL AND
						C.LANCAMENTO_CAIXA = R.LANCAMENTO_CAIXA AND								
						C.PARCELA = R.PARCELA
		--#38# #39# - FIM
WHERE	C.VALOR > 0 AND I.VALOR_TROCA = 0 AND --#12#
		C.LANCAMENTO_CAIXA NOT IN (	SELECT	LVP.LANCAMENTO_CAIXA 
									FROM	LOJA_VENDA_PARCELAS LVP WITH (NOLOCK) --#25#
									WHERE	C.TERMINAL = LVP.TERMINAL AND 
											C.LANCAMENTO_CAIXA = LVP.LANCAMENTO_CAIXA AND 
											C.CODIGO_FILIAL = LVP.CODIGO_FILIAL AND 
											LVP.VALOR < 0 AND   -- #15#
											LVP.TIPO_PGTO <> '\')  --#38#

UNION ALL

-------------------------------------------------------------------------------------------------------------------------------
--VENDA COM SAT + VITRINE #40#
-------------------------------------------------------------------------------------------------------------------------------

SELECT 
		10 AS ORDEM, 
		A.CODIGO_FILIAL,
		D.FILIAL,
		CAST(A.CF_NUMERO AS CHAR(15)) AS NF,
		A.SERIE_NF,
		A.TERMINAL, A.LANCAMENTO_CAIXA,
		A.GUID_VENDA_SAT,--CONVERT(CHAR(38), A.GUID_VENDA_SAT) AS GUID_VENDA_SAT, --#5##23#
		'XX' AS PARCELA,--CAST(ROW_NUMBER() OVER(PARTITION BY A.TERMINAL, A.LANCAMENTO_CAIXA ORDER BY A.TERMINAL, A.LANCAMENTO_CAIXA, C.TIPO_PGTO DESC) AS CHAR(02) ) AS PARCELA,--#23#
		CASE
			WHEN C.TIPO_PGTO IN ('D','M')			THEN '01'
			WHEN C.TIPO_PGTO IN ('C','P')			THEN '02'
			WHEN C.TIPO_PGTO IN ('A','B','I')		THEN '03'
			WHEN C.TIPO_PGTO IN ('E','K')			THEN '04'
			WHEN C.TIPO_PGTO IN ('#','@','N','>')	THEN '05'  --#32#
			WHEN C.TIPO_PGTO = '&'					THEN '12'
			ELSE '99'
		END AS TIPO_PAGAMENTO,
		C.CHEQUE_DIGITO, --#30#
		--INICIO - #22# #24#
		CASE 
			WHEN C.COD_CREDENCIADORA IS NOT NULL AND C.COD_CREDENCIADORA < 999 AND C.COD_CREDENCIADORA > 0 THEN RIGHT('000' + RTRIM(LTRIM(CAST(ISNULL(C.COD_CREDENCIADORA, '999') AS CHAR(03)))), 3)  
			WHEN C.COD_CREDENCIADORA IS NOT NULL AND C.COD_CREDENCIADORA > 999 OR C.COD_CREDENCIADORA < 0 AND C.TIPO_PGTO IN('A','B','E','I','K') THEN '999' --#8#
			WHEN ISNULL(C.COD_CREDENCIADORA,ISNULL(F.COD_CREDENCIADORA, E.COD_CREDENCIADORA)) IS NOT NULL THEN
				RIGHT('000' + RTRIM(LTRIM(CAST(ISNULL(F.COD_CREDENCIADORA, E.COD_CREDENCIADORA) AS CHAR(03)))), 3)  
			WHEN ISNULL(C.COD_CREDENCIADORA,ISNULL(F.COD_CREDENCIADORA, E.COD_CREDENCIADORA)) IS NULL AND C.TIPO_PGTO IN('A','B','E','I','K') THEN '999' --#8#
		-- FIM #23# #24#
		ELSE NULL END AS COD_CREDENCIADORA,
		--INICIO - #22#       
		--C.VALOR + C.TROCO AS VALOR, --#17# #40#
		R.VALOR + C.TROCO AS VALOR, --#40#
		CONVERT(NUMERIC(9,2) , 0) AS TROCO, --#5#		
		NULL AS CNPJ_CREDENCIADORA, --#9#
		NULL AS AUTORIZACAO, --#9#
		NULL AS BANDEIRA, --#9#
		CONVERT(BIT, 0) AS VENDA_ECF, --#10#
		CASE 
			WHEN C.TIPO_PGTO IN ('K','I')		THEN 1 --#14#
			WHEN C.TIPO_PGTO IN ('E','B','A')	THEN 2 --#14#
		ELSE NULL END AS TIPO_INTEGRA --#14#
FROM	LOJA_CF_SAT A WITH (NOLOCK) --#25#
		INNER JOIN	LOJA_VENDA_PGTO B			WITH (NOLOCK) --#25#
					ON	A.GUID_VENDA_SAT = B.GUID_VENDA_SAT AND			
						A.CODIGO_FILIAL = B.CODIGO_FILIAL AND			
						A.TERMINAL = B.TERMINAL AND         
						A.LANCAMENTO_CAIXA = B.LANCAMENTO_CAIXA 
		INNER JOIN	LOJA_VENDA_PARCELAS C		WITH (NOLOCK) --#25#
					ON	B.TERMINAL = C.TERMINAL AND         
						B.LANCAMENTO_CAIXA = C.LANCAMENTO_CAIXA AND         
						B.CODIGO_FILIAL = C.CODIGO_FILIAL 
		LEFT JOIN	ADMINISTRADORAS_CARTAO E	WITH (NOLOCK) --#25#
					ON C.CODIGO_ADMINISTRADORA = E.CODIGO_ADMINISTRADORA
		LEFT JOIN	CREDENCIADORA_CARTAO_EXCESSAO F WITH (NOLOCK) --#25# 
					ON	E.CODIGO_ADMINISTRADORA = F.CODIGO_ADMINISTRADORA AND 
						A.CODIGO_FILIAL = F.CODIGO_FILIAL AND F.INATIVO = 0
		INNER JOIN	LOJAS_VAREJO D				WITH (NOLOCK) --#20# --#25#
					ON A.CODIGO_FILIAL = D.CODIGO_FILIAL
		INNER JOIN	LOJA_VENDA I				WITH (NOLOCK) --#13# --#25#
					ON	B.CODIGO_FILIAL = I.CODIGO_FILIAL_PGTO AND	--#13#
						B.TERMINAL = I.TERMINAL_PGTO AND				--#13#
						B.LANCAMENTO_CAIXA = I.LANCAMENTO_CAIXA		--#13#
		--#40# - Início
		INNER JOIN	LOJA_VENDA_PARCELAS_ECOMMERCE R  WITH (NOLOCK)
					ON	C.CODIGO_FILIAL = R.CODIGO_FILIAL AND
						C.TERMINAL = R.TERMINAL AND
						C.LANCAMENTO_CAIXA = R.LANCAMENTO_CAIXA AND								
						C.PARCELA = R.PARCELA
		--#40# - Fim
WHERE 	C.VALOR > 0 AND I.VALOR_TROCA = 0 --#13#


UNION ALL

-------------------------------------------------------------------------------------------------------------------------------
--VENDA COM NFCE + TROCA + VITRINE + ARREDONDAR #41# #50#
-------------------------------------------------------------------------------------------------------------------------------
Select ORDEM,CODIGO_FILIAL ,FILIAL,NF,SERIE_NF ,TERMINAL,LANCAMENTO_CAIXA,GUID_VENDA_SAT,MIN(PARCELA) as PARCELAS,TIPO_PAGAMENTO,CHEQUE_DIGITO,
COD_CREDENCIADORA,VALOR ,MAX(TROCO) as TROCO,MAX(CNPJ_CREDENCIADORA) as CNPJ_CREDENCIADORA ,MAX(AUTORIZACAO) as AUTORIZACAO,MAX(BANDEIRA) as BANCEIRA,VENDA_ECF
,MAX(TIPO_INTEGRA) as TIPO_INTEGRA --#50#
	FROM 
	(
SELECT	
		11 AS ORDEM,
		A.CODIGO_FILIAL, --#5#
		D.FILIAL,
		A.NF_NUMERO AS NF,
		A.SERIE_NF	AS SERIE_NF,
		B.TERMINAL, 
		B.LANCAMENTO_CAIXA, --#5#
		B.GUID_VENDA_SAT, --#5#
		C.PARCELA	AS PARCELA,	 
		CASE	
			WHEN R.TIPO_PGTO IN ('D','M')			THEN '01' --#47#
			WHEN R.TIPO_PGTO IN ('C','P')			THEN '02' --#47#
			WHEN R.TIPO_PGTO IN ('A','B','I')		THEN '03' --#47#
			WHEN R.TIPO_PGTO IN ('E','K')			THEN '04' --#47#
		  --WHEN C.TIPO_PGTO IN ('#','@','N','>')	THEN '05' --#37# #47#
		  --WHEN C.TIPO_PGTO = '&'					THEN '12' --#37# #47#
			WHEN R.TIPO_PGTO IN ('#','N','>')		THEN '05' --#37# #47#
			WHEN R.TIPO_PGTO = '@'					THEN '12' --#37# #47#
			WHEN R.TIPO_PGTO = '&'					THEN '15' --#37# #47#
			when R.TIPO_PGTO = '+' AND (GETDATE() < CONVERT(DATETIME, N.VALOR_ATUAL,103)) THEN '05' --#37# #47#
			WHEN R.TIPO_PGTO = '+' AND E.MODALIDADE_QR = 3	THEN '17' --#37# #47#
			WHEN R.TIPO_PGTO = '+' AND E.MODALIDADE_QR != 3 THEN '18' --#37# #47#
			--ELSE '99' END AS TIPO_PAGAMENTO, --#37#
		ELSE '05' END AS TIPO_PAGAMENTO, --#37#
		C.CHEQUE_DIGITO, --#30#
		NULL AS COD_CREDENCIADORA, --#5#
		CASE
			WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_XML_NFE',   A.CODIGO_FILIAL), '0') < '4.00' AND K.NUMERO_MODELO_FISCAL = '55' THEN C.VALOR
			WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_JSON_NFCE', A.CODIGO_FILIAL), '0') < '4.00' AND K.NUMERO_MODELO_FISCAL = '65' THEN C.VALOR
			--ELSE ABS(C.VALOR) + C.TROCO END AS VALOR, --#26# #46# #47#	
			ELSE R.VALOR END AS VALOR, --#26# #47#		
		CASE
			WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_XML_NFE',   A.CODIGO_FILIAL), '0') < '4.00' AND K.NUMERO_MODELO_FISCAL = '55' THEN 0
			WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_JSON_NFCE', A.CODIGO_FILIAL), '0') < '4.00' AND K.NUMERO_MODELO_FISCAL = '65' THEN 0			
			--WHEN ISNULL(VV.VALOR_VITRINE, 0) > 0 AND VV.CODIGO_FILIAL = C.CODIGO_FILIAL AND VV.TERMINAL = C.TERMINAL AND VV.LANCAMENTO_CAIXA = C.LANCAMENTO_CAIXA AND VV.PARCELA = C.PARCELA THEN C.TROCO + ABS(VV.VALOR) --#38# #39#
			WHEN ISNULL(ABS(R.VALOR), 0) > 0 AND R.PARCELA = C.PARCELA THEN C.TROCO + ABS(R.TROCO) --#39##46#						
		ELSE C.TROCO END AS TROCO, --#26#
		CASE 
			WHEN C.TIPO_PGTO NOT IN ('A','B','I','E','K') THEN NULL ELSE
			( CASE WHEN A.PGTO_INTERMEDIADOR = 1 AND Q.ID_INTERMEDIADOR IS NOT NULL THEN Q.CNPJ --#37#
			       ELSE ISNULL(F.CNPJ_CREDENCIADORA,G.CNPJ_CREDENCIADORA) END) END AS CNPJ_CREDENCIADORA, --#9# #26#
		CASE 
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K')	THEN RIGHT(RTRIM(LTRIM(C.NUMERO_APROVACAO_CARTAO)),6) 
			ELSE NULL END AS AUTORIZACAO, --#9# #49#
		-- #19# - INÍCIO #27#
		-- #28# - INÍCIO - PASSOU A VALIDAR O NOME DA ADMINISTRADORA DA TABELA 'LX_ADMINISTRADORAS_CARTAO'
		CASE 
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%VISA%'				THEN '01'
	        WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%MASTERCARD%'		THEN '02' 
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%AMERICAN EXPRESS%'	THEN '03'
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%SOROCRED%'			THEN '04'
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%DINERS%'			THEN 
				CASE 
					WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_JSON_NFCE', C.CODIGO_FILIAL), '0') < '4.00' 
					THEN '99' ELSE '05' END			
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%ELO%'				THEN 
				CASE 
					WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_JSON_NFCE', C.CODIGO_FILIAL), '0') < '4.00' 
					THEN '99' ELSE '06' END
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%HIPERCARD%'		THEN 
				CASE
					WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_JSON_NFCE', C.CODIGO_FILIAL), '0') < '4.00' 
					THEN '99' ELSE '07' END
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%AURA%'				THEN 
				CASE 
					WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_JSON_NFCE', C.CODIGO_FILIAL), '0') < '4.00' 
					THEN '99' ELSE '08' END
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%CABAL%'			THEN --'09' --#26#
				CASE 
					WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_JSON_NFCE', C.CODIGO_FILIAL), '0') < '4.00' 
					THEN '99' ELSE '09' END		
		-- #19# - FIM	#27# #28#
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') THEN '99' --#9#    			
			ELSE NULL END BANDEIRA, --#9# #27#
	   CASE 
			WHEN ISNULL(B.ID_EQUIPAMENTO,'') = '' THEN CONVERT(BIT, 0) 
			ELSE CONVERT(BIT, 1) END AS VENDA_ECF, --#10#
	   CASE 
			WHEN C.TIPO_PGTO IN ('K','I')		THEN 1 --#14#
			WHEN C.TIPO_PGTO IN ('E','B','A')	THEN 2 --#14#
			ELSE NULL END AS TIPO_INTEGRA --#14#

FROM	LOJA_NOTA_FISCAL A						WITH (NOLOCK) --#25#
		INNER JOIN	LOJA_VENDA_PGTO B			WITH (NOLOCK) --#25#
					ON	A.CODIGO_FILIAL = B.CODIGO_FILIAL AND
						A.SERIE_NF = B.SERIE_NF_SAIDA AND
						A.NF_NUMERO = B.NUMERO_FISCAL_VENDA
		INNER JOIN	LOJA_VENDA_PARCELAS_ECOMMERCE R  WITH (NOLOCK)	--#47#
					ON	B.CODIGO_FILIAL = R.CODIGO_FILIAL AND		--#47#
						B.TERMINAL = R.TERMINAL AND					--#47#
						B.LANCAMENTO_CAIXA = R.LANCAMENTO_CAIXA		--#47#
		LEFT JOIN	LOJA_VENDA_PARCELAS C		WITH (NOLOCK) 		--#25# #47#
					ON	R.TERMINAL = C.TERMINAL AND 				--#47#
						R.LANCAMENTO_CAIXA= C.LANCAMENTO_CAIXA AND	--#47#
						R.CODIGO_FILIAL = C.CODIGO_FILIAL			--#47#
						AND C.TIPO_PGTO <> '\'						--#47#			
		INNER JOIN	LOJAS_VAREJO D				WITH (NOLOCK) --#20# --#25#
					ON	A.CODIGO_FILIAL = D.CODIGO_FILIAL
		LEFT JOIN	ADMINISTRADORAS_CARTAO E	WITH (NOLOCK) --#25#
					ON	C.CODIGO_ADMINISTRADORA = E.CODIGO_ADMINISTRADORA --#9#
		LEFT JOIN	CREDENCIADORA_CARTAO F		WITH (NOLOCK) --#25#
					ON	C.COD_CREDENCIADORA = F.COD_CREDENCIADORA --#9##21#
		LEFT JOIN	CREDENCIADORA_CARTAO G		WITH (NOLOCK) --#25#
					ON	E.COD_CREDENCIADORA = G.COD_CREDENCIADORA --#9#
		INNER JOIN	LOJA_VENDA I				WITH (NOLOCK) --#12# --#25#
					ON	B.CODIGO_FILIAL = I.CODIGO_FILIAL_PGTO AND --#12#
						B.TERMINAL = I.TERMINAL_PGTO AND --#12#
						B.LANCAMENTO_CAIXA = I.LANCAMENTO_CAIXA --#12#
		INNER JOIN	SERIES_NF J					WITH (NOLOCK)  --#29#
					ON	J.SERIE_NF = A.SERIE_NF
		INNER JOIN	CTB_ESPECIE_SERIE K			WITH (NOLOCK) --#29#
					ON	K.ESPECIE_SERIE = J.ESPECIE_SERIE
		LEFT JOIN	LX_ADMINISTRADORAS_CARTAO L	WITH (NOLOCK) --#29# -- #28#
					ON	LTRIM(RTRIM(L.LX_COD_ADMINISTRADORA)) = LTRIM(RTRIM(E.LX_COD_ADMINISTRADORA))  -- #28#
		INNER JOIN	(	SELECT SUM(CONVERT(INT,INDICA_ENTREGA_FUTURA)) AS TEM_ENTREGA_FUTURA, CODIGO_FILIAL, TICKET, DATA_VENDA 
						FROM LOJA_VENDA_PRODUTO	WITH (NOLOCK)
						WHERE QTDE_CANCELADA = 0 
						GROUP BY CODIGO_FILIAL, TICKET, DATA_VENDA	) M
					ON  M.CODIGO_FILIAL = I.CODIGO_FILIAL AND
						M.TICKET = I.TICKET AND 
						M.DATA_VENDA = I.DATA_VENDA AND 
						M.TEM_ENTREGA_FUTURA = 0
		INNER JOIN	W_PARAMETROS_LOJA N			WITH (NOLOCK) --#37#
					ON	A.CODIGO_FILIAL = N.CODIGO_FILIAL AND --#37#
						PARAMETRO = 'DATA_INI_NT2020_006' --#37#
		LEFT JOIN	LOJA_INTERMEDIADORES_TRANSACAO Q WITH (NOLOCK) --#37#
					ON	A.ID_INTERMEDIADOR = Q.ID_INTERMEDIADOR AND --#37# 
						Q.INATIVO = 0 --#37#
		--#38# #39 - INÍCIO		
		--LEFT JOIN	(	SELECT	A.CODIGO_FILIAL, A.TERMINAL, A.LANCAMENTO_CAIXA, '02' AS PARCELA, C.VALOR_ORIGINAL_PEDIDO AS VALOR_VITRINE, A.VALOR,
		--				FROM	LOJA_VENDA_PARCELAS A  WITH (NOLOCK)
		--						INNER JOIN	LOJA_VENDA B  WITH (NOLOCK)
		--									ON	A.CODIGO_FILIAL = B.CODIGO_FILIAL AND
		--										A.TERMINAL = B.TERMINAL AND
		--										A.LANCAMENTO_CAIXA = B.LANCAMENTO_CAIXA
		--						INNER JOIN	UNICO_VITRINE_PEDIDO C  WITH (NOLOCK)
		--									ON	B.TICKET = C.TICKET AND 
		--										B.DATA_VENDA = C.DATA_VENDA AND 
		--										B.CODIGO_FILIAL = C.CODIGO_FILIAL AND
		--										C.CANCELADO = 0							
		--				WHERE	A.TIPO_PGTO = '\' AND 
		--						A.VALOR < 0	 ) VV
		--			ON	C.LANCAMENTO_CAIXA = VV.LANCAMENTO_CAIXA AND 
		--				C.CODIGO_FILIAL =  VV.CODIGO_FILIAL AND 
		--				C.TERMINAL = VV.TERMINAL	
		--#47# - (Comentado) Início
		--INNER JOIN	LOJA_VENDA_PARCELAS_ECOMMERCE R  WITH (NOLOCK)
		--			ON	C.CODIGO_FILIAL = R.CODIGO_FILIAL AND
		--				C.TERMINAL = R.TERMINAL AND
		--				C.LANCAMENTO_CAIXA = R.LANCAMENTO_CAIXA AND								
		--				C.PARCELA = R.PARCELA 		
		--#47# - (Comentado) Início

		--#38# #39# - FIM

WHERE	I.VALOR_TROCA > 0 AND C.TIPO_PGTO <> '^' --#48#
      	   ) A
	   GROUP BY ORDEM, CODIGO_FILIAL ,FILIAL,NF,SERIE_NF ,TERMINAL,LANCAMENTO_CAIXA,GUID_VENDA_SAT,             -- #50#
				LANCAMENTO_CAIXA,GUID_VENDA_SAT,TIPO_PAGAMENTO,CHEQUE_DIGITO,COD_CREDENCIADORA,VALOR ,VENDA_ECF -- #50#
	--#47# - (Comentado) Início
		--AND		
		--C.LANCAMENTO_CAIXA IN (	SELECT	LVP.LANCAMENTO_CAIXA 
		--							FROM	LOJA_VENDA_PARCELAS LVP WITH (NOLOCK) --#25#
		--							WHERE	C.TERMINAL = LVP.TERMINAL AND 
		--									C.LANCAMENTO_CAIXA = LVP.LANCAMENTO_CAIXA AND 
		--									C.CODIGO_FILIAL = LVP.CODIGO_FILIAL AND 
		--									LVP.VALOR < 0 AND   -- #15#
		--									LVP.TIPO_PGTO = '\')  --#38#
		--#47# - (Comentado) Fim
		
UNION ALL

-------------------------------------------------------------------------------------------------------------------------------
--VENDA COM NFCE + TROCA +  ARREDONDAR #42#
-------------------------------------------------------------------------------------------------------------------------------
SELECT ORDEM,CODIGO_FILIAL,FILIAL,NF, --#48#-Inicio
SERIE_NF,
TERMINAL, 
LANCAMENTO_CAIXA,
GUID_VENDA_SAT, 
MIN(PARCELA) AS PARCELA, 
MIN(TIPO_PAGAMENTO) AS TIPO_PAGAMENTO, 
MAX(CHEQUE_DIGITO) AS CHEQUE_DIGITO,
COD_CREDENCIADORA,
SUM(VALOR) AS VALOR,
SUM(TROCO) AS TROCO,
CNPJ_CREDENCIADORA,
RIGHT(RTRIM(LTRIM(AUTORIZACAO)),6) as AUTORIZACAO, --#49#
BANDEIRA,
VENDA_ECF, 
TIPO_INTEGRA --#48#-Fim
FROM ( 
SELECT	
		12 AS ORDEM,
		A.CODIGO_FILIAL, --#5#
		D.FILIAL,
		A.NF_NUMERO AS NF,
		A.SERIE_NF	AS SERIE_NF,
		B.TERMINAL, 
		B.LANCAMENTO_CAIXA, --#5#
		B.GUID_VENDA_SAT, --#5#
		C.PARCELA	AS PARCELA,	 
		CASE	
			WHEN C.TIPO_PGTO IN ('D','M')			THEN '01'
			WHEN C.TIPO_PGTO IN ('C','P')			THEN '02'
			WHEN C.TIPO_PGTO IN ('A','B','I')		THEN '03'
			WHEN C.TIPO_PGTO IN ('E','K')			THEN '04'
			--WHEN C.TIPO_PGTO IN ('#','@','N','>')	THEN '05' --#37#
			--WHEN C.TIPO_PGTO = '&'				THEN '12' --#37#
			WHEN C.TIPO_PGTO IN ('#','N','>')		THEN '05' --#37#
			WHEN C.TIPO_PGTO = '@'					THEN '12' --#37#
			WHEN C.TIPO_PGTO = '&'					THEN '15' --#37#
			when C.TIPO_PGTO = '+' AND (GETDATE() < CONVERT(DATETIME, N.VALOR_ATUAL,103)) THEN '05' --#37#
			WHEN C.TIPO_PGTO = '+' AND E.MODALIDADE_QR = 3	THEN '17' --#37#
			WHEN C.TIPO_PGTO = '+' AND E.MODALIDADE_QR != 3 THEN '18' --#37#
			--ELSE '99' END AS TIPO_PAGAMENTO, --#37#
		ELSE '05' END AS TIPO_PAGAMENTO, --#37#
		C.CHEQUE_DIGITO, --#30#
		NULL AS COD_CREDENCIADORA, --#5#
		CASE
			WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_XML_NFE',   A.CODIGO_FILIAL), '0') < '4.00' AND K.NUMERO_MODELO_FISCAL = '55' THEN C.VALOR
			WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_JSON_NFCE', A.CODIGO_FILIAL), '0') < '4.00' AND K.NUMERO_MODELO_FISCAL = '65' THEN C.VALOR
			ELSE C.VALOR + C.TROCO END AS VALOR, --#26#
		CASE
			WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_XML_NFE',   A.CODIGO_FILIAL), '0') < '4.00' AND K.NUMERO_MODELO_FISCAL = '55' THEN 0
			WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_JSON_NFCE', A.CODIGO_FILIAL), '0') < '4.00' AND K.NUMERO_MODELO_FISCAL = '65' THEN 0						
		    ELSE C.TROCO END AS TROCO, --#26#		
		CASE 
			WHEN C.TIPO_PGTO NOT IN ('A','B','I','E','K') THEN NULL ELSE
			( CASE WHEN A.PGTO_INTERMEDIADOR = 1 AND Q.ID_INTERMEDIADOR IS NOT NULL THEN Q.CNPJ --#37#
			       ELSE ISNULL(F.CNPJ_CREDENCIADORA,G.CNPJ_CREDENCIADORA) END) END AS CNPJ_CREDENCIADORA, --#9# #26#
		CASE 
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K')	THEN RIGHT(RTRIM(LTRIM(C.NUMERO_APROVACAO_CARTAO)),6)  
			ELSE NULL END AS AUTORIZACAO, --#9# #49#
		-- #19# - INÍCIO #27#
		-- #28# - INÍCIO - PASSOU A VALIDAR O NOME DA ADMINISTRADORA DA TABELA 'LX_ADMINISTRADORAS_CARTAO'
		CASE 
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%VISA%'				THEN '01'
	        WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%MASTERCARD%'		THEN '02' 
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%AMERICAN EXPRESS%'	THEN '03'
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%SOROCRED%'			THEN '04'
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%DINERS%'			THEN 
				CASE 
					WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_JSON_NFCE', C.CODIGO_FILIAL), '0') < '4.00' 
					THEN '99' ELSE '05' END			
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%ELO%'				THEN 
				CASE 
					WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_JSON_NFCE', C.CODIGO_FILIAL), '0') < '4.00' 
					THEN '99' ELSE '06' END
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%HIPERCARD%'		THEN 
				CASE
					WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_JSON_NFCE', C.CODIGO_FILIAL), '0') < '4.00' 
					THEN '99' ELSE '07' END
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%AURA%'				THEN 
				CASE 
					WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_JSON_NFCE', C.CODIGO_FILIAL), '0') < '4.00' 
					THEN '99' ELSE '08' END
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') AND L.LX_ADMINISTRADORA LIKE '%CABAL%'			THEN --'09' --#26#
				CASE 
					WHEN ISNULL(DBO.FX_PARAMETRO_LOJA('VERSAO_LAYOUT_JSON_NFCE', C.CODIGO_FILIAL), '0') < '4.00' 
					THEN '99' ELSE '09' END		
		-- #19# - FIM	#27# #28#
			WHEN C.TIPO_PGTO IN ('A','B','I','E','K') THEN '99' --#9#    			
			ELSE NULL END BANDEIRA, --#9# #27#
	   CASE 
			WHEN ISNULL(B.ID_EQUIPAMENTO,'') = '' THEN CONVERT(BIT, 0) 
			ELSE CONVERT(BIT, 1) END AS VENDA_ECF, --#10#
	   CASE 
			WHEN C.TIPO_PGTO IN ('K','I')		THEN 1 --#14#
			WHEN C.TIPO_PGTO IN ('E','B','A')	THEN 2 --#14#
			ELSE NULL END AS TIPO_INTEGRA --#14#

FROM	LOJA_NOTA_FISCAL A						WITH (NOLOCK) --#25#
		INNER JOIN	LOJA_VENDA_PGTO B			WITH (NOLOCK) --#25#
					ON	A.CODIGO_FILIAL = B.CODIGO_FILIAL AND
						A.SERIE_NF = B.SERIE_NF_SAIDA AND
						A.NF_NUMERO = B.NUMERO_FISCAL_VENDA 
		INNER JOIN	LOJA_VENDA_PARCELAS C		WITH (NOLOCK) --#25#
					ON	B.TERMINAL = C.TERMINAL AND
						B.LANCAMENTO_CAIXA= C.LANCAMENTO_CAIXA AND
						B.CODIGO_FILIAL = C.CODIGO_FILIAL						
		INNER JOIN	LOJAS_VAREJO D				WITH (NOLOCK) --#20# --#25#
					ON	A.CODIGO_FILIAL = D.CODIGO_FILIAL
		LEFT JOIN	ADMINISTRADORAS_CARTAO E	WITH (NOLOCK) --#25#
					ON	C.CODIGO_ADMINISTRADORA = E.CODIGO_ADMINISTRADORA --#9#
		LEFT JOIN	CREDENCIADORA_CARTAO F		WITH (NOLOCK) --#25#
					ON	C.COD_CREDENCIADORA = F.COD_CREDENCIADORA --#9##21#
		LEFT JOIN	CREDENCIADORA_CARTAO G		WITH (NOLOCK) --#25#
					ON	E.COD_CREDENCIADORA = G.COD_CREDENCIADORA --#9#
		INNER JOIN	LOJA_VENDA I				WITH (NOLOCK) --#12# --#25#
					ON	B.CODIGO_FILIAL = I.CODIGO_FILIAL_PGTO AND --#12#
						B.TERMINAL = I.TERMINAL_PGTO AND --#12#
						B.LANCAMENTO_CAIXA = I.LANCAMENTO_CAIXA --#12#
		INNER JOIN	SERIES_NF J					WITH (NOLOCK)  --#29#
					ON	J.SERIE_NF = A.SERIE_NF
		INNER JOIN	CTB_ESPECIE_SERIE K			WITH (NOLOCK) --#29#
					ON	K.ESPECIE_SERIE = J.ESPECIE_SERIE
		LEFT JOIN	LX_ADMINISTRADORAS_CARTAO L	WITH (NOLOCK) --#29# -- #28#
					ON	LTRIM(RTRIM(L.LX_COD_ADMINISTRADORA)) = LTRIM(RTRIM(E.LX_COD_ADMINISTRADORA))  -- #28#
		INNER JOIN	(	SELECT SUM(CONVERT(INT,INDICA_ENTREGA_FUTURA)) AS TEM_ENTREGA_FUTURA, CODIGO_FILIAL, TICKET, DATA_VENDA 
						FROM LOJA_VENDA_PRODUTO	WITH (NOLOCK)
						WHERE QTDE_CANCELADA = 0 
						GROUP BY CODIGO_FILIAL, TICKET, DATA_VENDA	) M
					ON  M.CODIGO_FILIAL = I.CODIGO_FILIAL AND
						M.TICKET = I.TICKET AND 
						M.DATA_VENDA = I.DATA_VENDA AND 
						M.TEM_ENTREGA_FUTURA = 0
		INNER JOIN	W_PARAMETROS_LOJA N			WITH (NOLOCK) --#37#
					ON	A.CODIGO_FILIAL = N.CODIGO_FILIAL AND --#37#
						PARAMETRO = 'DATA_INI_NT2020_006' --#37#
		LEFT JOIN	LOJA_INTERMEDIADORES_TRANSACAO Q WITH (NOLOCK) --#37#
					ON	A.ID_INTERMEDIADOR = Q.ID_INTERMEDIADOR AND --#37# 
						Q.INATIVO = 0 --#37#
WHERE	I.VALOR_TROCA > 0 AND I.VALOR_TIKET > 0
and --#42#
		C.LANCAMENTO_CAIXA NOT IN --#42
								  ( SELECT	LVP.LANCAMENTO_CAIXA  
									FROM	LOJA_VENDA_PARCELAS LVP WITH (NOLOCK) --#25#
									WHERE	C.TERMINAL = LVP.TERMINAL AND 
											C.LANCAMENTO_CAIXA = LVP.LANCAMENTO_CAIXA AND 
											C.CODIGO_FILIAL = LVP.CODIGO_FILIAL AND 
											LVP.VALOR < 0 AND   -- #15#
								LVP.TIPO_PGTO IN('\','Y','W'))) A--#38# #48# #51#

GROUP BY A.ORDEM,A.CODIGO_FILIAL,A.FILIAL,A.NF, --#48#-Inicio
A.SERIE_NF,
A.TERMINAL, 
A.LANCAMENTO_CAIXA,
A.GUID_VENDA_SAT, 
A.COD_CREDENCIADORA,
A.CNPJ_CREDENCIADORA,
A.AUTORIZACAO,
A.BANDEIRA,
VENDA_ECF,
A.TIPO_INTEGRA --#48#-Fim

UNION ALL

--VENDA COM NFCE + TROCA + ARREDONDAR #45#
SELECT	
		13 AS ORDEM,
		A.CODIGO_FILIAL, 
		D.FILIAL,
		A.NF_NUMERO AS NF,
		A.SERIE_NF	AS SERIE_NF,
		B.TERMINAL, 
		B.LANCAMENTO_CAIXA,
		B.GUID_VENDA_SAT, 
		'99' AS PARCELA,	
		'05' as TIPO_PAGAMENTO,
		null as CHEQUE_DIGITO, 
		NULL AS COD_CREDENCIADORA,
		I.VALOR_TROCA as VALOR,
		0.00 AS TROCO, 
		null AS CNPJ_CREDENCIADORA, 
		NULL AS AUTORIZACAO, 
		NULL as BANDEIRA,
	   CASE 
			WHEN ISNULL(B.ID_EQUIPAMENTO,'') = '' THEN CONVERT(BIT, 0) 
			ELSE CONVERT(BIT, 1) END AS VENDA_ECF, 
	   NULL AS TIPO_INTEGRA 
FROM	LOJA_NOTA_FISCAL A						WITH (NOLOCK) 
		INNER JOIN	LOJA_VENDA_PGTO B			WITH (NOLOCK) 
					ON	A.CODIGO_FILIAL = B.CODIGO_FILIAL AND
						A.SERIE_NF = B.SERIE_NF_SAIDA AND
						A.NF_NUMERO = B.NUMERO_FISCAL_VENDA 					
		INNER JOIN	LOJAS_VAREJO D				WITH (NOLOCK) 
					ON	A.CODIGO_FILIAL = D.CODIGO_FILIAL
		INNER JOIN	LOJA_VENDA I				WITH (NOLOCK) 
					ON	B.CODIGO_FILIAL = I.CODIGO_FILIAL_PGTO AND
						B.TERMINAL = I.TERMINAL_PGTO AND
						B.LANCAMENTO_CAIXA = I.LANCAMENTO_CAIXA
		INNER JOIN	SERIES_NF J					WITH (NOLOCK)
					ON	J.SERIE_NF = A.SERIE_NF
		INNER JOIN	CTB_ESPECIE_SERIE K			WITH (NOLOCK)
					ON	K.ESPECIE_SERIE = J.ESPECIE_SERIE
		INNER JOIN	(	SELECT SUM(CONVERT(INT,INDICA_ENTREGA_FUTURA)) AS TEM_ENTREGA_FUTURA, CODIGO_FILIAL, TICKET, DATA_VENDA 
						FROM LOJA_VENDA_PRODUTO	WITH (NOLOCK)
						WHERE QTDE_CANCELADA = 0 
						GROUP BY CODIGO_FILIAL, TICKET, DATA_VENDA	) M
					ON  M.CODIGO_FILIAL = I.CODIGO_FILIAL AND
						M.TICKET = I.TICKET AND 
						M.DATA_VENDA = I.DATA_VENDA AND 
						M.TEM_ENTREGA_FUTURA = 0
		INNER JOIN	W_PARAMETROS_LOJA N			WITH (NOLOCK)
					ON	A.CODIGO_FILIAL = N.CODIGO_FILIAL AND
						PARAMETRO = 'DATA_INI_NT2020_006'
		LEFT JOIN	LOJA_INTERMEDIADORES_TRANSACAO Q WITH (NOLOCK)
					ON	A.ID_INTERMEDIADOR = Q.ID_INTERMEDIADOR AND
						Q.INATIVO = 0
WHERE	I.VALOR_TROCA > 0 AND I.VALOR_TIKET > 0 AND  K.NUMERO_MODELO_FISCAL = '65' and
		B.LANCAMENTO_CAIXA NOT IN
								  ( SELECT	LVP.LANCAMENTO_CAIXA  
									FROM	LOJA_VENDA_PARCELAS LVP WITH (NOLOCK)
									WHERE	b.TERMINAL = LVP.TERMINAL AND 
											b.LANCAMENTO_CAIXA = LVP.LANCAMENTO_CAIXA AND 
											b.CODIGO_FILIAL = LVP.CODIGO_FILIAL AND 
											LVP.VALOR < 0 AND LVP.TIPO_PGTO <> '^') --#48#


UNION ALL

SELECT	 --#51# INICIO
		14 AS ORDEM,
		A.CODIGO_FILIAL, 
		D.FILIAL,
		A.NF_NUMERO AS NF,
		A.SERIE_NF AS SERIE_NF,  
		B.TERMINAL, B.LANCAMENTO_CAIXA, 
		B.GUID_VENDA_SAT,
		'99' AS PARCELA,		
		CAST('05' AS VARCHAR(2)) AS TIPO_PAGAMENTO, 
		'' AS CHEQUE_DIGITO,
		NULL AS COD_CREDENCIADORA, 
		C.VALOR_TROCA + C.VALOR_PAGO AS VALOR_TROCA,   
		0 AS TROCO, 
		NULL AS CNPJ_CREDENCIADORA, 
		NULL AS AUTORIZACAO, 
		NULL AS BANDEIRA, 
		CASE WHEN ISNULL(B.ID_EQUIPAMENTO,'') = '' THEN CONVERT(BIT, 0) ELSE CONVERT(BIT, 1) END AS VENDA_ECF, 
		NULL AS TIPO_INTEGRA 

FROM	LOJA_NOTA_FISCAL A WITH (NOLOCK) 
		INNER JOIN	LOJA_VENDA_PGTO B WITH (NOLOCK) 
					ON	A.CODIGO_FILIAL = B.CODIGO_FILIAL AND         
						A.SERIE_NF = B.SERIE_NF_SAIDA AND         
						A.NF_NUMERO = B.NUMERO_FISCAL_VENDA 
		INNER JOIN	LOJA_VENDA C WITH (NOLOCK) 
					ON	B.CODIGO_FILIAL = C.CODIGO_FILIAL_PGTO AND   
						B.TERMINAL = C.TERMINAL_PGTO AND 
						B.LANCAMENTO_CAIXA = C.LANCAMENTO_CAIXA 
		INNER JOIN	LOJAS_VAREJO D WITH (NOLOCK) 
					ON	A.CODIGO_FILIAL = D.CODIGO_FILIAL
		INNER JOIN	(	SELECT SUM(CONVERT(INT,INDICA_ENTREGA_FUTURA)) AS TEM_ENTREGA_FUTURA, CODIGO_FILIAL, TICKET, DATA_VENDA 
						FROM LOJA_VENDA_PRODUTO  WITH (NOLOCK)
						WHERE QTDE_CANCELADA = 0 
						GROUP BY CODIGO_FILIAL, TICKET, DATA_VENDA	) E
					ON  E.CODIGO_FILIAL = C.CODIGO_FILIAL AND
						E.TICKET = C.TICKET AND 
						E.DATA_VENDA = C.DATA_VENDA AND 
						E.TEM_ENTREGA_FUTURA = 0
WHERE	C.VALOR_TROCA > 0  and C.VALOR_TIKET > 0
		
		AND	B.LANCAMENTO_CAIXA IN (	SELECT DISTINCT LVP.LANCAMENTO_CAIXA 
								FROM	LOJA_VENDA_PARCELAS LVP WITH (NOLOCK)
								WHERE	B.TERMINAL = LVP.TERMINAL AND 
										B.LANCAMENTO_CAIXA = LVP.LANCAMENTO_CAIXA AND 
										B.CODIGO_FILIAL = LVP.CODIGO_FILIAL AND 
										LVP.VALOR < 0 AND 
										LVP.TIPO_PGTO = 'Y')   --#51# FIM
		
