-- POSSP-5978 - Gilvano Santos - (31/08/2021) - Emissão da Nota Fiscal eletronica via MID-e
IF NOT EXISTS(SELECT PARAMETRO FROM PARAMETROS WHERE PARAMETRO = 'NFE_USA_CLIENT')
BEGIN
	Insert into parametros (PARAMETRO,PENULT_ATUALIZACAO,VALOR_DEFAULT, ULT_ATUALIZACAO ,VALOR_ATUAL, DESC_PARAMETRO,  
	TIPO_DADO,RANGE_VALOR_ATUAL, GLOBAL,NOTA_PROGRAMADOR,ESCOPO,POR_USUARIO_OK,	PERMITE_POR_EMPRESA,ENVIA_PARA_LOJA, PERMITE_POR_LOJA,
	PERMITE_POR_TERMINAL,PERMITE_ALTERAR_NA_LOJA,PERMITE_ALTERAR_NO_TERMINAL,
	ENVIA_PARA_REPRESENTANTE,PERMITE_POR_REPRESENTANTE,PERMITE_ALTERAR_NO_REPRESENTANTE,DATA_PARA_TRANSFERENCIA) 
	values('NFE_USA_CLIENT',GETDATE(),'.F.', GETDATE(),'.F.','Emissão da NF-e utilizando client',	
		'L','',0,'Este parametro permite a emissão da NF-e direto pelo MID-e Central quando esta com o valor .F. (Falso), caso contrario o LinxPOS vai utilizar o Fiscal Flow para emissão da NF-e.',
		0,0,1,1,1,0,1,0	,0,0,0,GETDATE())
END