IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE NAME = 'PEDIDO' AND ID = OBJECT_ID('OMS_CHANGE_TRACKING'))
BEGIN		
	ALTER TABLE DBO.OMS_CHANGE_TRACKING ADD PEDIDO INT NULL
END

IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE NAME = 'SITUACAO_OMS' AND ID = OBJECT_ID('OMS_CHANGE_TRACKING'))
BEGIN		
	ALTER TABLE DBO.OMS_CHANGE_TRACKING ADD SITUACAO_OMS INT NULL
END
