CREATE FUNCTION FN_GetOrderInformation(@HASH VARCHAR(80), @PEDIDO INT ,@CODIGO_FILIAL_ORIGEM CHAR(6), @PROCESS INT)
RETURNS	@INFORMATION_ORDER table
	(	
	PEDIDO  INT ,
	CODIGO_FILIAL_ORIGEM CHAR(6),
	HASH_VALIDO INT
	)
	 as
begin

declare @ped int, @codfilial char(6), @hash_valido int	 

IF @PROCESS = 1
begin  	
	SELECT 
		@ped=PEDIDO,
		@codfilial = CODIGO_FILIAL_ORIGEM,
		@hash_valido=(CASE WHEN LX_HASH = HASHBYTES('MD5', @HASH + 
		CODIGO_FILIAL_ORIGEM +
		CAST(PEDIDO AS VARCHAR) +
		CAST(ITEM AS VARCHAR) +
		CONVERT(VARCHAR, ISNULL(DATA_INCLUSAO, 0), 126) +
		ISNULL(CODIGO_BARRA,'') +
		ISNULL(DESCR_PRODUTO,'') +
		CAST(ISNULL(QTDE, 0) AS VARCHAR) +
		ISNULL(UNIDADE, '') +
		CAST(ISNULL(PRECO_LIQUIDO, 0) AS VARCHAR) +
		CAST(ISNULL(DESCONTO_ITEM, 0) AS VARCHAR) +
		ISNULL(SITUACAO_TRIBUTARIA, '') +
		CAST(ISNULL(ALIQUOTA, 0) AS VARCHAR) +
		CAST(ISNULL(CANCELADO, '') AS VARCHAR) +
		CAST(ISNULL(DECIMAIS_QTDE, 0) AS VARCHAR) +
		CAST(ISNULL(DECIMAIS_PREC_UNIT, 2) AS VARCHAR))THEN 1 ELSE 0 END) 
FROM
	LOJA_PEDIDO_PRODUTO 
WHERE 
	PEDIDO = @PEDIDO 
	AND CODIGO_FILIAL_ORIGEM = @CODIGO_FILIAL_ORIGEM  	
end	

IF @PROCESS = 2
begin
SELECT 
		@ped=PEDIDO,
		@codfilial=CODIGO_FILIAL_ORIGEM,
		@hash_valido=(CASE WHEN LX_HASH = HASHBYTES('MD5', @HASH + 
		CODIGO_FILIAL_ORIGEM +
		CAST(PEDIDO AS VARCHAR) +
		ISNULL(CNPJ_ESTABELECIMENTO, '') +
		ISNULL(ID_EQUIPAMENTO_DAV, '') +
		ISNULL(MF_ADICIONAL, ' ') +
		ISNULL(TIPO_ECF, '') +
		ISNULL(MARCA, '') +
		ISNULL(MODELO, '') +
		CAST(ISNULL(COO_DAV, 0) AS VARCHAR) +
		ISNULL(SEQUENCIAL_PRE_VENDA, '') +
		CONVERT(VARCHAR, ISNULL(DATA, 0), 126) +
		ISNULL(TITULO_DAV, '')+ 
		CAST(ISNULL(VALOR_TOTAL, 0) AS VARCHAR) +
		CAST(ISNULL(DESCONTO, 0) AS VARCHAR) +
		CAST(ISNULL(COO_VENDA, 0) AS VARCHAR) +
		CAST(ISNULL(SEQ_ECF_CF_DAV, 0) AS VARCHAR) +
		ISNULL(IDENTIFICACAO_CLIENTE, '') +
		ISNULL(CPF_CGC_ECF, '')) OR LX_HASH IS NULL THEN 1 ELSE 0 END) 
	FROM 
		DBO.LOJA_PEDIDO
	WHERE		 
		CODIGO_FILIAL_ORIGEM =@CODIGO_FILIAL_ORIGEM 	
		AND PEDIDO = @PEDIDO																	   

   
end
	INSERT INTO @INFORMATION_ORDER VALUES (@ped,@codfilial, @hash_valido)
	RETURN
END