IF NOT EXISTS ( 
		SELECT 1 FROM SYS.TABLES A 
		INNER JOIN SYS.COLUMNS B
		ON A.OBJECT_ID = B.OBJECT_ID 
		WHERE A.NAME ='LOJA_VENDA_TROCA' AND B.NAME ='MOTIVO_TROCA')
	BEGIN 
		EXEC ('
				ALTER TABLE LOJA_VENDA_TROCA ADD MOTIVO_TROCA SMALLINT ')
	END