IF NOT EXISTS( SELECT 1 FROM SYS.OBJECTS WHERE NAME ='HR_XFK14685_LOJA_VENDA' )
 BEGIN
  EXEC('
ALTER TABLE [dbo].[LOJA_VENDA]  WITH CHECK ADD  CONSTRAINT [HR_XFK14685_LOJA_VENDA] FOREIGN KEY([ID_TIPO_MODALIDADE])
REFERENCES [dbo].[HR_VENDA_TIPO_MODALIDADE] ([ID_TIPO_MODALIDADE])')
END


