IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[PROP_LOJA_ENTRADAS]') AND name = N'XPKPROP_LOJA_ENTRADAS')
ALTER TABLE [dbo].[PROP_LOJA_ENTRADAS] DROP CONSTRAINT [XPKPROP_LOJA_ENTRADAS]

IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[PROP_LOJA_ENTRADAS]') AND name = N'XPKPROP_LOJA_ENTRADAS')
ALTER TABLE  PROP_LOJA_ENTRADAS ALTER COLUMN ROMANEIO_PRODUTO CHAR(15) NOT NULL

IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[PROP_LOJA_ENTRADAS]') AND name = N'XPKPROP_LOJA_ENTRADAS')
ALTER TABLE [dbo].[PROP_LOJA_ENTRADAS] ADD  CONSTRAINT [XPKPROP_LOJA_ENTRADAS] PRIMARY KEY NONCLUSTERED 
(
	[PROPRIEDADE] ASC,
	[ROMANEIO_PRODUTO] ASC,
	[FILIAL] ASC,
	[ITEM_PROPRIEDADE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 80) ON [PRIMARY]

IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[PROP_LOJA_ENTRADAS]') AND name = N'XPKPROP_LOJA_ENTRADAS')
IF NOT EXISTS(SELECT * FROM SYS.OBJECTS WHERE NAME = N'XFKP2_PROP_LOJA_ENTRADAS')
ALTER TABLE [dbo].[PROP_LOJA_ENTRADAS]  WITH CHECK ADD  CONSTRAINT [XFKP2_PROP_LOJA_ENTRADAS] FOREIGN KEY([ROMANEIO_PRODUTO], [FILIAL])
REFERENCES [dbo].[LOJA_ENTRADAS] ([ROMANEIO_PRODUTO], [FILIAL])
ON UPDATE CASCADE
ON DELETE CASCADE

IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[PROP_LOJA_ENTRADAS]') AND name = N'XPKPROP_LOJA_ENTRADAS')
ALTER TABLE [dbo].[PROP_LOJA_ENTRADAS] CHECK CONSTRAINT [XFKP2_PROP_LOJA_ENTRADAS]