IF NOT EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[W_HR_LOJA_ENTRADAS]'))
EXEC dbo.sp_executesql @statement = N'CREATE VIEW [dbo].[W_HR_LOJA_ENTRADAS]  
AS  
SELECT    
 DATA_SAIDA AS EMISSAO,  
 CHAVE_NFE,  
 FILIAL,  
 NUMERO_NF_TRANSFERENCIA,  
 SERIE_NF_ENTRADA,  
 ROMANEIO_PRODUTO,  
 FORNECEDOR,  
 ESPECIE_SERIE,  
 ENTRADA_CONFERIDA,  
 ENTRADA_ENCERRADA,  
 ENTRADA_CANCELADA,  
 sum(QTDE_ENTRADA) as QTDE_TOTAL  
FROM   
W_HR_LOJA_ENTRADAS_PRODUTO     
group by  CHAVE_NFE,  
 FILIAL,  
 NUMERO_NF_TRANSFERENCIA,  
 SERIE_NF_ENTRADA,  
 ROMANEIO_PRODUTO,  
 FORNECEDOR,  
 DATA_SAIDA,
 ESPECIE_SERIE,  
 ENTRADA_CONFERIDA,  
 ENTRADA_ENCERRADA,  
 ENTRADA_CANCELADA
 ' 
