IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'HR_PESQUISA')
CREATE TABLE [dbo].[HR_PESQUISA](
	[ID_PESQUISA] [int] NOT NULL,
	[PESQUISA] [varchar](40) NULL,
	[INICIO] [datetime] NULL,
	[FIM] [datetime] NULL,
	[REDE_LOJAS] [varchar](2) NULL,
	[NUMERO_PEGUNTAS_VENDA] [int] NULL,
	[RANDOMICA] [bit] NULL,
	[PREMIADA] [bit] NULL,
 CONSTRAINT [PK_HR_PESQUISAS] PRIMARY KEY CLUSTERED 
(
	[ID_PESQUISA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

