IF NOT EXISTS(SELECT 1 FROM PARAMETROS WHERE PARAMETRO = 'HR_SH_PRECO_ZERO') 		
BEGIN
INSERT INTO PARAMETROS(PARAMETRO,DESC_PARAMETRO,VALOR_ATUAL,TIPO_DADO,
			GLOBAL,ESCOPO,POR_USUARIO_OK,PERMITE_POR_EMPRESA,
			ENVIA_PARA_LOJA,PERMITE_POR_LOJA,PERMITE_POR_TERMINAL,
			PERMITE_ALTERAR_NA_LOJA,PERMITE_ALTERAR_NO_TERMINAL,
			ENVIA_PARA_REPRESENTANTE,PERMITE_POR_REPRESENTANTE,
			PERMITE_ALTERAR_NO_REPRESENTANTE,PENULT_ATUALIZACAO,
			ULT_ATUALIZACAO,DATA_PARA_TRANSFERENCIA,NOTA_PROGRAMADOR)
VALUES('HR_SH_PRECO_ZERO','FILTRO DO PRECO DA PESQUISA DE PRECO','0','N',
  	   0,0,0,0,1,1,0,0,0,0,0,0,GETDATE(),GETDATE(),GETDATE(),'FILTRO DO PRECO DA PESQUISA DE PRECO USADO NA PROCEDURE LX_DETALHE_PRODUTO')
END  	   
