IF NOT EXISTS(SELECT 1
          FROM   INFORMATION_SCHEMA.COLUMNS
          WHERE  TABLE_NAME = 'LOJA_VENDA'
                 AND COLUMN_NAME = 'HR_DESCONTO')
BEGIN
  ALTER TABLE LOJA_VENDA    ADD HR_DESCONTO VARCHAR(2)
END 

