ALTER PROCEDURE [dbo].[sp_UpdateLogPrices] 
AS BEGIN 
/********************************************************************************************************     
 Alterado        : João Paulo Machado    Data            : 20150723     Motivo          : Adicionado para utilizar o Preços_Liquido    
 **********************************************************************************************************/
 
SET NOCOUNT ON
UPDATE A
SET A.PRECO1 = B.PRECO1,
    A.PRECO2 = B.PRECO2,
    A.PRECO3 = B.PRECO3,
    A.PRECO4 = B.PRECO4,
    A.PROMOCAO_DESCONTO = B.PROMOCAO_DESCONTO,
    A.INICIO_PROMOCAO = B.INICIO_PROMOCAO,
    A.FIM_PROMOCAO = B.FIM_PROMOCAO,
    A.PRECO_LIQUIDO1 = B.PRECO_LIQUIDO1,
    A.PRECO_LIQUIDO2 = B.PRECO_LIQUIDO2,
    A.PRECO_LIQUIDO3 = B.PRECO_LIQUIDO3,
    A.PRECO_LIQUIDO4 = B.PRECO_LIQUIDO4
FROM PRODUTOS_PRECO_COR A
INNER JOIN PRODUTOS_PRECO_COR_LOG B ON A.CODIGO_TAB_PRECO = B.CODIGO_TAB_PRECO
AND A.PRODUTO = B.PRODUTO
AND A.COR_PRODUTO = B.COR_PRODUTO
WHERE ISNULL(B.PROCESSADO, '0') != '1'
  AND B.DATA_ATIVACAO <= GETDATE()
  INSERT INTO PRODUTOS_PRECO_COR(CODIGO_TAB_PRECO, PRODUTO, COR_PRODUTO, PRECO1, PRECO2, PRECO3, PRECO4, PROMOCAO_DESCONTO, INICIO_PROMOCAO, FIM_PROMOCAO, PRECO_LIQUIDO1, PRECO_LIQUIDO2, PRECO_LIQUIDO3, PRECO_LIQUIDO4)
SELECT A.CODIGO_TAB_PRECO,
       A.PRODUTO,
       A.COR_PRODUTO,
       A.PRECO1,
       A.PRECO2,
       A.PRECO3,
       A.PRECO4,
       A.PROMOCAO_DESCONTO,
       A.INICIO_PROMOCAO,
       A.FIM_PROMOCAO,
       A.PRECO_LIQUIDO1,
       A.PRECO_LIQUIDO2,
       A.PRECO_LIQUIDO3,
       A.PRECO_LIQUIDO4
FROM PRODUTOS_PRECO_COR_LOG A
LEFT JOIN PRODUTOS_PRECO_COR B ON A.CODIGO_TAB_PRECO = B.CODIGO_TAB_PRECO
AND A.PRODUTO = B.PRODUTO
AND A.COR_PRODUTO = B.COR_PRODUTO
WHERE ISNULL(A.PROCESSADO, '0') != '1'
  AND A.DATA_ATIVACAO <= GETDATE()
  AND B.PRODUTO IS NULL
  UPDATE PRODUTOS_PRECO_COR_LOG
  SET PROCESSADO = '1' WHERE ISNULL(PROCESSADO, '0') != '1'
  AND DATA_ATIVACAO <= GETDATE()
  UPDATE A
  SET A.PRECO1 = B.PRECO1,
      A.PRECO2 = B.PRECO2,
      A.PRECO3 = B.PRECO3,
      A.PRECO4 = B.PRECO4,
      A.PROMOCAO_DESCONTO = B.PROMOCAO_DESCONTO,
      ULT_ATUALIZACAO = CONVERT(DATETIME, CONVERT(VARCHAR, GETDATE(), 112)),
      A.INICIO_PROMOCAO = B.INICIO_PROMOCAO,
      A.FIM_PROMOCAO = B.FIM_PROMOCAO,
      A.PRECO_LIQUIDO1 = B.PRECO_LIQUIDO1,
      A.PRECO_LIQUIDO2 = B.PRECO_LIQUIDO2,
      A.PRECO_LIQUIDO3 = B.PRECO_LIQUIDO3,
      A.PRECO_LIQUIDO4 = B.PRECO_LIQUIDO4
  FROM PRODUTOS_PRECOS A
  INNER JOIN PRODUTOS_PRECO_LOG B ON A.CODIGO_TAB_PRECO = B.CODIGO_TAB_PRECO
  AND A.PRODUTO = B.PRODUTO WHERE ISNULL(B.PROCESSADO, '0') != '1'
  AND B.DATA_ATIVACAO <= GETDATE()
  INSERT INTO PRODUTOS_PRECOS(CODIGO_TAB_PRECO, PRODUTO, PRECO1, PRECO2, PRECO3, PRECO4, PROMOCAO_DESCONTO, INICIO_PROMOCAO, FIM_PROMOCAO, PRECO_LIQUIDO1, PRECO_LIQUIDO2, PRECO_LIQUIDO3, PRECO_LIQUIDO4)
SELECT A.CODIGO_TAB_PRECO,
       A.PRODUTO,
       A.PRECO1,
       A.PRECO2,
       A.PRECO3,
       A.PRECO4,
       A.PROMOCAO_DESCONTO,
       A.INICIO_PROMOCAO,
       A.FIM_PROMOCAO,
       A.PRECO_LIQUIDO1,
       A.PRECO_LIQUIDO2,
       A.PRECO_LIQUIDO3,
       A.PRECO_LIQUIDO4
FROM PRODUTOS_PRECO_LOG A
LEFT JOIN PRODUTOS_PRECOS B ON A.CODIGO_TAB_PRECO = B.CODIGO_TAB_PRECO
AND A.PRODUTO = B.PRODUTO
WHERE ISNULL(A.PROCESSADO, '0') != '1'
  AND A.DATA_ATIVACAO <= GETDATE()
  AND B.PRODUTO IS NULL
  UPDATE PRODUTOS_PRECO_LOG
  SET PROCESSADO = '1' WHERE ISNULL(PROCESSADO, '0') != '1'
  AND DATA_ATIVACAO <= GETDATE()
  SET NOCOUNT OFF END