CREATE TRIGGER [dbo].[LXU_HR_SAP_LOJA_NOTA_OMS] ON [dbo].[HR_SAP_LOJA_NOTA] FOR UPDATE NOT FOR REPLICATION AS

-- 28/10/2021 - Mandicaju - Adicionado tratativa marcar RETORNOU_LOJA = 1 em casos de NF aprovada.
-- 03/09/2021 - Mandicaju - Adicionado tratativa para retorno do Retailsync #RS
-- 06/05/2018 - Marcio - Criação para compatibilizar com OMS

BEGIN

	DECLARE	@NUMROWS	      INT,
		    @NULLCNT	      INT,
		    @VALIDCNT	      INT,
		    @ERRNO            INT,
		    @ERRMSG           VARCHAR(255)

	SELECT @NUMROWS = @@ROWCOUNT

-- 28/10/2021 - Mandicaju - Adicionado tratativa marcar RETORNOU_LOJA = 1 em casos de NF aprovada.
IF UPDATE(STATUS) BEGIN
			UPDATE HR_SAP_LOJA_NOTA SET RETORNOU_LOJA = 
			CASE WHEN INSERTED.STATUS IN ('3', '7', '9') AND INSERTED.HR_LJ_NF_PROCESSO IN (
			'19', '21', '23','25', '27', '28', '100', '101', '103') AND INSERTED.RETORNOU_LOJA = '0'
			THEN '1'
			ELSE HR_SAP_LOJA_NOTA.RETORNOU_LOJA END
		FROM INSERTED
		INNER JOIN HR_SAP_LOJA_NOTA ON 
		HR_SAP_LOJA_NOTA.CHAVE_ORIGEM = INSERTED.CHAVE_ORIGEM  AND
		HR_SAP_LOJA_NOTA.CODIGO_FILIAL = INSERTED.CODIGO_FILIAL
END
	
	IF UPDATE(EMISSAO_NF) BEGIN

			UPDATE LOJA_PEDIDO
			   SET SITUACAO_OMS = CASE WHEN INSERTED.SERIE_NF = '180'
											THEN 6 
									   ELSE LOJA_PEDIDO.SITUACAO_OMS
								  END	
			 FROM INSERTED INSERTED
			 INNER JOIN LOJA_PEDIDO_DEVOLUCAO ON INSERTED.CODIGO_FILIAL =LOJA_PEDIDO_DEVOLUCAO.CODIGO_FILIAL_ORIGEM 
											 AND INSERTED.CHAVE_ORIGEM =LOJA_PEDIDO_DEVOLUCAO.CHAVE_ORIGEM
			 INNER JOIN LOJA_PEDIDO
						ON LOJA_PEDIDO.CODIGO_FILIAL_ORIGEM = LOJA_PEDIDO_DEVOLUCAO.CODIGO_FILIAL_ORIGEM
						AND LOJA_PEDIDO.PEDIDO = LOJA_PEDIDO_DEVOLUCAO.PEDIDO 

			UPDATE LOJA_PEDIDO_DEVOLUCAO 
				  SET NF_NUMERO =INSERTED.NF_NUMERO,	SERIE_NF=INSERTED.SERIE_NF
			 FROM INSERTED INSERTED
			 INNER JOIN LOJA_PEDIDO_DEVOLUCAO ON INSERTED.CODIGO_FILIAL =LOJA_PEDIDO_DEVOLUCAO.CODIGO_FILIAL_ORIGEM 
											 AND INSERTED.CHAVE_ORIGEM =LOJA_PEDIDO_DEVOLUCAO.CHAVE_ORIGEM
			 INNER JOIN LOJA_PEDIDO
						ON LOJA_PEDIDO.CODIGO_FILIAL_ORIGEM = LOJA_PEDIDO_DEVOLUCAO.CODIGO_FILIAL_ORIGEM
						AND LOJA_PEDIDO.PEDIDO = LOJA_PEDIDO_DEVOLUCAO.PEDIDO 

--Atualiza a SAIDA_ENCERRADA = '1', NUMERO_NF_TRANSFERENCIA E SERIE_NF no LOJA_SAIDAS #RS1
IF UPDATE(EMISSAO_NF) BEGIN
			UPDATE LOJA_SAIDAS SET SAIDA_ENCERRADA = 
			CASE WHEN INSERTED.STATUS = '3' AND INSERTED.HR_LJ_NF_PROCESSO IN (
			'19', '21', '23','25', '27', '28', '100', '101', '103')
			AND SOLICITA_CANCELAMENTO = '0'
			THEN '1'
			ELSE LOJA_SAIDAS.SAIDA_ENCERRADA END
		FROM INSERTED
		INNER JOIN LOJA_SAIDAS ON 
		LOJA_SAIDAS.ROMANEIO_PRODUTO = SUBSTRING(INSERTED.CHAVE_ORIGEM,8,8)
		INNER JOIN FILIAIS ON
		LOJA_SAIDAS.FILIAL = FILIAIS.FILIAL AND
		INSERTED.CODIGO_FILIAL = FILIAIS.COD_FILIAL
		END

	IF UPDATE(EMISSAO_NF) BEGIN
			UPDATE LOJA_SAIDAS SET NUMERO_NF_TRANSFERENCIA = 
			CASE WHEN INSERTED.STATUS = '3' AND INSERTED.HR_LJ_NF_PROCESSO IN (
			'19', '21', '23','25', '27', '28', '100', '101', '103')
			AND SOLICITA_CANCELAMENTO = '0'
			THEN INSERTED.NF_NUMERO
			ELSE LOJA_SAIDAS.NUMERO_NF_TRANSFERENCIA END
		FROM INSERTED
		INNER JOIN LOJA_SAIDAS ON 
		LOJA_SAIDAS.ROMANEIO_PRODUTO = SUBSTRING(INSERTED.CHAVE_ORIGEM,8,8)
		INNER JOIN FILIAIS ON
		LOJA_SAIDAS.FILIAL = FILIAIS.FILIAL AND
		INSERTED.CODIGO_FILIAL = FILIAIS.COD_FILIAL
		END

		IF UPDATE(EMISSAO_NF) BEGIN
			UPDATE LOJA_SAIDAS SET SERIE_NF = 
			CASE WHEN INSERTED.STATUS = '3' AND INSERTED.HR_LJ_NF_PROCESSO IN (
			'19', '21', '23','25', '27', '28', '100', '101', '103')
			AND SOLICITA_CANCELAMENTO = '0'
			THEN INSERTED.SERIE_NF
			ELSE LOJA_SAIDAS.SERIE_NF END
		FROM INSERTED
		INNER JOIN LOJA_SAIDAS ON 
		LOJA_SAIDAS.ROMANEIO_PRODUTO = SUBSTRING(INSERTED.CHAVE_ORIGEM,8,8)
		INNER JOIN FILIAIS ON
		LOJA_SAIDAS.FILIAL = FILIAIS.FILIAL AND
		INSERTED.CODIGO_FILIAL = FILIAIS.COD_FILIAL
		END

--Atualiza a SITUACAO_OMS do pedido para 4 em casos de NF Omni aprovada (3) #RS2

		IF UPDATE (EMISSAO_NF) BEGIN 
		   UPDATE LOJA_PEDIDO SET SITUACAO_OMS = CASE WHEN INSERTED.STATUS = '3' 
													   AND INSERTED.HR_LJ_NF_PROCESSO = '31'
													   AND SOLICITA_CANCELAMENTO = '0'
		THEN '4' ELSE LOJA_PEDIDO.SITUACAO_OMS END
		FROM INSERTED 
		INNER JOIN LOJA_PEDIDO ON
		inserted.CODIGO_FILIAL = LOJA_PEDIDO.CODIGO_FILIAL_ORIGEM INNER JOIN
		LOJA_VENDA_PGTO ON 
		LOJA_VENDA_PGTO.HR_SAP_CHAVE_NF_VENDA = inserted.CHAVE_ORIGEM AND
		LOJA_VENDA_PGTO.CODIGO_FILIAL = inserted.CODIGO_FILIAL INNER JOIN
		LOJA_VENDA ON
		LOJA_VENDA_PGTO.LANCAMENTO_CAIXA = LOJA_VENDA.LANCAMENTO_CAIXA AND
		LOJA_VENDA_PGTO.TERMINAL = LOJA_VENDA.TERMINAL AND
		LOJA_VENDA_PGTO.CODIGO_FILIAL = LOJA_VENDA.CODIGO_FILIAL INNER JOIN
		LOJA_PEDIDO_VENDA ON
		LOJA_VENDA.TICKET = LOJA_PEDIDO_VENDA.TICKET AND
		LOJA_PEDIDO.PEDIDO = LOJA_PEDIDO_VENDA.PEDIDO AND
		LOJA_PEDIDO_VENDA.CODIGO_FILIAL = LOJA_PEDIDO.CODIGO_FILIAL_ORIGEM
		END

--Cancelamento da SAÍDA quando o fluxo SAP for cancelado (Status 7 e 9) #RS3
		
IF UPDATE(STATUS) BEGIN
			UPDATE LOJA_SAIDAS SET SAIDA_CANCELADA =
			CASE WHEN INSERTED.STATUS IN ('7', '9') AND HR_LJ_NF_PROCESSO IN (
			'19', '21', '23','25', '27', '28', '100', '101', '103')
			AND SOLICITA_CANCELAMENTO = '1'
			THEN '1' 
			ELSE LOJA_SAIDAS.SAIDA_CANCELADA END
		FROM INSERTED
		INNER JOIN LOJA_SAIDAS ON
		LOJA_SAIDAS.ROMANEIO_PRODUTO = SUBSTRING(INSERTED.CHAVE_ORIGEM,8,8)
		INNER JOIN FILIAIS ON
		LOJA_SAIDAS.FILIAL = FILIAIS.FILIAL AND
		INSERTED.CODIGO_FILIAL = FILIAIS.COD_FILIAL
		END 

IF UPDATE(STATUS) BEGIN
			UPDATE LOJA_SAIDAS SET QTDE_TOTAL = 
			CASE WHEN INSERTED.STATUS IN ('7', '9') AND HR_LJ_NF_PROCESSO IN (
			'19', '21', '23','25', '27', '28', '100', '101', '103')
			AND SOLICITA_CANCELAMENTO = '1'
			THEN '0'
			ELSE LOJA_SAIDAS.QTDE_TOTAL END
		FROM INSERTED
		INNER JOIN LOJA_SAIDAS ON 
		LOJA_SAIDAS.ROMANEIO_PRODUTO = SUBSTRING(INSERTED.CHAVE_ORIGEM,8,8)
		INNER JOIN FILIAIS ON
		LOJA_SAIDAS.FILIAL = FILIAIS.FILIAL AND
		INSERTED.CODIGO_FILIAL = FILIAIS.COD_FILIAL
		END

IF UPDATE(STATUS) BEGIN
			UPDATE LOJA_SAIDAS SET VALOR_TOTAL = 
			CASE WHEN INSERTED.STATUS IN ('7', '9') AND HR_LJ_NF_PROCESSO IN (
			'19', '21', '23','25', '27', '28', '100', '101', '103')
			AND SOLICITA_CANCELAMENTO = '1'
			THEN '0'
			ELSE LOJA_SAIDAS.VALOR_TOTAL END
		FROM INSERTED
		INNER JOIN LOJA_SAIDAS ON 
		LOJA_SAIDAS.ROMANEIO_PRODUTO = SUBSTRING(INSERTED.CHAVE_ORIGEM,8,8)
		INNER JOIN FILIAIS ON
		LOJA_SAIDAS.FILIAL = FILIAIS.FILIAL AND
		INSERTED.CODIGO_FILIAL = FILIAIS.COD_FILIAL

    IF UPDATE (STATUS) BEGIN 
    UPDATE LOJA_SAIDAS_PRODUTO
	SET QTDE_SAIDA = 0,VALOR=0,PRECO1=0,PRECO2=0,PRECO3=0,PRECO4=0
			,EN1 = 0,EN2 = 0,EN3 = 0,EN4 = 0,EN5 = 0,EN6 = 0,EN7 = 0,EN8 = 0,EN9 = 0,EN10 = 0
			,EN11 = 0,EN12 = 0,EN13 = 0,EN14 = 0,EN15 = 0,EN16 = 0,EN17 = 0,EN18 = 0,EN19 = 0,EN20 = 0
			,EN21 = 0,EN22 = 0,EN23 = 0,EN24 = 0,EN25 = 0,EN26 = 0,EN27 = 0,EN28 = 0,EN29 = 0,EN30 = 0
			,EN31 = 0,EN32 = 0,EN33 = 0,EN34 = 0,EN35 = 0,EN36 = 0,EN37 = 0,EN38 = 0,EN39 = 0,EN40 = 0
			,EN41 = 0,EN42 = 0,EN43 = 0,EN44 = 0,EN45 = 0,EN46 = 0,EN47 = 0,EN48 = 0
		FROM INSERTED
		INNER JOIN LOJA_SAIDAS ON 
		LOJA_SAIDAS.ROMANEIO_PRODUTO = SUBSTRING(INSERTED.CHAVE_ORIGEM,8,8)
		INNER JOIN FILIAIS ON
		LOJA_SAIDAS.FILIAL = FILIAIS.FILIAL AND
		INSERTED.CODIGO_FILIAL = FILIAIS.COD_FILIAL
		INNER JOIN LOJA_SAIDAS_PRODUTO ON
		LOJA_SAIDAS.ROMANEIO_PRODUTO = LOJA_SAIDAS_PRODUTO.ROMANEIO_PRODUTO AND
		LOJA_SAIDAS.FILIAL = LOJA_SAIDAS_PRODUTO.FILIAL
		INNER JOIN 
	   (SELECT CHAVE_ORIGEM,
			   CODIGO_FILIAL, 
			   HR_LJ_NF_PROCESSO FROM 
			   HR_SAP_LOJA_NOTA WHERE 
			   SOLICITA_CANCELAMENTO = '1' AND 
			   HR_LJ_NF_PROCESSO IN 
			  ('19', '21', '23','25', '27', '28', '100', '101', '103') AND
		STATUS IN ('7', '9')) AS SAP_NOTA ON
		INSERTED.CHAVE_ORIGEM = SAP_NOTA.CHAVE_ORIGEM
		END
END

--Vincular o numero da NF com a reserva incluindo retorno (Processos 28 e 29) #RS4
    IF UPDATE (EMISSAO_NF) BEGIN 
    UPDATE LOJA_RESERVA
	SET NUMERO_NF = INSERTED.NF_NUMERO, SERIE_NF = INSERTED.SERIE_NF
		FROM INSERTED
		INNER JOIN LOJA_RESERVA ON 
		LOJA_RESERVA.NUMERO_RESERVA = SUBSTRING(INSERTED.CHAVE_ORIGEM,8,8)
		INNER JOIN FILIAIS ON
		LOJA_RESERVA.FILIAL = FILIAIS.FILIAL AND
		INSERTED.CODIGO_FILIAL = FILIAIS.COD_FILIAL
		INNER JOIN 
	   (SELECT CHAVE_ORIGEM,
			   CODIGO_FILIAL, 
			   HR_LJ_NF_PROCESSO FROM 
			   HR_SAP_LOJA_NOTA WHERE 
			   SOLICITA_CANCELAMENTO = '0' AND 
			   HR_LJ_NF_PROCESSO = '28' AND
		STATUS = '3') AS SAP_NOTA ON
		INSERTED.CHAVE_ORIGEM = SAP_NOTA.CHAVE_ORIGEM
		END

	IF UPDATE (EMISSAO_NF) BEGIN 
    UPDATE LOJA_RESERVA
	SET NUMERO_NF_RETORNO = INSERTED.NF_NUMERO, SERIE_NF_RETORNO = INSERTED.SERIE_NF
		FROM INSERTED
		INNER JOIN LOJA_RESERVA ON 
		LOJA_RESERVA.NUMERO_RESERVA = SUBSTRING(INSERTED.CHAVE_ORIGEM,8,8)
		INNER JOIN FILIAIS ON
		LOJA_RESERVA.FILIAL = FILIAIS.FILIAL AND
		INSERTED.CODIGO_FILIAL = FILIAIS.COD_FILIAL
		INNER JOIN 
	   (SELECT CHAVE_ORIGEM,
			   CODIGO_FILIAL, 
			   HR_LJ_NF_PROCESSO FROM 
			   HR_SAP_LOJA_NOTA WHERE 
			   SOLICITA_CANCELAMENTO = '0' AND 
			   HR_LJ_NF_PROCESSO = '29' AND
		STATUS = '3') AS SAP_NOTA ON
		INSERTED.CHAVE_ORIGEM = SAP_NOTA.CHAVE_ORIGEM
		END

------------------------------------------------------
--- Fim adequação Retail para Pedidos e Saídas #RS ---
------------------------------------------------------

			IF @@ROWCOUNT > 0 AND OBJECT_ID('OMS_CHANGE_TRACKING') IS NOT NULL BEGIN -- #3#
                DELETE OMS_CHANGE_TRACKING
                FROM INSERTED INSERTED
                 INNER JOIN LOJA_PEDIDO_DEVOLUCAO LOJA_PEDIDO_DEVOLUCAO
							ON LOJA_PEDIDO_DEVOLUCAO.CODIGO_FILIAL_ORIGEM = INSERTED.CODIGO_FILIAL
							AND LOJA_PEDIDO_DEVOLUCAO.CHAVE_ORIGEM = INSERTED.CHAVE_ORIGEM and INSERTED.SERIE_NF IS NOT NULL
                 INNER JOIN LOJA_PEDIDO LOJA_PEDIDO (NOLOCK)
							ON LOJA_PEDIDO.CODIGO_FILIAL_ORIGEM = LOJA_PEDIDO_DEVOLUCAO.CODIGO_FILIAL_ORIGEM
							AND LOJA_PEDIDO.PEDIDO = LOJA_PEDIDO_DEVOLUCAO.PEDIDO
                 INNER JOIN OMS_CHANGE_TRACKING OMS_CHANGE_TRACKING (NOLOCK)
							ON OMS_CHANGE_TRACKING.ORDERID = LOJA_PEDIDO.ID_PEDIDO_ORIGEM
            END
         END 

	RETURN
ERROR:
	raiserror(@errmsg, 18, 1)
	ROLLBACK TRANSACTION
END
