IF NOT EXISTS (SELECT 1 FROM SYS.objects WHERE NAME ='TRU_HR_LOJA_VENDA')

exec('
CREATE trigger [dbo].[TRU_HR_LOJA_VENDA] on [dbo].[LOJA_VENDA]  for UPDATE NOT FOR REPLICATION  as    
-- Daniel 25-11-2019 Trigger criada para tratar promoção de cliente unico e exclusivo
begin    
      

 IF UPDATE(TICKET_IMPRESSO) OR UPDATE (DATA_HORA_CANCELAMENTO)
 BEGIN    
    
	INSERT INTO HR_PROMOCAO_CLIENTE ( ID_PROMOCAO,CPF_CLIENTE,DATA_HORA,TIPO)
	SELECT 
	HR_VENDA_PROMOCAO.ID_PROMOCAO,
	CLIENTES_VAREJO.CPF_CGC AS CPF_CLIENTE,
	HR_VENDA_PROMOCAO.DATA_PARA_TRANSFERENCIA AS DATA_HORA,
	TIPO =''U''
	FROM INSERTED
	INNER JOIN HR_VENDA_PROMOCAO
	ON HR_VENDA_PROMOCAO.CODIGO_FILIAL = INSERTED.CODIGO_FILIAL 
	AND HR_VENDA_PROMOCAO.TICKET = INSERTED.TICKET
	AND HR_VENDA_PROMOCAO.DATA_VENDA = INSERTED.DATA_VENDA
	INNER JOIN HR_PROMOCAO
	ON HR_VENDA_PROMOCAO.ID_PROMOCAO = HR_PROMOCAO.ID_PROMOCAO 
	INNER JOIN CLIENTES_VAREJO
	ON INSERTED.CODIGO_CLIENTE = CLIENTES_VAREJO.CODIGO_CLIENTE
	WHERE TICKET_IMPRESSO =1 
	AND DATA_HORA_CANCELAMENTO IS NULL 
	AND HR_PROMOCAO.ID_TIPO_PROMOCAO = 5 
	AND NOT EXISTS(SELECT top 1 1 FROM HR_PROMOCAO_CLIENTE x WHERE x.TIPO =''U'' and x.cpf_cliente = CLIENTES_VAREJO.CPF_CGC and x.id_promocao = HR_PROMOCAO.ID_PROMOCAO)

	DELETE HR_PROMOCAO_CLIENTE
	FROM INSERTED
	INNER JOIN HR_VENDA_PROMOCAO
	ON HR_VENDA_PROMOCAO.CODIGO_FILIAL = INSERTED.CODIGO_FILIAL 
	AND HR_VENDA_PROMOCAO.TICKET = INSERTED.TICKET
	AND HR_VENDA_PROMOCAO.DATA_VENDA = INSERTED.DATA_VENDA
	INNER JOIN HR_PROMOCAO
	ON HR_VENDA_PROMOCAO.ID_PROMOCAO = HR_PROMOCAO.ID_PROMOCAO 
	INNER JOIN CLIENTES_VAREJO
	ON INSERTED.CODIGO_CLIENTE = CLIENTES_VAREJO.CODIGO_CLIENTE
	INNER JOIN HR_PROMOCAO_CLIENTE
	ON  HR_PROMOCAO.ID_PROMOCAO = HR_PROMOCAO_CLIENTE.ID_PROMOCAO AND CLIENTES_VAREJO.CPF_CGC = HR_PROMOCAO_CLIENTE.CPF_CLIENTE
	WHERE DATA_HORA_CANCELAMENTO IS NOT NULL AND HR_PROMOCAO.ID_TIPO_PROMOCAO = 9 AND HR_PROMOCAO_CLIENTE.TIPO =''U''


 END    
 -----------------------------------------------------------------------------------------------------------------       
end

--------------------------------------------------------------------------------')
