IF EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE NAME ='SP_BEFORE_FINISH_SALE')
	BEGIN
		DROP PROCEDURE [dbo].[SP_BEFORE_FINISH_SALE]
	END
		BEGIN
EXEC(
'
CREATE PROCEDURE [dbo].[SP_BEFORE_FINISH_SALE] (@CODIGOFILIAL VARCHAR(6) = NULL, @DATA DATETIME, @TICKET VARCHAR(10), @PEDIDO INT = NULL) 
  AS 
  BEGIN 
  
  -- Mandicaju - 20220621 - Removido C.DESCONTO_ITEM devido ao PRECO_LIQUIDO já considerar o desconto da remarcação do ítem
  -- Mandicaju - 20220601 - Tratamento para corrigir pedidos que existem mais de endereço ou tipo de entrega. #01#
  -- Daniel Martins - 20200629 - Criado tratamento para se existir promoção de cupom para ativar chamar a SP_HR_PROMOCAO com parametro de Cupom 
  -- Daniel Martins - 20200629 - Adicionado campo frete_gratis na @tbl_final
  
  DECLARE @PROMOCAO VARCHAR(MAX), 
  @DATA_INICIO DATETIME, 
  @DATA_FIM DATETIME, 
  @DESCONTOPROM NUMERIC(14,2), 
  @GERATICKET INT, 
  @MESG VARCHAR(MAX),  
  @TIPO INT, 
  @CPF_CLIENTE varchar(20),
  @Cupom varchar(max)
 
   SET @DESCONTOPROM = 0 
   SET @MESG = '''' 
   SET @TIPO = 1 
   set @cupom = null
 
  if @CPF_CLIENTE is null and @TICKET is not null
   select @CPF_CLIENTE = CLIENTES_VAREJO.CPF_CGC
   from loja_venda (nolock)
   inner join CLIENTES_VAREJO
   on LOJA_VENDA.CODIGO_CLIENTE = CLIENTES_VAREJO.CODIGO_CLIENTE
   where loja_venda.TICKET = @TICKET

   DECLARE @TBL_FINAL TABLE (
    ID_PROMOCAO INT
   ,DATA_INICIO DATETIME
   ,DATA_FIM DATETIME
   ,MESG VARCHAR(MAX)
   ,DESCONTOPROM NUMERIC(14, 2)
   ,TIPO INT
   ,GERA_TICKET BIT
   ,QUANTIDADE_VOUCHER INT
   ,VALIDADE_VOUCHER DATETIME
   ,TIPO_VOUCHER INT /*3 = VALOR / 4 = PORCENTAGEM*/
   ,VALOR_VOUCHER NUMERIC(14, 2)
   ,TEXTO_CAMPANHA VARCHAR(MAX)
   ,CODIGO_VOUCHER VARCHAR(20)
   ,TIPO_GATILHO_RESGATE INT
   ,VALOR_GATILHO_RESGATE NUMERIC(18,2)
   ,BRINDE BIT
   ,FRETE_GRATIS BIT

  ) 
 
  BEGIN TRY 
   INSERT INTO @TBL_FINAL (ID_PROMOCAO, DATA_INICIO, DATA_FIM, MESG, DESCONTOPROM, TIPO, GERA_TICKET, QUANTIDADE_VOUCHER, VALIDADE_VOUCHER, TIPO_VOUCHER, VALOR_VOUCHER, TEXTO_CAMPANHA, CODIGO_VOUCHER, TIPO_GATILHO_RESGATE, VALOR_GATILHO_RESGATE, BRINDE, FRETE_GRATIS) 
   EXEC SP_HR_PROMOCAO @CODIGOFILIAL, @TICKET, @DATA, @PEDIDO, @CPF_CLIENTE
  END TRY
  BEGIN CATCH
   INSERT INTO @TBL_FINAL (ID_PROMOCAO, DATA_INICIO, DATA_FIM, MESG, DESCONTOPROM, TIPO, GERA_TICKET, QUANTIDADE_VOUCHER, VALIDADE_VOUCHER, TIPO_VOUCHER, VALOR_VOUCHER, TEXTO_CAMPANHA, CODIGO_VOUCHER, TIPO_GATILHO_RESGATE, VALOR_GATILHO_RESGATE, BRINDE, FRETE_GRATIS)
   EXEC SP_HR_PROMOCAO @CODIGOFILIAL, @TICKET, @DATA, @PEDIDO, @CPF_CLIENTE
  END CATCH

-- Daniel Martins - 20200629 - INICIO 

 DECLARE @INDICA_CUPOM BIT
 SET @INDICA_CUPOM = CASE WHEN EXISTS (select 1 from hr_venda_promocao where CODIGO_FILIAL = @CODIGOFILIAL AND TICKET = @TICKET AND DATA_VENDA = @DATA AND CODIGO_VOUCHER IS NOT NULL) THEN 1 ELSE 0 END
 
 IF @INDICA_CUPOM = 1
 begin
   select @Cupom = CODIGO_VOUCHER from hr_venda_promocao where CODIGO_FILIAL = @CODIGOFILIAL AND TICKET = @TICKET AND DATA_VENDA = @DATA AND CODIGO_VOUCHER IS NOT NULL 
   DELETE FROM @TBL_FINAL
   INSERT INTO @TBL_FINAL (ID_PROMOCAO, DATA_INICIO, DATA_FIM, MESG, DESCONTOPROM, TIPO, GERA_TICKET, QUANTIDADE_VOUCHER, VALIDADE_VOUCHER, TIPO_VOUCHER, VALOR_VOUCHER, TEXTO_CAMPANHA, CODIGO_VOUCHER, TIPO_GATILHO_RESGATE, VALOR_GATILHO_RESGATE, BRINDE, FRETE_GRATIS) 
   EXEC SP_HR_PROMOCAO @CODIGOFILIAL, @TICKET, @DATA, @PEDIDO, @CPF_CLIENTE,'''',@CUPOM
  END

  -- Daniel Martins - 20200629 - FIM


  IF NOT EXISTS(SELECT TOP 1 1 FROM @TBL_FINAL WHERE CONVERT(DATE,getdate()) BETWEEN DATA_INICIO And DATA_FIM) 
  INSERT INTO @TBL_FINAL 
  VALUES (0,CONVERT(DATE, GETDATE()), CONVERT(DATE,GETDATE()),'''', 0, 1, 0, 0, null, 0, 0, null, null, 0, 0,0,0 ) 
 
   SELECT @DATA_INICIO = MIN(DATA_INICIO),
  @DATA_FIM = MAX(@DATA_FIM),
  @DESCONTOPROM = SUM(DESCONTOPROM),
  @GERATICKET = case when sum(case when GERA_TICKET = 1 and QUANTIDADE_VOUCHER IS NOT NULL then 1 else 0 end) > 0 then 1 else 0 end
   FROM @TBL_FINAL

   SELECT @MESG = @MESG + MESG
   FROM @TBL_FINAL

   SELECT ''Motor Promocao v2.0 Ativo'' AS PROMOCAO, 
  ISNULL(@DATA_INICIO, CONVERT(DATE, GETDATE())) AS DATA_INICIO, 
  ISNULL(@DATA_FIM, CONVERT(DATE, GETDATE())) AS DATA_FIM, 
  @DESCONTOPROM AS DESCONTOPROM, 
  @GERATICKET as GERATICKET, 
  SUBSTRING(@MESG,1,250) AS MESG, 
  @TIPO AS TIPO,
  @CPF_CLIENTE AS CPF_CLIENTE

    DECLARE @DESCONTO NUMERIC(13,2) =0, @BASEFRETE NUMERIC(13,2)=0, @FRETEGRATIS NUMERIC(13,2)=0, @FRETETOTAL NUMERIC(13,2)=0, @VALORTOTAL NUMERIC(13,2)=0  
       
    SELECT @BASEFRETE   = CONVERT(NUMERIC(13,2),ISNULL(VALOR_ATUAL,''0'')) FROM PARAMETROS WHERE PARAMETRO = ''HR_CAMPANHA_FRETE''        
    SELECT @FRETEGRATIS = ISNULL(SUM(ISNULL(FRETE,0)),0) FROM LOJA_PEDIDO_ENTREGA WHERE PEDIDO =@PEDIDO AND CODIGO_FILIAL_ORIGEM =@CODIGOFILIAL AND (upper(OPCAO_ENTREGA) LIKE ''%"METHODID":"1"%'' or upper(OPCAO_ENTREGA) LIKE ''%"METHOD":"ENTREGA NORMAL"%'')
    SELECT @FRETETOTAL  = ISNULL(SUM(ISNULL(FRETE,0)),0)FROM LOJA_PEDIDO_ENTREGA WHERE PEDIDO =@PEDIDO AND CODIGO_FILIAL_ORIGEM =@CODIGOFILIAL      
    SELECT @VALORTOTAL  = ISNULL(SUM(ISNULL(VALOR_TOTAL,0)),0) FROM LOJA_PEDIDO WHERE PEDIDO =@PEDIDO AND CODIGO_FILIAL_ORIGEM =@CODIGOFILIAL   
        
   UPDATE LOJA_PEDIDO SET DESCONTO =ISNULL(@DESCONTO,0),   
   FRETE = CASE WHEN VALOR_TOTAL >= @BASEFRETE THEN @FRETETOTAL-@FRETEGRATIS ELSE @FRETETOTAL END   
   WHERE CODIGO_FILIAL_ORIGEM =@CODIGOFILIAL AND PEDIDO =@PEDIDO AND VALOR_TOTAL > 0  
  
   UPDATE LOJA_PEDIDO_ENTREGA SET FRETE = CASE WHEN @VALORTOTAL >= @BASEFRETE THEN 0 ELSE FRETE END   
   WHERE CODIGO_FILIAL_ORIGEM =@CODIGOFILIAL AND PEDIDO =@PEDIDO AND @VALORTOTAL >0 AND (UPPER(OPCAO_ENTREGA) LIKE ''%"METHODID":"1"%'' OR UPPER(OPCAO_ENTREGA) LIKE ''%"METHOD":"ENTREGA NORMAL"%'')

   UPDATE LOJA_PEDIDO_ENTREGA_LISTA SET FRETE = CASE WHEN @VALORTOTAL >= @BASEFRETE THEN 0 ELSE FRETE END   
   WHERE CODIGO_FILIAL_ORIGEM =@CODIGOFILIAL AND PEDIDO =@PEDIDO AND @VALORTOTAL >0 AND (UPPER(CONVERT(VARCHAR(MAX),OPCAO_ENTREGA)) LIKE ''%"METHODID":"1"%'' OR UPPER(CONVERT(VARCHAR(MAX),OPCAO_ENTREGA)) LIKE ''%"METHOD":"ENTREGA NORMAL"%'')
   
-- Inicio #01#
UPDATE B SET B.VALOR_TOTAL = C.VALOR_TOTAL
FROM LOJA_PEDIDO_ENTREGA_LISTA B
INNER JOIN (SELECT C.CODIGO_FILIAL_ORIGEM, C.PEDIDO, C.SEQ_ENTREGA, SUM (C.QTDE * (C.PRECO_LIQUIDO)) VALOR_TOTAL
			FROM LOJA_PEDIDO_PRODUTO C
			WHERE C.INDICA_ENTREGA_FUTURA =1
			GROUP BY C.PEDIDO,C.CODIGO_FILIAL_ORIGEM, C.SEQ_ENTREGA
			) C ON C.CODIGO_FILIAL_ORIGEM = B.CODIGO_FILIAL_ORIGEM
			AND C.PEDIDO=B.PEDIDO
			AND C.SEQ_ENTREGA = B.SEQ_ENTREGA
INNER JOIN LOJA_PEDIDO A ON
A.PEDIDO = B.PEDIDO AND A.CODIGO_FILIAL_ORIGEM = B.CODIGO_FILIAL_ORIGEM
WHERE A.CODIGO_FILIAL_ORIGEM = @CODIGOFILIAL AND A.PEDIDO = @PEDIDO

UPDATE B SET B.VALOR_TOTAL = C.VALOR_TOTAL
FROM LOJA_PEDIDO_ENTREGA B
INNER JOIN (SELECT C.CODIGO_FILIAL_ORIGEM, C.PEDIDO, C.SEQ_ENTREGA, SUM (C.QTDE * (C.PRECO_LIQUIDO)) VALOR_TOTAL
			FROM LOJA_PEDIDO_PRODUTO C
			WHERE C.INDICA_ENTREGA_FUTURA =1
			GROUP BY C.PEDIDO,C.CODIGO_FILIAL_ORIGEM, C.SEQ_ENTREGA
			) C ON C.CODIGO_FILIAL_ORIGEM = B.CODIGO_FILIAL_ORIGEM
			AND C.PEDIDO=B.PEDIDO
			AND C.SEQ_ENTREGA = B.SEQ_ENTREGA
INNER JOIN LOJA_PEDIDO A ON
A.PEDIDO = B.PEDIDO AND A.CODIGO_FILIAL_ORIGEM = B.CODIGO_FILIAL_ORIGEM
WHERE A.CODIGO_FILIAL_ORIGEM = @CODIGOFILIAL AND A.PEDIDO = @PEDIDO 
-- Fim #01#


  SET NOCOUNT OFF 
  END
')
END